### ISSUE TITLE
Feature request - Adding "next alarm" to serverstatus or status for a player

### ISSUE THREAD

**Issue by cirdanlunae** [LMS-Community/slimserver#1003]
Is it possible for "next alarm" be added to "serverstatus" or "status" for a player? Adding this information would be useful in adding extended features to LMS Material, where upcoming alarms could be visible, along with indicators showing that alarms are indeed set.

**Comment by michaelherger** [comment]
If you run the `status` query with the additional `menu:1` parameter you should get information about the upcoming alarm.

**Comment by CDrummond** [comment]
@michaelherger The problem is passing "menu:1" causes the returned track info to be severely reduced (only track_id, not artist_id, album_id, etc.)

**Comment by mherger** [comment]
Argh... it can never be easy 😠. I see it:

https://github.com/Logitech/slimserver/blob/public/8.5/Slim/Control/Queries.pm#L3831-L3844

In menu mode the tags are simply overwritten. How stupid is this?... We need to fix this somehow. The least intrusive and risky probably would be if I added another flag like `alarm:1` to return the same data? Changing the tag handling seems a bit riskier to me at this point. I don't want to do any big changes before 8.5 has been released - which is supposed to happen within the next few weeks.

**Comment by CDrummond** [comment]
"alarm:1" sounds fine to me :)

**Comment by mherger** [comment]
Would something like this work? (totally untested!)

```diff
diff --git a/Slim/Control/Queries.pm b/Slim/Control/Queries.pm
index 5d15ddda2..90833ca18 100644
--- a/Slim/Control/Queries.pm
+++ b/Slim/Control/Queries.pm
@@ -3741,8 +3741,7 @@ sub statusQuery {
 		$request->addResult('digital_volume_control', $digitalVolumeControl + 0);
 	}
 
-	# give a count in menu mode no matter what
-	if ($menuMode) {
+	if ($menuMode || $request->getParam('alarmData')) {
 		# send information about the alarm state to SP
 		my $alarmNext    = Slim::Utils::Alarm->alarmInNextDay($client);
 		my $alarmComing  = $alarmNext ? 'set' : 'none';
@@ -3796,7 +3795,9 @@ sub statusQuery {
 		# send client pref for alarm timeout
 		my $alarm_timeout_seconds = $prefs->client($client)->get('alarmTimeoutSeconds');
 		$request->addResult('alarm_timeout_seconds', defined $alarm_timeout_seconds ? $alarm_timeout_seconds + 0 : 300);
+	}
 
+	if ($menuMode) {
 		# send which presets are defined
 		my $presets = $prefs->client($client)->get('presets');
 		my $presetLoop;
```

**Comment by mherger** [comment]
I made it `alarmData:1` in this patch...

**Comment by CDrummond** [comment]
That seems to work for me.

**Comment by michaelherger** [comment]
I added this to 8.5. Please give it a try! Thanks.
