### ISSUE TITLE
Log is filled with error comming from /lms/gdresized.pl

### ISSUE THREAD

**Issue by smogol66** [LMS-Community/slimserver#1004]
I'm running a fresh installation of LMS on my NAS over the container from lmscommunity/logitecmediaserver:stable.
Logitech Media Server Version: 8.4.1 - 1708787582 @ Sun Feb 25 04:53:35 CET 2024
Hostname: xxxxxx
Server IP Address: using same as the host
Server HTTP Port Number: 9002
Operating system: Debian (Docker) - EN - utf8
Platform Architecture: x86_64-linux
Database Version: SQLite
Total Players Recognized: 2 ( picoreplayer on HIFBerry + bluetooth speaker)

Having problems to connect another BT speacker, I looked into the logs and noticed a lot of errors in the log from LMS and on the log on the container.
on the container's log I got this entries every 6-10 seconds:

2024/03/01 23:17:33,stdout,Unable to open socket: Address already in use at /lms/gdresized.pl line 109.
2024/03/01 23:17:27,stdout,Unable to open socket: Address already in use at /lms/gdresized.pl line 109.
2024/03/01 23:17:21,stdout,Unable to open socket: Address already in use at /lms/gdresized.pl line 109.
2024/03/01 23:17:16,stdout,[24-03-01 22:17:16.9181] Slim::Utils::ImageResizer::__ANON__ (67) daemon failed to connect: 
Connection refused

on the LMS log only some 
2024/03/01 23:17:16,stdout,[24-03-01 22:17:16.9181] Slim::Utils::ImageResizer::__ANON__ (67) daemon failed to connect: 
Connection refused

Do you have any clue?
Regards

**Comment by mherger** [comment]
Not sure what's wrong there. But you can probably mitigate this by going to Settings/Advanced/Performance and have LMS resize the artwork without the helper application.

**Comment by smogol66** [comment]
Thanks mherger, 
I apply your did your changes, now I got no more the annoying the socket issues, but still the connection failures.
Here the logs after a reboot ( Container site as it is more verbose...):
2024/03/02 12:09:13,stdout,[24-03-02 11:09:13.1726] Slim::Utils::ImageResizer::__ANON__ (67) daemon failed to connect: Connection refused
2024/03/02 12:08:29,stdout,[24-03-02 11:08:29.0015] Slim::Utils::ImageResizer::__ANON__ (67) daemon failed to connect: Connection refused
2024/03/02 12:02:47,stdout,[24-03-02 11:02:47.6808] Slim::Utils::ImageResizer::__ANON__ (67) daemon failed to connect: Connection refused
2024/03/02 12:02:26,stdout,[24-03-02 11:02:26.2145] Slim::Music::Artwork::__ANON__ (808) precacheArtwork finished in 0.00898218154907227
2024/03/02 12:02:26,stdout,[24-03-02 11:02:26.2051] Slim::Music::Artwork::precacheAllArtwork (657) Starting precacheArtwork for 206 albums
2024/03/02 12:02:15,stdout,"[24-03-02 11:02:15.7157] main::init (386) Starting Logitech Media Server (v8.4.1, 1708787582, Sun Feb 25 04:53:35 CET 2024) perl 5.032001 - x86_64-linux-gnu-thread-multi
2024/03/02 12:02:15,stdout,Starting Logitech Media Server on port 9000...
2024/03/02 12:02:14,stdout,usermod: no changes

**Comment by michaelherger** [comment]
Can you double check the setting? What is it really set to after the restart?

**Comment by smogol66** [comment]
No Problem, here are the settings of the performance tab:
Database Memory Config : **High (recommended for machines with 1+ GB RAM)** 
Trigger Scan on Preference Changes : **Trigger scan automatically**
Shuffle method : **Use faster, but less balanced shuffle**
Library Statistics : **Enable Library Statistics**
 
Artwork Pre-caching : **Do not pre-cache artwork** 
 
Custom pre-caching specifications

Delete
	100x100_m 	jiveliteskin
	300x300_f 	Material Skin
	600x600_f 	Material Skin (HiDPI)
 
Artwork resizing : **_Use Logitech Media Server to resize artwork_**
 
Server Priority :  **Current Server Priority**
 
Scanner Priority : **0 Normal**
 
Maximum Playlist Length : **2500**

**Comment by mherger** [comment]
I don't get it. There are two places where the daemon would be started. And both check the resizing setting. Can you check the prefs file for the value of `useLocalImageproxy`?

Also: I'd strongly recommend to enable artwork pre-caching, as lack of doing so can severely impact performance when browsing albums.

**Comment by smogol66** [comment]
There is some unattended quote in the setting, can this be the problem?
useBalancedShuffle: 1
useLocalImageproxy: **'1'**
useTPE2AsAlbumArtist: 0
useUnifiedArtistsList: 0
Thanks for the hint about the pre-caching, I will enable it...

**Comment by smogol66** [comment]
I will try to edit the pref file, restart the container and see what happen.

**Comment by smogol66** [comment]
Still getting the issue, I even try to connect to mysqueezebox.com.

**Comment by mherger** [comment]
What do you mean by "even try to connect to MySB"?

Are you sure you're configuring the LMS instance in your Docker?...

**Comment by smogol66** [comment]
As I don't know exactly what is used as service on MySB, I've tried to logging from the LMS to MySD 
to see if anything get better.
Sure, there is only one instance I'm working on. The entries in the file reflect what I'm change over the web interface.
The entries are generated by the scanning activity.
Can it be that some plugin are responsible for that?

**Comment by smogol66** [comment]
After a completely new installation with the same preferences, the issue has disappeared.
I assume that this behaviour has something to do whit the dockers implementation in Synology NAS.

**Comment by smogol66** [comment]
After a completely new installation with the same preferences, the issue has disappeared.
I assume that this behaviour has something to do whit the dockers implementation in Synology NAS.
