### ISSUE TITLE
No audio on SB Radio after LMS upgrade to 8.4.0

### ISSUE THREAD

**Issue by chewiiie** [LMS-Community/slimserver#1006]
The SB radio seems to be playing but I'm not getting any sound, like if it was in mute but it is not.
Sometimes, switching off the radio for a while fixes the issue. But if I put it in sleep mode for a while and try to resume later, then I get no sound again.
It was working perfectly fine with LMS 8.3.x and previous versions.
LMS log attached [server.log.zip](https://github.com/Logitech/slimserver/files/14507641/server.log.zip)

LMS is running on a Pi4 with Raspbian OS. Squeezebox Radio is running the last community firmware. infos below

Logitech Media Server Version: 8.4.0 - 1707213032 @ Thu 08 Feb 2024 12:23:54 PM CET
Server HTTP Port Number: 9001
Operating system: Debian - EN - utf8
Platform Architecture: aarch64-linux
Database Version: SQLite
Total Players Recognized: 8

Squeezebox
Player Model: Squeezebox Radio
Player Type: baby
Firmware: 8.0.1-r16924
Wireless Signal Strength: 100%

Let me know if you need any other info or debug log.
Thanks !

**Comment by michaelherger** [comment]
Do you see the issue with all kinds of media, or only radio streams? From your log file I see that you're hitting an issue many TuneIn users currently are hitting: the add in the beginning can cause playback to fail. But that shouldn't have any impact on playback of Spotify content, or local media.

**Comment by chewiiie** [comment]
Yes I also have that issue with Spotify streams.

**Comment by chewiiie** [comment]
I've just upgraded to the nightly stable 8.4.1, and it seems to be working now. Pending further sleep/wake up testing

**Comment by chewiiie** [comment]
I confirm it is fixed ! 
Thanks
