### ISSUE TITLE
Monkey's Audio won't play

### ISSUE THREAD

**Issue by rdzak** [LMS-Community/slimserver#101]
I installed the latest nighty today hoping this issue is solved. 
System: Ubuntu 15.04, x64.
Error: Couldn't create command line for ape playback for...

Files are scanned no problem, and I remember it sued to work long time ago.
Also in Andvanced > FileTypes I see Monkey's Audio options greyed out.

Advice or fix much, much appreciated.

**Comment by mherger** [comment]
This is not a bug. We no longer provide binaries for all platforms, as this usually can be accomplished using whatever Linux' packet manager.
