### ISSUE TITLE
Radio stops after 2 sec after start And don't  starting play

### ISSUE THREAD

**Issue by piotrek2555** [LMS-Community/slimserver#1015]
when I play the radio via lms. It stops 2 seconds after starting. the symptom is that there is an intro "this is tune in" then the playback stops. I have to restart playback myself.

**Comment by michaelherger** [comment]
See https://forums.slimdevices.com/forum/user-forums/squeezebox-radio/1659280-new-tunein-jingle-advertisement-on-squeezebox-radio.
