### ISSUE TITLE
8.5.0 / Module load error at startup

### ISSUE THREAD

**Issue by un99known99** [LMS-Community/slimserver#1024]
I installed version 8.5.0 on latest patched Debinan install according to the install instruction.

The service is not starting, in the logfile I can see:

Mar 23 11:32:06 myserver systemd[1]: Started logitechmediaserver.service - Logitech Media Server.
Mar 23 11:32:06 myserver squeezeboxserver[5374]: **The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name**
Mar 23 11:32:06 myserver squeezeboxserver[5374]: This is perl 5, version 36, subversion 0 (v5.36.0) built for aarch64-linux-gnu-thread-multi
Mar 23 11:32:06 myserver squeezeboxserver[5374]: (with 53 registered patches, see perl -V for more detail)
Mar 23 11:32:06 myserver squeezeboxserver[5374]: Copyright 1987-2022, Larry Wall
Mar 23 11:32:06 myserver squeezeboxserver[5374]: Perl may be copied only under the terms of either the Artistic License or the
Mar 23 11:32:06 myserver squeezeboxserver[5374]: GNU General Public License, which may be found in the Perl 5 source kit.
Mar 23 11:32:06 myserver squeezeboxserver[5374]: Complete documentation for Perl, including FAQ lists, should be found on
Mar 23 11:32:06 myserver squeezeboxserver[5374]: this system using "man perl" or "perldoc perl".  If you have access to the
Mar 23 11:32:06 myserver squeezeboxserver[5374]: Internet, point your browser at https://www.perl.org/, the Perl Home Page.
Mar 23 11:32:06 myserver squeezeboxserver[5374]: *******
Mar 23 11:32:06 myserver squeezeboxserver[5374]: NOTE:
Mar 23 11:32:06 myserver squeezeboxserver[5374]: If you're running some unsupported Linux/Unix platform, please use the buildme.sh
Mar 23 11:32:06 myserver squeezeboxserver[5374]: script located here:
Mar 23 11:32:06 myserver squeezeboxserver[5374]: https://github.com/Logitech/slimserver-vendor/tree/public/8.5/CPAN
Mar 23 11:32:06 myserver squeezeboxserver[5374]: If 8.5 is outdated by the time you read this, Replace "8.5" with the major version
Mar 23 11:32:06 myserver squeezeboxserver[5374]: You should never need to do this if you're on Windows or Mac OSX. If the installers
Mar 23 11:32:06 myserver squeezeboxserver[5374]: don't work for you, ask for help and/or report a bug.
Mar 23 11:32:06 myserver squeezeboxserver[5374]: *******
Mar 23 11:32:06 myserver squeezeboxserver[5374]: #011#011#011
Mar 23 11:32:06 myserver squeezeboxserver[5374]: Exiting..
Mar 23 11:32:06 myserver systemd[1]: logitechmediaserver.service: Deactivated successfully.

Any help on this topic?

Thanks in advance

**Comment by michaelherger** [comment]
What package did you install? Looks as if you didn't use the ARM version.

**Comment by un99known99** [comment]
@michaelherger 

I used logitechmediaserver_8.5.0_amd64.deb

my server:
Linux myserver 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux

**Comment by un99known99** [comment]
ok, used different package

pi@jitsi:[/usr/local/etc/INSTALL/SQUEEZEBOX] $ sudo dpkg -i logitechmediaserver_8.5.0_arm.deb
Selecting previously unselected package logitechmediaserver.
(Reading database ... 80563 files and directories currently installed.)
Preparing to unpack logitechmediaserver_8.5.0_arm.deb ...
Unpacking logitechmediaserver (8.5.0) ...
dpkg: dependency problems prevent configuration of logitechmediaserver:
 logitechmediaserver depends on libio-socket-ssl-perl; however:
  Package libio-socket-ssl-perl is not installed.
 logitechmediaserver depends on libcrypt-openssl-rsa-perl; however:
  Package libcrypt-openssl-rsa-perl is not installed.

dpkg: error processing package logitechmediaserver (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 logitechmediaserver


sudo apt --fix-broken install


pi@jitsi:[/usr/local/etc/INSTALL/SQUEEZEBOX] $ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libcrypt-openssl-bignum-perl libcrypt-openssl-random-perl libcrypt-openssl-rsa-perl libio-socket-ssl-perl libnet-ssleay-perl libregexp-ipv6-perl liburi-perl perl-openssl-defaults
Suggested packages:
  libbusiness-isbn-perl libwww-perl debhelper
The following NEW packages will be installed:
  libcrypt-openssl-bignum-perl libcrypt-openssl-random-perl libcrypt-openssl-rsa-perl libio-socket-ssl-perl libnet-ssleay-perl libregexp-ipv6-perl liburi-perl perl-openssl-defaults
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 688 kB of archives.
After this operation, 2,596 kB of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://deb.debian.org/debian bookworm/main arm64 perl-openssl-defaults arm64 7+b1 [7,924 B]
Get:2 http://deb.debian.org/debian bookworm/main arm64 libnet-ssleay-perl arm64 1.92-2+b1 [308 kB]
Get:3 http://deb.debian.org/debian bookworm/main arm64 libio-socket-ssl-perl all 2.081-2 [219 kB]
Get:4 http://deb.debian.org/debian bookworm/main arm64 libcrypt-openssl-bignum-perl arm64 0.09-2+b1 [22.4 kB]
Get:5 http://deb.debian.org/debian bookworm/main arm64 libcrypt-openssl-random-perl arm64 0.15-3+b1 [10.5 kB]
Get:6 http://deb.debian.org/debian bookworm/main arm64 libcrypt-openssl-rsa-perl arm64 0.33-3+b1 [23.9 kB]
Get:7 http://deb.debian.org/debian bookworm/main arm64 libregexp-ipv6-perl all 0.03-3 [5,212 B]
Get:8 http://deb.debian.org/debian bookworm/main arm64 liburi-perl all 5.17-1 [90.4 kB]
Fetched 688 kB in 1s (733 kB/s)
Selecting previously unselected package perl-openssl-defaults:arm64.
(Reading database ... 84915 files and directories currently installed.)
Preparing to unpack .../0-perl-openssl-defaults_7+b1_arm64.deb ...
Unpacking perl-openssl-defaults:arm64 (7+b1) ...
Selecting previously unselected package libnet-ssleay-perl:arm64.
Preparing to unpack .../1-libnet-ssleay-perl_1.92-2+b1_arm64.deb ...
Unpacking libnet-ssleay-perl:arm64 (1.92-2+b1) ...
Selecting previously unselected package libio-socket-ssl-perl.
Preparing to unpack .../2-libio-socket-ssl-perl_2.081-2_all.deb ...
Unpacking libio-socket-ssl-perl (2.081-2) ...
Selecting previously unselected package libcrypt-openssl-bignum-perl.
Preparing to unpack .../3-libcrypt-openssl-bignum-perl_0.09-2+b1_arm64.deb ...
Unpacking libcrypt-openssl-bignum-perl (0.09-2+b1) ...
Selecting previously unselected package libcrypt-openssl-random-perl:arm64.
Preparing to unpack .../4-libcrypt-openssl-random-perl_0.15-3+b1_arm64.deb ...
Unpacking libcrypt-openssl-random-perl:arm64 (0.15-3+b1) ...
Selecting previously unselected package libcrypt-openssl-rsa-perl:arm64.
Preparing to unpack .../5-libcrypt-openssl-rsa-perl_0.33-3+b1_arm64.deb ...
Unpacking libcrypt-openssl-rsa-perl:arm64 (0.33-3+b1) ...
Selecting previously unselected package libregexp-ipv6-perl.
Preparing to unpack .../6-libregexp-ipv6-perl_0.03-3_all.deb ...
Unpacking libregexp-ipv6-perl (0.03-3) ...
Selecting previously unselected package liburi-perl.
Preparing to unpack .../7-liburi-perl_5.17-1_all.deb ...
Unpacking liburi-perl (5.17-1) ...
Setting up perl-openssl-defaults:arm64 (7+b1) ...
Setting up libcrypt-openssl-bignum-perl (0.09-2+b1) ...
Setting up libregexp-ipv6-perl (0.03-3) ...
Setting up libcrypt-openssl-random-perl:arm64 (0.15-3+b1) ...
Setting up libcrypt-openssl-rsa-perl:arm64 (0.33-3+b1) ...
Setting up liburi-perl (5.17-1) ...
Setting up libnet-ssleay-perl:arm64 (1.92-2+b1) ...
Setting up libio-socket-ssl-perl (2.081-2) ...
Setting up logitechmediaserver (8.5.0) ...
Adding system user `squeezeboxserver' (UID 113) ...
Adding new user `squeezeboxserver' (UID 113) with group `nogroup' ...
Not creating home directory `/usr/share/squeezeboxserver'.
Created symlink /etc/systemd/system/multi-user.target.wants/logitechmediaserver.service → /lib/systemd/system/logitechmediaserver.service.
Processing triggers for man-db (2.11.2-2) ...
needrestart is being skipped since dpkg has failed

**sudo apt --fix-broken install** seems to solved "brokness"

**Comment by un99known99** [comment]
but squeezbox itself still "dead", how to get back previous functionality like displaying clock, etc. ...... ?

Still server of mysqueezbox.com 99.80.253.17 in showing non connection possible, do I have to link that (and how?) to the local server?

**Comment by michaelherger** [comment]
How do you define "dead"? Can you access http://localhost:9000 on that machine?

**Comment by un99known99** [comment]
seems working now, getting local IP, so how can I silence the calls to baby.squeezenetwork.com now? Old server cannot be removed

**Comment by michaelherger** [comment]
There's a new community firmware in the works which tries to get rid of all ties with the old infrastructure. Make sure you join https://forums.slimdevices.com to not miss any updates on that.
