### ISSUE TITLE
Play Other Songs In Album

### ISSUE THREAD

**Issue by marcolefo** [LMS-Community/slimserver#1025]
Hi

The mode _Play other songs in album or directory_ of _Play Other Songs In Album_ in _Basic Settings_ of the player does not work anymore.

When I select a song of an album or a playlist, the player stop after the end of the song. 
Before it was playing the next song of the album.

I thinks it's after 8.3 to 8.5 upgrade.
I tried to upgrade 8.5.0 to 8.5.1~1711149930

```
Player Model: SqueezeLite
Player Type: squeezelite
Firmware: Max2Play v1.0.3 based on v1.8.7-999
Logitech Media Server Version: 8.5.1 - 1711149930 @ Sat 23 Mar 2024 04:19:01 AM CET
Operating system: Debian - EN - utf8
Platform Architecture: x86_64-linux
Database Version: SQLite
Total Players Recognized: 3
```

Thanks a lot for your work !

**Comment by michaelherger** [comment]
What interface are you using? I believe this is only for the menu mode of the "classic" players.

**Comment by marcolefo** [comment]
I use the max2play squeezelite  on a raspberry with touch screen 7" and the web squeezebox 
[Capture d’écran 2024-03-24 à 01.28.36.pdf](https://github.com/LMS-Community/slimserver/files/14733968/Capture.d.ecran.2024-03-24.a.01.28.36.pdf)
[Capture d’écran 2024-03-24 à 01.29.53.pdf](https://github.com/LMS-Community/slimserver/files/14733974/Capture.d.ecran.2024-03-24.a.01.29.53.pdf)

**Comment by michaelherger** [comment]
I believe those options are for the display menu only, not for the web UI.

**Comment by marcolefo** [comment]
I confirm that it does not work with a player squeezelite (and jive lite) on a pi.
