### ISSUE TITLE
Play count increase with in-track jumps

### ISSUE THREAD

**Issue by AF-1** [LMS-Community/slimserver#1027]
If you jump to a different time in a track that's already playing, the track's play count increases with every jump - which it shouldn't.
Checked with local tracks on LMS 9.0.0 (1711180501 @ Sun Mar 24), macOS & latest Docker dev image, Default skin & Material.

**Steps to reproduce:**
- Add a local track to your client playlist.
- Check the play count on the Song info page (if it's not displayed it's probably = 0).
- Starting playing that track.
- Check the play count on the Song info page (Default skin) again. PC increased by 1.
- Jump some seconds forward in that song.
- Check the play count on the Song info page again. PC increased by 1. And +1 for every subsequent jump.

**Comment by michaelherger** [comment]
Fixed via #1080 - thanks @darrell-k!
