### ISSUE TITLE
Create new artwork for Lyrion

### ISSUE THREAD

**Issue by terual** [LMS-Community/slimserver#1030]
There are a couple of images which need a new version:

Server:
- [x] ~https://github.com/LMS-Community/slimserver/blob/public/9.0/HTML/Default/html/images/logo.png~
- [x] ~https://github.com/LMS-Community/slimserver/blob/public/9.0/HTML/EN/html/images/lms.png~
- [x] https://github.com/LMS-Community/slimserver/blob/public/9.0/HTML/EN/html/images/lms.svn
- [x] https://github.com/LMS-Community/slimserver/blob/public/9.0/HTML/EN/html/images/slimdevices_logo.gif
- [x] https://github.com/LMS-Community/slimserver/raw/public/9.0/HTML/EN/html/mypage.ico

Platforms:
- [x] https://github.com/LMS-Community/slimserver-platforms/blob/public/9.0/osx/Preference%20Pane/icon.icns
- [x] https://github.com/LMS-Community/slimserver-platforms/blob/public/9.0/osx/Preference%20Pane/logitech-logo.png
- [x] https://github.com/LMS-Community/slimserver-platforms/blob/public/9.0/win32/res/SqueezeCenter.ico
- [x] https://github.com/LMS-Community/slimserver-platforms/blob/public/9.0/win32/res/SqueezeCenterOff.ico
- [x] https://github.com/LMS-Community/slimserver-platforms/blob/public/9.0/win32/res/lms_splash.png
- [x] https://github.com/LMS-Community/slimserver-platforms/blob/public/9.0/win32/res/logitech-logo.png
- [x] https://github.com/LMS-Community/slimserver-platforms/blob/public/9.0/win32/res/logitech-squeezebox.png
- [x] https://github.com/LMS-Community/slimserver-platforms/blob/public/9.0/win32/installer/logo.bmp

Other:
- [x] https://lyrion.org - I guess at the very least a logo and a favicon (can be re-used from LMS).
- [x] https://forums.slimdevices.com/filedata/fetch?filedataid=45076 (top left banner logo on https://forums.slimdevices.com)

**Comment by michaelherger** [comment]
Thanks @gobuleberbu!
