### ISSUE TITLE
LMS Web controller interface problem with Artists whose first char not in 0-9, A-Z, a-z

### ISSUE THREAD

**Issue by Daksol** [LMS-Community/slimserver#1047]
### INTRO

There is a problem in the functionality of the "first letter navigation bar" on the out-of-box HTML interface handles a locally stored Music Library for Artist names which start with a character outside 0-9, a-z, A-Z.

So for Icelandic music aficionados think Ólafur Arnalds and Ásgeir Trausti.

This problem can be made to go away if tracks are tagged with ARTISTSORT and ALBUMARTISTSORT tags which use regular "a-z, A-Z" first characters. However situation as it stands is really confusing. The first letter navigation bar becomes out of synch with the Artists - the more Artists with non A-Z first letters, the worse it gets as you go thru the Alphabet.

This issue raised after examining how my set up works, and from feedback from a number of discussions in the forums.

### APPLICABILITY

The problem as describes applies to:-
- Functionality - Library Navigation for Artist and Album Artists only (not Albums which is fine)
- Controllers
    - the out-of-box web controller interface of LMS v8.5
    - Squeezelite-X (for Windows) with Default Skin (which closely resembles default player)

Other interfaces tested:-
- problem does not apply to these interfaces
    - Squeezelite-X with Material Skin (the special chars do not get added to first letter navigation)
    - Squeezebox Radio
    - Squeezer controller for Android 
- Note that for these interfaces the Artists with non A-Z first letters appear in Artists listing after the Zs.
- And, by contrast, the Albums are handled optimally - the Á È Ó albums are in the main list near A E and O as is sensible.

**Problem NOT there for ALBUMS!!**

All interfaces, hardware etc for Albums handled this situation just fine.
 - Where there is a first letter navigation bar (so LMS std web) includes the special characters in the right place logically, and you can click the special char to see the Albums. And the first letter navigation blocks stay in synch.
 - Where no first letter navigation bar the albums with special chars as first letter appear in the main list of albums at appropriate point (and not flushed to after the Zs)  

### PROBLEM DEMO

To reproduce the problem add the three FLAC files (attached to this post in a zip file), and add them to your music library, and then do a full scan. This introduces artists, album artists and albums starting with special letters:-
- Á A-acute, unicode 193
- È E-grave, unicode 200
- Ó O-acute unicode 211 
**[FLAC Files with special first chars for Artist and Album tags.zip](https://github.com/LMS-Community/slimserver/files/14919784/FLAC.Files.with.special.first.chars.for.Artist.and.Album.tags.zip)**

To show the problem there are included Screenshots from Album Artists, though the same behaviour is there with All Artists.

- First letter navigation bar not fully functional
- The Album Artists first letter index bar has included the three special letters (Á A-acute, È E-grave, Ó O-acute) at logical places in that bar. Unfortunately if you click those letters (Á È Ó)  no matching Artists are shown.
![image](https://github.com/LMS-Community/slimserver/assets/42010857/b7f3c42b-18ef-4496-9faf-d8b76efcf857)

- To see what it should be working like, just click across to "Albums" where the first letter navigation bar works as was intended.

- Mismatches in the first letter blocks

    - If we look at the "ÁABC" block of Artists, there is one Artist (Daft Punk) which belongs with the Ds.
![image](https://github.com/LMS-Community/slimserver/assets/42010857/c2929ffa-db4f-4bdc-b8aa-739e2331d6bf)

    -  This mismatch gets worse as you go thru the alphabet. The block "DÈEFGH" has two Artists at the end who belong in letter I (Iron Butterfly, Interpol). 
![image](https://github.com/LMS-Community/slimserver/assets/42010857/30b19b07-41f1-4260-b05c-db4859862dfe)

    - And after the special O, in blck "ÓOPQRST" there is now a mismatch of three Us - U2, Umberto Eco and Ultravox. 
![image](https://github.com/LMS-Community/slimserver/assets/42010857/b09d6c10-8099-4eb7-adff-2ecd4f520f17)

- The Artists with non A-Z first chars are listed after Z
     - This is not necessarily wrong - this is where they get placed via a raw Unicode number sort
     - But clearly mismatched wrt the placement of the special letters in the first letter index bar
     - But Albums does it better
    
![image](https://github.com/LMS-Community/slimserver/assets/42010857/1fd6b6d9-6c9d-4844-bf45-527d77ad2311)

**PRAISING THIS INTERFACE**
I understand what those working on this interface were trying to achieve - by recognising that the likes of Á, È, Ó belong with A, E and O. And that is approach (if executed correctly) would benefit those LMS users who lacked the capability or inclination to add in ARTISTSORT tags and the like. And this was achieved for the Albums. 

**WHERE THE PROBLEM MAY LIE**
Contrast the difference between the Artists and the Albums on Squeezebox Radio and on Android Squeezer. It  looks as if the default sort order (when items do not have ARTISTSORT tags etc) is different between Albums and Artists. So to make an educated guess (just possibly) the daylight between Artists and Albums might be in the database, rather than the controller interface.

**Comment by Daksol** [comment]
An observant commenter (@fastfwd) in Forums found that this problem is broadly similar to that which was raised (but not fixed) in #388

That one mentioned both Albums and Artists with a problem - but given Albums now appears ok, let us be optimistic wrt Artists too.

**Comment by michaelherger** [comment]
@Daksol can you confirm the locale you're using on that system? You should see what LMS is using in Settings/Information.

**Comment by Daksol** [comment]
Presume the relevant string is "EN - utf8" (full server status below)

I would be happy to test further with different locale settings - advise how I can do that with my Docker setup started up via a docker-compose file.

Note that LMS running in Docker in Host mode (so Castbridge works) - but I presume that should not affect locale and such.

Edit: _doing Locale in Docker looks messy. Other thing I could do is to create VMs on my homelab hypervisor, selecting regional options for places with other alphabets,_ 

_The albums are under control - only the artists still to conquer?!!_

***

Logitech Media Server Status

- Logitech Media Server Version: 8.5.0 - 1710422688 @ Thu Mar 14 16:29:49 CET 2024
- Hostname: HPT620
- Server IP Address: 192.168.5.75
- Server HTTP Port Number: 9005
- Operating system: Debian (Docker) - EN - utf8
- Platform Architecture: x86_64-linux
- Database Version: SQLite
- Total Players Recognized: 2

**Comment by carsten-h** [comment]
I think I am talking about the same issue here: [https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1686900-ordering-of-artists-with-lms-8-5-0-1710422688](url)

What I found out, is that it worked in LMS 8.3.1 and was broken in LMS 8.4.0.

**Comment by Daksol** [comment]
> I think I am talking about the same issue here: [https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1686900-ordering-of-artists-with-lms-8-5-0-1710422688](url)
> 
> What I found out, is that it worked in LMS 8.3.1 and was broken in LMS 8.4.0.

Indeed quite a few Forums posts about this. I felt confident that this was something worth taking up a level wrt attention - given that "Albums" works just fine. While "locale" may be an issue, it is difficult to see how it is not an issue for Albums, but is for Artists.

IMHO this is kind of thing we need to fix in order to keep a wide audience for the LMS ecosystem; not everyone out there has ability or inclination to add lots of ARTISTSORT tags. 

QQ for you. Do Albums sort Ok for you? What is yr locale setting?

**Comment by Daksol** [comment]
### v8.31 does Artist sorting fine

Following up @carsten-h comment. 
I installed LMS v8.3.1 from the lmscommunity/logitechmediaserver:8.3.1 docker image.
As @carsten-h says the ordering of the Artists (and Albums) works just fine on that version of LMS.
The extra letters appear in the A-Z navigation bar in the right places. And the artists appear in the logical locations of the sort order (and not flushed out past the ZZZZs).

Locale: EN - UTF

**Comment by carsten-h** [comment]
> Do Albums sort Ok for you?

Yes, they are totally Ok!

> What is yr locale setting?

LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=

Inside LMS is: "Debian - DE - utf8"

Michael wrote in the forum: "My guess is that this is related to the "Release Type" changes introduced in 8.4."

**Comment by Daksol** [comment]
Minor refinement. LMS v8.3.2 also works fine wrt Artist sort order. Problem started with v8.4
(I determined this by running LMS via the Docker images for v8.3.1, 8.3.2, 8.4.0 and observing changes).

**Comment by carsten-h** [comment]
Yes, this is correct! I got a 8.3.2 version from Michael to test.

**Comment by carsten-h** [comment]
As you can read in the thread in the forum, that I linked above, Michael found the possible solution.

In the file /usr/share/perl5/Slim/Control/Queries.pm (maybe it is in another folder in your installation)
has been a change in line 859:
https://github.com/LMS-Community/slimserver/commit/1cd7391f191df7b3ed1c6148b4acde545d80ae4e

If you take the version 8.4.0 or 8.5.0 and edit the file locally into this:
$sort = "contributors.namesort $collate, contributors.musicbrainz_id";
And now restart your server (maybe this is not neccessary), your sort order should be correct again!

**Comment by michaelherger** [comment]
Please give tomorrow's builds another try. Thanks!

**Comment by carsten-h** [comment]
I tested it with the build: logitechmediaserver_8.5.2~1713971774_amd64.deb and it works without any problem again!

Thank you very much!
