### ISSUE TITLE
Erroneous Album Artists appear in Library Views

### ISSUE THREAD

**Issue by texneus** [LMS-Community/slimserver#1052]
LMS 8.5.0

I have a library view created using a path (i.e. contains music\Jazz and Swing\).  Under the Album Artist view there are several artists listed that are not album artists.  For example -

1) "Tony Bennett feat. Count Basie Big Band" is substituted for "Tony Bennett" even though all Tony Bennett albums in this directory are tagged ALBUMARTIST=Tony Bennett.  There is one unrelated file in a different directory that is tagged "Tony Bennett feat. Count Basie Big Band", but that does not explain why tags for these albums are not recognized/used.

Ex:
![image](https://github.com/LMS-Community/slimserver/assets/23441049/5f9ea40e-75c7-453a-a2a4-254af5e864e1)

Sample of all tags containing the word 'Tony'
$ metaflac --export-tags-to=- 01-01*.flac | grep Tony
ALBUMARTIST=Tony Bennett
ALBUMARTISTS=Tony Bennett
ALBUMARTISTSORT=Bennett, Tony
ARRANGER=Tony Bennett
ARTIST=Tony Bennett
ARTISTS=Tony Bennett
ARTISTSORT=Bennett, Tony
PERFORMER=Tony Bennett (lead vocals)

2) Tracks with ALBUMARTIST=Various Artists are listed multiple times under individual track artists.  That is not consistent with expectation of choosing to view Album Artists.  All Various Artists albums/tracks should appear under "Various Artists" only.

Ex: (see first item in screen capture above)

3) There are some very mysterious artist entries that are not even relevant and choosing those only results in a single "Empty" descriptor for the album listing.  I have no idea where these come from as they do not match any existing album or track artist tag.

Ex:
![image](https://github.com/LMS-Community/slimserver/assets/23441049/54f6addf-32b5-4c4d-aed7-087ba15494fe)![image](https://github.com/LMS-Community/slimserver/assets/23441049/f3dfa9d2-ae81-42dc-a566-594789bb5fed)

**Comment by michaelherger** [comment]
Please note that an artist's name is not defined per Library. So if you have a single incorrectly tagged track or album you could end up with this kind of issue. You'll have to check all files related to "Tony Bennett" and check artists, roles, and Musicbrianz IDs.

**Comment by texneus** [comment]
All albums are tagged correctly.  As noted in 1, there is a legitimate album by "Tony Bennett feat. Count Basie Big Band" with "ALBUMARTIST=Tony Bennett feat. Count Basie Big Band".  Surely LMS can tell the difference between "Tony Bennett" and "Tony Bennett feat. Count Basie Big Band".  I'm pretty sure this and the others are recent phenomena.

FWIW, poking around it seems #3 is confusing COMPOSER tag with ALBUMARTIST, but is only displaying them if there are other albums by that same artist in LMS.

**Comment by michaelherger** [comment]
Two differently spelled artists would not be merged unless there were identical Musicbrainz IDs. LMS doesn't invent things. Feel free to share your library.db with me and I can look into this.

**Comment by texneus** [comment]
> Two differently spelled artists would not be merged unless there were identical Musicbrainz IDs.

Ah, that explains the item 1 behavior (maybe - the ARTISTID and ALBUMARTISTID are the same for all Tony Bennett albums, but other MB IDs seem unique), but that is the way this particular album comes from Musicbrainz, i.e. it is correctly tagged.

Ref: https://musicbrainz.org/release-group/8fa1df76-c0c5-3d9d-bcd3-010bc5f365d7

What I'm having difficulty understanding right now though is why Musicbrainz IDs play into this at all.  ALBUMARTIST and all other relevant tags are already provided, no Musicbrainz IDs or lookups are needed.  So, if I might ask, what is the purpose of using Musicbrainz IDs here?  More specifically, how would I use this feature to my advantage?  If there is no clear advantage, can it be turned off since it can cause problems?

Does this also play into items 2 and 3 above?  What do I need to look for?

> Feel free to share your library.db with me and I can look into this.

Certainly.  If we reach a dead end, where should I send it?

**Comment by michaelherger** [comment]
If you don't care about Musicbrainz IDs, then get rid of them. They're really useful for those who care a lot about groupings and what not, but can be painful if you don't. I don't use them. Many prefer to fire up something like mp3tag and remove them from all there files.

**Comment by texneus** [comment]
I do care, actually.  Musicbrainz tags are used heavily to fetch aditional metadata in Kodi and Jellyfin.  Furthermore this is only a temporary fix.  Removed tags will be re-added next time I run Picard and all new music will have these tags by default.  A test case on a small sample of music also shows it does not resolve items 2 and 3.  It honestly would make more sense for me to make an exception to the ARTISTID tag in the affected album(s).

What I still don't know though is what's going on with items 2 and 3?

**Comment by michaelherger** [comment]
2.) make sure you have the compilation flag set on those tracks
3.) might be a caching issue which would go away after a full wipe & rescan

You'd probably get better support on https://forums.slimdevices.com, where there are a ton of super helpful people.

**Comment by texneus** [comment]
> 2.) make sure you have the compilation flag set on those tracks

OK yes, I found some ancient documentation saying to add a COMPILATION tag set to 0 to avoid having LMS doing it's own thing with them.  That works.


> 3.) might be a caching issue which would go away after a full wipe & rescan

It's not a caching issue.  I always clear and rescan the entire library precisely to avoid this problem.  As noted in my second post, the errant artists are actually composers who appear when they also happen to be album artists in another library.  The only way I have found to rid myself of them is to delete the composer tags which isn't acceptable.  I suggest this is a bug.


> You'd probably get better support on https://forums.slimdevices.com/, where there are a ton of super helpful people.

Yes, and not to sound critical (this is intended as constructive feedback) but the forums you point at also show several people with well curated collections having the same kinds of issues.

Ex:
https://forums.slimdevices.com/forum/user-forums/logitech-media-server/107807-composers-in-all-artist-list
(I don't see any meaningful troubleshooting or a solution given)

https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1673617-album-artist-issue-in-lms-8-4/page2
(Suggestions to retag an entire library to suit one player should be ringing alarm bells.  It potentially breaks other players/organizers that have no issues.  That other players/organizers do not have these kinds of problems should convince the problem is not the tags.)

LMS might be organizing/presenting music as intended, but recent experience and forum posts seem to suggest it's not organizing/presenting music as expected.  I humbly suggest the logic LMS is using to read/interpret tags and organize/present music may be due for an overhaul.  I don't know what changed, when, or why, but I'm sure it didn't use to have these problems, and I see others saying the same things.

Maybe it just needs to be brought up to date given modern tagging software and tag interpretations.  Maybe it's just had so many band-aids, cluges, and bodges applied over the years it's become confused.  I don't know.  I do know the absence of a compilation tag means the album is not a compilation (don't look for excuses to treat it as one).  I do know when I choose to browse by album artists I should see only album artists (not composers, not track artists).  I want to browse my collection grouped by ALBUMARTIST, (track) ARTIST, etc., not grouped by MUSICBRAINZ IDs (I still don't know what advantage this is intended to provide and seems to have needlessly confused many).

Anyway, make of this info as you will and apologize if it sounds a bit curt. Feel free to close if there is no further action.

**Comment by michaelherger** [comment]
Any change to the scanner will have some installations go "unexpected". People are used to a way of behaviour. If it changes, they consider it wrong. So what happened is the scanner did adjust to eg. use MBIDs more consequently. That's an improvement for many who use taggers supporting Musicbrainz, but makes things worse for all those who didn't care in the past.

So you can rewrite as much as you like: people will always complain. What you consider wrong might be a big relieve for someone else.

I believe the scanner is in better shape than in the past, behaving more consistently than before. But it's not perfect, that's for sure. Feel free to dive in to the code and track down those remaining bugs!

**Comment by gharris999** [comment]
I'm a little confused by LMS's current behavior regarding compilations.  For FLAC albums with more than one artist, a explicit COMPILATION=1 tag has to be set for the album to be recognized as a compilation and to show up in Various Artists.  But with MP3s, there's no similar requirement for a TCMP:1 tag to be set.  Maybe it's just me, but that seems inconsistent.

**Comment by michaelherger** [comment]
Compilations... would be worth their own ticket. But I believe the official statement is to use the compilation flag and not rely on any guesswork.
