### ISSUE TITLE
Feature request: Being able to control powerplug to switch on / off external amplifier

### ISSUE THREAD

**Issue by storfusker** [LMS-Community/slimserver#1053]
First I want to thank this community for keeping the Logitech Squeezebox platform alive.
It's still the best streaming platform out there

It would be nice to be able to switch on / off an external power amplifier when switching on / off the Squeezebox receiver from the GUI or from the Controller
That can be done via eg. a Tasmota enabled plug.
Either via MQTT or directly via the api in the Tasmota software
That way it is not necessary to have a separate circuit listening on the audio output from the Squeezebox receiver

Br Steen from Denmark

**Comment by michaelherger** [comment]
I'm pretty sure there already is a plugin to do that. I'd recommend you ask in forums.slimdevices.com.
