### ISSUE TITLE
Analytics plugin: reporting delay is dependent on debug setting 

### ISSUE THREAD

**Issue by terual** [LMS-Community/slimserver#1055]
A lot of users use the debug setting for `plugin.analytics` so they can see what is being reported.  According to https://github.com/LMS-Community/slimserver/blob/661131affb3134f3bed0a64d9bf24d12830c0987/Slim/Plugin/Analytics/Plugin.pm#L34 the delay timing is reduced when debug logging is used.

To solve this maybe we can also show what data is being reported to info logging, that way users can see what is being reported and still use the 4 minutes delay. And when you are a developer and want to quickly check what is being reported you can use the debug logging for the plugin.

**Comment by michaelherger** [comment]
Right! Too many people are watching logs. I thought I was the only one doing this 😁.
