### ISSUE TITLE
Feature request : Plugin for SPOTUBE

### ISSUE THREAD

**Issue by GG700** [LMS-Community/slimserver#1059]
Hi,

Is that possible to create a plugin for SPOTUBE ?
SPOTUBE have an API : https://github.com/KRTirtho/spotube

SPOTUBE is a sofware, it uses SPOtify and search the musics in YouTUBE.

thanks.

**Comment by michaelherger** [comment]
Please ask on forums.slimdevices.com. But I don't really see a need, as there are plugins for both Spotify (Spotty) and YouTube.

**Comment by GG700** [comment]
Hi, 

This software allows you to have the same interface as spotify. This is an important feature.

**Comment by michaelherger** [comment]
To answer your question: yes, it's possible to create a plugin. But you'll have to find someone to do it, or do it yourself. It's not going to happen as part of LMS.
