### ISSUE TITLE
Add WORK tag to additional browse modes plugin

### ISSUE THREAD

**Issue by Blackfiction** [LMS-Community/slimserver#1062]
Would it be possible to add the Work tag to the additional browse modes plugin so that users can browse by work instead of album and artist?

**Comment by darrell-k** [comment]
Please expand a little bit on what you would like to see here.

You can already browse all Works (sorted by Composer) from the top level "Works" menu, and you can see a list of works for a composer or featuring another artist by browsing to that artist, either through an additional browse modes menu or the standard artists menus.

**Comment by Blackfiction** [comment]
Maybe everything is covered indeed. Only thing I can now think of is that users can browse the works based on specific genres? Like if you have specified in a tag that the work is from the baroque period. Or for example if it is chamber music.

**Comment by darrell-k** [comment]
PR https://github.com/LMS-Community/slimserver/pull/1064 created. Now you can do something like:

![image](https://github.com/LMS-Community/slimserver/assets/97928054/76201863-2ce9-4c4e-9941-8795723ce447)

**Comment by michaelherger** [comment]
Closed via #1064.

@darrell-k - you can have issues closed by prefixing a PR's description with something like "fix #1064" (fix + hashtag are crucial). That way the issue would be closed when the PR is merged.

**Comment by Blackfiction** [comment]
thanks!!
