### ISSUE TITLE
podcast plugin - cannot delete items from list (Version: 9.0.0 - 1714490454)

### ISSUE THREAD

**Issue by dierochade** [LMS-Community/slimserver#1078]
I run Lyrion Music Server Version: 9.0.0 - 1714490454 

In settings → podcasts → I can add new sources, but cannot delete. The delete button ('Löschen') seems just plain text and no action is executed.

![image](https://github.com/LMS-Community/slimserver/assets/125600882/d41061e3-ccd5-4c2b-b182-7c4b52ed21c6)

**Comment by michaelherger** [comment]
Check the box, then apply the changes with the button bottom right (not shown in your screenshot).
