### ISSUE TITLE
Slimserver fails to play streams without .mp3/.mp2/etc. ending in the url

### ISSUE THREAD

**Issue by Hypfer** [LMS-Community/slimserver#109]
I'm currently trying to get my DVB-C radio channels running on my squeezeboxes.
For this i'm using tvheadend which provides those as  "file format: MPEG-TS (MPEG-2 Transport Stream) (libavformat)" to quote mplayer.

Problem is:
The squeezebox server just fails to play it and displays "Fehler: Wiedergabeliste ist leer" on the connected squeezeboxes.

I've investigated the problem and found out that the stream doesn't need recoding and/or remuxing but just a "special" url format.

Here's a command for vlc to proxy the stream and make it work:

cvlc : -v http://tvheadendhost:9981/play/stream/channel/ad42deb29e4f478ab49199a4431f3ced --sout '#http{mux=raw,dst=:8080/bla.mp2}'

(Open http://machinewithvlc:8080/bla.mp2 in the squeezebox server)

And here's a command which just fails with the empty playlist message:

cvlc : -v http://tvheadendhost:9981/play/stream/channel/ad42deb29e4f478ab49199a4431f3ced --sout '#http{mux=raw,dst=:8080/}'

(Open http://machinewithvlc:8080/ in the squeezebox server)

For testing, you can just replace the tvheadend stream url with a normal internet radio station like for example http://main-high.rautemusik.fm (Just don't forget to change bla.mp2 to bla.mp3 in this case)
The behaviour is the same.

**Comment by mherger** [comment]
I'm not familiar with tvheadend and cvlc at all. But what would you get if you used "curl -vI http://..." to request your URL?

LMS needs to somehow learn what your stream is. Either by its extension or by a content-type header. Otherwise it can't play it.

**Comment by Hypfer** [comment]
Server: HTS/tvheadend
Cache-Control: no-cache
Connection: Close
Content-Type: audio/mp2t

A content type header is set. Maybe LMS doesn't know mp2t? (It can play it, though.)

**Comment by mherger** [comment]
Yep, that type would not be recognized. You could add it though:
- find the file types.conf within the LMS installation (location depends on your OS)
- create a file called custom-types.conf in that same folder
- add the following line:

```
mp3       mp2,mp3         audio/mp2t     audio
```

Make sure you don't have any whitespace except between those three fields ID, extension, content type, and media type. Then restart LMS and try again.

You could get more information by setting logging for player.streaming.direct and player.streaming.remote to debug.

**Comment by Hypfer** [comment]
Okay so it at least tries to play the stream now, however it's not remotely sounding like music. Just some audio glitches with silence inbetween.

[16-08-25 09:08:20.2232] Slim::Utils::Misc::msg (1243) Warning: [09:08:20.2231] Error: Unable to read at least 577 bytes from file.
[16-08-25 09:08:20.2234] Slim::Utils::Misc::msg (1243) Warning: [09:08:20.2233] Unable to find any MP3 frames in file: (filehandle)
[16-08-25 09:08:23.0264] Slim::Player::Protocols::HTTP::canSeekError (815) bitrate unknown for: http://tvheadendhost:9981/stream/channel/a8a142c5bdb1c07726c4fbc7f8cc150c?profile=Squeezebox&ticket=52ABF5FBB3525B355C0C9725E2549D1CD52E30DC

Does this have anything todo with the glitching or do I need to set some other logging feature to verbose?

Tvheadend streams take some time before they work like they should. mplayer for example spams me with cache not filling messages before it starts playing. Could that be related?

**Comment by Hypfer** [comment]
Cache size set to 320 KBytes
Cache fill: 19.11% (62604 bytes)   

libavformat version 54.6.100 (internal)
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
Cache empty, consider increasing -cache and/or -cache-min. [performance issue]
TS file format detected.

# NO VIDEO! AUDIO MPA(pid=256) NO SUBS (yet)!  PROGRAM N. 1

Opening audio decoder: [mpg123] MPEG 1.0/2.0/2.5 layers I, II, III
AUDIO: 48000 Hz, 2 ch, s16le, 128.0 kbit/8.33% (ratio: 16000->192000)

# Selected audio codec: [mpg123] afm: mpg123 (MPEG 1.0/2.0/2.5 layers I, II, III)

AO: [alsa] 48000Hz 2ch s16le (2 bytes per sample)
Video: no video
Starting playback...
A:   1.4 (01.4) of -0.0 (unknown)  0.1% 71% 
Audio device got stuck!
A:   1.5 (01.5) of -0.0 (unknown)  0.1% 71% 
Audio device got stuck!
A:   1.6 (01.6) of -0.0 (unknown)  0.1% 72% 
Audio device got stuck!
A:   1.7 (01.7) of -0.0 (unknown)  0.1% 72% 
Audio device got stuck!
A:  88.6 (01:28.5) of -0.0 (unknown)  0.3% 45% 

Mplayer output for reference

**Comment by mherger** [comment]
Please post all of the server.log since the point you started playback with the aforementioned debug flags set.

**Comment by Hypfer** [comment]
[16-08-25 09:32:58.6363] Slim::Player::Protocols::HTTP::canSeekError (815) bitrate unknown for: http://tvheadendhost:9981/stream/channel/a8a142c5bdb1c07726c4fbc7f8cc150c?profile=Squeezebox&ticket=26A57EC09D952AFE5A5D7EBE416B475E4BFF03E4
[16-08-25 09:32:58.6370] Slim::Player::Protocols::HTTP::canDirectStream (267) [00:04:20:1f:2b:37] Not direct streaming because player is synced
[16-08-25 09:32:58.6372] Slim::Formats::RemoteStream::open (70) Opening connection to http://tvheadendhost:9981/stream/channel/a8a142c5bdb1c07726c4fbc7f8cc150c?profile=Squeezebox&ticket=26A57EC09D952AFE5A5D7EBE416B475E4BFF03E4: [tvheadendhost on port 9981 with path /stream/channel/a8a142c5bdb1c07726c4fbc7f8cc150c?profile=Squeezebox&ticket=26A57EC09D952AFE5A5D7EBE416B475E4BFF03E4 with timeout 45]
[16-08-25 09:32:58.6378] Slim::Formats::RemoteStream::request (141) Request: GET /stream/channel/a8a142c5bdb1c07726c4fbc7f8cc150c?profile=Squeezebox&ticket=26A57EC09D952AFE5A5D7EBE416B475E4BFF03E4 HTTP/1.0
Cache-Control: no-cache
Connection: close
Accept: _/_
Host: tvheadendhost:9981
User-Agent: iTunes/4.7.1 (Linux; N; Debian; x86_64-linux; DE; utf8) SqueezeCenter, Squeezebox Server, Logitech Media Server/7.9.0/1461319207
Icy-Metadata: 1

[16-08-25 09:32:58.7363] Slim::Formats::RemoteStream::request (148) Response: HTTP/1.0 200 OK
[16-08-25 09:32:58.7367] Slim::Player::Protocols::HTTP::parseDirectHeaders (348) header-ds: Server: HTS/tvheadend
[16-08-25 09:32:58.7368] Slim::Player::Protocols::HTTP::parseDirectHeaders (348) header-ds: Cache-Control: no-cache
[16-08-25 09:32:58.7369] Slim::Player::Protocols::HTTP::parseDirectHeaders (348) header-ds: Connection: Close
[16-08-25 09:32:58.7370] Slim::Player::Protocols::HTTP::parseDirectHeaders (348) header-ds: Content-Type: audio/mp2t
[16-08-25 09:32:58.7376] Slim::Formats::RemoteStream::request (209) Opened stream!
[16-08-25 09:32:58.7470] Slim::Player::Squeezebox2::directHeaders (471) Processing headers for direct streaming:
HTTP/1.1 200 OK
Server: Logitech Media Server (7.9.0 - 1461319207)
Connection: close
Content-Type: audio/mpeg

[16-08-25 09:32:58.7705] Slim::Player::Squeezebox2::directHeaders (471) Processing headers for direct streaming:
HTTP/1.1 200 OK
Server: Logitech Media Server (7.9.0 - 1461319207)
Connection: close
Content-Type: audio/mpeg

[16-08-25 09:32:58.7733] Slim::Player::Squeezebox2::directHeaders (471) Processing headers for direct streaming:
HTTP/1.1 200 OK
Server: Logitech Media Server (7.9.0 - 1461319207)
Connection: close
Content-Type: audio/mpeg

[16-08-25 09:32:58.7737] Slim::Player::Squeezebox2::directHeaders (471) Processing headers for direct streaming:
HTTP/1.1 200 OK
Server: Logitech Media Server (7.9.0 - 1461319207)
Connection: close
Content-Type: audio/mpeg

[16-08-25 09:32:58.7740] Slim::Player::Squeezebox2::directHeaders (471) Processing headers for direct streaming:
HTTP/1.1 200 OK
Server: Logitech Media Server (7.9.0 - 1461319207)
Connection: close
Content-Type: audio/mpeg

[16-08-25 09:32:58.7761] Slim::Player::Squeezebox2::directHeaders (471) Processing headers for direct streaming:
HTTP/1.1 200 OK
Server: Logitech Media Server (7.9.0 - 1461319207)
Connection: close
Content-Type: audio/mpeg

[16-08-25 09:32:59.7775] Slim::Player::Protocols::HTTP::canSeekError (815) bitrate unknown for: http://tvheadendhost:9981/stream/channel/a8a142c5bdb1c07726c4fbc7f8cc150c?profile=Squeezebox&ticket=26A57EC09D952AFE5A5D7EBE416B475E4BFF03E4
[16-08-25 09:33:05.6653] Slim::Player::Protocols::HTTP::canSeekError (815) bitrate unknown for: http://tvheadendhost:9981/stream/channel/a8a142c5bdb1c07726c4fbc7f8cc150c?profile=Squeezebox&ticket=26A57EC09D952AFE5A5D7EBE416B475E4BFF03E4

**Comment by mherger** [comment]
Ok, I did some more reading. mp2t actually isn't an audio format, but a transport format (http://www.w3.org/2013/12/byte-stream-format-registry/mp2t-byte-stream-format.html). Why don't you just use the URL which tells it to stream the actual audio data?

**Comment by Hypfer** [comment]
Because there is none. I was just able to do that by manually putting a vlc instance as a proxy inbetween.

Even though tvheadend does contain a transcoding feature, it can only transcode into container formats. Those being mp2t, mkv and webm. Would it be better to use one of those?

**Comment by mherger** [comment]
I'm sorry, that's out of my scope. You better join forums.slimdevices.com. There are many users who have done things I've never even thought of. Maybe someone will be able to help you there?

**Comment by Hypfer** [comment]
I'm making progress I think.

Using the MPEG-PS (DVD) container, LMS plays the stream without editing the conf file.
However, apparently it can't handle what I think is metadata/EPG-information in the stream and it tries to play that, too which means some periodic disorted noises. Or maybe its just the container information. Not sure about that. Running strings on the audio stream returns no normal text but I'm not sure if that means anything.

I think this is in the scope of the LMS. The Content-Type is audio/mpeg and so it _should_ work.
No error messages playing that stream so apparently it doesn't even know that the data its interpreting as audio is in fact not audio at all.

**Comment by ulope** [comment]
@Hypfer Have you found a solution to this? I'm currently switching from VDR (which worked fine with LMS but had many other problems) to tvheadend and am struggling with the same problems.

**Comment by Hypfer** [comment]
@ulope see https://github.com/tvheadend/tvheadend/pull/888

No idea if or when they will merge, though...

**Comment by Hypfer** [comment]
TVHeadend just merged the PR.
