### ISSUE TITLE
Remote music library - don't show another LMS

### ISSUE THREAD

**Issue by lexmark3200** [LMS-Community/slimserver#1102]
Hi

I used the "latest" version 8.5.2, now I change to the "stable" 8.5.3. And the problem is still present.
I have two LMS in my network - one is Daphile, the second is LMS container on ubuntu server.
Daphile is findind properly the LMS on ubuntu, but the LMS on Ubuntu doesn't.
In option "Advanced" -> Remote Music Libraries-> I have enabled _Enabled, look for other Ligitech Media Severs_.
but, nothing is showing up in Home/Remote Music 
`No other media server was found in your network. Please make sure it's up and running and reachable. Then try again in a minute or two.`

**Comment by michaelherger** [comment]
Are both systems in the same network? Is there some kind of firewall in front of one of the systems? You could enable logging for `plugin.remotelibrary` on the Ubuntu machine to see what it's saying about your environment. 

Did you try to add the Daphile system in the Remote Library settings?

**Comment by lexmark3200** [comment]
Yes, the both LMS are in the same network. From Daphile I can see the second LMS ( LMS on Ubuntu).
If I put manually the IP of my Daphile, the Remote Server is showing up, but not automatic.

**Comment by lexmark3200** [comment]
> You could enable logging for `plugin.remotelibrary` on the Ubuntu machine to see what it's saying about your environment.

How do to do correct??
I tryed but not with possitive result.

**Comment by michaelherger** [comment]
Settings/Advanced/Logging. Set the flag to "debug" to get most output. Then let it run for a while. Do so on the Ubuntu machine. On that same page there are links to watch the log, or to download it as server.log.zip file.

**Comment by lexmark3200** [comment]
Ok.
That is from Scanner Log:
[scanner_log.txt](https://github.com/user-attachments/files/15521469/scanner_log.txt)
That is from server log:
[server_log.txt](https://github.com/user-attachments/files/15521470/server_log.txt)

**Comment by michaelherger** [comment]
Are these log files from the Daphile system? I see an error about a missing string in `Slim::Utils::OS::Custom` - that's a file which can override some of a system's behavior. Would you be able to extract that file and attach it here?

**Comment by lexmark3200** [comment]
> Are these log files from the Daphile system? 

No, these log files are from docker container LMS on Ubuntu.

>Would you be able to extract that file and attach it here?

I will try to do that. ;-)

On Ubuntu server I've installed alsa and squeezelite player. In etc/default/squeezelite

>
> Squeezebox server (Logitech Media Server):
> Uncomment the next line if you want to point squeezelite at the IP address of
> your squeezebox server. This is usually unnecessary as the server is
> automatically discovered.
>SB_SERVER_IP="192.168.x.y"

SB_SERVER_IP,  I put the IP of my Ubuntu, so the squeezelite don't looking for another LMS as player. Without this IP squeezelite player is alwayes connecting to Daphile as primary LMS server.

**Comment by lexmark3200** [comment]
On Ubuntu server I've installed alsa and squeezelite player. cat etc/default/squeezelite

>The name for the squeezelite player:
SL_NAME="$(hostname -s)"

# ALSA output device:
#SL_SOUNDCARD="default:CARD=Set"
SL_SOUNDCARD="default"
# Squeezebox server (Logitech Media Server):
# Uncomment the next line if you want to point squeezelite at the IP address of
# your squeezebox server. This is usually unnecessary as the server is
# automatically discovered.
#SB_SERVER_IP="192.168.x.y"

# Additional options to pass to squeezelite:
# Please do not include -z to make squeezelite daemonise itself.
SB_EXTRA_ARGS="

SB_SERVER_IP,  I put the IP of my Ubuntu, so the squeezelite don't looking for another LMS as player. Without this IP IT alwayes connect to Daphile as promary LMS server.

**Comment by lexmark3200** [comment]
`Slim::Utils::OS::Custom`
`cat /lms/Slim/Utils/Prefs.pm`
Here is the file:

[Prefs.pm.tar.gz](https://github.com/user-attachments/files/15521418/Prefs.pm.tar.gz)

**Comment by lexmark3200** [comment]
I've made some tests.
I've installed DietPI on Virtualbox. From Dietpi-Software I have installed LMS and squeezelite player. After settings LMS on DietPi, I can see my Daphile, and LMS on Ubuntu in Docker as Remote Music.

So, I have made another test:
I have purged the LMS from Dietpi, and installed it in Docker. The Remote Music is empty, no another LMS on the Network.
So the problem is with docker...

**Comment by michaelherger** [comment]
Oh, you didn't mention Docker before. That's crucial: Docker would by default use "bridge" mode, in which the container would run in its own network. In that case broadcasts wouldn't work. And LMS uses broadcasts to discover other servers or players. You'd have to run Docker in "host" mode instead to make the container fully integrated into your network.

**Comment by lexmark3200** [comment]
> Oh, you didn't mention Docker before. 

I'm sorry for that.

> And LMS uses broadcasts to discover other servers or players.

I trayed to put macvlan to docker, but without possitive result. Docker "get" the correct IP from my LAN, and the gateway is correct, but I can't login to LMS or even ping.

**Comment by michaelherger** [comment]
I'm not familiar with macvlan. "Host" should do https://docs.docker.com/network/drivers/host/.

**Comment by lexmark3200** [comment]
A few month later I added two lines to my docker compose:
>network_mode: host
> - EXTRA_ARGS="--advertiseaddr=192.168.1.100"
 

Now docker see another LMS on my LAN.
