### ISSUE TITLE
Random Mix plugin repeatedly reverts to defaults

### ISSUE THREAD

**Issue by Braklet** [LMS-Community/slimserver#1103]
98% of the time I use the "Random songs" feature of the Random Mix plugin.  I disable genres that would likely induce the neighbors to lynch me.  This works great... as long as my settings persist.

Unfortunately, at seemingly random intervals, the Random Mix settings revert to defaults, exposing said lynchable genres in the course of "Random songs" play.

I can't find anything in the logs that corresponds to the Random Mix plugins, so I've no idea what causes Random Mix to wipe my settings.  Log settings are defaults as well.

I notice that /var/lib/squeezeboxserver/prefs/plugin/randomplay.prefs gets overwritten every time this happens, so I saved off my preferences in a backup file.  When I notice my lost settings, I overwrite randomplay.prefs and restart the lyrionmusicserver.service, which restores settings temporarily.  (This is quicker than doing it through the web interface.)

LMS server running on Ubuntu 22.04 desktop, via standard systemd service.

Current observed version exhibiting problem:  9.0.0 - 1716922840, default skin.  However, I've seen this in v8.5.2 and intermittently with prior versions certainly in the 8.x and 7.x releases, and probably earlier.

Default settings excerpt:
```
---
_ts_continuous: 1511465555
_ts_exclude_genres: 1717168803
_ts_library: 1511469655
_ts_newtracks: 1511465555
_ts_oldtracks: 1511465555
_version: 1
continuous: 1
exclude_genres:
- [genre1]
- [genre2]
- [... every other genre in my collection ...]
library: ''
newtracks: 10
oldtracks: 10

```
Preferred settings excerpt:
```
---
_ts_continuous: 1511465555
_ts_exclude_genres: 1716817220
_ts_library: 1511469655
_ts_newtracks: 1511465555
_ts_oldtracks: 1511465555
_version: 1
continuous: 1
exclude_genres:
- [genre1]
- [genre2]
library: ''
newtracks: 10
oldtracks: 10
```

Let me know if and how I can increase logging to help isolate this issue.  Thanks!

**Comment by Braklet** [comment]
I just noticed something else, based on file timestamp and speculation (i.e. unverified gut feel):

This happens regularly on my LMS system using Don't Stop The Music, which is configured to use Song Mix.

Could it be possible that when DSTM kicks in with Song Mix, my Random Mix settings revert to defaults?

I have a primary LMS system that does not exhibit the "revert to defaults" issue anywhere near as often.  DSTM on that system is disabled.

I have been listening to some new-to-me albums and the DSTM Song Mix gets added at the bottom of my playlist.  I'll try disabling DSTM here and see what happens.

**Comment by michaelherger** [comment]
There's a choice to play a "Song Mix (keep genre selection)". Did you try that? "Song Mix" would indeed reset the settings.

**Comment by Braklet** [comment]
> There's a choice to play a "Song Mix (keep genre selection)". Did you try that? "Song Mix" would indeed reset the settings.

I had no idea DSTM could overwrite the Random Mix settings.  I'll let it run w/DSTM disabled for a few days and see what happens.  Your description makes perfect sense.

In over 20 years of Squeezeboxserver use, I've always paid primary attention to the Random Mix plugin, and nearly no attention to Don't Stop The Music.

Thanks for your response.

**Comment by Braklet** [comment]
Ran a Random Mix song stream overnight, genre settings persist.  Closing this as pilot error.

Thanks for the guidance, @michaelherger.
