### ISSUE TITLE
Update Massage still show the 8.5.2 is not installed

### ISSUE THREAD

**Issue by hellgelino** [LMS-Community/slimserver#1105]
Hi, there is a maybe a Problem with the detection of the Version in 8.5.2, its still saying there is an Update avilable.

Installed: Logitech Media Server Version: 8.5.2 - 1716215514 @ Sun 26 May 2024 05:45:34 PM CEST

**Comment by michaelherger** [comment]
There was a problem indeed, which could cause this behaviour. When did you update?

Try one of the following:

* re-install the update, even if it's the same
* shut down LMS and remove the update files from LMS' cache folder (which you'd have to find while LMS is running: Settings/Information). Then restart LMS.

**Comment by hellgelino** [comment]
"remove the update files from LMS' cache folder" fixed it
