### ISSUE TITLE
DSTM from a playlist

### ISSUE THREAD

**Issue by puck** [LMS-Community/slimserver#111]
Hey, DSTM looks great, but I don't tend to my from a genre.

How about having it select songs from a playlist. I have a bunch of playlists that I've created (i.e., kids, favourite songs per kid, general (no kids music!)). It'd be great to have DSTM just pull songs from the currently selected playlist.

**Comment by mherger** [comment]
Wouldn't saving a playlist as a favorite do the trick? It then could be picked as an option for DSTM.

I do see some potential in the idea. Will take a note. Other than that I think it's a great idea for a 3rd party plugin ;-).

**Comment by puck** [comment]
Saving it as a favourite will only one playlist to be used, not the currently selected playlist. I hadn't realised this was an option, and will work as a stop gap measure.

I did start looking into writing a 3rd party plugin, and may yet pick it up again. ;)

Cheers, Andrew

**Comment by mherger** [comment]
What do you mean by "currently selected playlist"? Would you want to play the same list again?

**Comment by puck** [comment]
Yes, I would. One my playlists has almost 5k songs in it. I'd prefer to just have DSTM just grab 10 songs from that a go. But then be able to change the playlist and have it grab the next batch of songs from the new playlist.

**Comment by mherger** [comment]
Ok, next suggestion: instead of creating those massive playlists, why don't you build library views instead? You could then simply use a song mix limited to the currently selected library view.
