### ISSUE TITLE
Supporting Disc Subtitles (TSST tag)

### ISSUE THREAD

**Issue by chrober** [LMS-Community/slimserver#1111]
It would be great for multi-disc releases if the UI would show the disc subtitle (if present in the TSST tag). Is there any chance (or even a plan) to implement this?

**Comment by michaelherger** [comment]
@chrober what LMS version are you using? 

@darrell-k - isn't this something you've been working on?

**Comment by chrober** [comment]
> @chrober what LMS version are you using?

I am using **Logitech Media Server Version: 8.5.1 - 1713072758 @ Mon 15 Apr 2024 11:43:22 AM CEST**.

**Comment by darrell-k** [comment]
I added a subtitle column to the albums table in 9.0, but we're not doing anything with it yet.

The subtitle column in the tracks table is populated from the scan (with TIT3 in mp3-land).

**Comment by CDrummond** [comment]
I'd also support this. Currently Material can be configured to use the comment field for this, but that's always felt a bit hacky. Would be great if LMS supported the actual tag. So, am I correct in understanding that the subtitle is there, just not supplied to the clients?

**Comment by darrell-k** [comment]
Currently the scanner maps SUBTITLE/TIT3 to tracks.subtitle in the database.

The column albums.subtitle exists, but is not yet populated by the scan.

**Comment by CDrummond** [comment]
Any chance of having this in soon? Would be good to have to deprecate Material's work-around - and next release seems a good time for this.

**Comment by chrober** [comment]
Here is a list of disc-subtitle tags for various audio formats used by Musicbrainz Picard: https://picard-docs.musicbrainz.org/en/appendices/tag_mapping.html#disc-subtitle

**Comment by darrell-k** [comment]
Should be simple enough to add to the scanner. Presumably you would want the value to be returned in the albums message?

I can add it to this PR, best keep the changes that require release coordination and retagging together.

**Comment by CDrummond** [comment]
In the albums message would be great. I currently just get all tracks - but having this in the albums command would reduce complexity.

**Comment by darrell-k** [comment]
> In the albums message would be great. I currently just get all tracks - but having this in the albums command would reduce complexity.

@CDrummond Actually, thinking about this, it's not album level data is it? ie in a multidisc set, there might be a different discsubtitle for each disc in the set, though it is a single album?

In which case I'd need to add a new column to the tracks table, and you'd have to do what you're doing now, retrieve all the tracks?

Is this correct?

**Comment by CDrummond** [comment]
@darrell-k Yeah, adding to the tracks _probably_ makes more sense - as, AFAIK, there is no reliable way to return a list (LMS uses a comma separated string, but that's prone to failures).

**Comment by darrell-k** [comment]
@CDrummond at a database level, it has to be in the Tracks table, as it's an attribute of track, not of album. I misunderstood before.

So simplest from the LMS point of view is to return discsubtitle for each track in the tracks response, and leave you to do with it what you're already doing with comments.

**Comment by darrell-k** [comment]
@CDrummond do you only need this from the tracks command, or also the status command?

**Comment by CDrummond** [comment]
Just tracks should be enough.

**Comment by darrell-k** [comment]
@CDrummond changes made in https://github.com/LMS-Community/slimserver/pull/1109

**Comment by CDrummond** [comment]
With https://github.com/LMS-Community/slimserver/pull/1109 isn't this issue now resolved?

**Comment by darrell-k** [comment]
I think so, I wonder if the issue raiser agrees?

**Comment by michaelherger** [comment]
@chrober would you be willing to give LMS 9 a try (https://lyrion.org/downloads/#lyrion-music-server-v900-development-build)? Or we can close this and you re-open or open a new issue once LMS9 has been released and you see need for more changes?

**Comment by chrober** [comment]
> @chrober would you be willing to give LMS 9 a try (https://lyrion.org/downloads/#lyrion-music-server-v900-development-build)?

Sure, I am looking forward to try this! Thanks, for implementing this so quickly!

> Or we can close this and you re-open or open a new issue once LMS9 has been released and you see need for more changes?

Whatever you prefer to keep your issue list and backlog groomed. I will not have time for setting up LMS 9 in the next three days, but I will definitely reserve some time during the weekend.

**Comment by chrober** [comment]
Hi @darrell-k, @CDrummond,
I've just installed LMS 9 (Lyrion Music Server Version: 9.0.0 - 1718877384 @ Fri 21 Jun 2024 02:38:05 AM CEST) on a clone of my pCP card
... and waited for the re-scan to complete
... and upgraded to latest versions of plugins (e.g. Material Skin 5.0.3)
...and... **ta-da!**

![grafik](https://github.com/LMS-Community/slimserver/assets/26856218/986ef814-e0d1-4ae5-9932-9e4efa55d6bd)

The album view gives me disc titles instead of disc numbers if TSST is present!

**Thank you so much guys, it looks fantastic!**

**Comment by michaelherger** [comment]
Thanks for the feedback, @chrober!
