### ISSUE TITLE
UNC path not supported for music library in Lyrion 9.0.0

### ISSUE THREAD

**Issue by AgXCz** [LMS-Community/slimserver#1118]
Until recent Lyrion versions it was working fine, but current version seems to not support UNC paths (like \\192.168.1.10\music1\) anymore. Which makes Lyrion useless for me.

Server

Version: 9.0.0 - 1718058304 @ Tue Jun 11 02:24:27 WEDT 2024
OS: Windows 10 - CS - cp1250
Architecture of platform: 8664
Perl: 5.14.1 - MSWin32-x86-multi-thread
Audio::Scan: 1.08
IO::Socket::SSL: 2.068
Db version: DBD::SQLite 1.58 (sqlite 3.22.0)

**Comment by michaelherger** [comment]
This should work as before. Just make sure LMS is not running as the system service user, as that one usually can't access network shares. You'll have to configure the service to run as a regular user with permission to access the share.

**Comment by AgXCz** [comment]
@michaelherger You are right, thanks.
