### ISSUE TITLE
Podcast atom feed player

### ISSUE THREAD

**Issue by kanyi** [LMS-Community/slimserver#113]
Hi guys!

Do you have a plan for atom-feed podcast playing? Like this? 
[https://tilos.hu/feed/show/hi-fi-budapest]
Or is this already possible?

**Comment by mherger** [comment]
How does it fail?

**Comment by kanyi** [comment]
I can add the podcast stream (http://tilos.hu/feed/show/hi-fi-budapest)
I can see the streams under the podcast menu but I can not play it. I did not see the play button. I see nothing in the logfile.

If I try the http://tilos.hu/feed/show/hi-fi-budapest=mp4 url
I find this in the LMS logfile: (/usr/local/slimserver/Logs/server.log)

`[16-09-22 19:27:26.3427] Slim::Plugin::Podcast::Settings::__ANON__ (119) Error validating feed http://tilos.hu/feed/show/hi-fi-budapest=mp4: 406 Not Acceptable`

`[16-09-22 19:27:26.3442] Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Networking::Async::_async_read: Undefined subroutine &Slim::Plugin::Podcast::Settings::string called at /usr/local/slimserver/Slim/Plugin/Podcast/Settings.pm line 121.
; fh=Slim::Networking::Async::Socket::HTTPS=GLOB(0x7967530)`

But I see now, the second link with `=mp4` is not working.

**Comment by mherger** [comment]
Oh, that second message actually looks like a real bug to me. What LMS version are you running? Please make sure you are running the latest nightly of whatever version you're on. Thanks!

**Comment by kanyi** [comment]
My LMS version: 
Logitech Media Server Version: 7.9.0 - 1474277583 @ Thu Sep 22 04:08:46 UTC 2016

If only the second one a real bug, why I can not play the first url? ([https://tilos.hu/feed/show/hi-fi-budapest])

**Comment by mherger** [comment]
Problem seems to be that this feed has multiple link elements per entry, of which only one is playable audio. I don't know yet whether this is valid Atom or not. But I'll look into this.

**Comment by mherger** [comment]
This issue should be fixed in commit 56ee60182f88de485a6dfd7a71a7fd8739e8723c (or the next build). Please let me know if you still encounter issues.
