### ISSUE TITLE
Forums: Impossible to register

### ISSUE THREAD

**Issue by labor4** [LMS-Community/slimserver#1143]
Hi

I cannot register in the forums. [https://forums.slimdevices.com/register](https://forums.slimdevices.com/register)
I tried without any special chars...

On second/third try: "Contact the Admin"

![Bildschirmfoto 2024-08-05 um 18 47 46](https://github.com/user-attachments/assets/183b9019-407a-4ee9-9943-8f6cc6e24c80)

Regards
Manu

**Comment by michaelherger** [comment]
This is not a LMS issue... Re-consider what you enter in the "Subject of Interest" field and try again. Worst case contact the admin using the contact form on the site.

**Comment by labor4** [comment]
@michaelherger i know this is not the source. but where else to report this proven bug. 

kindly give me an url to said form or another means of contact. 

thanks

**Comment by michaelherger** [comment]
Bottom right you'd find "contact us": https://forums.slimdevices.com/contact-us.
