### ISSUE TITLE
2 typos in German "version"

### ISSUE THREAD

**Issue by frank1969b** [LMS-Community/slimserver#1155]
On browsing "Recently Updated Albums" is translated as "Zuletzte aktualisierte Alben".
should be "Zuletzt aktualisierte Alben" (leaving out the "e" at the end of "Zuletzt")

On the "view tags" site, LYRICIST is translated as "Text" - should be translated as "Texter"
(like "Composer" => "Komponist")
Not sure if it is in custom strings or server strings...?!

**Comment by michaelherger** [comment]
The View Tags titles are user defined. Please check the settings in Einstellungen/Erweitert/Erweiterte Tag Ansicht or similar.

Thanks for the heads up about the typo.
