### ISSUE TITLE
DLNA not playing full albums

### ISSUE THREAD

**Issue by nyanloutre** [LMS-Community/slimserver#116]
When I try to play an album (with Emby and BubbleUpnp) to the Squeezebox, it play the first song and then stop. I've seen many people with this bug but I still didn't found a fix or workaround fot this.

**Comment by mherger** [comment]
Please join us at forums.slimdevices.com for a better level of (community) support. And please bring a reference or two to some discussion of this issue. I'm not familiar with it. Thanks!

**Comment by mherger** [comment]
As per the forum discussion this is not a bug in LMS, but an expected, non existent behavior.
