### ISSUE TITLE
Songs randomly being skipped, pauses/stutters/crackles 

### ISSUE THREAD

**Issue by Auram** [LMS-Community/slimserver#1162]
Hello, I am trying to find a suitable replacement for my dying Chromecast-based whole home audio solution. Currently I'm trying LMS and MA with two Philips Soundrings and a Pioneer AVR via AirPlay. Sync works perfectly and everything starts up and plays great, but not without issue.

I'm using Spotty to play music to the three aforementioned AirPlay devices in a speaker group.

Every few tracks, in the middle of a song, it will just skip to the next in the queue for seemingly no reason. Nothing in the logs reports an error from Spotty, AirPlay bridge, the server, anything. My network can handle casting to 6 Google Home Mini's just fine, it should be able to handle the traffic to these three AirPlay devices no problem. I can live with very occasional minor dropouts or stutters, but the random skipping is very confusing and irritating.

I'd love to hear if I'm doing something wrong or if I'm butting up against some kind of limit. When it's working it really works quite well and I'd be happy to switch over to LMS completely, but the inconsistencies are frustrating. 

Logs:
[server.log.zip](https://github.com/user-attachments/files/16934271/server.log.zip)
[scanner.log.zip](https://github.com/user-attachments/files/16934273/scanner.log.zip)

**Comment by Auram** [comment]
Just a followup, I've been listetning to music since I made this post and the AirPlay bridge just up and crashed just now

[24-09-09 14:00:54.0757] Plugins::RaopBridge::Squeeze2raop::beat (179) crashed ... restarting
[24-09-09 14:01:24.0824] Plugins::RaopBridge::Squeeze2raop::beat (179) crashed ... restarting
[24-09-09 14:01:54.0898] Plugins::RaopBridge::Squeeze2raop::beat (179) crashed ... restarting
[24-09-09 14:02:24.0970] Plugins::RaopBridge::Squeeze2raop::beat (179) crashed ... restarting
[24-09-09 14:02:54.1032] Plugins::RaopBridge::Squeeze2raop::beat (179) crashed ... restarting
[24-09-09 14:03:24.1103] Plugins::RaopBridge::Squeeze2raop::beat (179) crashed ... restarting

Only restarting the LMS docker container fixed it.

**Comment by michaelherger** [comment]
You might want to join https://forums.slimdevices.com or head over to https://github.com/philippe44/LMS-Raop?

**Comment by Auram** [comment]
I'll make a post on the forum if that's preferred, thanks!

**Comment by michaelherger** [comment]
Thanks! Yes, you'll find most contributors and developers in the forums. 

I guess that's your thread: https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1725057-songs-randomly-being-skipped-pauses-stutters-crackles

**Comment by Auram** [comment]
Yep that's me! Hopefully we can get everything squared away over there.
