### ISSUE TITLE
Couldn't create command line for hls playback

### ISSUE THREAD

**Issue by devdems** [LMS-Community/slimserver#1165]
Hi, there is an issue playing stream https://stream.nextmedia.si/hls2/rr/128k/RR-128.m3u8

Plugin PlayHLS is installed but it's giving me the error:
[24-09-13 15:27:01.0313] Slim::Player::Song::open (424) Error: Couldn't create command line for hls playback for [https://stream.nextmedia.si/hls2/rr/128k/RR-128.m3u8]

I'm running this on docker v8.5.3

Does anyone have any idea?

**Comment by michaelherger** [comment]
Please head over to https://forums.slimdevices.com where you'll find the plugin's developer(s). It is not part of core LMS. Thanks!
