### ISSUE TITLE
Enhancement - Provide options for priority in searching

### ISSUE THREAD

**Issue by gstalnaker** [LMS-Community/slimserver#1176]
Now, by default, when I search my 120,000 track library, the search uses "contains" for its search method which is, if I'm understanding it, is OR'd search terms. With a library this large that is not optimal. I can go to Advanced Search and with a field's dropdown select "Begins with" which works as expected, for example, with Title. It would be advantageous if I could tell the UI that I'd like searches to use a specific option like 'Begins With" or "Contains." rather than having to go into Advanced Search every time to select such an option.

**Comment by michaelherger** [comment]
Settings/Behaviour/Search within words?
