### ISSUE TITLE
Tidal Timeout Errors

### ISSUE THREAD

**Issue by Seveerl** [LMS-Community/slimserver#1184]
Sorry if this is addressed somewhere else here, I'm not smart enough enough to figure out where it be located.
Using -Version: 8.5.2 - 1716215514 @ Sun May 26 17:41:21 WEDT 2024
Hostname: Robert-pc
Server IP Address: Not my real IP
Operating system: Windows 10 (64-bit) - EN - cp1252
Platform Architecture: 8664
Perl Version: 5.32.1 - MSWin32-x64-multi-thread
Audio::Scan: 1.08
IO::Socket::SSL: 2.069
Database Version: DBD::SQLite 1.66 (sqlite 3.32.3)
Having continuous issues with Tidal. Typically plays 1 song then stops, sometimes i can get it play the next song in the que , but most often i need to restart , reload the que. 
My server log is filled with the following error.
Plugins::TIDAL::API::Async::__ANON__ (810) Error: Connect timed out: Bad file descriptor

Any help is appreciated.

**Comment by michaelherger** [comment]
Closing in favor of https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1730002-tidal-time-out-error#post1730002 - thanks!
