### ISSUE TITLE
Random mix section not accepting accented name

### ISSUE THREAD

**Issue by werdeil** [LMS-Community/slimserver#1188]
Hello I just came accross an issue on random mix menus: I simply saved a random mix playlist with an accent in it (yes I'm French, we have accent)
--> First issue: the saved playlist doesn't have the accent but some utf-8 code instead: `AlÃ©atoire unplayed tracks` instead of `Aléatoire unplayed tracks`
--> Second issue: the saved playlist is "blocked": I cannot do anything with it neither play, edit nor remove it.

Note: same playlist without accent in it created right after is working as expected.

<img width="643" alt="image" src="https://github.com/user-attachments/assets/19f55f48-9b1a-4b54-8be7-26a345c00a4f">

Tell me if you need anything to help you fix this (and how I can clean my environment if necessary). I looked in the LMs logs but nothing visible when trying to edit/remove and I got this issue when trying to play
```
[24-10-19 22:20:52.2123] Slim::Web::JSONRPC::requestMethod (481) Request failed with error: Bad params!
```

**Comment by CDrummond** [comment]
This is a Material-Skin issue, not LMS.

**Comment by werdeil** [comment]
Thanks a lot @CDrummond for the quick answer and the quick fix, and my apologies for opening this issue on the wrong repository, I should have tested on the default view too.

Closing this as not related and already fixed on Material-Skin.

**Comment by michaelherger** [comment]
No worries, @werdeil. Thanks for following up and confirming the fix.
