### ISSUE TITLE
update to perl 5.40 support needed for imminent release of Fedora 41

### ISSUE THREAD

**Issue by FBachofner** [LMS-Community/slimserver#1198]
I upgraded to Fedora 41 and LMS broke due to perl being upgraded to 5.40 . . .

@mherger made a [forum post](https://forums.slimdevices.com/forum/developer-forums/beta/1730918-tentative-release-date-for-lms-9-end-of-november/page4#post1731786) indicating this would happen when "there's popular demand (eg. an official release of Debian/Ubuntu/Fedora using it)"

So . . . this issue is ONLY submitted as a _gentle_ reminder that the release of Fedora 41 is imminent -- [likely in less than 36 hours](https://fedorapeople.org/groups/schedule/f-41/f-41-all-tasks.html)

**Comment by FBachofner** [comment]
Interesting!

It looks like they just pushed the release date to Nov 12 sometime this afternoon.

A bit of a reprieve. Earlier today it showed as Oct 29!! ...

**Comment by michaelherger** [comment]
What hardware platform would you be using?

**Comment by michaelherger** [comment]
Would you be able to download https://github.com/LMS-Community/slimserver-vendor/actions/runs/11548692352/artifacts/2110726086?

**Comment by michaelherger** [comment]
Never mind - I committed the files. Please give them a try and let me know about the outcome.

**Comment by FBachofner** [comment]
Hi Michael:

I have installed the newest 9.0.0 dev build you uploaded and it works flawlessly on Fedora 41 (amd-64)

Thanks for the extremely quick turnaround!
