### ISSUE TITLE
long pause, then play results in players completely out of sync

### ISSUE THREAD

**Issue by cavoknosig** [LMS-Community/slimserver#120]
i have a setup with 6 synchronized (1 wifi, 5 wired) "SB play" running from an LMS, formerly on a QNAP NAS, now on a dedicated raspberry pi.
we're mostly streaming from the internet, so the LMS is in proxy mode in these cases.
while the LMS is playing, the players keep nicely in sync, hardly ever a problem.

but with the typical use case "pause" before going to bed in the evening and a "play" as next action in the morning, the music will continue playing, but completely out of sync between the various players. and they also won't resync while playing. 
so i constantly have to press "previous track", for the internet stream to reload and more importantly trigger the players/server to resync.

it would be nice if in these cases, "play" would be sufficient to also resync the players and continue playing the stream correctly aligned.
the problem with the "previous track" workaround are obvious once there are multiple streams or offline music from the NAS in the playlist.

**Comment by mherger** [comment]
What kind of players are you using? Could you please post to forums.slimdevices.com or give me a reference to a thread where this was being discussed? I'd like to have feedback from more users with similar setups. Thanks!

**Comment by cavoknosig** [comment]
hi,

 

all players report:

Player Model: Squeezebox Radio

Player Type: baby

Firmware: 7.7.3-r16676

 

in the synchronize options, they all have “maintain synchronization while playing” enabled.

 

will post to a thread in the forums...

 

regards
