### ISSUE TITLE
Another albumsQuery contributor bug

### ISSUE THREAD

**Issue by darrell-k** [LMS-Community/slimserver#1205]
I've just seen this happen while testing some Material Skin changes.

https://github.com/LMS-Community/slimserver/blob/a1719ae7ab4d8a6238e958781196931fd7c9ec9c/Slim/Control/Queries.pm#L846-L863

Line 846 sets `artist_id` to the input parameter if it exists, rather than `albums.contributor` column.

Then at 854-862, if the input parm and the `album.contributor` column are different,  `artist` is set to the name of `album.contributor`, so `artist` no longer matches `artist_id`. 

So one or the other is wrong, but which way to go? Not sure where these are used, rather than `artist_ids` and `artists`, which we've just been working on, but still...

**Comment by michaelherger** [comment]
We should evaluate what contributor ID to report before the `/S/` check, then use the same in both places. The name was evaluated in response to a bug report (which unfortunately is no longer available). So... I'd think the visual part was stronger than the link. We should go with the logic used there?

**Comment by darrell-k** [comment]
fixed by #1206
