### ISSUE TITLE
ReadyNAS102 no longer boots

### ISSUE THREAD

**Issue by 2020to20** [LMS-Community/slimserver#1209]
It was working fine until recently, but around November, LMS stopped working on ReadyNAS102.
What do you think is the cause of this?
Please let me know if there is any way to investigate the cause.

The service status is as follows:
root@ReadyNAS102:~# systemctl status lyrionmusicserver.service
● lyrionmusicserver.service - Lyrion Music Server
   Loaded: loaded (/lib/systemd/system/lyrionmusicserver.service; enabled; vendo
r preset: enabled)
   Active: failed (Result: exit-code) since Wed 2024-11-06 18:36:06 J
ST; 2min 50s ago
  Process: 28074 ExecStart=/usr/sbin/squeezeboxserver --prefsdir $PREFSDIR --log
dir $LOGDIR --cachedir $CACHEDIR --charset $CHARSET $SLIMOPTIONS (code=e
xited, status=255)
 Main PID: 28074 (code=exited, status=255)

Nov 06 18:36:06 ReadyNAS102 squeezeboxserver[28074]: BEGIN failed--compilation a
borted at /usr/share/perl5/Slim/Utils/Alarm.pm line 49.
Nov 06 18:36:06 ReadyNAS102 squeezeboxserver[28074]: Compilation failed in requi
re at /usr/share/perl5/Slim/Buttons/Alarm.pm line 13.
Nov 06 18:36:06 ReadyNAS102 squeezeboxserver[28074]: BEGIN failed--compilation a
borted at /usr/share/perl5/Slim/Buttons/Alarm.pm line 13.
Nov 06 18:36:06 ReadyNAS102 squeezeboxserver[28074]: Compilation failed in requi
re at /usr/share/perl5/Slim/Buttons/Common.pm line 41.
Nov 06 18:36:06 ReadyNAS102 squeezeboxserver[28074]: BEGIN failed--compilation a
borted at /usr/share/perl5/Slim/Buttons/Common.pm line 41.
Nov 06 18:36:06 ReadyNAS102 squeezeboxserver[28074]: Compilation failed in requi
re at /usr/sbin/squeezeboxserver line 233.
Nov 06 18:36:06 ReadyNAS102 squeezeboxserver[28074]: BEGIN failed--compilation a
borted at /usr/sbin/squeezeboxserver line 233.
Nov 06 18:36:06 ReadyNAS102 systemd[1]: lyrionmusicserver.service: Main
process exited, code=exited, status=255/n/a
Nov 06 18:36:06 ReadyNAS102 systemd[1]: lyrionmusicserver.service: Unit
entered failed state.
Nov 06 18:36:06 ReadyNAS102 systemd[1]: lyrionmusicserver.service: Faile
d with result 'exit-code'.

**Comment by michaelherger** [comment]
Could you please confirm the Perl version your device is running? I think I've found an issue with older Perl version (< 5.26) I introduced a few days back. Thanks for the heads up!

**Comment by paul-1** [comment]
Not working on Docker.  Not sure what version is started to fail, but just working with docker again, updated to latest, then noticed this failing.

Lyrion Music Server Version: 9.0.0 - 1730891874 @ Wed Nov 6 11:18:55 UTC 2024

[24-11-06 19:37:01.5794] Slim::Utils::PluginManager::load (395) Warning: Couldn't call Slim::Plugin::FullTextSearch::Plugin->initPlugin: Carp::Clan::__ANON__(): DBI Exception: DBD::SQLite::db do failed: Undefined subroutine &Slim::Slim::Utils::Misc::uniq called at /lms/Slim/Plugin/FullTextSearch/Plugin.pm line 507.

In this case, it only errors during scanning..... lms otherwise runs okay.

**Comment by paul-1** [comment]
Never mind.  Seems docker just updated within the last hour to 1730926294, and now its fine.

What times trigger nightlies to update?

**Comment by michaelherger** [comment]
I thought it was around 3am UTC. But yesterday I triggered a build manually... which resulted in LMS starting, but FTS being broken 🤦🏻. I'm sorry about that.

**Comment by 2020to20** [comment]
> Could you please confirm the Perl version your device is running? I think I've found an issue with older Perl version (< 5.26) I introduced a few days back. Thanks for the heads up!

My Perl version is 5.20.2. 
Will I be able to use older versions of Perl again?

**Comment by michaelherger** [comment]
Yes, Perl 5.20.2 should be fine again.

**Comment by 2020to20** [comment]
> Yes, Perl 5.20.2 should be fine again.

Wow.
Thanks.
When will that be?

**Comment by michaelherger** [comment]
Just install the latest build from last night.

**Comment by paul-1** [comment]
No worries.  I was just looking at commit times vs build date stamps, and trying to figure out the timing.

I just did a bit of poking around, and now see how/where the build action happens.

**Comment by michaelherger** [comment]
But you can't see the build action artifacts, can you? Would be nice if they were available that way, too. As an archive of recent builds.

**Comment by paul-1** [comment]
You can save the artifacts from a run, GH will by default save them from 90days.  I think there is a max storage amount, 

```
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: Bytecode-mpy${{ matrix.mpy.version }} # optional, default is artifact
          path: "*.mpy"         # A file, directory or wildcard pattern that describes what to upload
          overwrite: true       # optional, default is false
```
In the above case, it uploads a zip file with all of my compiled micropython bytecode for each matrix run

**Comment by michaelherger** [comment]
We're way off-topic... but oh well 😀. 

Saving the artefacts is part of the flow. Alas, they're not public. And I don't want to publish them through GH, as that would tag a release each time. But then the need for such builds is rare anyway. Let's not overthink.

**Comment by 2020to20** [comment]
Thank you.
I tried it and it worked perfectly.
That really helped.

**Comment by paul-1** [comment]
Oops, looked at the wrong workflow.  Yes the artifacts are there.
