### ISSUE TITLE
Modify #CURTRACK to Reset Value When Playlist Finishes

### ISSUE THREAD

**Issue by w3wilkes** [LMS-Community/slimserver#1213]
Title says it all. The way #CURTRACK currently works is when a playlist ends the value is left pointing to the end of the playlist. When subsequent selection of "Play Now" is used to start the playlist it plays just the last song in the list. I think that when #CURTRACK is active and the end of the playlist is reached the value in #CURTRACK should be reset to "0" (zero) so that the next time "Play Now" is selected for that playlist the playlist will start on the 1st track in the playlist.

**Comment by michaelherger** [comment]
Could you please test this with debugging for `formats.playlists` enabled. Then provide the tail of `server.log`. Thanks!

**Comment by w3wilkes** [comment]
The playlist has 78 tracks. I set #CURTRACK to 76 so the playlist would start on track 77. I let the playlist finish and when it stopped I removed it from the queue. The #CURTRACK statement was left at 77. I cleared the log, restarted LMS, set format.playlists to debug and then started the playlist. Log is attached.
[server.log.zip](https://github.com/user-attachments/files/17601043/server.log.zip)

**Comment by w3wilkes** [comment]
Issue updated with log in above update as requested.

**Comment by w3wilkes** [comment]
Interesting. I went to look at the clientplaylist_002315f9d2b9.m3u that was saved in the prefs folder and it has #CURTRACK set to "0", see attached. Had to rename it to a .txt to upload.
[clientplaylist_002315f9d2b9.txt](https://github.com/user-attachments/files/17601249/clientplaylist_002315f9d2b9.txt)

**Comment by michaelherger** [comment]
Unfortunately you cleared the log. There's not much left. Neither is in the playlist: it's empty?

**Comment by w3wilkes** [comment]
Yes, I did shut down LMS and clear the log before I did this test so that this test would be all there is in the log. Then I restarted LMS, set format.playlists to debug and then started the playlist with #CURTRACK set to the 2nd to last track in the playlist (76) so the playlist would start on track 77. Let the playlist finish (78 tracks in the playlist). Once the playlist finished I cleared the queue and stopped LMS. The first line in the log shows LMS 8.5.3 starting. The next line is the playlist starting identifying that it found the track to start on (76) which plays track 77. you can see it play the last 2 tracks and the last write to the prefs folder to file clientplaylist_002315f9d2b9.m3u which I uploaded in the 5th update to this issue which shows #CURTRACK set to "0" but no subsequent write to the actual playlist.

**Comment by w3wilkes** [comment]
One other note is the write of clientplaylist_002315f9d2b9.m3u appears to be some type temporary "placeholder" for the #CURTRACK statement. The actual playlist is in my root music folder called Stuff 2.1.m3u. Here's the actual playlist as it was left by LMS when finished. Note that #CURTRACK was left at 77 which would start the playlist on track 78. The #CURTRACK clientplaylist_002315f9d2b9.m3u "placeholder" was not written to the playlist (2nd to last entry in the log) where #CURTRACK is set to "0".
[Stuff 2.1.txt](https://github.com/user-attachments/files/17669069/Stuff.2.1.txt)

**Comment by michaelherger** [comment]
I did some investigation. It's important to understand that saving the queue ("right hand side playlist") is treated differently from stored playlists. Unfortunately the same applies when it comes to how position state is handled in there. Saved playlists would only be updated if they're local, stored in the defined playlist folder. And currently only on track changes, but NOT when reaching the end.

This could relatively easily be fixed:

```diff
diff --git a/Slim/Control/Commands.pm b/Slim/Control/Commands.pm
index 738297720..6ffb0a08c 100644
--- a/Slim/Control/Commands.pm
+++ b/Slim/Control/Commands.pm
@@ -1763,7 +1763,7 @@ sub playlistXtracksCommand {
 
                        # And set a callback so that we can
                        # update CURTRACK when the song changes.
-                       Slim::Control::Request::subscribe(\&Slim::Player::Playlist::newSongPlaylistCallback, [['playlist'], ['newsong']]);
+                       Slim::Control::Request::subscribe(\&Slim::Player::Playlist::newSongPlaylistCallback, [['playlist'], ['newsong', 'stop']]);
                }
                # bug 14662: Playing a specific track while track shuffle is enabled will play another track
                elsif (defined $jumpToIndex && Slim::Player::Playlist::shuffle($client)) {
diff --git a/Slim/Player/Playlist.pm b/Slim/Player/Playlist.pm
index 00b7df044..067648ee7 100644
--- a/Slim/Player/Playlist.pm
+++ b/Slim/Player/Playlist.pm
@@ -1100,7 +1100,11 @@ sub newSongPlaylistCallback {
 
        my $client = $request->client() || return;
 
-       newSongPlaylist($client)
+       my $reset = $request->isCommand([['playlist'], ['stop']])
+               && (Slim::Player::Source::playingSongIndex($client) + 1) ==  count($client)
+               && !Slim::Player::Source::progress($client);
+
+       newSongPlaylist($client, $reset);
 }
```

Unfortunately this wouldn't fix the case where you reached the end in the current queue. The above would only take effect if the playlist was started anew, selected from the playlists menu (or some other command referring the playlist, not the queue).

The queue I don't know how to address.
