### ISSUE TITLE
"Music Folder" Option in "My Music" is not visible if all folders have "Music" "Pictures" "Video" unchecked

### ISSUE THREAD

**Issue by angerized** [LMS-Community/slimserver#122]
If you leave all three "Music" "Pictures" and "Video" checkboxes unchecked in your media folders options, then the "Music Folder" option is not visible in "My Music". But it is still active (visible from a previous page refresh, or url http://a.b.c.d:9000/clixmlbrowser/clicmd=browselibrary+items&linktitle=BROWSE_MUSIC_FOLDER&mode=bmf/index.html ), with all folders being shown between brackets. 

If you check only one of these options on any of the folders, then the option reappears in "My Music", the folders with no options being shown between brackets, the one(s) with checkboxes shown without brackets.

I for one do not want my music scanned, since I only use the music folder browsing. It would be great if "Music Folder" was always showing when at least a music folder is added, regardless of options (un)checked.

Thanks :)

**Comment by mherger** [comment]
Don't know whether this is a bug or a new feature. But it makes sense anyway :-)

**Comment by mherger** [comment]
Fixed in 7b0c21c898385aa8a438564e828eb432cbdef60c

**Comment by angerized** [comment]
Well that was quick. Thanks a lot ;)
