### ISSUE TITLE
Installation Issues With Version 9.0.0-win64

### ISSUE THREAD

**Issue by RMMTSLLP** [LMS-Community/slimserver#1239]
Could be something or nothing just upgraded LMS to ver 9 When I first download installation file .exe I get a warning "isn't commonly downloaded etc" I allow the file to download and continue with the installation however when LMS starts I get the "Wacapwe.C!ml" threat detected and LMS fails to start.  I assume this could be a false positive detected by windows defender.  I look forward to your comments

![Lyrion Download Warning](https://github.com/user-attachments/assets/d8e14f90-65f6-4d5e-b1ae-3841b230e662)

![Wacapew C!ml](https://github.com/user-attachments/assets/6d8d0d02-7cd8-43fc-a7df-a17b2506a18b)

**Comment by michaelherger** [comment]
The first warning is probably valid, as a file which has only been provided for download a few days ago isn't "commonly downloaded". It takes some time. So consider this a warning to be careful what you download. But if you downloaded it from the original URL, you should be safe.

The second is more annoying. Antivirus (and other security applications) do signal false positives every now and then. It happens. What you can do is have the file scanned by virustotal.com: that service would use dozens of AV scanners to analyse a file. If only one or two of them signals it as bad, all the others are happy with it, chances are those two signaled a false positive. 

I see from the timestamp this has happened today. Maybe you can try again in a day or two. Or you give the 9.0.1 nightly build another try (https://lyrion.org/downloads/#v901-stable-nightly-build).

**Comment by michaelherger** [comment]
BTW: the file it's complaining about isn't even LMS itself, but only the service manager. You should be able to run LMS anyway, or it should actually already be running. Did you try to open it in your browser? http://localhost:9000 would typically be the entry point.

**Comment by RMMTSLLP** [comment]
Michael, thanks for your responses,  I can confirm that LMS 9.0.0 is up and running.  All I did was to download and install again.  It's strange that the windows defender detected the wacapew issue at the point of LMS installation.  From my point you can close this issue off.  Many thanks Roger

**Comment by michaelherger** [comment]
👍🏻
