### ISSUE TITLE
"Une nouvelle version du Logitech Media Server et disponible..." à chaque redémarrage

### ISSUE THREAD

**Issue by bawois** [LMS-Community/slimserver#1241]
8.5.2 repeatedly indicating (the same) update is available - even after an install

Mac Pro 5.1 High Sierra

**Comment by michaelherger** [comment]
What did you update to?

**Comment by bawois** [comment]
Thank You for this quick answer.
The problem occurs curiously only on one MiniServeur Late 2012 (and not my Mac Pro or other Mac).
The upgrade just concerns Lyrion Music Serveur: it is presented as a 8.5.2 Logitech Media Server upgrade.
As I open Lyrion it also ask for an upgrade.

**Comment by michaelherger** [comment]
As a user of 8.5.2 you should indeed get a prompt to install Lyrion Music Server 9.0.0. Did this not happen?

What is a "MiniServeur"?

**Comment by bawois** [comment]
That did happen, but the Lyrion Music Server upgrade is asked at every start.
I tried to upgrade directly from Lyrion with no effect.
The « MiniServer » is just a Mac Mini.

**Comment by michaelherger** [comment]
You should uninstall the pref pane. LMS 9 is controlled using a menu bar item. See https://lyrion.org/reference/uninstall-legacy-mac/ for details. 

If that's not the case can you please share a screenshot of the update prompt you are getting?

**Comment by bawois** [comment]
By removing Logitech Media Server and activing Lyrion the upgrade message doesn’t come back.Thank you a lot and have a good day.Envoyé de mon iPhoneLe 6 déc. 2024 à 19:33, Michael Herger ***@***.***> a écrit :﻿
You should uninstall the pref pane. LMS 9 is controlled using a menu bar item. See https://lyrion.org/reference/uninstall-legacy-mac/ for details.
If that's not the case can you please share a screenshot of the update prompt you are getting?
