### ISSUE TITLE
[Firmware] ethernet cable plug/unplug should reconfigure interface

### ISSUE THREAD

**Issue by marcaurele** [LMS-Community/slimserver#125]
When the device is started and configured with DHCP, if the DHCP request timeouts out, the device doesn't get a valid one. But then, if the ethernet cable is unplugged and plugged in again, the DHCP is not reconfigured. IMO the interface should go down when the cable is unplugged, and reconfigured when it's active again to allow the DHCP to reconfigure the interface.

This happens at least with the transporter.

**Comment by mherger** [comment]
There won't be any new firmware for the Squeezebox provided by Logitech. There's an effort in the community to build new firmwares. Maybe you should ask around the relevant threads in forums.slimdevices.com.
