### ISSUE TITLE
Radio stream without album cover - docker

### ISSUE THREAD

**Issue by lexmark3200** [LMS-Community/slimserver#1250]
Hi.
After pulled new version 9.0 (Lyrion not Logitech) I do not see album cover, when I play from radio stream. It shows only the radio station logo (cover).
I use Lyrion in docker.

**Comment by michaelherger** [comment]
Anything in server.log (see Settings/Information)? What display? Web browser? Mobile app? On device?

**Comment by lexmark3200** [comment]
Lyrion Music Server Version: 9.0.1 - 1733855934 @ Wed Dec 11 03:48:34 UTC 2024
Server HTTP Port Number: 9000
Operating system: Debian (Docker) - EN - utf8
Platform Architecture: x86_64-linux
Database Version: SQLite
Total Players Recognized: 1
 
Perl and Module Versions
Perl Version: 5.36.0 - x86_64-linux-gnu-thread-multi
Audio::Scan: 1.10
DBD::SQLite: 1.58 (sqlite 3.22.0)
IO::Socket::SSL: 2.081
Mozilla::CA: Unknown
Net::SSLeay: 1.92 - OpenSSL 3.0.15 3 Sep 2024

Player Model: SqueezeLite
Player Type: squeezelite
Firmware: v1.9.9-1449

It display, artist and song title - that is ok.
But I can't see album cover. Firefox, Chrome, and Squeezer too.


LOG:

> [24-12-12 19:54:33.3576] main::init (387) Starting Lyrion Music Server (v9.0.1, 1733855934, Wed Dec 11 03:48:34 UTC 2024) perl 5.036000 - x86_64-linux-gnu-thread-multi

>[24-12-12 19:54:34.5131] Slim::Plugin::FullTextSearch::Plugin::_initPopularTerms (634) Fulltext index missing or outdated - re-building
>[24-12-12 19:54:34.5135] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (513) Starting fulltext index build
>[24-12-12 19:54:34.5139] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (521) Initialize fulltext table
>[24-12-12 19:54:34.5171] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (534) Create fulltext index for tracks
>[24-12-12 19:54:34.5192] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (544) Create fulltext index for albums
>[24-12-12 19:54:34.5200] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (553) Create fulltext index for contributors
>[24-12-12 19:54:34.5208] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (563) Create fulltext index for works
>[24-12-12 19:54:34.5220] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (572) Create fulltext index for playlists
>[24-12-12 19:54:34.5274] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (587) Optimize fulltext index
>[24-12-12 19:54:34.5293] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (602) Fulltext index build done!
>[24-12-12 19:54:34.7656] main::checkDataSource (1110) Warning: Schema updated or no media found in the database, initiating scan.
>[24-12-12 19:54:34.8100] main::init (661) Server done init: http://192.168.1.99:9000
>[24-12-12 19:54:37.8729] Slim::Plugin::FullTextSearch::Plugin::_initPopularTerms (634) Fulltext index missing or outdated - re-building
>[24-12-12 19:54:37.9539] Slim::Plugin::FullTextSearch::Plugin::_initPopularTerms (634) Fulltext index missing or outdated - re-building

>[24-12-12 19:54:33.3576] main::init (387) Starting Lyrion Music Server (v9.0.1, 1733855934, Wed Dec 11 03:48:34 UTC 2024) perl 5.036000 - x86_64-linux-gnu-thread-multi
>[24-12-12 19:54:34.5131] Slim::Plugin::FullTextSearch::Plugin::_initPopularTerms (634) Fulltext index missing or outdated - re-building
>[24-12-12 19:54:34.5135] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (513) Starting fulltext index build
>[24-12-12 19:54:34.5139] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (521) Initialize fulltext table
>[24-12-12 19:54:34.5171] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (534) Create fulltext index for tracks
>[24-12-12 19:54:34.5192] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (544) Create fulltext index for albums
>[24-12-12 19:54:34.5200] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (553) Create fulltext index for contributors
>[24-12-12 19:54:34.5208] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (563) Create fulltext index for works
>[24-12-12 19:54:34.5220] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (572) Create fulltext index for playlists
>[24-12-12 19:54:34.5274] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (587) Optimize fulltext index
>[24-12-12 19:54:34.5293] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (602) Fulltext index build done!
>[24-12-12 19:54:34.7656] main::checkDataSource (1110) Warning: Schema updated or no media found in the database, initiating scan.
>[24-12-12 19:54:34.8100] main::init (661) Server done init: http://192.168.1.99:9000
>[24-12-12 19:54:37.8729] Slim::Plugin::FullTextSearch::Plugin::_initPopularTerms (634) Fulltext index missing or outdated - re-building
>[24-12-12 19:54:37.9539] Slim::Plugin::FullTextSearch::Plugin::_initPopularTerms (634) Fulltext index missing or outdated - re-building`

**Comment by michaelherger** [comment]
Oh, just re-read your message again: are you saying that you would get the station's logo, but no cover art? And NOT the generic radio station placeholder image?

What station would that be, and how do you start it? Are you using the Radio Now Playing plugin?

**Comment by lexmark3200** [comment]
Hi. 
No you don't undersood me. 
I get only logo station (Austrian Rock Radio). On old Logitech MS I saw the album cover when the song was playing. 
Title of the song, and the artist is showing correctly, but I don't see the album cover (cover art).

**Comment by lexmark3200** [comment]
![Lyrion](https://github.com/user-attachments/assets/4cf1a49a-370f-4ccf-85a5-e29af3b9428a)
On left you can see album cover this print screen is from Daphile (LMS ) on right side from Lyrion. No album cover - only the Radio station logo.

**Comment by michaelherger** [comment]
Wee my previous question: how do you start the two? And are you using Radio Now Playing on any of the two installations?

As you can see the two aren't using 100% identical metadata ("(Rock)" added to the station name or whatever).

BTW: if you prefer to write in German, please feel free to do so.

**Comment by lexmark3200** [comment]
Daphile is a system installed on my Fujitsu thin client. Lyrion is on docker on another thin client. I don't use Radio Now Playing plugin, just standard in both system. Streams are the same I don't know why on Lyrion is (Rock). 
A few dayes ago I just change on docker compose
**image: lmscommunity/lyrionmusicserver:stable** from Logitech...:stałe, the rest of compose is the same. Previosly on Logitech the album cover was like in my daphile. Even the Favorites stream didn't change after pull/upgrade from Logitech to Lyrion.
On print screen in the same time both are playing the same sound track. 
The same problem is with Virgin Switzerland. Daphile is showing album art, Lyrione doesn't. 

BTW.
Deutch sprechen ist nicht meine erste sprechen. I habe gelern etwas in Grundschule, aber jetz ist nicht perfect... Viele ich habe vergessen. 
So I prefer english, it is better for me than German. 
I am your neighbor but from east.... 


I'm sorry for my bad englisch, but bellive me or not, is better then german 🤣

**Comment by michaelherger** [comment]
Sorry about the German: as I saw "Austrian Rock" I thought you might be Austrian 😄.

The answer I'm still looking for: how do you start playback of those streams? Do you navigate to them using the Radios menu? Do you start them from a saved Favorite? Do you enter the URL manually?

**Comment by lexmark3200** [comment]
In both systems, I found the stream by searching in "Local Radio", then I added it to my Favorite. When I want to play one of my Favorites I just tap to  "play icons". Sometimes from GUI of Daphile/Lyrion (www.ipserver:9000) or from mobile apps like Squeezer.  

BTW. You don't have to apologize me 😉

**Comment by michaelherger** [comment]
Could you please share the two URLs as stored in the Favorites? In the Default skin you should be able to click a favorite to see its URL. Are they _absolutely_ identical, incl. the `partnerId`?

**Comment by lexmark3200** [comment]
From Lyrion im docker
http://opml.radiotime.com/Tune.ashx?id=s248047&formats=aac,ogg,mp3,wmpro,wma,wmvoice&partnerId=15&serial=da329c720d0dd612ecb02da3e8c84d59&filter=s:~A:country
Daphile
http://opml.radiotime.com/Tune.ashx?id=s248047&formats=aac,ogg,mp3,wmpro,wma,wmvoice,hls&partnerId=15&serial=ae63793833b307beb4e5d72ee9c8052b
Strange the serial is different... 
I will put from daphile to Lyrion and check if the album shows up

**Comment by lexmark3200** [comment]
Ok I put the same URL to both. Daphile is showing album cover, but Lyrion doesn't. 
http://opml.radiotime.com/Tune.ashx?id=s248047&formats=aac,ogg,mp3,wmpro,wma,wmvoice,hls&partnerId=15&serial=ae63793833b307beb4e5d72ee9c8052b

**Comment by michaelherger** [comment]
Ok, thanks. I've been able to reproduce the issue.

**Comment by michaelherger** [comment]
Please give the latest `stable` image another try. Thanks!

**Comment by lexmark3200** [comment]
I think, now is working like a charm...
Look yourself:
From GUI Lyrion:
![Lyrion_ok](https://github.com/user-attachments/assets/e4a30f43-1220-477b-ad31-9fdbfc69336c)
From Squeezer:
![Screenshot_2024-12-14-13-15-02-214_uk org ngo squeezer-edit](https://github.com/user-attachments/assets/2d6980fd-d305-4465-b338-05ec53e493bd)

**Comment by lexmark3200** [comment]
And next song...
![111](https://github.com/user-attachments/assets/bc03ac35-114d-4ea2-ba28-5460d6e4c2c3)
Many thanks for your time to find the solution.
Viele danke !!!
