### ISSUE TITLE
Volume control when using fixed volume with the material skin does not work

### ISSUE THREAD

**Issue by bjarteskogoy** [LMS-Community/slimserver#1254]
Volume is set to 100%: 
![image](https://github.com/user-attachments/assets/0be4dd52-53da-4d2b-81cf-acc0c29140ce)

Looks like this in the original skin: 
![image](https://github.com/user-attachments/assets/a0461743-7d1f-4a4a-a3a3-eebba19a9899)

Looks like this in material:
![image](https://github.com/user-attachments/assets/82b6fc89-c898-40e9-92f9-8dd2fd7bc6de)

**Comment by michaelherger** [comment]
Now the question is... isn't Default wrong?

**Comment by bjarteskogoy** [comment]
Not sure how this works in detail.
I'm using the Denon/Marantz plugin also. With fixed volume, the server controls the volume of the receiver instead of the player it self.
Works as expected in the original skin and also in the iPeng app.
Does not work with the Duet Controller.

**Comment by bjarteskogoy** [comment]
Description of the feature here: https://github.com/aesculus/denonavpcontrol/wiki/How-to-Use#changing-the-volume

**Comment by michaelherger** [comment]
I'd recommend you head over to https://forums.lyrion.org as you'll meet all those devs over there.

**Comment by bjarteskogoy** [comment]
Discovered a setting for Material skin enabling the behaviour I expected, so closing this.
![image](https://github.com/user-attachments/assets/f0a9af95-38e8-42da-b98b-c5e0b6807828)
