### ISSUE TITLE
Can we help users (especially new ones) confused by the change in New Music sort order

### ISSUE THREAD

**Issue by mikeysas** [LMS-Community/slimserver#1259]
See the following post regarding using file modified timestamps on the first scan (new persist.db):
https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1741701-wrong-sorting-in-new-music?p=1741913#post1741913

**Comment by michaelherger** [comment]
As outlined in that discussion I'm going to try to make the initial scan use the file's timestamp as the "added" time. But only on the very first time, when there's no library yet. We'll see...

**Comment by gharris999** [comment]
Re use file mod time as added time on wipecache: That would work for me. My library now weighs in at about 3T.  But it's on a NVMe ssd and a wipecache rescan only takes a few minutes.

**Comment by michaelherger** [comment]
Wipecache won't fix an existing database, unless you haven't used it yet. The new behaviour only applies when there's no `lastPlayed` or `playCount` in the table.

**Comment by gharris999** [comment]
Re wipecache won't fix:  So....stop LMS, delete the *.db files, restart LMS, then?  I'm guessing that will kill favorites, & etc, which is too bad. But I'm willing to pay that price for a new music order that makes sense to me.  I.e. music files that are new »to me« (i.e. ripped recently) rather than new to the library.

**Comment by michaelherger** [comment]
Pleas see https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1741701-wrong-sorting-in-new-music?p=1742015#post1742015 for a potential way to re-initialize the `added` timestamp with the files'.
