### ISSUE TITLE
plugin wont install: raop airplay bridge 

### ISSUE THREAD

**Issue by mothabrain** [LMS-Community/slimserver#1260]
i cannot install the airplay bridge via the plugin page. the zip file is been stuck in the downloaded plugin folder. other plugins get instantly installed and are useable after restart. 

does anyone have any clues so far?

**Comment by michaelherger** [comment]
Did you check your server.log for any hint about the failure? It might be that the download failed, or something else. 

If you're on LMS 9.0.0 give it a minute or two after you got the restart prompt before actually restarting LMS. Or update to the 9.0.1 nightly build (https://lyrion.org/downloads/#v901-stable-nightly-build).

**Comment by mothabrain** [comment]
i took ver 9.1.0 and now it works like a charm.
