### ISSUE TITLE
Registry value "DataPath" is in the wrong place

### ISSUE THREAD

**Issue by APMichael** [LMS-Community/slimserver#1264]
For the 64-bit server, the registry value `DataPath` is in the wrong place.

After the installation, it is still located under the key `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Lyrion\Server`. The unistaller seems to respect the value and deletes a moved data directory. The server, however, does not recognize the value and thus the moved data directory.

However, if the value is recreated under the correct key `HKEY_LOCAL_MACHINE\SOFTWARE\Lyrion\Server`, the server now also respects the value.

This should please be fixed in one of the next releases. Many thanks in advance.

[LMS v9.0.0, Windows 10 22H2, 64-bit]

**Comment by michaelherger** [comment]
Would you be able to submit a pull request with the suggested change?

**Comment by APMichael** [comment]
Thank you very much for the quick reply.

Unfortunately, I don't have much coding knowledge.

The file to be changed should be this one: https://github.com/LMS-Community/slimserver-platforms/tree/public/9.1/win32/installer/SqueezeCenterX64.iss

However, the variable `SBRegKey` is correct here. Since the installer is probably a 32-bit application, Windows redirects the writing to the registry to the `WOW6432Node` subkey. Unfortunately, I do not know how to prevent this redirection to the `WOW6432Node` subkey in an InnoSetup script.

**Comment by michaelherger** [comment]
Oh, this actually might be the answer to the question I noted here:

https://github.com/LMS-Community/slimserver-platforms/blob/public/9.1/win32/installer/SqueezeCenterX64.iss#L173-L175

**Comment by michaelherger** [comment]
Ok, I think I've been able to reproduce and hopefully fix this - in 9.1 only for now. Could you please give it a try?

https://lyrion.org/downloads/#v910-development-build

You can go back to 9.0 at any time. If that is doing what you were looking for I'll back-port to the upcoming 9.0.1 patch release.

Can you please also confirm that this was an issue for you as you wanted to move the data to a different folder (manually), and LMS didn't pick up the modified value, as it was looking in the wrong place?

**Comment by APMichael** [comment]
> Ok, I think I've been able to reproduce and hopefully fix this - in 9.1 only for now. Could you please give it a try? ...

Wow, that was fast. Thank you very much! 😃

I have tested the development build in a VM and it works as intended again. It is also good that the data directory is now created under "Lyrion" by default.

> Can you please also confirm that this was an issue for you as you wanted to move the data to a different folder (manually), and LMS didn't pick up the modified value, as it was looking in the wrong place?

Yes, that was exactly the reason for my issue report.

**Comment by michaelherger** [comment]
Thanks for the confirmation! I'll leave it in the dev 9.1 branch for a few more days and will back-port to 9.0.1 in the new year.
