### ISSUE TITLE
Add hint on Classic screensaver configuration page if Date and Time plugin isn't installed

### ISSUE THREAD

**Issue by michaelherger** [LMS-Community/slimserver#1267]
We no longer enable the "Date and Time" screensaver plugin by default, as the Classic/Boom/Transporter represent a single digit percentage of all players, and even fewer installations. But we should tell users when they try to configure the screensaver that it can be installed (or install it automatically).

Details (in German): https://forums.slimdevices.com/forum/user-forums/deutsch/1741759

**Comment by dhml** [comment]
🙏
