### ISSUE TITLE
creating favorites from triodes spotify plugin not working fully

### ISSUE THREAD

**Issue by jamestarin** [LMS-Community/slimserver#13]
I am running logitech media server 7.7.2 on an asustor 302T NAS and it is working fine
The triode spotify plugin version 2.2.16 is also working fine.

However:

When favorite a spotify track from the "Home > Song info" page by clicking on the heart, the favorite gets added to the favorite list but with no cover art icon.
If favorite a track directly from spotify search results ("Home > Spotify > Search") then the favorite gets added with the icon
If I favorite a track from my music library for the "Home > Song info" page then the favorite gets added with the icon

So it seems like favoriting from the song info page is not playing nicely with the spotify plugin.

Any suggestions as to why or how to fix it?

many thanks

**Comment by mherger** [comment]
Please check forums.slimdevices.com for any help on this issue. Thanks!
