### ISSUE TITLE
Unable to run any version on Ubuntu GNOME 16.04 64-bit

### ISSUE THREAD

**Issue by olejon** [LMS-Community/slimserver#134]
I am unable to run any version on Ubuntu GNOME 16.04 64-bit from here: http://downloads.slimdevices.com/nightly/

I read in another issue it might be because of the Perl version (5.22)? Anyway, anyone got it running or can point me in the right direction?

The error is always some problem with some Perl module(s). If they are all installed correctly it still fails. Also I have absolutely no idea how one should configure v 10, as I understand it does not have a web interface, and I can not find any general configuration file or documentation.

**Comment by mherger** [comment]
"any version" is a bit vague. What exact version did you try? How did they fail? What processor architecture are you using? 7.9 definitely should run on intel x64.

10 is not LMS but UE Music Server - to be used with the UE Smart Radio only, but not a Squeezebox. Is this what you have?

**Comment by olejon** [comment]
Sorry. I tried 10.0, 7.9 and 7.8. I have a Squeezebox Radio *upgraded* to UE Smart Radio.

Tried both the Deb packages and the tarballs with Perl modules included, but they always stop with some Perl module error. If it's a missing module (they should be included though), and I install it with cpanm or from the distro package repository, some other vague error comes up. Also I don't really see any difference between the various versions even though UE is supposed to be different (no web interface or something). They just have different binary names and config folders if installed as Deb package. The tarballs are all slimserver.pl

**Comment by mherger** [comment]
Try to start from scratch. Get rid of all logitechmediaserver, squeezebox, uemusiclibrary and related packages, files and folders.

Grab the latest .deb from http://downloads.slimdevices.com/nightly/index.php?ver=7.9 (you still haven't told me what architecture you're using). Install it. Send the resulting server.log file.

**Comment by olejon** [comment]
Done several times (Deb packages always purged and dependencies removed with apt-get --purge autoremove and tarballs just extracted in local user dir and run ./slimserver.pl, that's when I get an error. In fact the Deb packages give no errors and actually runs the daemon using the safe binary to run the regular, and it runs I can see using ps but using no RAM or CPU so I suspected something wrong and stopped the service, for the various versions, and ran the main binary directly and I get the same Perl errors. Check one of the closed issues, it says Perl 5.22 is not supported but I'm not sure if this is the case. No error indicate that directly, but it's certainly Perl related). I'm on x86_64. I'm pretty tech savvy so don't hesitate to ask for special instructions/details.

**Comment by olejon** [comment]
See above first. Will send server.log, but I looked at it and no useful errors. Only when running the binary directly I get relevant errors. Perl modules missing or mismatch or whatever cryptic.

**Comment by mherger** [comment]
"Only when starting the application the wrong way I get meaningful errors". Yes, that's true. Because when things run correctly, they don't log errors ;-).

So when you saw the process running, but it didn't eat all CPU, you decided it actually wasn't running?!? You got me rather confused there...

**Comment by olejon** [comment]
Sorry. On my desktop now. More details.

* Downloaded `http://downloads.slimdevices.com/nightly/10.0/sc/864a697/uemusiclibrary_10.0.5~1487060072_all.deb`
* Installed with no errors using `dpkg -i` (only has this in deb control file: `Depends: perl (>= 5.8.8), adduser, libc6` so installs)
* Running the service (using systemctl, which just uses the LSB script as with /etc/init.d) gives this:

```
feb. 16 14:17:51 tux uemusiclibrary[25783]: Making sure that UE Music Library is not running first: start-stop-daemon: warning: failed to kill 20318: No such process
feb. 16 14:17:51 tux uemusiclibrary[25783]: No process in pidfile '/var/run/uemusiclibrary.pid' found running; none killed.
feb. 16 14:17:51 tux uemusiclibrary[25783]: Starting UE Music Library.
feb. 16 14:17:51 tux systemd[1]: Started LSB: Startup script for the UE Music Library.
```

`server.log` goes on like this:

```
2017-02-16 14:21:51 UE Music Library died. Restarting.
2017-02-16 14:21:56 UE Music Library died. Restarting.
2017-02-16 14:22:01 UE Music Library died. Restarting.
2017-02-16 14:22:06 UE Music Library died. Restarting.
2017-02-16 14:22:11 UE Music Library died. Restarting.
2017-02-16 14:22:16 UE Music Library died. Restarting.
2017-02-16 14:22:21 UE Music Library died. Restarting.
2017-02-16 14:22:26 UE Music Library died. Restarting.
2017-02-16 14:22:31 UE Music Library died. Restarting.
2017-02-16 14:22:36 UE Music Library died. Restarting.
```

Running `ps aux|grep uemusic` shows running:

`/bin/bash /usr/sbin/uemusiclibrary_safe /usr/sbin/uemusiclibrary --prefsdir /var/lib/uemusiclibrary/prefs --logdir /var/log/uemusiclibrary/ --cachedir /var/lib/uemusiclibrary/cache --charset=utf8`

**Comment by olejon** [comment]
See above first. Running `/usr/sbin/uemusiclibrary` directly gives:

```
Can't locate Slim/bootstrap.pm in @INC (you may need to install the Slim::bootstrap module) (@INC contains: /usr/sbin /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/sbin/uemusiclibrary line 149.
BEGIN failed--compilation aborted at /usr/sbin/uemusiclibrary line 149.
```

**Comment by mherger** [comment]
Only 7.9 will work on your platform. UEML 10.0 will NOT work.

**Comment by olejon** [comment]
Ehm, here it says https://raw.githubusercontent.com/Logitech/slimserver/public/10.0/Installation.txt (10.0):

> Welcome to UE Music Library. This document describes the steps for installing the UE Music Library on Unix-like platforms.

and

> Linux Notes...

Version 7.x gives the exact same errors...

**Comment by olejon** [comment]
Okay, seems to work now when installing the `_amd64.deb` package and not the `_all.deb package` for 7.9.

Would still like 10.0 to work. Maybe possible by symlinking the modules to perl @INC (?)

**Comment by mherger** [comment]
There were a few more changes to make the code compatible with newer Perl versions. You'd have to cherry-pick them...

Why would you want to use UEML instead of LMS?

**Comment by olejon** [comment]
Aha...

Because I upgraded my Squeezebox Radio to UE Smart Radio. Is that not supported with LMS?

**Comment by mundschenk-at** [comment]
@olejon Most would doubt the classification as an _up_grade.

**Comment by olejon** [comment]
@mundschenk-at Yeah, I know. It is the second time I did it. First time I downgraded again... Just wanted to try the "latest".

**Comment by olejon** [comment]
@mherger Wow, so I actually got it up and running, lots of fiddling with Perl stuff. See if I can make a recipe, but have to do a clean install again for that. Output:

```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE (.*?)}/ at /usr/share/uemusiclibrary/CPAN/Log/Log4perl/Config/PropertyConfigurator.pm line 60.
[17-02-16 19:04:16.0940] main::init (343) Starting UE Music Library (v10.0.5, 1487060072, Thu Feb 16 04:04:33 UTC 2017) perl 5.022001
[17-02-16 19:04:16.1905] Slim::Utils::SQLiteHelper::postConnect (359) Optimizing DB because of missing or empty sqlite_stat1 table
[17-02-16 19:04:16.2428] main::checkDataSource (1088) Warning: Schema updated or no media found in the database, initiating scan.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE (.*?)}/ at /usr/share/uemusiclibrary/CPAN/Log/Log4perl/Config/PropertyConfigurator.pm line 60.
[17-02-16 19:04:16.4341] main::main (212) Starting scanner (v10.0.5, 1487060072, Thu Feb 16 04:04:33 UTC 2017) perl 5.022001
[17-02-16 19:04:16.5287] Slim::Schema::forceCommit (2134) Warning: Trying to commit transactions before DB is initialized!
[17-02-16 19:04:16.5533] Slim::Music::Import::runImporter (511) Starting Slim::Media::MediaFolderScan scan
[17-02-16 19:04:16.5534] Slim::Music::Import::endImporter (644) Completed Slim::Media::MediaFolderScan Scan in 0 seconds.
[17-02-16 19:04:16.5555] Slim::Music::Artwork::precacheAllArtwork (447) Starting precacheArtwork for 0 albums
[17-02-16 19:04:16.5556] Slim::Music::Import::endImporter (644) Completed precacheArtwork Scan in 0 seconds.
[17-02-16 19:04:16.5571] Slim::Music::Import::runScanPostProcessing (426) Starting Database optimization.
[17-02-16 19:04:16.5576] Slim::Music::Import::endImporter (644) Completed dbOptimize Scan in 0 seconds.
[17-02-16 19:04:16.5946] Slim::Utils::SQLiteHelper::postConnect (359) Optimizing DB because of missing or empty sqlite_stat1 table
```

**I can open My Music on my Radio and my computer's hostname appears at the top!**

**Question now: How to configure where the music is?**

**Comment by olejon** [comment]
Nevermind, found web interface port in `/var/lib/uemusiclibrary/prefs/server.prefs`. Let's see if it works.

**Comment by olejon** [comment]
@mherger UEML **does** work. It is working fine now. I downloaded the [uemusiclibrary-10.0.5-1487060072-noCPAN.tgz](http://downloads.slimdevices.com/nightly/10.0/sc/864a697/uemusiclibrary-10.0.5-1487060072-noCPAN.tgz) to get the most clean package to experiment with in my local directory.

Running `./ueml.pl` gives:
```
[17-02-17 01:03:11.7121] main::init (343) Starting UE Music Library (v10.0.5, 1487060072, Thu Feb 16 04:16:52 UTC 2017) perl 5.022001
[17-02-17 01:03:11.8370] Slim::Utils::PluginManager::load (234) Skipping plugin: MusicMagic - disabled
[17-02-17 01:03:11.8405] Slim::Utils::PluginManager::load (234) Skipping plugin: iTunes - disabled
[17-02-17 01:03:11.8592] Slim::Control::Jive::deleteMenuItem (487) randomplaymenu menu id slated for deletion
[17-02-17 01:03:29.4492] Slim::Utils::Prefs::OldPrefs::_oldPrefs (84) no old preference file found - using default preferences
```

After that I go to `http://localhost:3546/` and set my settings. Then on my radio, when I go to My Music from Home, it shows the name I have set for my Media Library, and all my local music. It plays it all just fine. At first it ate up my 8 GB RAM when playing a song and making my computer almost unresponsive. Could just SSH in and do a `sudo reboot` to fix it. It was some zlib thing from the output, and after installing a package from the distro repo it fixed it.

Only packages I had to install with `cpanm` (`apt install cpanminus`) were:

* Digest::SHA1
* Image::Scale
* Tie::Cache::LRU

The rest I was able to find in the distro repo by installing them with `cpanm` and then doing an uninstall with `cpanm -U` and looking for relevant files it outputs for removal, and searching on [http://packages.ubuntu.com/](http://packages.ubuntu.com/) for the relevant packages. I do not have the complete list of packages now, but I will do an install on a Virtual Machine to find it out.

Hope maybe this can lead  to a guide for Linux users who want to run UEML? Maybe I will make a build script for Ubuntu 16.04+ based distros.

Only thing I miss is the Podcast app. The Spotify app is better. Luckily I can find my crucial podcasts on TuneIn, which is an included app. Best to use the TuneIn website to search for the podcasts and add them. The radio is a bit smoother as well.

**Comment by olejon** [comment]
See above first.

Oh, and it is also **very** important to **delete**:

```
./CPAN/XML
./CPAN/DBD
./CPAN/JSON
./CPAN/Class
./CPAN/Digest
./CPAN/Image
./CPAN/Sub
./CPAN/DBI
./CPAN/Template
./CPAN/DBI.pm
./CPAN/Test
./CPAN/Template.pm
./CPAN/Compress
./CPAN/HTML
```

I forgot I also installed with `cpanm`:

* JSON::XS::VersionOneAndTwo

**Comment by olejon** [comment]
@mherger So I have created a build script for Ubuntu Linux 16.04+ based distros for UE Smart Radio (UEML). Here it is:

https://gist.github.com/olejon/304813a02045e22c63b3041861ee7aef

Cheers.

**Comment by cgoldberg** [comment]
would it be easier to just install another older/compatible Perl version onto 16.04 and run LMS/UEML with that?

**Comment by olejon** [comment]
Don't know. My script is dead simple. Just add the code to a file like `build.sh` and run `chmod +x build.sh` and `./build.sh` and that's it. You get information at the end on how to run it. Nothing is overwritten. Might add a systemctl startup/shutdown service to it later. Just put the dir in `/opt` and go from there. I might even create a deb package and put it in my repo. Click and install...

**Comment by mherger** [comment]
I think anyone who seriously wants to use his own music library should not be using the Logitech UE firmware. Just "downgrade" to SB, install the .deb and be happy. There's nothing deadlier simpler than using a working solution to start with :-).

I consider this case closed. Ok?
