### ISSUE TITLE
Document releases/versions

### ISSUE THREAD

**Issue by phile314** [LMS-Community/slimserver#137]
I find it hard to figure out how slimserver versioning works. I see that there are many version branches, but I couldn't find any information about what the different branches contain.

I suggest to add a short list to add a short README with a small list explaining the different versions.

Is 7.9 reasonably stable during normal usage? What version would you recommend for normal day-to-day usage?

**Comment by mherger** [comment]
This post probably comes closest:

http://forums.slimdevices.com/showthread.php?98711-LMS-Changelogs

And yes, 7.9 is very stable and offers the best platform support.
