### ISSUE TITLE
Small error in CLI docs about favorites

### ISSUE THREAD

**Issue by decibyte** [LMS-Community/slimserver#140]
The CLI docs about favorites say:

> `<playerid> <favorites> playlist <play|load|insert|add> <taggedParameters>`
>
> This command adds or plays a favorite.
> If item_id defines an item that can't be played, but contains playable subitems, then
> these will be played instead. This allows to eg. play all tracks of a genre.

I believe the command description should instead be:

`<playerid> favorites playlist <play|load|insert|add> <taggedParameters>`

Without angle brackets around `favorites`.

It's found [in this file](https://github.com/Logitech/slimserver/blob/3473847e1c71b500e7b81e9542ad718336902fa1/HTML/EN/html/docs/cli-api.html#L9645). I can fork and do a pull request if you like, but I believe it's easier for everyone if someone with direct access just fixes this minor thing.

**Comment by mherger** [comment]
Good catch! Fixed in commit a79c1bd3e4d8e719aebd7c0e023ad657d56c6cb2.

Someone who's seeing such issues is reading the docs carefully... what are you up to? :-)

**Comment by decibyte** [comment]
Wow, that was quick.

> Someone who's seeing such issues is reading the docs carefully...

Haha!

> what are you up to? 

Announcement is imminent :)

Btw, having read through a lot of the docs by now, it generally looks like the description of CLI responses could also use a lot of love. But, as long as the commands are properly documented, reverse engineering the responses based on whatever is returned works for me.

I could give the CLI docs some love some day.
