### ISSUE TITLE
Picture library plugin is re-enabled every upgrade. Causes crash!

### ISSUE THREAD

**Issue by howlermonkeys** [LMS-Community/slimserver#141]
Every time I install the nightly, the "picture library" plugin becomes re-enabled.  This then Scans my entire computer for images, making the server slow and crash often.

Can this not be defaulted to be enabled every reinstall please?

**Comment by mherger** [comment]
Don't panic - but you've been hacked. See the following thread:

http://forums.slimdevices.com/showthread.php?107165-IMPORTANT-Stop-forwarding-your-LMS-ports-to-the-internet!

Make sure you do NOT forward LMS' ports. Somebody is having fun making your system crash (at best), or spying your photos.
