### ISSUE TITLE
webstream fails

### ISSUE THREAD

**Issue by meus** [LMS-Community/slimserver#143]
all podcasts from https://metaebene.me/podcasts/ for example http://cre.fm/feed/mp3/ fail with the following message
`Slim::Utils::Scanner::Remote::__ANON__ (193) Error: Can't connect to remote server to retrieve playlist for, https://tracking.feedpress.it/link/13441/1885518/cre206-das-ohr.mp3: Connect timed out: .`

Usually there are a series of redirects to the final file:
1. https://tracking.feedpress.it/link/13441/1885518/cre206-das-ohr.mp3 -> 301
2. http://cre.fm/podlove/file/3239/s/feed/c/mp3/cre206-das-ohr.mp3 -> 301
3. https://cre.fm/podlove/file/3239/s/feed/c/mp3/cre206-das-ohr.mp3 -> 301
4. https://meta.metaebene.me/media/cre/cre206-das-ohr.mp3?ptm_source=feed&ptm_context=mp3&ptm_request=f3c66e32f4a5&ptm_file=cre206-das-ohr.mp3

In slimserver the request fails at the first step. It is no difference whether I open the link from the podcast plugin or by opening the stream url directly. If I start from the second link or use http instead of https in the first link everything works fine.
I saw that https://tracking.feedpress.it supports http/2, could that be the reason?

Logitech Media Server Version: 7.9.1 - 1493198727 @ Wed Apr 26 09:39:11 UTC 2017
Betriebssystem: Debian - DE - utf8
Plattformarchitektur: x86_64-linux
Perl-Version: 5.20.2 - x86_64-linux-gnu-thread-multi
Audio::Scan: 0.95

**Comment by mherger** [comment]
make sure you have IO::Socket::SSL installed on your system. Otherwise LMS will fail to follow https links.

**Comment by meus** [comment]
Thanks for the quick response.
I have the debian package libio-socket-ssl-perl installed. HTTPS usually works, as mentioned above the actual stream from above (which is https) works. It's just the first link in that row that has a problem.

**Comment by mherger** [comment]
Did this work for you previously? You could ask the podcast owner whether they recently changed something. Or whether they do apply rules to keep certain clients out.

The "timed out" in the error imho is misleading. It returns empty within a fraction of a second (immediately). There's something else wrong.

**Comment by meus** [comment]
They added the service tracking.feedpress.it, before that it did work.
The timeout also made me think and I tried to debug a little bit but perl is not my world and i could not find where exactly it fails ;(
The client string should not be the problem - with curl and a modified agent-string to represent the one send by slimserver I get the HTTP 301 answer.
`curl -v -A "iTunes/4.7.1 (Linux; N; Debian; x86_64-linux; DE; utf8) SqueezeCenter, Squeezebox Server, Logitech Media Server/7.9.1/1493198727" https://tracking.feedpress.it/link/13441/1885518/cre206-das-ohr.mp3`

> ...
> SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
> Server certificate:
> 	 subject: CN=tracking.feedpress.it
> 	 start date: 2017-05-02 19:20:00 GMT
> 	 expire date: 2017-07-31 19:20:00 GMT
> 	 subjectAltName: tracking.feedpress.it matched
> 	 issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
> 	 SSL certificate verify ok.
> 
> 
> GET /link/13441/1885518/cre206-das-ohr.mp3 HTTP/1.1
> User-Agent: iTunes/4.7.1 (Linux; N; Debian; x86_64-linux; DE; utf8) SqueezeCenter, Squeezebox Server, Logitech Media Server/7.9.1/1493198727
> Host: tracking.feedpress.it
> Accept: */*
> 
> 
> HTTP/1.1 301 Moved Permanently
> Server nginx is not blacklisted
> Server: nginx
> Date: Tue, 09 May 2017 08:07:33 GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Set-Cookie: PHPSESSID=a2f8613347f53a9d3e60be5762a048ed; path=/
> Expires: Thu, 19 Nov 1981 08:52:00 GMT
> Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> Pragma: no-cache
> Location: http://cre.fm/podlove/file/3239/s/feed/c/mp3/cre206-das-ohr.mp3
> X-Backend-Server: 172.16.0.51

**Comment by michaelherger** [comment]
Could you please give this patch a try:

http://bugs.slimdevices.com/attachment.cgi?id=7759

**Comment by michaelherger** [comment]
Fixed in commit 1021146a41db9b5ff50072e51a9a178049bba5bf.

**Comment by meus** [comment]
You are awesome!
Works like a charm.

Thanks a lot.

**Comment by mherger** [comment]
Wasn't me :-). All praise goes to Martin Williams who figured this all out (see http://bugs.slimdevices.com/show_bug.cgi?id=18152).
