### ISSUE TITLE
Missing images in 7.9.0

### ISSUE THREAD

**Issue by hartzell** [LMS-Community/slimserver#145]
I'm trying to track down an 'Aw Snap' issue in Chrome with the LMS that is included as part of piCorePlayer v3.20.

> Logitech Media Server Version: 7.9.0 - 1488878280 @ Wed Mar 8 14:07:50 UTC 2017`

The page crash is a separate issue (though not yet an Issue worthy of reporting somewhere) that I'm pretty sure it's related to Ghostery (ad blocking and etc... plugin).

Along the way I noticed that there seems to be a handful of missing images in the web UI:

<img width="682" alt="screen shot 2017-05-21 at 8 20 31 am" src="https://cloud.githubusercontent.com/assets/312978/26285207/1f4a52d6-3e00-11e7-8c82-70138ba92b77.png">

The images seem to be present in the installation, but are in the `EN` subtree instead of `Default`.

```
tc@slim:/usr/local/slimserver$ find . | xargs grep -i shadow-c.png
./HTML/EN/html/ext/resources/css/ext-all.css:    background-image: url(../images/default/shadow-c.png);
./HTML/Default/html/ext/resources/css/ext-main.css:    background-image: url(../images/default/shadow-c.png);
./HTML/Default/html/ext/resources/css/ext-browse.css:    background-image: url(../images/default/shadow-c.png);
^C
tc@slim:/usr/local/slimserver$ find HTML | grep shadow
HTML/EN/html/ext/resources/images/default/shadow.png
HTML/EN/html/ext/resources/images/default/shadow-lr.png
HTML/EN/html/ext/resources/images/default/shadow-c.png
```

I'm not sure how these bits are wired together.  Perhaps the problem is that they're in the `EN` subtree instead of `Default`, or perhaps it's a case-sensitivity issue (`Default` vs `default`)?

**Comment by mherger** [comment]
Yes, path names are case sensitive. How did they get in there in lower case?!?

The skin handling is falling back to EN resources if one was missing in another skin.

**Comment by hartzell** [comment]
I've asked the folks over in the piCorePlayer about how/where their LMS binaries get built.

http://forums.slimdevices.com/showthread.php?107437-Missing-images-in-LMS-in-piCorePlayer-3-20-(aka-slimserver-issue-145)

**Comment by hartzell** [comment]
@mherger -- Are you saying that the 404's aren't really errors, that the skin machinery asking for a specific version of the file, get's the 404 and then asks for the generic version?

**Comment by mherger** [comment]
Your browser is asking for an invalid path (lowercase "default"), the server returns the correct answer: not found. You're not accessing LMS directly, are you? Is there some proxy sitting in between Chrome and LMS? Or yet another add-on?

**Comment by hartzell** [comment]
I'm just pointing my browser at port 9000 on the Pi.

The image that's being asked for, e.g. `shadow-c.png` has the same case as the string that I find in the CSS that I think is "asking for it".  I can't clip it out of the image I embedded above, but here's the bit from the code block above:

```
background-image: url(../images/default/shadow-c.png);
```

**Comment by mherger** [comment]
Oh, these are images from the underlying ExtJS framework. Yes, they're all lower-case, that's fine.

I can only ask you again to try Chrome without any extension/add-on. This is not a LMS bug.

**Comment by hartzell** [comment]
Also happens in Safari

<img width="1359" alt="screen shot 2017-05-26 at 10 24 08 am" src="https://cloud.githubusercontent.com/assets/312978/26505492/d6d4f054-41fd-11e7-9ccf-f45dad6fb0c2.png">

and in Chrome w/ no extensions installed (except the Google Docs extensions that are included oit of the box) in a newly created account on a Mac.

It doesn't happen right away, I need to wave my house around  bit, presumably causing something to get hilit/shadowed/...

I'll close this since I don't have an idea how to dig further and it seems to be a bug in ExtJS.
