### ISSUE TITLE
Volume Sync: Group of 3. 2xBooms with Volume Sync also Sync Touch with no Sync

### ISSUE THREAD

**Issue by olemr** [LMS-Community/slimserver#147]
Have a sync group with 2x Booms with volume sync. and 1x Touch without volume sync enabled.
The Touch is connected to an AVR and need to be at 100% volume.

When activating group, Booms are also set to 100% :-O

**Comment by mherger** [comment]
What LMS version? Would it make any difference if you synched the Touch with a Boom or the other way around?

**Comment by olemr** [comment]
I'm on Logitech Media Server Version: 7.9.1 - 1498468656 @ Mon Jun 26 10:16:02 UTC 2017
No, no difference. Changing Volume on the Touch also changes the Booms, even though setting says 'Don't sync players volume'

**Comment by olemr** [comment]
Sorry, didn't mean to Close issue. Thought I closed the Dialog :-)

**Comment by mherger** [comment]
Are you using the player setting to fix the volume to 100% (Audio settings of the Touch) or do you simply always crank it up to 100%? Did you check sync settings on both players?

**Comment by olemr** [comment]
Thanks! The tip to fix the touch audio @ 100% did the trick.
Now I can keep my AVR at a low volume without the Booms also going to 100% volume.
