### ISSUE TITLE
Allow configuration of IP address externally from environment variable.

### ISSUE THREAD

**Issue by snowzach** [LMS-Community/slimserver#148]
I prefer to run the media server from a docker container which NATS and the routines to discover the IP address of the server end up picking up the docker IP instead of the actual IP address of the docker host. This breaks some plugins like the Triode spotify plugin. It would be nice to set the public IP from an environment variable if set.

I changed /usr/share/perl5/Slim/Utils/Network.pm
For whatever reason setting it from the command line didn't work for me. 
sub serverAddr {
     if(defined $ENV{'PUBLIC_IP'}) { return $ENV{'PUBLIC_IP'} }
     return $main::httpaddr || hostAddr();
}

**Comment by mherger** [comment]
Why don't you use the httpaddr runtime parameter?

**Comment by snowzach** [comment]
Hm, perhaps I should have opened a bug ticket but that parameter doesn't work for me. For whatever reason it still has the wrong address.

**Comment by michaelherger** [comment]
There are lots of container configurations for LMS, and quite a few of them are using httpaddr iirc. Did you try one of them?

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=logitech&starCount=0
