### ISSUE TITLE
Perl 5.22 not supported by LMS 7.9 or 7.8 on Ubuntu 16.04 on Raspberry Pi 3 (ARM)

### ISSUE THREAD

**Issue by willberriss** [LMS-Community/slimserver#154]
Hi

The latest nightly LMS 7.9  (and 7.8) fails to run on Ubuntu 16.04 due to Perl being too recent, version 5.22

The error message is this:

`root:/var/log/squeezeboxserver# /usr/sbin/squeezeboxserver --prefsdir /var/lib/squeezeboxserver/prefs --logdir /var/log/squeezeboxserver/ --cachedir /var/lib/squeezeboxserver/cache --charset=utf8`
` `
`The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name`

My system is this - a Raspberry Pi 3 Model B with Ubuntu 16.04 installed on it.

root:/var/log/squeezeboxserver# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"

root:/var/log/squeezeboxserver# uname -a
Linux moya 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux

N.B.  The Pi 3 is actually an armv8 processor, but Ubuntu on it reports arm v7  (a well-known issue it seems)

`will:~$ perl -v`
``
`This is perl 5, version 22, subversion 1 (v5.22.1) built for arm-linux-gnueabihf-thread-multi-64int
(with 58 registered patches, see perl -V for more detail)`
``
`Copyright 1987-2015, Larry Wall`
`...`

I am wondering why Perl isn't backwards compatible, i.e. if LMS was built against Perl 5.20, then why doesn't it run on Perl 5.22?

**Comment by willberriss** [comment]
My workaround for now is this:

See also some instructions here:  https://forums.freenas.org/index.php?threads/9-3-how-to-build-and-install-lms-7-9-from-scratch.27161/

STEP 1:  I cloned **https://github.com/Logitech/slimserver.git** to  /opt/logitechmediaserver_7.9.1
               I put it under /opt/logitechmediaserver_7.9.1/

STEP 2:  I cloned **https://github.com/Logitech/slimserver-vendor.git**
                I put it under /root/logitech-media-server/

STEP 3:  I ran **buildme.sh** in the slimserver-vendor directory

STEP 4:   cd /opt/logitechmediaserver_7.9.1/slimserver/CPAN/arch/5.22
                **cp -Rp /root/logitech-media-server/slimserver-vendor/CPAN/build/arch/5.22/arm-linux-gnueabihf-thread-multi-64int .**

STEP 5:   cd /opt/logitechmediaserver_7.9.1/slimserver/CPAN/Image
                 root:# **mv Scale.pm Scale.pm.0.08**
                 root:# **cp /root/logitech-media-server/slimserver-vendor/CPAN/build/5.22/lib/perl5/arm-linux-gnueabihf-thread-multi-64int/Image/Scale.pm .**

STEP 6:  It must not run as root, so I chown the lot:
              root:/opt/logitechmediaserver_7.9.1# **chown -R squeezeboxserver:nogroup /opt/logitechmediaserver_7.9.1/slimserver**

STEP 7: Run it as user squeezeboxserver
            squeezeboxserver:/opt/logitechmediaserver_7.9.1/slimserver# **./slimserver.pl --daemon**

**Comment by michaelherger** [comment]
That's not a workaround, but a proper solution ;-). Just keep the self-compiled files in a safe place in case the next LMS update would overwrite or delete them.

**Comment by willberriss** [comment]
Regarding installing LMS 7.9 on a Raspberry Pi 3, are the ARM distributions in the following 2 deb packages identical?
From [http://downloads.slimdevices.com/nightly/index.php?ver=7.9](http://downloads.slimdevices.com/nightly/index.php?ver=7.9)
`(1) logitechmediaserver_7.9.1~1499900819_arm.deb  (ARM)`
`(2)  logitechmediaserver_7.9.1~1499900819_all.deb  (ARM EABI and friends)`
It's just that (1) says ARM but (2) says ARM EABI and now I am wondering if there is a subtle difference?
Finally will the deb file (1) just work on Raspbian Jessie and Raspbian Jessie Lite? 
[https://www.raspberrypi.org/downloads/raspbian/](https://www.raspberrypi.org/downloads/raspbian/)

**Comment by michaelherger** [comment]
Yes, they're all the same.

**Comment by mcl-chinnock** [comment]
hi,

on ubuntu 16.04...

following these instructions and stuck at this error with the buildme.sh which I'm  running in the CPAN directory..

mv Makefile Makefile.old > /dev/null 2>&1
build_module run tests:1 clean:1 hints 1 Audio-Scan-0.95 
'../hints/darwin.pl' -> './hints/darwin.pl'
Generating a Unix-style Makefile
Writing Makefile for Audio::Scan
Writing MYMETA.yml and MYMETA.json
Skip blib/lib/Audio/Scan.pm (unchanged)
Running Mkbootstrap for Audio::Scan ()
chmod 644 "Scan.bs"
x86_64-linux-gnu-gcc -c  -I. -I.. -Isrc -Iinclude -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"0.95\" -DXS_VERSION=\"0.95\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.22/CORE"  -O2 -Wall -Wno-unused-value -Wno-format-security Scan.c
Makefile:343: recipe for target 'Scan.o' failed
make test failed, aborting


New to all of this so any pointers greatly appreciated.

**Comment by michaelherger** [comment]
@githubchinny - isn't there a build log which would have more information? Like eg. what test failed?

But FWIW: why would you want to build those binaries on that platform anyway? They're part of LMS already.

**Comment by mcl-chinnock** [comment]
I was getting the error at the top of this thread ... I thought I had to recompile an old version of perl.

Just grabbed logitechmediaserver_7.9.1~1505480690_amd64.deb and tried again and it is working.

Sorry but thanks for the pointer.
