### ISSUE TITLE
LMS dies after 5 seconds (since 2 day) - Debian Testing (Daily updated) 

### ISSUE THREAD

**Issue by klakklak** [LMS-Community/slimserver#156]
Linux debt21 4.11.0-1-amd64 #1 SMP Debian 4.11.6-1 (2017-06-19) x86_64 GNU/Linux

ii  logitechmediaserver                  7.9.1~1496913376 

2017-07-28 06:36:27 squeezeboxserver_safe started.
2017-07-28 06:36:32 Logitech Media Server died. Restarting.
2017-07-28 06:36:37 Logitech Media Server died. Restarting.
2017-07-28 06:36:42 Logitech Media Server died. Restarting.
2017-07-28 06:36:47 Logitech Media Server died. Restarting.
2017-07-28 06:36:52 Logitech Media Server died. Restarting.
2017-07-28 06:36:57 squeezeboxserver_safe stopped.

**Comment by clarkspark** [comment]
I am having the same issue in testing after an update to perl 5.26.


perl info:
root@bk:~# perl -v

This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux-gnu-thread-multi
(with 51 registered patches, see perl -V for more detail)

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.




LMS info:
root@bk:~# squeezeboxserver -v
The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name

*******

NOTE:

If you're running some unsupported Linux/Unix platform, please use the buildme.sh 
script located here:

https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN

If 7.9 is outdated by the time you read this, Replace "7.9" with the major version
You should never need to do this if you're on Windows or Mac OSX. If the installers
don't work for you, ask for help and/or report a bug.

*******

			
Exiting..

**Comment by mherger** [comment]
We don't have binaries for Perl 5.26 yet. So your best bet is to follow the instructions as quoted by @clarkspark and build them yourselves.

**Comment by IcePee** [comment]
Attempted to run the buildme script. It says:
```
RUN_TESTS:1 CLEAN:1 USE_HINTS:1 target all
Building for Linux / x86_64-linux-thread-multi
Failed to find supported Perl version for '/usr/bin/perl'
```

**Comment by sanduhrs** [comment]
Same issue on RaspberryPi with Raspian and Arch, both  Perl v5.24.1, arm7:
Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux

**Comment by michaelherger** [comment]
There are a bunch of pull requests in the slimserver-vendor repository dealing with more recent Perl versions (https://github.com/Logitech/slimserver-vendor/pull/25). You might want to give them a try? Please report back, if you do, as I'd like to merge them should they prove to be working.

**Comment by Leicas** [comment]
I had to use (https://github.com/Logitech/slimserver-vendor/pull/25) to update to perl v5.26, confirmed to work on Debian.

**Comment by fsbruva** [comment]
@klakklak Did the updated build script (or new binaries) solve your issue?

**Comment by mherger** [comment]
Let's be optimistic :-)

**Comment by klakklak** [comment]
A new binaries solve my issue.

Thnaks for all

**Comment by wyleu** [comment]
I'm experiencing exactly this problem with my raspberry-pi3.
I've downloaded version 7.9 as the logitechmediaserver_7.9.1~1517314665_arm.deb
and that has installed...
I've downloaded buildme.sh
and run it which gave:-

********************************************** WARNING *************************************
*                                                                                          *
*    Perl was compiled with arm-linux-gnueabihf-gcc,
*    which is different than gcc.
*    This may cause significant problems.                                                  *
*                                                                                          *
* Press CTRL^C to stop the build now...                                                    *
********************************************************************************************
Building for Linux / arm-linux-gnueabihf-thread-multi-64int
Building with Perl 5.24 at /usr/bin/perl5.24.1
build_module run tests:0 clean:1 hints 1 Sub-Uplevel-0.22
ERROR: cannot find source code archive Sub-Uplevel-0.22.tar.gz
Please download all source files from http://github.com/Logitech/slimserver-vendor

I did download http://github.com/Logitech/slimserver-vendor last night and it took an hour or so to build from the buildme.sh script but it failed . . . I dont' have the error message to hand as I had to go and have a shower before the guests arrived and set up my wife's iphone and a bluetooth speaker to provide music . . . .


I'm a Perl novice so really just following instructions but have reached a bit of an impasse. 

So I am trying to get my slimserver working again ( it worked last week) in the face of some fairly caustic comments from my partner.

Could someone explain what has actually changed and what I do to get it working?

p.s. sorry to sound slightly raw but I was meant to be demonstrating the slimserver to someone who was interested and we'd organised the evening partly to do that.

**Comment by michaelherger** [comment]
@wyleu - Given the Perl version string this should run out of the box. What exact OS are you running? How does LMS fail (server.log)?

**Comment by wyleu** [comment]
Thanks for getting back to me,

pi@hifiberry3:/etc $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@hifiberry3:/etc $
2018-02-16 07:51:01 Logitech Media Server died. Restarting.
2018-02-16 07:51:06 Logitech Media Server died. Restarting.
2018-02-16 07:51:11 Logitech Media Server died. Restarting.
2018-02-16 07:51:16 Logitech Media Server died. Restarting.
2018-02-16 07:51:21 Logitech Media Server died. Restarting.
2018-02-16 07:51:26 Logitech Media Server died. Restarting.
2018-02-16 07:51:31 Logitech Media Server died. Restarting.
2018-02-16 07:51:36 Logitech Media Server died. Restarting.

pi@hifiberry3:/etc $ perl -v

This is perl 5, version 24, subversion 1 (v5.24.1) built for arm-linux-gnueabihf-thread-multi-64int
(with 75 registered patches, see perl -V for more detail)

**Comment by michaelherger** [comment]
@wyleu - I somehow lost track of your issue... did you say what LMS build you installed?

Could you try to run `/usr/sbin/squeezeboxserver --d_startup` from the shell and report what it says?

**Comment by fsbruva** [comment]
> I've downloaded version 7.9 as the logitechmediaserver_7.9.1~1517314665_arm.deb
and that has installed...
I've downloaded buildme.sh
and run it which gave:-

His run of buildme.sh failed because that was the only thing he downloaded from -vendor.

Once got all the sources, the build failed after an hour, but he didn't retain the error message.

**Comment by wyleu** [comment]
/usr/sbin/squeezeboxserver --d_startup > /tmp/d_startup.txt

[d_startup.txt](https://github.com/Logitech/slimserver/files/1732179/d_startup.txt)

**Comment by wyleu** [comment]
Probably not relevant 

I've installed squeezelite and it is producing a click every second or so.

sudo apt-get install squeezelite from instruction http://www.winko-erades.nl/index.php?option=com_content&view=article&id=54:installing-squeezelite-player-on-a-raspberry-pi-running-jessie&catid=20:raspbian


* added the SB_EXTRA_ARGS="-a 180"

**Comment by wyleu** [comment]
And when I get the correct version of the software 7.9 it works !!!

**Comment by wyleu** [comment]
This is a new hifiberry2 with a raspberry pi 3 I'd picked up 7.7 & Perl components for 7.9 . . .


Presumably I should take the following elsewhere for discussion . . .  :-D
installed the squeezelite but it clicks once a second in one channel . . . 
http://www.winko-erades.nl/index.php?option=com_content&view=article&id=54:installing-squeezelite-player-on-a-raspberry-pi-running-jessie&catid=20:raspbian

including the SB_EXTRA_ARGS="-a 180"

**Comment by mherger** [comment]
You had 7.6 installed?... now that's super old :-). But rather than mix 7.7 with modules from 7.9, why don't you go to 7.9 straight away? It has a bunch of nice additions compared to 7.7.

**Comment by wyleu** [comment]
I've got 7.9 running ! late night installation isn't always a good idea :-D

![image](https://user-images.githubusercontent.com/79083/36339832-e3a89188-13c5-11e8-9013-0f22da590424.png)

Many thanks guys. I will pursue the clicking issue with the squeezelite community! unless of course anyone does know an answer.

**Comment by wyleu** [comment]
Turns out it's a duff hifiberry Amp2 card.
