### ISSUE TITLE
How do I get the current artist from JSON RPC in 7.9.0?

### ISSUE THREAD

**Issue by oliwarner** [LMS-Community/slimserver#162]
For a while I've been using the JSON RPC from a little home-made script to grab the artist/track and display the lyrics. My side of the equation isn't that important, the problem is, since upgrading from [a very old] nightly of 7.9.0 to this year's release, the API has changed.

The player-status endpoint still contains a playlist (the next few songs about to play) but none of the playlist items have an `artist` item. This kills my lyrics script.

But you're still showing the artist (and a bit load of meta data) in the Web UI. What I can't work out is where that data's coming from. I've snooped on most of the XHR interaction.

Where can I get the current artist now? And why isn't it in the status endpoint's playlist any more?

Edit: I've noticed that the UI's first request _does_ get `albumartist` and `trackartist` entries but subsequent replies do not feature these. The only difference is the "tag" value that gets posted through in the request. Can somebody explain the difference between `tags:cgABbehldiqtyrSuoKLNJ` (first load) and `tags:uB` (subsequent). These _look_ deliberately unique.

Edit2: Posting through `tags:cgABbehldiqtyrSuoKLNJ` as part of my request works, but why? What does this hellstring mean?

**Comment by mherger** [comment]
Please see the CLI documentation http://yourserver:9000/html/docs/cli-api.html
