### ISSUE TITLE
Soma.fm plugin doesn't display artwork / titles

### ISSUE THREAD

**Issue by craigmaloney** [LMS-Community/slimserver#163]
It looks like the Soma.fm app / plugin doesn't display the artwork or the titles of the songs that it plays.

I have some old favorites that I saved that work just fine. I took a look at the URLs that the app generates and compared them with the old favorites. The only difference I noticed was that the new URLs appear to use https instead of http.

It looks like both of the playlists that are sent are identical, but it appears the https fetch is causing some heartburn.

Thoughts on how to resolve this?

**Comment by michaelherger** [comment]
The Soma.fm "app" actually is nothing but a link to an OPML file Soma.fm provides. There is no code involved other than for any other radio station.

That said their switching to https can cause issues on some installations. What LMS build are you using? If on 7.8 or later, what option to resize artwork are you using (Settings/Advanced/Performance)?

**Comment by craigmaloney** [comment]
Ah, that makes sense.

I'm using:

Logitech Media Server Version: 7.9.0 - 1488878280 @ Tue Mar 7 09:29:54 UTC 2017

Under Advanced / Performance it was using mysqueezebox.com to resize artwork. I changed it to LMS but there's no change in behavior with Soma.fm via the "app".

**Comment by craigmaloney** [comment]
Updated to Logitech Media Server Version: 7.9.1 - 1502265250 @ Sat Aug 12 04:20:11 UTC 2017

Same behavior.

**Comment by michaelherger** [comment]
The artwork information is missing from the stream's metadata:

```
[17-08-14 20:10:23.3573] Slim::Player::Protocols::HTTP::parseHeaders (487) Bitrate for http://ice1.somafm.com/bagel-128-mp3 set to 128000
[17-08-14 20:10:23.3577] Slim::Formats::RemoteStream::request (209) Opened stream!
[17-08-14 20:10:23.7015] Slim::Player::Protocols::HTTP::readMetaData (88) Metadata size: 48
[17-08-14 20:10:23.7018] Slim::Player::Protocols::HTTP::readMetaData (115) Metadata: StreamTitle='The Drums - Mirror';StreamUrl='';
[17-08-14 20:10:23.7020] Slim::Player::Protocols::HTTP::parseMetadata (154) Icy metadata received: StreamTitle='The Drums - Mirror';StreamUrl='';
```

"StreamUrl" is what would tell us what artwork to show. It's empty. You should try to reach out to Soma.fm.

**Comment by michaelherger** [comment]
Hmm.... so Rusty says they never included artwork in their streams:

> We haven't included that ever. It's because the URL then shows that URL in the iTunes Player window. And if we set it to just SomaFM.com the player shows broken images. Also if they use the somafm app the image in the xml file usually shows up if there is nothing set for stream URL.

Did you really get artwork before? Or did you just get the station icon as seen in the station listing?

**Comment by craigmaloney** [comment]
I got the channel artwork (not the album artwork).

But it seems if I use the https stream it doesn't even give me the song titles, no matter how long I wait. If I use http then it seems to work with no problem.

**Comment by michaelherger** [comment]
Could you please give me a working URL? Replacing https with http doesn't work for me.

**Comment by decibyte** [comment]
I'm using the SFM app (not a plugin, afaik) every day and I _do_ see channel logos on my Radio. If I remember it, I'll check again when I'm back home.

**Comment by craigmaloney** [comment]
I made a quick video of what I'm seeing when I select a https:// soma.fm stream, and what happenes when I just use http://

Hopefully this clarifies what's going on. Thanks!

https://www.dropbox.com/sh/184dbdydkszclwv/AAAlny2xaeRQebzAHm69Rc03a?dl=0

**Comment by michaelherger** [comment]
Excellent! Thanks for bringing this up. It's not a soma.fm issue after all, but a generic http vs. https issue. I should have a fix shortly.

**Comment by craigmaloney** [comment]
Just updated to the latest nightly and it appears to work perfectly.
Thank you so much!
