### ISSUE TITLE
LMS keeps dying

### ISSUE THREAD

**Issue by ultraschuppi** [LMS-Community/slimserver#165]
Good morning!

out of a sudden my LMS keeps looping to die forever...

> root@heimat:/home/pi# tail -F /var/log/squeezeboxserver/server.log
> 2017-09-14 06:26:34 Logitech Media Server died. Restarting.
> 2017-09-14 06:26:39 Logitech Media Server died. Restarting.
> 2017-09-14 06:26:44 Logitech Media Server died. Restarting.
> 2017-09-14 06:26:49 Logitech Media Server died. Restarting.
> 2017-09-14 06:26:54 Logitech Media Server died. Restarting.
> 2017-09-14 06:26:59 Logitech Media Server died. Restarting.
> 2017-09-14 06:27:04 Logitech Media Server died. Restarting.
> 2017-09-14 06:27:09 Logitech Media Server died. Restarting.
> 2017-09-14 06:27:14 Logitech Media Server died. Restarting.
> 2017-09-14 06:27:19 squeezeboxserver_safe stopped.

it runs on a pretty old respian, LMS is some 7.x

> 
> root@heimat:/home/pi# perl -v
> 
> This is perl 5, version 20, subversion 2 (v5.20.2) built for arm-linux-gnueabihf-thread-multi-64int
> (with 47 registered patches, see perl -V for more detail)
> 
> Copyright 1987-2015, Larry Wall
> 
> Perl may be copied only under the terms of either the Artistic License or the
> GNU General Public License, which may be found in the Perl 5 source kit.
> 
> Complete documentation for Perl, including FAQ lists, should be found on
> this system using "man perl" or "perldoc perl".  If you have access to the
> Internet, point your browser at http://www.perl.org/, the Perl Home Page.`

i noticed https://github.com/Logitech/slimserver/issues/156 - looking like same sympthoms, but my perl-version did not change for a long time. maybe it is some other, deeper problem?

is there a way to "wipe out the cache" (not the config!) and try it this way? i would rather not do a fresh install since my google-music-plugin is finally working ;-)

anyone else having this problem?

**Comment by mherger** [comment]
Run ```sudo /usr/sbin/squeezeboxserver --d_startup``` and report what you get.

**Comment by ultraschuppi** [comment]
> pi@heimat:~ $ sudo /usr/sbin/squeezeboxserver --d_startup
> Found SELinux - setting security context to: texrel_shlib_t for *.so files.
> Got @INC containing:
> /usr/share/squeezeboxserver/CPAN
> /usr/share/squeezeboxserver
> /usr/sbin
> /etc/perl
> /usr/local/lib/arm-linux-gnueabihf/perl/5.20.2
> /usr/local/share/perl/5.20.2
> /usr/lib/arm-linux-gnueabihf/perl5/5.20
> /usr/share/perl5
> /usr/lib/arm-linux-gnueabihf/perl/5.20
> /usr/share/perl/5.20
> /usr/local/lib/site_perl
> .
> 
> Extended @INC to contain:
> /usr/share/squeezeboxserver/CPAN/arch/5.20/arm-linux-gnueabihf-thread-multi-64int
> /usr/share/squeezeboxserver/CPAN/arch/5.20/arm-linux-gnueabihf-thread-multi-64int/auto
> /usr/share/squeezeboxserver/CPAN/arch/5.20.2/arm-linux-gnueabihf-thread-multi-64int
> /usr/share/squeezeboxserver/CPAN/arch/5.20.2/arm-linux-gnueabihf-thread-multi-64int/auto
> /usr/share/squeezeboxserver/CPAN/arch/5.20/arm-linux-gnueabihf-thread-multi-64int
> /usr/share/squeezeboxserver/CPAN/arch/5.20/arm-linux-gnueabihf-thread-multi-64int/auto
> /usr/share/squeezeboxserver/CPAN/arch/arm-linux-gnueabihf-thread-multi-64int
> /usr/share/squeezeboxserver/CPAN/arch/5.20
> /usr/share/squeezeboxserver/lib
> /usr/share/squeezeboxserver/CPAN
> /usr/share/squeezeboxserver
> /usr/share/squeezeboxserver/CPAN
> /usr/share/squeezeboxserver
> /usr/sbin
> /etc/perl
> /usr/local/lib/arm-linux-gnueabihf/perl/5.20.2
> /usr/local/share/perl/5.20.2
> /usr/lib/arm-linux-gnueabihf/perl5/5.20
> /usr/share/perl5
> /usr/lib/arm-linux-gnueabihf/perl/5.20
> /usr/share/perl/5.20
> /usr/local/lib/site_perl
> .
> 
> Loaded module: [version] ok!
> Loaded module: [Time::HiRes] ok!
> Loaded module: [DBI] ok!
> Loaded module: [EV] ok!
> Loaded module: [XML::Parser::Expat] ok!
> Loaded module: [HTML::Parser] ok!
> Loaded module: [JSON::XS] ok!
> Loaded module: [Digest::SHA1] ok!
> Loaded module: [YAML::XS] ok!
> Loaded module: [Sub::Name] ok!
> The following modules are loaded after the first attempt:
> 	vars.pm => /usr/share/perl/5.20/vars.pm
> 	Scalar/Util.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Scalar/Util.pm
> 	File/Spec/Functions.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/File/Spec/Functions.pm
> 	Slim/Utils/OS/Linux.pm => /usr/share/perl5/Slim/Utils/OS/Linux.pm
> 	Exporter.pm => /usr/share/perl/5.20/Exporter.pm
> 	Sub/Name.pm => /usr/share/squeezeboxserver/CPAN/Sub/Name.pm
> 	Slim/Utils/OSDetect.pm => /usr/share/perl5/Slim/Utils/OSDetect.pm
> 	strict.pm => /usr/share/perl/5.20/strict.pm
> 	Fcntl.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Fcntl.pm
> 	re.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/re.pm
> 	Time/HiRes.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Time/HiRes.pm
> 	warnings.pm => /usr/share/perl/5.20/warnings.pm
> 	POSIX.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/POSIX.pm
> 	if.pm => /usr/share/perl/5.20/if.pm
> 	Carp.pm => /usr/share/perl/5.20/Carp.pm
> 	Slim/Utils/OS.pm => /usr/share/perl5/Slim/Utils/OS.pm
> 	File/Spec.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/File/Spec.pm
> 	constant.pm => /usr/share/perl/5.20/constant.pm
> 	HTML/Parser.pm => /usr/share/squeezeboxserver/CPAN/HTML/Parser.pm
> 	overload.pm => /usr/share/perl/5.20/overload.pm
> 	EV.pm => /usr/share/squeezeboxserver/CPAN/EV.pm
> 	locale.pm => /usr/share/perl/5.20/locale.pm
> 	Config.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Config.pm
> 	HTML/Entities.pm => /usr/share/squeezeboxserver/CPAN/HTML/Entities.pm
> 	Config_git.pl => /usr/lib/arm-linux-gnueabihf/perl/5.20/Config_git.pl
> 	overloading.pm => /usr/share/perl/5.20/overloading.pm
> 	version/vpp.pm => /usr/share/squeezeboxserver/CPAN/version/vpp.pm
> 	Cwd.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Cwd.pm
> 	File/Basename.pm => /usr/share/perl/5.20/File/Basename.pm
> 	Config_heavy.pl => /usr/lib/arm-linux-gnueabihf/perl/5.20/Config_heavy.pl
> 	lib.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/lib.pm
> 	warnings/register.pm => /usr/share/perl/5.20/warnings/register.pm
> 	feature.pm => /usr/share/perl/5.20/feature.pm
> 	Symbol.pm => /usr/share/perl/5.20/Symbol.pm
> 	List/Util.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/List/Util.pm
> 	YAML/XS/LibYAML.pm => /usr/share/squeezeboxserver/CPAN/YAML/XS/LibYAML.pm
> 	DynaLoader.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/DynaLoader.pm
> 	File/Spec/Unix.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/File/Spec/Unix.pm
> 	B/Deparse.pm => /usr/share/perl/5.20/B/Deparse.pm
> 	B.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/B.pm
> 	File/Path.pm => /usr/share/perl/5.20/File/Path.pm
> 	Slim/Utils/OS/Unix.pm => /usr/share/perl5/Slim/Utils/OS/Unix.pm
> 	Digest/base.pm => /usr/share/squeezeboxserver/CPAN/Digest/base.pm
> 	version/regex.pm => /usr/share/squeezeboxserver/CPAN/version/regex.pm
> 	version.pm => /usr/share/squeezeboxserver/CPAN/version.pm
> 	attributes.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/attributes.pm
> 	Exporter/Heavy.pm => /usr/share/perl/5.20/Exporter/Heavy.pm
> 	Digest/SHA1.pm => /usr/share/squeezeboxserver/CPAN/Digest/SHA1.pm
> 	common/sense.pm => /usr/share/squeezeboxserver/CPAN/common/sense.pm
> 	Slim/Utils/OS/Debian.pm => /usr/share/perl5/Slim/Utils/OS/Debian.pm
> 	Slim/bootstrap.pm => /usr/share/perl5/Slim/bootstrap.pm
> 	XML/Parser/Expat.pm => /usr/share/squeezeboxserver/CPAN/XML/Parser/Expat.pm
> 	JSON/XS.pm => /usr/share/squeezeboxserver/CPAN/arch/5.20/JSON/XS.pm
> 	XSLoader.pm => /usr/share/perl/5.20/XSLoader.pm
> 	base.pm => /usr/share/perl/5.20/base.pm
> 	Tie/Hash.pm => /usr/share/perl/5.20/Tie/Hash.pm
> 	Getopt/Long.pm => /usr/share/perl/5.20/Getopt/Long.pm
> 	YAML/XS.pm => /usr/share/squeezeboxserver/CPAN/YAML/XS.pm
> 	FindBin.pm => /usr/share/perl/5.20/FindBin.pm
> 	DBI.pm => /usr/share/squeezeboxserver/CPAN/arch/5.20/DBI.pm
> 
> The following modules are loaded after the second attempt:
> 	vars.pm => /usr/share/perl/5.20/vars.pm
> 	Scalar/Util.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Scalar/Util.pm
> 	File/Spec/Functions.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/File/Spec/Functions.pm
> 	Slim/Utils/OS/Linux.pm => /usr/share/perl5/Slim/Utils/OS/Linux.pm
> 	Exporter.pm => /usr/share/perl/5.20/Exporter.pm
> 	Sub/Name.pm => /usr/share/squeezeboxserver/CPAN/Sub/Name.pm
> 	Slim/Utils/OSDetect.pm => /usr/share/perl5/Slim/Utils/OSDetect.pm
> 	strict.pm => /usr/share/perl/5.20/strict.pm
> 	Fcntl.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Fcntl.pm
> 	re.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/re.pm
> 	Time/HiRes.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Time/HiRes.pm
> 	warnings.pm => /usr/share/perl/5.20/warnings.pm
> 	POSIX.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/POSIX.pm
> 	if.pm => /usr/share/perl/5.20/if.pm
> 	Carp.pm => /usr/share/perl/5.20/Carp.pm
> 	Slim/Utils/OS.pm => /usr/share/perl5/Slim/Utils/OS.pm
> 	File/Spec.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/File/Spec.pm
> 	constant.pm => /usr/share/perl/5.20/constant.pm
> 	HTML/Parser.pm => /usr/share/squeezeboxserver/CPAN/HTML/Parser.pm
> 	overload.pm => /usr/share/perl/5.20/overload.pm
> 	EV.pm => /usr/share/squeezeboxserver/CPAN/EV.pm
> 	locale.pm => /usr/share/perl/5.20/locale.pm
> 	Config.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Config.pm
> 	HTML/Entities.pm => /usr/share/squeezeboxserver/CPAN/HTML/Entities.pm
> 	Config_git.pl => /usr/lib/arm-linux-gnueabihf/perl/5.20/Config_git.pl
> 	overloading.pm => /usr/share/perl/5.20/overloading.pm
> 	version/vpp.pm => /usr/share/squeezeboxserver/CPAN/version/vpp.pm
> 	Cwd.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/Cwd.pm
> 	File/Basename.pm => /usr/share/perl/5.20/File/Basename.pm
> 	Config_heavy.pl => /usr/lib/arm-linux-gnueabihf/perl/5.20/Config_heavy.pl
> 	lib.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/lib.pm
> 	warnings/register.pm => /usr/share/perl/5.20/warnings/register.pm
> 	feature.pm => /usr/share/perl/5.20/feature.pm
> 	Symbol.pm => /usr/share/perl/5.20/Symbol.pm
> 	List/Util.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/List/Util.pm
> 	YAML/XS/LibYAML.pm => /usr/share/squeezeboxserver/CPAN/YAML/XS/LibYAML.pm
> 	DynaLoader.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/DynaLoader.pm
> 	File/Spec/Unix.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/File/Spec/Unix.pm
> 	B/Deparse.pm => /usr/share/perl/5.20/B/Deparse.pm
> 	B.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/B.pm
> 	File/Path.pm => /usr/share/perl/5.20/File/Path.pm
> 	Slim/Utils/OS/Unix.pm => /usr/share/perl5/Slim/Utils/OS/Unix.pm
> 	Digest/base.pm => /usr/share/squeezeboxserver/CPAN/Digest/base.pm
> 	version/regex.pm => /usr/share/squeezeboxserver/CPAN/version/regex.pm
> 	version.pm => /usr/share/squeezeboxserver/CPAN/version.pm
> 	attributes.pm => /usr/lib/arm-linux-gnueabihf/perl/5.20/attributes.pm
> 	Exporter/Heavy.pm => /usr/share/perl/5.20/Exporter/Heavy.pm
> 	Digest/SHA1.pm => /usr/share/squeezeboxserver/CPAN/Digest/SHA1.pm
> 	common/sense.pm => /usr/share/squeezeboxserver/CPAN/common/sense.pm
> 	Slim/Utils/OS/Debian.pm => /usr/share/perl5/Slim/Utils/OS/Debian.pm
> 	Slim/bootstrap.pm => /usr/share/perl5/Slim/bootstrap.pm
> 	XML/Parser/Expat.pm => /usr/share/squeezeboxserver/CPAN/XML/Parser/Expat.pm
> 	JSON/XS.pm => /usr/share/squeezeboxserver/CPAN/arch/5.20/JSON/XS.pm
> 	XSLoader.pm => /usr/share/perl/5.20/XSLoader.pm
> 	base.pm => /usr/share/perl/5.20/base.pm
> 	Tie/Hash.pm => /usr/share/perl/5.20/Tie/Hash.pm
> 	Getopt/Long.pm => /usr/share/perl/5.20/Getopt/Long.pm
> 	YAML/XS.pm => /usr/share/squeezeboxserver/CPAN/YAML/XS.pm
> 	FindBin.pm => /usr/share/perl/5.20/FindBin.pm
> 	DBI.pm => /usr/share/squeezeboxserver/CPAN/arch/5.20/DBI.pm
> 
> Unrecognized character \xF3; marked by <-- HERE after u<-- HERE near column 2 at /usr/share/perl5/Slim/Schema/Debug.pm line 11.
> Compilation failed in require at /usr/share/perl5/Slim/Schema.pm line 52.
> BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Schema.pm line 52.
> Compilation failed in require at /usr/share/perl5/Slim/Player/Song.pm line 18.
> BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Player/Song.pm line 18.
> Compilation failed in require at /usr/share/perl5/Slim/Player/StreamingController.pm line 17.
> BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Player/StreamingController.pm line 17.
> Compilation failed in require at /usr/share/perl5/Slim/Player/Client.pm line 29.
> BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Player/Client.pm line 29.
> Compilation failed in require at /usr/share/perl5/Slim/Utils/Alarm.pm line 48.
> BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Utils/Alarm.pm line 48.
> Compilation failed in require at /usr/share/perl5/Slim/Buttons/Alarm.pm line 12.
> BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Buttons/Alarm.pm line 12.
> Compilation failed in require at /usr/share/perl5/Slim/Buttons/Common.pm line 41.
> BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Buttons/Common.pm line 41.
> Compilation failed in require at /usr/sbin/squeezeboxserver line 227.
> BEGIN failed--compilation aborted at /usr/sbin/squeezeboxserver line 227.
> pi@heimat:~ $ 
>

**Comment by ultraschuppi** [comment]
wow... wtf is that?
 

> root@heimat:~# sed -n '10,12p' /usr/share/perl5/Slim/Schema/Debug.pm
> 
> u?e stric?;

i have no clue about pörl, but this does not look correct?

**Comment by michaelherger** [comment]
Check your file system. Maybe it's corrupted a file or two? Re-install if the FS is fine.

**Comment by ultraschuppi** [comment]
btw:

> root@heimat:~# ls -la /usr/share/perl5/Slim/Schema/Debug.pm
> -rw-r--r-- 1 root root 970 Aug 18  2016 /usr/share/perl5/Slim/Schema/Debug.pm

**Comment by ultraschuppi** [comment]
thx @mherger - will fsck

**Comment by ultraschuppi** [comment]
helped, thanks a lot for helping with this non-LMS-related-bug @mherger :)
