### ISSUE TITLE
Trojan warning on Windows 10 1709

### ISSUE THREAD

**Issue by RobWJ** [LMS-Community/slimserver#171]
I downloaded http://downloads.slimdevices.com/nightly/7.9/sc/40212cd/LogitechMediaServer-7.9.1-1508251793.exe and installed it on my fresh installed Windows 10 1709

Through Install, Windows Defender send the C:\Program Files (x86)\Squeezebox\server\SqueezeSvr.exe into quarantine with the Error:
Trojan:Win32/Azden.A!cl

**Comment by mherger** [comment]
According to virustotal.com this file is clean. Either your personal copy is infected, or that was a false positive - which hopefully has been cleared by now.

https://www.virustotal.com/#/url/49e66f70ff495b399479ae5fa9be8cfbbb6e837c9a0ef9ddf2f995235617d838/detection
