### ISSUE TITLE
7.9.1 Problems on MacOS Sierra - Synchronize

### ISSUE THREAD

**Issue by jcferguson** [LMS-Community/slimserver#176]
I'm running LMS 7.91 - 1509357021 on MacOS 10.12.6, connecting to five RPi 3 devices all running PiCorePlayer v3.22. Three are connected via Ethernet and two via wireless. 

When streaming to any single device the server works fine and apparently indefinitely. When multiple players are synchronized (2 or more), music plays for anywhere from 30 seconds to a few minutes and stops. The song timer/counter seems to be dithering, advances a few seconds, backs up a few seconds, does this several times then starts the track over. The Pause function does not work when this is occurring, whether the music is playing or not. This continues until sync is broken or the song(s) are deleted from the song list box. mysqueezebox.com integration in server settings is enabled.

This is one of three issues on the same system.

**Comment by mherger** [comment]
AFAIK synchronization with Pi based players is hit'n'miss. It depends on the sound card etc. and has little to do with LMS itself. It's rather a squeezelite problem. Please check pCP related threads on the forums.
