### ISSUE TITLE
sox x86_64

### ISSUE THREAD

**Issue by satfreak** [LMS-Community/slimserver#182]
x86_64 sox wont start, complains about missing libgomp.so.1 on Qnap nas system.
Tested al other no problem, only sox gives error.

SlimServer/Bin/x86_64-linux/sox -v
SlimServer/Bin/x86_64-linux/sox: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory

 ldd SlimServer/Bin/x86_64-linux/sox
        linux-vdso.so.1 (0x00007ffdee3b9000)
        libgomp.so.1 => not found
        libm.so.6 => /lib/libm.so.6 (0x00007f93321cb000)
        libpthread.so.0 => /lib/libpthread.so.0 (0x00007f9331fae000)
        libc.so.6 => /lib/libc.so.6 (0x00007f9331c0b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f93324d0000)

**Comment by mherger** [comment]
How do you install on QNAP? For Debian based installations commit https://github.com/Logitech/slimserver-platforms/commit/bd10a4e747a07fe7ff5bc92d8c3b31d7211e1b73 should fix this in 7.9.

**Comment by satfreak** [comment]
On the QNap uses the nightly version.
Always uses the tarball version with CPAN.
( Logitech Media Server: Unix Tarball (i386, x86_64, i386 FreeBSD, ARM EABI, PowerPC)
It complains about missing libgomp, something which belongs to ffmpeg.

**Comment by fabferrr** [comment]
Good morning,

how do I get to the folder where Sox is in qnap?

thank you

**Comment by mherger** [comment]
ralphy from the forums recently re-built binaries with the latest code. This should bring improved performance in particular on slower systems. You might give those binaries a try, too:

https://sourceforge.net/projects/lmsclients/files/utility/sox/20180807-19b35e9/

As for the path: go to Settings/Information in LMS to find the helper path.

**Comment by fabferrr** [comment]
All right but from mac terminal you can’t find that folder, and with container terminal I don’t know the command.
what terminal I have to use?

thanks

Fabio Ferrantini  D.I.T.
fabioferrantini@me.com
http://www.imdb.com/name/nm3712081/
+39 3202826229
+44 (0) 7447522652

**Comment by fabferrr** [comment]
I've found the way in to SOX folder but now I can't find the correct SOX version for qnap: I've tried all the binaries you suggested but still the message "Squeezebox server can't find SOX.exe in the system"  
I've renamed many sox file, I downloaded sox.exe, I've tried with capital letters.
Any suggestion

**Comment by mherger** [comment]
If it's indeed asking for `sox.exe`, then you must be running LMS on Windows, not a QNAP NAS. `*.exe` files are Windows only.

**Comment by fabferrr** [comment]
I know that but i'm actually running LMS in a Qnap container, looks strange to me asking sox.exe.
What should be the correct one?

**Comment by mherger** [comment]
On systems other than Windows it would be just `sox`. Are you running some 3rd party plugin requiring it? That might be buggy, looking for the wrong file in the wrong place. Where exactly would you get that error message?

**Comment by fabferrr** [comment]
Im getting it from logitech media server, trying to read dsd. The third party plugin is c-3po
![screen shot 2018-08-27 at 14 11 07](https://user-images.githubusercontent.com/42694262/44659043-278d5e00-aa03-11e8-8186-0f5d23871106.png)

**Comment by mherger** [comment]
Ok, then you should get in touch with the plugin author. It his plugin which doesn't find the binary, not LMS.

**Comment by fabferrr** [comment]
all right, thnx
