### ISSUE TITLE
[LMS Alternative] Capturing ALSA PCM And Streaming Through SlimProto

### ISSUE THREAD

**Issue by gimesketvirtadieni** [LMS-Community/slimserver#184]
Hello LMS Community

Let me introduce my pet project, I have been working for while. [SlimStreamer](https://github.com/gimesketvirtadieni/slimstreamer) is an audio streamer that captures PCM data from ALSA in a transparent to applications way and sends it over to Squeezebox players through SlimProto protocol. Moreover, while capturing, original sampling rate is preserved and PCM stream does not get resampled to a predefined frequency. Other solutions (like AirPlay, SnapCast, ...) use predefined sample rate, so original PCM stream is resampled in case sample rate does not match.

In other words, you can use any Linux software that outputs audio to the default ALSA device (MPD, Mopidy, Spotify client, ...) and SlimStreamer will capture it and redirect to connected Squeezebox players (for example squeezelite) in a transparent way.

I am still working on supporting SlimProto (it is still missing). However most tricky part, PCM capture in a bit-perfect way, is working fine, also single-threaded asynchronous TCP server is done.

Few more details:
-> SlimStreamer is written in C++17 (one should read it is very fast and lightweight)
-> It uses two ALSA plugins: [SlimPlexor](https://github.com/gimesketvirtadieni/slimplexor) and Loopback
-> SlimStreamer's source code is in Public Domain (Unlicensed)

Any comments / feedback about whether you find it relevant / interesting / useful are much appreciated ;)

**Comment by mherger** [comment]
Thanks for posting to the forums, too. While this sounds interesting, it's not an issue, is it? The forum sounds like the right place to post to.
