### ISSUE TITLE
Image Viewer issue when image transition delay > screensaver onset delay

### ISSUE THREAD

**Issue by matseku** [LMS-Community/slimserver#190]
The bug affects the Image Viewer app and is described in more detail here:

http://bugs.slimdevices.com/show_bug.cgi?id=16360

Adding it here in the hope that it can be addressed in a future update.

**Comment by mherger** [comment]
This is not a server side issue, but client side (https://github.com/Logitech/squeezeplay)

**Comment by matseku** [comment]
Thanks, that's true of course. From somewhere I understood that the client firmware is bundled with the server software, and hence I thought this is the issue tracker to post this issue. I checked out the link to the other repository you provided, and there seems to be no recent maintenance activity there. Hmm..

**Comment by mherger** [comment]
That's correct. It's unlikely there will ever be a firmware update for the devices any more. That said, the original error report mentions running SqueezePlay on a desktop computer. And the same would probably apply to running SP or JiveLite on a Pi or similar. There's ralphy's repository which still is maintained: https://github.com/ralph-irving/squeezeplay

**Comment by matseku** [comment]
OK. I can confirm that the problem occurs also on SB Touch.
I was thinking, if the server software is still maintained, and if the client software comes bundled with it, those users who update their server software could potentially benefit from it being fixed in the bundled client firmware. Not very important, but could be nice...
