### ISSUE TITLE
difference when using perl ELF32 or ELF64

### ISSUE THREAD

**Issue by satfreak** [LMS-Community/slimserver#191]
When i uses LMS with a Perl ELF64, it uses around 100MB memory more them with ELF32.
The other thing is, when running on a perl ELF64, there are many more messages.
It test it by doning 1>/dev/null 2>testfile.log, after the startup line.

Are there more errors on ELF64, or its this a mistake ?

**Comment by mherger** [comment]
Higher memory usage is a known side effect of using 64 bits. But what OS are you talking about? What messages?

**Comment by satfreak** [comment]
Oke i using it on a qnap system.
And regarding the messages found the issue, all the error messages come from squeeze2cast and squeeze2upnp.
They keep giving error messages, so nothing to do LMS.
