### ISSUE TITLE
Automate OR skip setup step with preset values

### ISSUE THREAD

**Issue by RyanRamchandar** [LMS-Community/slimserver#193]
How can we automate or skip the first launch setup step so that the following are predefined:

- skipping mysqueezebox.com sign in
- set Local Music Folder
- set Playlist Folder
- do first file scan

**Comment by michaelherger** [comment]
See eg. http://wiki.slimdevices.com/index.php/Customizing_Logitech_Media_Server_using_Slim::Utils::OS::Custom 

Instead of basing your class on Slim::Utils::OS you’d probably use the Linux or even Debian class.
