### ISSUE TITLE
hovering with mouse over cover in chrome shows old image... safari seems to be ok - after FEB 14th updates

### ISSUE THREAD

**Issue by gahabana** [LMS-Community/slimserver#194]
![image](https://user-images.githubusercontent.com/881265/36252268-403cda7c-1244-11e8-895f-31972c64e66c.png)

**Comment by gahabana** [comment]
if i refresh chrome then it gets reset and its ok but as long as i hover 1st time - that is the image that shows on any other song afterwards.

**Comment by mherger** [comment]
Update of Chrome or LMS? What LMS build?

**Comment by mherger** [comment]
Never mind. I can reproduce the issue. Thanks!

**Comment by mherger** [comment]
Fixed in commit cec8060901a8247d75dcf45d3ab660f81c64a300

**Comment by gahabana** [comment]
@mherger - awesome speed and problem gone 👍 
thank you !
