### ISSUE TITLE
add Perl modules for arm running Ubuntu 17.10

### ISSUE THREAD

**Issue by rowmoney** [LMS-Community/slimserver#196]
I have a Rock64 running Ubuntu 17.10, and I can't get LMS to start correctly.  From reading posts, I think it's a Perl issue.  17.10 has Perl 5.26.  and I don't think 5.26 for arm has been added yet.

**Comment by rowmoney** [comment]
As a follow-up, the error I get after squezzeboxserver -v is:
The following modules failed to load: DBI EV XML: :Parser: :Expat HTML: :Parser JSON: :YAML: :XS Sub: :Name

.... and then all the stuff about buildme.sh, which I have tried, but doesn't help

**Comment by mherger** [comment]
The instructions given there are what I'd be doing if I wanted to add support for your platform. Therefore you should elaborate as to how the build of those modules fails. What you tried, error messages etc.

**Comment by rowmoney** [comment]
Thanks for responding, I really appreciate the help.  I got this rock64 a few months ago as a hobby project and I have learned alot so far, but I'm relatively new to linux so I'm not entirely sure of what I'm doing.
I installed a nightly build from sometime in January, and it installed successfully.  However, the webif does not initiate.  the logfile gives no specific information, just line after line of restarting messages. I copied the buildme.sh file from the location indicated to my machine.  When I attempt to run it, I get another error message.  I copied and pasted everything below.
```
Welcome to Ubuntu 17.10 (GNU/Linux 4.4.77-rockchip-ayufan-133 aarch64)
                _     __   _  _   
 _ __ ___   ___| | __/ /_ | || |  
| '__/ _ \ / __| |/ / '_ \| || |_ 
| | | (_) | (__|   <| (_) |__   _|
|_|  \___/ \___|_|\_\\___/   |_|  
                                  

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Sat Feb 17 14:17:04 UTC 2018

  System load:  0.24               Processes:           155
  Usage of /:   42.9% of 14.56GB   Users logged in:     0
  Memory usage: 27%                IP address for eth0: 10.0.0.155
  Swap usage:   0%

  => There is 1 zombie process.

  Graph this data and manage this system at:
    https://landscape.canonical.com/

 * Ubuntu 17.10 releases with Gnome, Kubernetes 1.8, and minimal
   base images
   - https://ubu.one/u1710
Last login: Sat Feb 17 14:04:28 2018 from 10.0.0.129
rock64@rock64:~$ sudo service logitechmediaserver start
[sudo] password for rock64: 
rock64@rock64:~$ squeezeboxserver -v
The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name


*******

NOTE:

If you're running some unsupported Linux/Unix platform, please use the buildme.sh 
script located here:

https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN

If 7.9 is outdated by the time you read this, Replace "7.9" with the major version
You should never need to do this if you're on Windows or Mac OSX. If the installers
don't work for you, ask for help and/or report a bug.

*******


Exiting..
rock64@rock64:~$ sudo service logitechmediaserver stop 
rock64@rock64:~$ ./buildme.sh
RUN_TESTS:1 CLEAN:1 USE_HINTS:1 target all
Looks like your compiler is gcc
gcc (Ubuntu/Linaro 7.2.0-8ubuntu3) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

********************************************** ERROR ****************************************
*
*    It looks like you're using GCC earlier than 4.2,
*    Cowardly choosing to abandon build.
*    This is because modern ICU requires -std=c99
*
********************************************************************************************
rock64@rock64:~$ perl -v

This is perl 5, version 26, subversion 0 (v5.26.0) built for arm-linux-gnueabihf-thread-multi-64int
(with 56 registered patches, see perl -V for more detail)

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

rock64@rock64:~$ 
```
Per some of the forums I read, I tried perlbrew and installed an older perl version that I thought should be supported, but again - not quite sure what I'm doing.  Here's what that looks like:

```
rock64@rock64:~$ perlbrew init

perlbrew root (~/perl5/perlbrew) is initialized.

Append the following piece of code to the end of your ~/.bash_profile and start a
new shell, perlbrew should be up and fully functional from there:

    source ~/perl5/perlbrew/etc/bashrc

Simply run `perlbrew` for usage details.

Happy brewing!

rock64@rock64:~$ perlbrew list
  perl-5.22.4
rock64@rock64:~$ perlbrew switch perl-5.22.4

A sub-shell is launched with perl-5.22.4 as the activated perl. Run 'exit' to finish it.

rock64@rock64:~$ sudo service logitechmediaserver start
[sudo] password for rock64: 
rock64@rock64:~$ squeezeboxserver -v
The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name


*******

NOTE:

If you're running some unsupported Linux/Unix platform, please use the buildme.sh 
script located here:

https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN

If 7.9 is outdated by the time you read this, Replace "7.9" with the major version
You should never need to do this if you're on Windows or Mac OSX. If the installers
don't work for you, ask for help and/or report a bug.

*******


Exiting..
rock64@rock64:~$ 
```

I'm at a loss as to what to try next.  Any suggestions?

**Comment by rowmoney** [comment]
Now that I wrote this, I just noticed that part about copying code to bash_profile for perlbrew to be fully functional.  I have not done that yet.  Do you think that might make a difference?

**Comment by michaelherger** [comment]
If you want to give perlbrew a try, then go with 5.24. That’s the only Perl version for which we have support for the aarch64 architecture.

I’d be surprised though, if compilation of the modules wasn’t possible. I‘ll try to get Ubuntu on my Rock64...

**Comment by cgoldberg** [comment]
> I just noticed that part about copying code to bash_profile 
> for perlbrew to be fully functional. I have not done that yet. 
> Do you think that might make a difference?

adding to your .bash_profile will execute that command when spawning a new shell.  so you will need to run it in every new shell you spawn. 

note: AFAIK, Ubuntu reads shell settings from `.bashrc` by default, not `bash_profile`.

**Comment by michaelherger** [comment]
Can you tell me which exact image you installed on your Rock64? I would have expected this to be an aarch64 architecture (armv8), but from perl's version string (arm-linux-gnueabihf-thread-multi-64int) it looks like armhf (armv7). Before I try to build I'd need to know what image I'd have to use.

**Comment by rowmoney** [comment]
Yeah, it is armhf: auyfan's artful minimal armhf build.  I did this for the purpose of more extensive software compatability.

**Comment by michaelherger** [comment]
Unfortunately I have to confirm that the build process currently is broken. Some changes to make the script compatible for FreeBSD and/or Solaris must have broken it. I'm trying to figure out how to get it done anyway.

**Comment by rowmoney** [comment]
Hey any help is better than the unlimited head-scratching I've been doing.  Thanks for everything.

**Comment by michaelherger** [comment]
Quick update: I was able to compile the modules for the aarch64 configuration on this platform. But armhf is still failing. From the errors I saw it looks as if during one of the compilations the architecture would still be interpreted as aarch64, even on the armhf installation. While it does successfully compile, the code would fail to run.

What is the assumption, that armhf would be better supported than aarch64, based on?

**Comment by rowmoney** [comment]
Well, less assumption and more research based.  My primary video server is Plex, which simply does not support aarch64.  I looked into switching to XMBC, but it wouldn't work the way I'd like.  I found a way to make Plex work on this machine using armhf.  Now I have invested time getting openhab and owncloud up and running as well.  While those might work on aarch, I'm in pretty deep now to consider switching.  When I started, I had the idea of maybe eventually also installing LMS, but it looked to me like it wasn't supported in any way shape or form, so I saved it till last.

I know the method I'm using to get Plex to work includes something that allows armhf to be installed even though the architecture is identified as aarch64.  It's above my pay grade, but maybe would be helpful?  It's here:  https://github.com/ayufan-rock64/plexmediaserver-installer/commits/master

**Comment by michaelherger** [comment]
FWIW: I do have something working now. Using an older revision from slimserver-vendor allowed me to successfully compile for armhf on the rock64. Now running some more tests to get to the latest of it again (as I've learned a few things on the way...). I'll hopefully have something for you test later today.

Are you installing the .deb file?

**Comment by rowmoney** [comment]
Awesome.  Yeah, I downloaded and installed the nightly .Deb file before.

**Comment by michaelherger** [comment]
Commit c9d53b80cfc9ad6a4596b3471d106b89194332bb is adding armhf binaries. aarch64 to follow.

**Comment by rowmoney** [comment]
Cool.  Should I clone and build a .deb to test, or sit tight for now?  (You said the build process was broken above)

**Comment by mherger** [comment]
The build system never has been more broken than today... fortunately I already was preparing a completely new setup in VMs. While I don't have the server host yet, I can run the whole system on my dev machine... Should be up soon!

**Comment by michaelherger** [comment]
Oh, my split personality... is reporting that commit 94b8f29 is adding support for Perl 5.26/aarch64.

**Comment by michaelherger** [comment]
Builds are up for testing. Please give them a try. Thanks!

**Comment by rowmoney** [comment]
installed successfully and I can control/play on my kitchen squeezebox.  Mission accomplished!  Thank you sincerely for your hard work.  Now for the configuration to begin

**Comment by mherger** [comment]
Cool. Thanks for the testing!
