### ISSUE TITLE
Update CLI documentation to tell us what `waitingToPlay:1` is about

### ISSUE THREAD

**Issue by decibyte** [LMS-Community/slimserver#199]
I've started to get an undocumented parameter back for the `<player_id> status` CLI query.

In some cases `waitingToPlay:1` is returned as the first parameter, as in this example:

`waitingToPlay:1 playlist%20index:0 id:97140 ...`

It happens when I do the query immediately after changing the track, so it's probably something that only shows up very shortly while rebuffering or something like that. But as the documentation doesn't say anything about it, I don't know how to handle it correctly.

**Comment by mherger** [comment]
I like the "really" parameter:

https://github.com/Logitech/slimserver/blob/7df0d4675461df3922ccbb063fa7b352e979c24b/Slim/Control/Queries.pm#L3575

**Comment by decibyte** [comment]
> I like the "really" parameter

Haha!

For now I've just added a filter to remove `waitingToPlay` from the response, as it doesn't really matter in my case whether the player is _really_ playing. But it would be nice to have it documented and know in which responses to expect it (if anywhere else than `status`).

**Comment by mherger** [comment]
Added in commit 263c002f5be8b8e33aa546c0e9cd79374f6780e2

**Comment by decibyte** [comment]
Thanks, @mherger!
