### ISSUE TITLE
"notindexed" option for SQLite FTS

### ISSUE THREAD

**Issue by dolodobendan** [LMS-Community/slimserver#200]
SQLite FTS searches ID column, too, (see [here](http://forums.slimdevices.com/showthread.php?108735-Full-text-search-missed-results&p=907980&viewfull=1#post907980)) generating false positives in the search.

I just wanted to make this a somewhat official "buglet" report.

**Comment by mherger** [comment]
Might be helpful: https://www.sqlite.org/fts3.html#the_notindexed_option

**Comment by mherger** [comment]
Some more context: titles like "1999" or "99 Luftballons" can't be found easily, as the numbers in those titles would match the ID column, leading to unexpected/invalid results.

**Comment by dolodobendan** [comment]
I should have included more context, sorry.

I don't know what other columns there are, but if there's a "time stamp" column or other random data columns, maybe they should be excluded, too?

**Comment by michaelherger** [comment]
Unfortunately this isn't an easy change: the "not indexed" option requires a more recent SQLite implementation than we are using. I'm looking into alternatives.

**Comment by michaelherger** [comment]
@dolodobendan what platform are you on?

**Comment by michaelherger** [comment]
This is now in the repository. Please not that depending on what platform you're running LMS on the feature might still not be available. Please let me know what DBD::SQLite and Perl versions you see in Settings/Information.

**Comment by dolodobendan** [comment]
I'm sorry, you got me by surprise! I didn't expect any changes here anytime soon.

Perl Version: 5.24.4 - x86_64-linux-thread-multi
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

**Comment by mherger** [comment]
No worries :-). Did you re-run a scan and test for the "99 Luftballons"? You seem to be running the latest code which should have the `notindexed` implemented.

**Comment by dolodobendan** [comment]
I just saw this here, so no. But I will start a scan right now and report back!

**Comment by dolodobendan** [comment]
It works now, thank you so much!

**Comment by michaelherger** [comment]
Excellent, thanks for the confirmation! Then at least the whole updating exercise has had one use :)
