### ISSUE TITLE
Search function returns incorrect count (tagged search)

### ISSUE THREAD

**Issue by s25a** [LMS-Community/slimserver#202]
Issues posted in forum: https://forums.slimdevices.com/showthread.php?108946-Search-function-returns-incorrect-count-in-LMS-7-9-and-7-9-1

The response (count) is not correct when using the (tagged search).

**Comment by mherger** [comment]
I never got an answer to my last question in that thread: Are you sure you're seeing this issue with all of these queries? I tried to reproduce and only was able to do so with the titles/songs/tracks query. I actually already fixed this three years ago - only missed the titles query at the time...

**Comment by michaelherger** [comment]
Did you try the latest nightly build? I fixed this about a week ago: https://github.com/Logitech/slimserver/commit/4e583ec8d166f6a53f701c0a4b113e27041f148a
