### ISSUE TITLE
MS Edge in Windows 1809 fails to load navigation area

### ISSUE THREAD

**Issue by mherger** [LMS-Community/slimserver#221]
This is only a partial fix as in Edge on 1809 if more than one player is connected and the Choose Player menu is used to select another player the leftcontent does not update the target player.

_Originally posted by @pseud0nym0 in https://github.com/Logitech/slimserver/commit/b758dc0c1b270e3052c435ebc345f285eeb717b1#commitcomment-30797992_

**Comment by mherger** [comment]
@pseud0nym0 - could you please provide more information? Eg. the error message from the browser's  dev tools or JS console? This seems to be working as expected on my installation.

**Comment by mherger** [comment]
Ok, was able to reproduce this. Thanks for the update.

**Comment by pseud0nym0** [comment]
Sorry, only just getting back to this. Glad you were able to reproduce.

**Comment by Daniel-Ebert** [comment]
Isn't Edge also going to use the chromium engine in the near future ? https://thenextweb.com/microsoft/2018/12/06/microsoft-edge-is-officially-switching-to-chromium-in-2019-heres-why-thats-a-good-thing/
Maybe this will make the fix obsolete....

**Comment by mherger** [comment]
I decided to not address this, as Edge based on Chromium is what will be working.
