### ISSUE TITLE
Can't find files with excessive periods in filename

### ISSUE THREAD

**Issue by b0rnwr0ng** [LMS-Community/slimserver#224]
7.9.2, win10.  Been noticing files are scanned and in the database but get an error when trying to playing them, like "1983... (a merman).flac"

**Comment by b0rnwr0ng** [comment]
It looks like it wants to play the filename  %20ELL%20PCM2CH%20-%2011%20-%201983...%20(A%2

Also, came across this later in the log for different filename.  My files are accessing via unc shares.

[18-11-21 10:58:29.7445] Slim::Control::Request::renderAsArray (2233) Error: request should set useIxHashes in Slim::Control::Request->new()

**Comment by mherger** [comment]
Would the server.log have any hint about the playback failure when you tried to play that file?

**Comment by b0rnwr0ng** [comment]
I don't think so.  It's been awhile, but I'm pretty sure it doesn't even appear in the library at all to actually be played.

**Comment by michaelherger** [comment]
If it didn't appear in the library, how did you play it?!? And you said:

> Been noticing files are scanned and in the database but get an error when trying to playing them, like "1983... (a merman).flac"

**Comment by b0rnwr0ng** [comment]
I had to rename the files with less periods and rescan them into the library.
