### ISSUE TITLE
Old playlist name returned after saving active playlist (queue)

### ISSUE THREAD

**Issue by CDrummond** [LMS-Community/slimserver#227]
As discussed [on the slimdevices forum](https://forums.slimdevices.com/showthread.php?109781-Playlist-name), the `status` command is always returning the name of the playlist that was loaded (or empty, if none loaded) even after the active playlist (i.e. the currently playing queue) is a saved under a different (or new) name.

**Comment by mherger** [comment]
@CDrummond could you please test with LMS8? If it's working as expected I'm going to backport to 7.9. Thanks!

**Comment by CDrummond** [comment]
Odd. Seems to work fine if i use default web UI. I load a palylist, save as new name, new name is shown. If I do this in Material new playlist is saved, but new name name is not shown - neither in default nor Material. I guess Material's command is wrong? I'm using:

```
["playlist", "save", name]
```

**Comment by CDrummond** [comment]
Ah! Code seems to intercept a `playlists` comands - which act on the list of saved playlists. Whereas Material uses `playlist save` to save the current queue as a playlist. The saving via this method still does not update the name in the status messages.

**Comment by michaelherger** [comment]
You’re right. I only covered the `playlist rename` case, but not `playlist save`. I’ll look into this later this weekend. Should be straightforward to fix, now that I know the underlying mechanism.

**Comment by CDrummond** [comment]
As an aside to this, how would I know that the currently loaded playlist has been modfied? (The default web UI indicates this state). Just if I'm going to show the name, then a modified indicator seems like a good idea.

**Comment by michaelherger** [comment]
There should be a `playlist_modified` flag in the response to the `status` query.

**Comment by michaelherger** [comment]
More complete fix now in 7.9 and 8.0.

**Comment by CDrummond** [comment]
This still does not work. To save the queue as a playlist I use (showing curl command so you can run on commandline):

```
curl 'http://localhost:9000/jsonrpc.js' --data-raw '{"id":0,"method":"slim.request","params":["01:02:03:04:05:06",["playlist","save","ABC"]]}'
```

If the queue is loaded with tracks, not from a playlist, and I save - then the new name is shown. But if I now save this as another name, or I load playlist X and save as Y - the new name is not shown (the old one remains). Not in Material or the default web UI.

**Comment by CDrummond** [comment]
I'm guessing as the default UI does a rename this works, but Material does a save-as. In most apps when you save-as the name of the current 'document' is updated (as the new;y named one is now the active one). This is what is not happening here.

**Comment by CDrummond** [comment]
...also, if I then delete the playlist that is currently loaded the name still remains. I guess this is OK, but perhaps the modified flag should be set?

**Comment by michaelherger** [comment]
> ...also, if I then delete the playlist that is currently loaded the name still remains. I guess this is OK, but perhaps the modified flag should be set?

Argh... LMS never has been strong in playlist management. It shows. How do you delete the playlist?

> I'm guessing as the default UI does a rename this works, but Material does a save-as. In most apps when you save-as the name of the current 'document' is updated (as the new;y named one is now the active one). This is what is not happening here.

Hehe... just double checked this with my wife who's often doing "save as" in office and other applications - which I absolutely hate as a way of copying a file. I do copy before editing :-). But I see your point.

I think I missed the fact that the `save` call actually requires a client object. Therefore I implemented some logic as to when to update the client's playlist reference and when not. But as the client is required, I can set the playlist unconditionally. Would the following work?

```patch
diff --git a/Slim/Control/Commands.pm b/Slim/Control/Commands.pm
index 82234120b..e3b5964e6 100644
--- a/Slim/Control/Commands.pm
+++ b/Slim/Control/Commands.pm
@@ -1196,9 +1196,7 @@ sub playlistSaveCommand {
 
 	$request->addResult('__playlist_id', $playlistObj->id);
 
-	if ($client && $playlistObj->title ne Slim::Utils::Strings::string('UNTITLED')
-		&& (!$client->currentPlaylist || $playlistObj->id == $client->currentPlaylist->id)
-	) {
+	if ($client && $playlistObj->title ne Slim::Utils::Strings::string('UNTITLED')) {
 		$client->currentPlaylist($playlistObj);
 		$client->currentPlaylistUpdateTime(Time::HiRes::time());
 		$client->currentPlaylistModified(0);
```

**Comment by michaelherger** [comment]
> ...also, if I then delete the playlist that is currently loaded the name still remains. I guess this is OK, but perhaps the modified flag should be set?

How do you delete it?

**Comment by CDrummond** [comment]
Seems to work great. Sometimes its a bit slow to update, but I think that's LMS's cometd notifications not always been sent quickly (batching?) - but I can work-around that.

Delete:
```
["playlists","delete","playlist_id:79675"]
```

**Comment by michaelherger** [comment]
> Seems to work great.

Cool, thanks.

> ```
> ["playlists","delete","playlist_id:79675"]
> ```

I got confused by `playlist delete` vs. `playlists delete`...

I tend to remove the playlist reference from clients when deleting it. IMHO no player should refer to a list which no longer exists. Agreed?

**Comment by CDrummond** [comment]
I'm fine with either way - i.e. indicate modified, or clear playlist name.

**Comment by michaelherger** [comment]
Wipe playlist reference from clients when playlist is deleted:

```patch
diff --git a/Slim/Control/Commands.pm b/Slim/Control/Commands.pm
index e3b5964e6..30242ac7a 100644
--- a/Slim/Control/Commands.pm
+++ b/Slim/Control/Commands.pm
@@ -2298,6 +2298,14 @@ sub playlistsDeleteCommand {
 		});
 	}
 
+	foreach my $client ( Slim::Player::Client::clients() ) {
+		if ($client->currentPlaylist && $client->currentPlaylist->id == $playlistObj->id) {
+			# must send defined, but falsy value
+			$client->currentPlaylist(0);
+			$client->currentPlaylistUpdateTime(Time::HiRes::time());
+		}
+	}
+
 	_wipePlaylist($playlistObj);
 
 	$request->setStatusDone();
```

In this case we don't have a client reference, but remove from all clients instead. Ok?

**Comment by CDrummond** [comment]
Makes total sense to me :)
