### ISSUE TITLE
single track repeating playlists should turn off crossfading

### ISSUE THREAD

**Issue by born-daniel** [LMS-Community/slimserver#237]
When using a single track (possibly shorter than a certain number of seconds, say 60) with auto-repeat on, cross-fading should be disabled. A particular use case for this is for an alarm application using a short sound clip.

Otherwise, allow changing player's cross-fading settings from the CLI.

**Comment by born-daniel** [comment]
Here is my solution in Squeezebox.pm:
```
921c921,923
< 			( Slim::Player::ReplayGain->trackAlbumMatch( $master, -1 ) 
---
> 			( Slim::Player::Playlist::count($master) < 2
>                           ||
>                           Slim::Player::ReplayGain->trackAlbumMatch( $master, -1 ) 
```

**Comment by mherger** [comment]
I'm not sure everybody would agree not to cross-fade single tracks... but we can give it a try. Thanks!

**Comment by vco1** [comment]
@born-daniel How would you create such a playlist (i.e. one with a single repeating track)? I have a playlist for my alarm, but for now I've just added the same track (an alarm sound) multiple times to the playlist. Would be easier if it was just one track with a repeat flag. Is this possible?

**Comment by cgoldberg** [comment]
Wouldn't the solution for disabling cross-fading be to turn the setting off?  Introducing a corner case where you enable the cross-fading setting but cross-fading isn't actually done seems confusing.

**Comment by michaelherger** [comment]
This case is only for the "smart crossfading" selection where the decision to fade or not is left to LMS. Same album tracks: don't fade. Mixed album tracks: do fade. etc.

**Comment by born-daniel** [comment]
I would also be okay with being able to change the smart crossfading options from the CLI for a specific player but this doesn't appear to be possible ATM. Yes, as Michael mentioned, this is for a special case of smart crossfading of a single track, set to auto-repeat.

**Comment by born-daniel** [comment]
> @born-daniel How would you create such a playlist (i.e. one with a single repeating track)? I have a playlist for my alarm, but for now I've just added the same track (an alarm sound) multiple times to the playlist. Would be easier if it was just one track with a repeat flag. Is this possible?

It's definitely possible to set the auto repeat for the playlist (of 1 track). I don't have the CLI documentation handy but I remember it was easy to do.

**Comment by michaelherger** [comment]
@vco1 do you have the "Don't Stop The Music" plugin enabled? That would start adding tracks if you only played a single track.

**Comment by vco1** [comment]
@michaelherger  I wasn't aware of this plugin. Thanks for the heads up! Not sure if it fully covers my need though. I'm basically looking for a (local) replacement for the alarmsounds on mysqueezebox.com.
Will continue the discussion on the forum though, as it has little to do with the issue.
