### ISSUE TITLE
SB Radio stop playing

### ISSUE THREAD

**Issue by typhon0815** [LMS-Community/slimserver#239]
Server: Ubuntu 18.04.2
Media Server: 7.9.2 - 1550612824 (same Issue with logitechmediaserver_7.9.2_1545144292)
Radio SW-Version: 7.7.3 r16676

Issue: I shut down my media server every night and it starts in the morning. With version 7.9.2_1545144292 i had the issue that if I listen to internet radio (no matter which channel) sometimes the logo on the screen has not appeared. If that happend the radio stops playing after a while. When the correct logo was shown the radio works well the whole day. After a reboot of the radio (press the power button long) it works as expected.

After the update to 1550612824 this behavior is every day. Before the update to 7.9.* it works like a charm. My last version whose works correct was: logitechmediaserver_7.7.7_1542289924_all.

**Comment by mherger** [comment]
Please join forums.slimdevices.com to discuss this issue. This description is too generic to be followed up with.
