### ISSUE TITLE
What happend to the Debian packages

### ISSUE THREAD

**Issue by alexte** [LMS-Community/slimserver#240]
http://wiki.slimdevices.com/index.php/Debian_Package#installing_7.9.2
Shows 
http://www.mysqueezebox.com/update/?version=7.9.2&revision=1&geturl=1&os=debamd64
for .deb souce but gives "0"

Where are the debian packages ?

**Comment by mherger** [comment]
Hi @alexte - thanks for the heads up. It seems there's some DNS configuration or other problem. I'll ping IT.

**Comment by worsco** [comment]
It appears all of the content is missing, too:

http://downloads.slimdevices.com/nightly/7.9/sc/

**Comment by CraniumDad** [comment]
Yikes.  All the download content is indeed missing.

**Comment by worsco** [comment]
It's like Corp-IT did a restore from a really old back-up from Jan 2018.... or the URL is pointing to the wrong server... or... some other nefarious conspiracy theory.

**Comment by mherger** [comment]
I think this should be fixed again. Thanks for the heads-up.

**Comment by alexte** [comment]
Thanx
