### ISSUE TITLE
Imageproxy returning a larger image than original

### ISSUE THREAD

**Issue by kayue** [LMS-Community/slimserver#247]
I'm using the Qobuz plugin, and I noticed the image returnning from image proxy is larger than the original one from Qobuz server.

Image proxy returning 1500px 

```
/imageproxy/https%3A%2F%2Fstatic.qobuz.com%2Fimages%2Fcovers%2F52%2F13%2F0094636981352_600.jpg/image.jpg
```

Original picture is 600px

```
https://static.qobuz.com/images/covers/52/13/0094636981352_600.jpg
```

**Comment by mherger** [comment]
These  two images are absolutely identical when downloaded through my LMS. Identical down to the last bit.

**Comment by kayue** [comment]
@mherger You are right. Looks like the problem only exists for images that are loaded through LMS. 
If I load an image that has never been loaded from LMS before, then the result are identical.

May I know are there any pre-cache mechanism that might cause this problem? My LMS is always busy downloading 1400x1400 images for me... 

![Logitech_Media_Server_and_Slack_-_Development_Team_and_Internal_Policy__2019__IT](https://user-images.githubusercontent.com/193112/55721316-a20c6a80-5a35-11e9-8475-fe14822b5d0d.png)

**Comment by michaelherger** [comment]
Where do these requests come from? If the image proxy is called with just `image.jpg`, then no resizing-parameters are given. In that case the original file would be downloaded - which can be large. The UI should take care of only requesting what it needs. This has nothing to do with the image proxy itself, as it's serving what it's told to serve. But the caller needs to correctly ask for a resized image if that's what it needs.

**Comment by kayue** [comment]
I'm using Qobuz plugin with Material theme. (Shopify doesn't have this problem because it is passing the size parameter, so I guess it is Qobuz plugin that need fixing?)

- https://github.com/pierrepoulpe/SqueezeboxQobuz
- https://github.com/CDrummond/lms-material

**Comment by mherger** [comment]
Then this is an issue with the Material skin not requesting an adequately resized image.
