### ISSUE TITLE
Mint 19.1: modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Sub::Name

### ISSUE THREAD

**Issue by fenchu** [LMS-Community/slimserver#260]
On a vanilla mint19.1, it tried installing slimserver via:
```
wget http://downloads.slimdevices.com/LogitechMediaServer_v7.7.6/logitechmediaserver_7.7.6_all.deb
sudo dpkg -i logitechmediaserver_7.7.6_all.deb
```
it installs something, but fails to start

I tried installing the modules manually with perl -MCPAN -e shell
same result (I think this stage may have messed up)

I tried downloading the slimserver-vendor and run the CPAN/buildme.sh
install all fine.

but still:
```
/usr/sbin/squeezeboxserver --help
The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Sub::Name
:
```
But I see this:
```
cpan[1]> install DBI
Reading '/root/.cpan/Metadata'
  Database was generated on Fri, 17 May 2019 06:41:02 GMT
DBI is up to date (1.642).
```
in slimserver-vendor I see:
```
/dist/dev/slimserver-vendor/CPAN# ls -l DBI-[0-9]*
-rw-r--r-- 1 root dist 576803 mai   17 09:28 DBI-1.616.tar.gz
-rw-r--r-- 1 root dist 586733 mai   17 09:28 DBI-1.628.tar.gz
```

So put it simply does it mean I've messed up by installing latests?
How can I fix this?

**Comment by michaelherger** [comment]
Try [7.9.2](http://downloads.slimdevices.com/nightly/?ver=7.9) instead. Its platform support is much more advanced.

**Comment by fenchu** [comment]
Thanks worked like a charm.
