### ISSUE TITLE
Radio tracks in Now Playing use Genre instead of Title

### ISSUE THREAD

**Issue by rh2600** [LMS-Community/slimserver#263]
I've just noticed that since updating to the latest nightly (Logitech Media Server Version: 7.9.2 - 1560488529 @ Fri Jun 14 07:24:19 CEST 2019) that when I play a radio station via TuneIn, that the now playing screen shows the Genre, not the actual title of the radio station.

See attached screenshot for Radio New Zealand that now shows as US News when playing

![Screen Shot 2019-06-15 at 11 14 54 AM](https://user-images.githubusercontent.com/85782/59543741-f0237a00-8f60-11e9-9a37-1814bfd060c8.png).

I can see on TuneIn where the genre is
https://tunein.com/radio/Radio-New-Zealand-National-567-s25645/

Not sure if this occurred the latest nightly, but it has been very recent as in the last few weeks/days.

**Comment by michaelherger** [comment]
Are you saying "US News" is the "genre" of "Radio NZ National"? There's not really a notion of Genres in radio stations. There's no such data related to a station when you're playing it. This title must be coming from somewhere else.

**Comment by rh2600** [comment]
I know, it seems really odd. But the only place I can find any reference to the 'US News' string is in this genres field. I can't find it present in the M3U or MP3 file. Perhaps it's a change that TuneIn has made? The genre is showing up instead of the title for all the radio stations I try, they also match with the genre being shown on the TuneIn listing page (the only place I can find it).

![Screen Shot 2019-06-17 at 1 03 40 PM](https://user-images.githubusercontent.com/85782/59572332-9d80c400-9100-11e9-98b3-954919378ddd.png)

**Comment by rh2600** [comment]
I've closed this issue, as it appears to have resolved itself. I suspect TuneIn has reverted a change.
![Screen Shot 2019-06-17 at 8 23 30 PM](https://user-images.githubusercontent.com/85782/59589532-4994d000-913e-11e9-9b85-b53149b06699.png)
