### ISSUE TITLE
MusicIP Plugin not working on Synology NAS

### ISSUE THREAD

**Issue by chrober** [LMS-Community/slimserver#266]
Hi,

I'd like to use the MusicIP Plugin, but it fails to initialize:
`Slim::Plugin::MusicMagic::Plugin::initPlugin (155) Can't connect to port 10002 - MusicIP disabled.`

The problem has already been reported to a different site a while ago:
https://forums.slimdevices.com/showthread.php?109276-musicip-stopped-working-on-Synology

It does not matter what port number I choose, the error remains the same. Is there something different in how the MusicIP plugin is attempting to bind the port (in comparison to other LMS components and/or plugins)?

I am currently using the 7.9.2-168.0024 image from here:
https://sourceforge.net/projects/lmsupdate/files/DSM6.x/
`Logitech Media Server Version: 7.9.2 - 1560488529 @ Fri Jun 14 07:24:19 CEST 2019`

Best regards,
Christoph

**Comment by mherger** [comment]
Is MusicIP running on your machine? Can you access it on port 10002? 

Please note that you must install and run MusicIP yourself. LMS does not take care of this.

**Comment by chrober** [comment]
OK, good point. Thanks for the clarification!

I assumed the MusicIP plugin would also add the server.
So the answer to your question is NO, MusicIP is not running on my machine.
I will go and find a way to get MusicIP running on Synology's DSM6.

**Comment by mherger** [comment]
And please share if you figure it out: I wanted to give it a spin recently, too. But eg. the Docker images I found wouldn't work...

**Comment by chrober** [comment]
I hardly find information on MusicIP (I have to admit, I had only very little time to search the Internet). Can you tell me where you found Docker images? Do you know if the source code of the MusicIP server is available somewhere?

**Comment by mherger** [comment]
I found it where you should start any search for Docker images: on Docker Hub :-).

https://hub.docker.com/search?q=musicip&type=image

MusicIP has been a dead product for many years. One of the best resources probably is spicefly:

https://www.spicefly.com/section.php?section=musicip

And no, the product never has been open-sourced.
