### ISSUE TITLE
Support for armel + perl > 5.20

### ISSUE THREAD

**Issue by lpaolini** [LMS-Community/slimserver#269]
server: Linux debian 4.19.0-5-marvell #1 Debian 4.19.37-5 (2019-06-19) armv5tel GNU/Linux
perl: **5.28.1**
media server: 7.9.2 nightly

The media server dies as the arm-linux-gnueabi-thread-multi-64int directory does not exist in /usr/share/squeezeboxserver/CPAN/arch/5.xx where x > 20, I guess.
Would it be possible to add support for perl > 5.20 for this architecture?

See [the result](https://github.com/Logitech/slimserver/files/3389578/report.txt) of /usr/sbin/squeezeboxserver --d_startup

**Comment by lpaolini** [comment]
Update: I've built [slimserver-vendor/CPAN](https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN) following the instructions and that worked.
It'd be nice not to have to, as it takes several hours on that platform.

**Comment by mherger** [comment]
Hi @lpaolini - good to hear it's working for you.

What kind of hardware is this? I'm always hesitant to add support for new platforms... I'm always trying to find a balance of usefulness and bloat. I haven't heard much of newer platforms using this type of CPU.

**Comment by lpaolini** [comment]
Hi, it's a QNAP TS-219P NAS running plain Debian 10. Definitely not new hardware, but it used to be supported... Actually, I was still running Debian Jessie on it (Perl v 5.20) just for this reason.
It'd be great if it could be re-added, but if you feel it's a too old platform I'll keep on building the modules myself.

**Comment by mherger** [comment]
But it wouldn't come with Debian installed by the vendor, would it? Did you install Debian yourself?

**Comment by lpaolini** [comment]
Yes, I installed it myself.

**Comment by mw9** [comment]
@mherger 
>  I'm always trying to find a balance of usefulness and bloat

Are you thinking of (a) bloat in the LMS server tree, or (b) bloat in the installers ?

If (a), would you be averse to to carrying a supplementary debian package of binaries for exotic platforms somewhere in the download section ?  I see that an i386 variant also falls into this category. It would not need rebuilding very often, although I haven't thought through the detail.

If (b), I could see that an 'armel' (debian name for these older cpus) platform variant might achieve that. Although at the expense of generating yet another installer package.

I'm a SheevaPlug user, running with self built modules, which has worked very well. But not all users would be able to that. (How many are there ?)

**Comment by mw9** [comment]
I should add that I was thinking in terms of the Perl module binaries. The LMS custom binaries in `bin/arm-linux ` (sox et al.) continue to support this older arm cpu.

**Comment by michaelherger** [comment]
> (How many are there ?)

That's exactly my point. I bet most users still using armel to run an updated OS are tinkerers who should be able to compile stuff.

WRT. bloat: it's both. The repository already weighs around 1.5GB, a lot of which is for those Perl binaries. Adding a new build wouldn't be impossible to do, but is it worth it for a hand full of users?

**Comment by mw9** [comment]
> is it worth it for a hand full of users?

In light of what you say, very probably not.

**Comment by stefansielaff** [comment]
Building lms is often, if I may say so, a pain (except on arch for which a good aur package exists, lol).
But for many older NAS like the Zyxel NSA325 running e.g. Debian with lms is a pretty fun thing.
So imho supporting the older architectures should not be underrated, soon those architectures (okay, more armhf for sure) might be the last who use this fine piece of software.

**Comment by samwatling** [comment]
I also run a SheevaPlug - would be great to have Perl modules that would work on Debian Buster (perl 5.28.1) - again, per previous comments, this is not a fast device - compiling CPAN modules on it takes ages!

**Comment by mw9** [comment]
For anyone interested in Debian Buster (perl 5.28) on armel:

I've built perl 5.28 armel binaries for use on my Sheeva plug. They appear to be working just fine.

So, dear reader, if you can make yourself comfortable with using binaries built by a complete stranger, please feel free to use them.

I've pushed a commit containing the binaries to a forked LMS, https://github.com/mw9/slimserver, under a branch named: _feature/armel_5.28_binaries_.

The specific commit, from which the binaries can be gleaned, may be found here:
[Add Perl 5.28 binaries for Debian armel (arm-linux-gnueabi-thread-multi-64int)](https://github.com/mw9/slimserver/commit/46c22a3c7e69187a2ead9392c53f1c90790a03fa)

**Comment by mx1up** [comment]
i'm also on debian on QNAP TS-112 device (armel). anyone having binaries for bullseye or bookworm?
