### ISSUE TITLE
iTunes user agent breaks some streams

### ISSUE THREAD

**Issue by ronan-ln** [LMS-Community/slimserver#271]
Hi,

I am trying to play this feed from Mixcloud: https://stream1.mixcloud.com/secure/c/m4a/64/8/6/9/0/f57f-4056-4ff0-a2c3-75bf6cd14f53.m4a?sig=-8LmFylwgFQrLNnFprXuGQ

It works fine from my browser, but returns 403 Forbidden from SlimServer.
By reproducing the requests with cURL, I have managed to restrict the issue to the User-Agent string that Slimserver uses:
This does not work: 
```curl https://stream1.mixcloud.com/secure/c/m4a/64/8/6/9/0/f57f-4056-4ff0-a2c3-75bf6cd14f53.m4a?sig=-8LmFylwgFQrLNnFprXuGQ -H "User-Agent: iTunes/4.7.1 (Linux; N; Debian; armv7l-linux; EN; utf8)"```
However removing iTunes makes it work:
```curl https://stream1.mixcloud.com/secure/c/m4a/64/8/6/9/0/f57f-4056-4ff0-a2c3-75bf6cd14f53.m4a?sig=-8LmFylwgFQrLNnFprXuGQ -H "User-Agent: 4.7.1 (Linux; N; Debian; armv7l-linux; EN; utf8)"```

Ideally, the user agent string should be configurable in preferences. Is there a way to do that?

**Comment by StigNygaard** [comment]
Interesting discovery. I have always wondered why my ASUS router's net-traffic statistics shows the major part of my internet traffic is iTunes traffic. I don't have iTunes software installed. I don't even have an iTunes account! I hear a lot of netradio, and so far my guess has been that ASUS regards traffic to TuneIn/RadioTime servers as iTunes-traffic. But if LMS reports itself as iTunes, that is probably a more likely explanation.

Yes, why not be honest? And make it an option to override the useragent if it breaks something?...

**Comment by michaelherger** [comment]
I take it from the comment in the code that some radio stations required iTunes in the user agent string to provide the correct - back in the days 14 years ago...

Are you using a plugin to stream from Mixcloud? Maybe the plugin could override the behaviour for its own purposes (but leave it alone for LMS in general)?

**Comment by ronan-ln** [comment]
Unfortunately, the Mixcloud plugin is broken and I have to generate a stream URL manually which I then input into LMS. Updating the user agent in the plugin would therefore not be a solution.

**Comment by michaelherger** [comment]
Is the plugin orphaned? Maybe the bug should be fixed instead?...

**Comment by mherger** [comment]
Should be fixed in the plugin rather than in LMS.
