### ISSUE TITLE
Yamaha net reciever does not find LMS

### ISSUE THREAD

**Issue by Knudch** [LMS-Community/slimserver#272]
I have a Yamaha R-N301 net receiver

It does not find LMS except if I have a Windows machine running on my LAN
(Windows machine find it without problem)

LMS is running on Linux Fedora F30 version logitechmediaserver-7.9.2-0.1.1564003588

Any ideas ?

Knud

**Comment by datenstation** [comment]
Got the same problem with my Onkyo TX-8270.

My LMS runs on a Netgear ReadyNAS Duo V1 (sparc). Unfortunately, my TX-8270 can't see the DLNA media server named "Logitech Media Server" and play music from it. It says "no server".

I also tried running the media server coming from Netgear (MiniDLNA) on my NAS and there were no problems with it. It didn't disappear from the AV receiver's server list.

(Logitech Media Server Version: 7.9.2 - 1549285218)

**Comment by Knudch** [comment]
It seems strange why a windows machine (win7 or win10 tested) on my LAN makes the LMS found by the Yamaha net receiver

**Comment by michaelherger** [comment]
I guess you're using the UPnP/DLNA functionality? You might want too look into philippe_44's set of plugins which does integrate UPnP/DLNA renderers as Squeezeboxen into LMS.

See https://forums.slimdevices.com/showthread.php?103728.

**Comment by michaelherger** [comment]
Oh... but I doubt's it's available for the Duo v1... that CPU just isn't powerful enough.

**Comment by Knudch** [comment]
The UPnPBridge module did it ! :)
Now the Yamaha Net receiver find the LMS without help from a WIN machine on my LAN
Problem about missing favorites  opml url links persists (se other posting)
Thanks
Knud

**Comment by Knudch** [comment]
Sorry ....misunderstood Duo1 as the the handset from Logitech
>>>>>>>>>>>>>>>>>>
About Duo v1
I dont understand....??
LMS is running on Linux server with plenty of power/ram

Knud

**Comment by Knudch** [comment]
It seems that another dlna plugin need to be active also
UPnP/Dlna module by Andy Grundman

**Comment by Knudch** [comment]
Sorry seems I was to quick in my conclussions...
It does not help with the plugin from phillip
Again these random times where the netreceiver find the LMS
Only one thing is working....start a WIN machine on the LAN

**Comment by Knudch** [comment]
Some one would say it is bug in Yamaha R-N301
But ... !
Do I another dlna server on my linux desktop machine....Gerbera dlna server
It is found at once by R-N301 stable and again..again

**Comment by datenstation** [comment]
After restarting the Onkyo TX 8270 AV receiver the media server shows up for a few minutes in the menu. During this time it is possible to start streaming but after a short while it seems that the connection is lost, because the current song is repeated continuously. Then the TX-8270 keeps saying "no server".

**Comment by Knudch** [comment]
The UPnP-brigde can and shall not solve this problem about Yamaha R-N301 not finding the LMS
See other posting #273

**Comment by mherger** [comment]
@Knudch I'm a little confused, as you just stated in that other report that it did work for you?

**Comment by Knudch** [comment]
I know it is a little confusing....
I will try to clear it a little up
The basic problem that the R-N301 receiver can not find (or only under certain conditions) the LMS as DLNA media server is NOT solved.
The UPnP-bridge is another solution to get the same functionality and work around the problem which this threads starts about.

The UPNp-bridge FIND the R-N301 and makes it a player just as other squeeze players.
You can then operate/control the R-N301 from the Squeezebox controllers you are using and all the settings favorites and what ever is accessible via you squeeze controllers.

I am primarily using a android app for my mobilephone as controller called Squeezer, I also have 2 Duet handset ctrl's but are barely using them....take to long time to start up and your mobile phone is proberly always on.

I hope that clarified things

**Comment by Knudch** [comment]
Previous I used a yamaha app NP controller for android to controll the R-N301
I had never could get the R-N301 to find reliable the LMS server when chosing the media server function in the R-N301.
Net radio was supported by Vtuner and a contract between Yamaha and Vtuner, in the last year there had been troubles between Vtuner and Yamaha (they proberly will not pay for the service).
Then recently it is turn completely off and Yamaha doesnt care about the users...to bad not working anymore !.
As the receiver does not support direct entering Netradio URL's is was complete useles for me....no access to LMS, no acces to netradio !
The UPnp-bridge solves both problems ...perfect !

**Comment by mherger** [comment]
Thanks for the feedback!
