### ISSUE TITLE
Let LMS share out favorit netradio URL's

### ISSUE THREAD

**Issue by Knudch** [LMS-Community/slimserver#273]
Is it possible to get LMS to share out the netradio URL's ?
Fx... those you have in favorites 

Special interest for a Yamaha R-N301 as Yamaha has refused to pay Vtuner to service there netreceivers

Knud

**Comment by michaelherger** [comment]
I'm not sure I understand. Your LMS favorites are saved in `favorites.opml`. If your other software can read opml files, then you should be fine. Otherwise there's certainly some tool to convert it to whatever you need.

**Comment by Knudch** [comment]
I have tried 2 different sw/HW to acces LMS
1. Explorer (network view) in WIN7, WIN mediaplayer
2. Yamaha R-N301 (when running a WIN machine in samme network...read other posting)

In case1 there are 4 folders visible:
Music
Videos
Pictures 
Recorded TV

In case 2
Music
Videos
Pictures

Favorites as I see them in DUO2 handset or Squeezer android APP are not visible

Knud

**Comment by Knudch** [comment]
Sorry it took a while before I understood the concept of the UPnP-bridge

It works.....I can now use the R-N301 as player sourced by LMS and controlled by the squeeze app
perfect !
