### ISSUE TITLE
MySqueezeBox.com Password issue

### ISSUE THREAD

**Issue by LeighCreekGuzzler** [LMS-Community/slimserver#278]
If you log on to MySqueezeBox.com directly it is possible to set a working password that contains the £ symbol (GBP symbol). However this does not work when you enter the password in LMS, either in the web browser interface or the Control Panel. The issue was discovered using 7.9.1 on a windows home server 2011 and confirmed on the earlier version of WHS.

**Comment by mherger** [comment]
Could you please confirm whether the pound sign was still causing problems? Thanks!

New builds should be out in about an hour.

**Comment by LeighCreekGuzzler** [comment]
Michael

 

I have just tried to change my password to include a £ sign. Mysqueezebox.com accepted this happily, but as before LMS will not. I am using Logitech Media Server Version: 7.9.2 - 1567524015 @ Tue Sep 3 17:38:12 WEDT 2019. Is that the version I should be on? It is the one that my system prompted me to install last night (I have been away for a week).

 

Cheers

 

 

Paul

**Comment by mherger** [comment]
Please update your LMS to yesterday's build. It's a LMS change, not mysb.com.

**Comment by LeighCreekGuzzler** [comment]
Michael

 

I have just installed last night’s build Logitech Media Server Version: 7.9.2 - 1567938514 @ Sun Sep 8 12:39:30 WEDT 2019 on my main server (which runs WHS 2011) and the problem is still there. I am currently installing the same version on my old server (which runs WHS) and I will let you know if that works.

 

Cheers

 

 

Paul

**Comment by LeighCreekGuzzler** [comment]
Michael

 

Sorry it doesn’t work on the other system either.

 

Cheers

 

 

Paul

PS I am happy to temporarily change my password to one of your choosing so that you can test it on your system.

 

From: leighcreekguzzler@gmail.com <leighcreekguzzler@gmail.com> 
Sent: 09 September 2019 11:04
To: 'Logitech/slimserver' <reply@reply.github.com>; 'Logitech/slimserver' <slimserver@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [Logitech/slimserver] MySqueezeBox.com Password issue (#278)

 

Michael

 

I have just installed last night’s build Logitech Media Server Version: 7.9.2 - 1567938514 @ Sun Sep 8 12:39:30 WEDT 2019 on my main server (which runs WHS 2011) and the problem is still there. I am currently installing the same version on my old server (which runs WHS) and I will let you know if that works.

 

Cheers

 

 

Paul

**Comment by LeighCreekGuzzler** [comment]
Quick update, it will not now let me enter any password in either system

 

From: leighcreekguzzler@gmail.com <leighcreekguzzler@gmail.com> 
Sent: 09 September 2019 11:12
To: 'Logitech/slimserver' <reply@reply.github.com>; 'Logitech/slimserver' <slimserver@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [Logitech/slimserver] MySqueezeBox.com Password issue (#278)

 

Michael

 

Sorry it doesn’t work on the other system either.

 

Cheers

 

 

Paul

PS I am happy to temporarily change my password to one of your choosing so that you can test it on your system.

 

From: leighcreekguzzler@gmail.com <mailto:leighcreekguzzler@gmail.com>  <leighcreekguzzler@gmail.com <mailto:leighcreekguzzler@gmail.com> > 
Sent: 09 September 2019 11:04
To: 'Logitech/slimserver' <reply@reply.github.com <mailto:reply@reply.github.com> >; 'Logitech/slimserver' <slimserver@noreply.github.com <mailto:slimserver@noreply.github.com> >
Cc: 'Author' <author@noreply.github.com <mailto:author@noreply.github.com> >
Subject: RE: [Logitech/slimserver] MySqueezeBox.com Password issue (#278)

 

Michael

 

I have just installed last night’s build Logitech Media Server Version: 7.9.2 - 1567938514 @ Sun Sep 8 12:39:30 WEDT 2019 on my main server (which runs WHS 2011) and the problem is still there. I am currently installing the same version on my old server (which runs WHS) and I will let you know if that works.

 

Cheers

 

 

Paul

**Comment by michaelherger** [comment]
Are both of your systems Windows? What browser are you using?

**Comment by LeighCreekGuzzler** [comment]
Yes both are Windows based, one Windows Home Server 2012 and the other
Windows Home Server. I have been using Chrome as my browser, but I have
also been trying to update the password using the LMS control panel, so I
don't think that it is a browser issue.

Cheers


Paul

**Comment by mherger** [comment]
Installed the latest code on Windows 10. Used `£@#yo!` as the password, and it worked as expected. I can't reproduce this issue any more.

**Comment by LeighCreekGuzzler** [comment]
Michael

In an hour or so I will retest.

Cheers


Paul

**Comment by LeighCreekGuzzler** [comment]
Michael

 

I confirm that that password works on both my systems. I have also reset the password to one that didn’t work yesterday. This worked, however it took two attempts on the old system, not sure what caused this. I wonder whether this was the problem yesterday.

 

Anyway thanks for sorting this out.

 

Cheers

 

 

Paul
