### ISSUE TITLE
Issue Lms stops randomly

### ISSUE THREAD

**Issue by an0Nym0us63** [LMS-Community/slimserver#279]
Hello @mherger i'm a big user of LMS since almost 8 years. I develop some plugins for home automation and so on.

I never had issues or onlys some minor issues. But since i upgraded to 9.2 i encouter some annoying issue. Totally randomly (5hours to 48hours) the server stops responding. No more cli interaction no more webUI. Only solution is to service restart.

I tried to analyse by myself for almost 2 months but did not manage to find where it struggles. Server.log doesnt show anything interesting. If i rollback to 9.1 no more issues on the same machine. If you have any clue or any idea to see where to dig i would really appreciate. 

And by the way Congrats for the best implementation in LMS so far ....... SPOTTY.

Regards

**Comment by bpa-code** [comment]
This sort of non-specific problem is best dealt with the forums where more than just Michael can help find the problem as locating the problem is time consuming.
Once identified - Michael may be able to fix.
