### ISSUE TITLE
Problem with Search and FTS enabled

### ISSUE THREAD

**Issue by dolodobendan** [LMS-Community/slimserver#284]
"There's a problem if the Fulltext Search plugin has been
enabled. In this case the search would find stuff which the simplified
link would not."

[https://forums.slimdevices.com/showthread.php?110264-Search-not-working/page5](url)

**Comment by michaelherger** [comment]
When searching using the looking glass in the web UI, the resulting page's "Play All" etc. links would use the simplified SQL statement which does not use the FTS. Therefore the results can be dramatically different from the actual search result.

**Comment by ruanom** [comment]
I confirm the behaviour as follows:

1.- If the FTS plugin is enabled, the play All Songs link will work correctly with the search results produced by FTS, but it won't work with the results of 'simple search'.

2- If the FTS plugin is not enabled, the play All Songs link will work correctly with the search results produced by 'simple search'.
