### ISSUE TITLE
i386 binaries for 5.28 and 5.30

### ISSUE THREAD

**Issue by rellla** [LMS-Community/slimserver#285]
Hi,
i ran into a problem with squeezeboxserver after upgrading to debian buster which uses perl 5.28.
It ends up in endless restarting and after some research i think it is due to the missing libraries for my platform which is i686...
Are there any plans to integrate 5.28/i386 support? If not, I would try to do that manually, but probably need some help how to do that :)
Thanks
rellla

**Comment by michaelherger** [comment]
The plan was to not include them... it's something hardly anyone is still using. And Linux users I'd expect to be able to build those files themselves ;-). Did you try building from https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN? Get a copy and run `buildme.sh`. This should automatically build all binaries.

**Comment by rellla** [comment]
Yeah, i already succeeded in building them by myself. Iirc i found some double-declaration bug yesterday in some module. Let me see if i can remember. Was late :)
I think this can be closed then.

**Comment by michaelherger** [comment]
```
--- lib/AnyEvent/Socket.pm	2019-10-15 21:25:03.000000000 +0200
+++ CPAN/AnyEvent/Socket.pm	2019-10-19 10:07:26.000000000 +0200
@@ -459,11 +459,10 @@
 
 sub inet_aton {
    my ($name, $cb) = @_;
-   my $ipn;
 
-   if ($ipn = &parse_ipv4) {
+   if (my $ipn = &parse_ipv4) {
       $cb->($ipn);
-   } elsif ($ipn = &parse_ipv6) {
+   } elsif (my $ipn = &parse_ipv6) {
       $cb->($ipn);
    } elsif ($name eq "localhost") { # rfc2606 et al.
       $cb->(v127.0.0.1, v0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.1);
```

I'll probably apply that one no matter what...

**Comment by michaelherger** [comment]
FWIW: I applied that patch to 7.9. New build should be out shortly.

**Comment by rellla** [comment]
Iirc it was sth like that, but not that one. I only can remember line 39 iirc :p

**Comment by rellla** [comment]
It was this line, where I encountered an error:
https://github.com/Logitech/slimserver/blob/public/7.9/CPAN/AnyEvent/Handle.pm#L1773
The second "my" has to be dropped.
Regards rellla

**Comment by mherger** [comment]
Thanks a lot! That code is still broken even in the latest version of `AnyEvent`...

**Comment by LeSpocky** [comment]
> The plan was to not include them... it's something hardly anyone is still using. And Linux users I'd expect to be able to build those files themselves ;-). Did you try building from https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN? Get a copy and run `buildme.sh`. This should automatically build all binaries.

This is the blocker for upgrading my Debian 9 (stretch) i686 virtual machine running slimserver. Too bad. I have to build this by myself now or migrate the whole VM with all other stuff to x86_64. :disappointed:

**Comment by mherger** [comment]
Building should be easy enough. Give it a try.
