### ISSUE TITLE
Regression from 7.9.1 to 7.9.2 - wav support broken

### ISSUE THREAD

**Issue by fredilarsen** [LMS-Community/slimserver#288]
I just upgraded to version 7.9.2 (downloaded from here: http://downloads.slimdevices.com/nightly/?ver=7.9) and now my collection of wav+cue (rips of my CD collection) does not play.

The albums are found and shown as normal, but when starting play it quickly skips through all tracks and stops.

Reverting back to 7.9.1 and all plays fine.

EDIT: I see that this is perhaps related to https://github.com/Logitech/slimserver/issues/277
Server was set to Norwegian region with "," as decimal symbol. I did change this now but am now on 7.9.1 so I cannot re-test immediately.

**Comment by mherger** [comment]
Sounds very much related. What platform would you run your LMS on?

**Comment by mherger** [comment]
Could you please check your server.log whether there are traces about the issue? What if you turned off WAV -> FLAC transcoding (Settings/Advanced/File Types)?

**Comment by fredilarsen** [comment]
Thanks for the feedback. I am running it on Windows 8.1 (god forbid, but it is actually very stable with updates deactivated).
I have no transcoding activated.

I upgraded to 7.9.2 again, and changed regional settings to use "." as decimal symbol instead of ",".
With this change it plays wav again. That confirms the reason was #277.

**Comment by mherger** [comment]
Thanks for the confirmation!
