### ISSUE TITLE
libmediascan / Media::Scan do not belong in CPAN

### ISSUE THREAD

**Issue by pgalbavy** [LMS-Community/slimserver#291]
While trying to get the basics of a port sorted out, I noiticed that Media::Scan and the depended libmediascan reside in the CPAN/ dir - but they are not from CPAN but rather from https://github.com/andygrundman/libmediascan

To avoid confusion I suggest moving them out of CPAN to a directory more appropriate.

**Comment by mherger** [comment]
Strictly speaking nothing's directly from CPAN, but from https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN instead. But still they're modules available from CPAN, and not specific to that project. I don't see why we should change this.

**Comment by pgalbavy** [comment]
Media::Scan is not in / from the public CPAN archive. They are bindings in andyg's project above.

**Comment by mherger** [comment]
If that's really important to you, then you should probably ask @andygrundman to publish it.
