### ISSUE TITLE
Web interface in Chrome with "Force Dark Mode for Web Contents" enabled

### ISSUE THREAD

**Issue by kimheino** [LMS-Community/slimserver#292]
I've enabled "Force Dark Mode for Web Contents" in latest Chrome browser. So far all other web sites have been looking much better than without it.

Slimserver's (7.9-public branch) web interface is an exception. It looks horrible. Quickly testing, "div#background" and "#squeezeboxLogo" and such items in css are big reason for this. It's better to try and see it yourself.

(I know, patches are welcome...)

**Comment by michaelherger** [comment]
Please provide more details, examples, screenshots etc. I think it's looking quite ok, actually (in Default mode!).

**Comment by michaelherger** [comment]
oh, ok, settings look... challenging

**Comment by mherger** [comment]
I think that with the availability of the Material skin, there's a great alternative available.
