### ISSUE TITLE
I have an amazing difficulty... server freeze every Sunday...

### ISSUE THREAD

**Issue by Adherack** [LMS-Community/slimserver#293]
Hello,
I have an amazing difficulty... every Sunday around 20:30 (Paris time), my squeezebox server (v7.9.2... 1533... last version) stops and it doesn't restart before the end of the evening... finally the previous weeks... today I don't know...
The rest of the week, I don't have a problem... 
Is it the quality of the internet connection? (down 12Mb / up 1Mb)
Is it because I listen mostly on Spotify?
Thank you in advance for your help!
Have a good day.

nb : I use the standard setting without modification on a Windows 10 PC

**Comment by mherger** [comment]
I think you'd better join the community on forums.slimdevices.com to get this resolved. There are more eyes in the community than are here.

Please check your server.log file for any hint about a failure around that time. See Settings/Information in the LMS web UI.

**Comment by Adherack** [comment]
Many thanks  Michael !
