### ISSUE TITLE
Queries requesting ratings return incomplete data sets (status, songinfo)

### ISSUE THREAD

**Issue by grasshide** [LMS-Community/slimserver#294]
The songinfo command returns incorrect results if the parameter "R" for rating is used. It filters the result in a strange way (what should not happen) and returns the unfiltered number of songs.
This leads to errors with the LMS-Material skin. There are already two reports of this error.
One by myself: https://github.com/CDrummond/lms-material/issues/192
And another one: https://github.com/CDrummond/lms-material/issues/128
I can not see why song 4 is returned by the songinfo command but song 3 is not for the following songs of my database:
Query: 
`select *
     from tracks t, albums a, track_statistics ts 
     where t.album = a.id 
     and t.url = ts.url 
     and a.title like "Overloaded%"`

Result line for song 3:
`id;url;title;titlesort;titlesearch;customsearch;album;tracknum;content_type;timestamp;filesize;audio_size;audio_offset;year;secs;cover;vbr_scale;bitrate;samplerate;samplesize;channels;block_alignment;endian;bpm;tagversion;drm;disc;audio;remote;lossless;lyrics;musicbrainz_id;musicmagic_mixable;replay_gain;replay_peak;extid;primary_artist;urlmd5;coverid;cover_cached;virtual;added_time;updated_time;dlna_profile;hash;id;title;titlesort;titlesearch;customsearch;compilation;year;artwork;disc;discc;replay_gain;replay_peak;musicbrainz_id;musicmagic_mixable;contributor;url;musicbrainz_id;playCount;added;lastPlayed;rating;urlmd5
264317;file:///xxx/Sugababes%20-%202006%20-%20Overloaded%20The%20Singles%20Collection/03.%20Red%20Dress.mp3;Red Dress;RED DRESS;RED DRESS;;17493;3;mp3;1401353441;6268735;6264511;4096;2006;217.96;/xxx/Sugababes - 2006 - Overloaded The Singles Collection/cover.jpg;1;229000.0;44100;;2;1;;;ID3v2.3.0, ID3v1.1;0;;1;0;0;;9217f2fc-c0a6-4f56-90a1-e607a2c99369;;;;;50609;c0de75bb0cd22030f76fb6df9fa71c7e;ba34f69a;1;;1563956587;1563956587;MP3;;17493;Overloaded: The Singles Collection;OVERLOADED THE SINGLES COLLECTION;OVERLOADED THE SINGLES COLLECTION;;0;2006;ba34f69a;;;;;5626aa80-0570-4d59-bff1-3ebafa0d7aa1;;50609;file:///xxx/Sugababes%20-%202006%20-%20Overloaded%20The%20Singles%20Collection/03.%20Red%20Dress.mp3;9217f2fc-c0a6-4f56-90a1-e607a2c99369;;1401353441;;;c0de75bb0cd22030f76fb6df9fa71c7e`

Result line for song 4:
`id;url;title;titlesort;titlesearch;customsearch;album;tracknum;content_type;timestamp;filesize;audio_size;audio_offset;year;secs;cover;vbr_scale;bitrate;samplerate;samplesize;channels;block_alignment;endian;bpm;tagversion;drm;disc;audio;remote;lossless;lyrics;musicbrainz_id;musicmagic_mixable;replay_gain;replay_peak;extid;primary_artist;urlmd5;coverid;cover_cached;virtual;added_time;updated_time;dlna_profile;hash;id;title;titlesort;titlesearch;customsearch;compilation;year;artwork;disc;discc;replay_gain;replay_peak;musicbrainz_id;musicmagic_mixable;contributor;url;musicbrainz_id;playCount;added;lastPlayed;rating;urlmd5
264318;file:///xxx/Sugababes%20-%202006%20-%20Overloaded%20The%20Singles%20Collection/04.%20In%20the%20Middle.mp3;In the Middle;IN THE MIDDLE;IN THE MIDDLE;;17493;4;mp3;1401353442;6467849;6463615;4106;2006;239.066;/xxx/Sugababes - 2006 - Overloaded The Singles Collection/cover.jpg;1;216000.0;44100;;2;1;;;ID3v2.3.0, ID3v1.1;0;;1;0;0;;08ca34ed-7833-4047-9ba4-6242fa59f1de;;;;;50609;91d60242c85efd9b05814e51a54163ec;ba34f69a;1;;1563956587;1563956587;MP3;;17493;Overloaded: The Singles Collection;OVERLOADED THE SINGLES COLLECTION;OVERLOADED THE SINGLES COLLECTION;;0;2006;ba34f69a;;;;;5626aa80-0570-4d59-bff1-3ebafa0d7aa1;;50609;file:///xxx/Sugababes%20-%202006%20-%20Overloaded%20The%20Singles%20Collection/04.%20In%20the%20Middle.mp3;08ca34ed-7833-4047-9ba4-6242fa59f1de;;1414944465;;;91d60242c85efd9b05814e51a54163ec`

I'm happy to provide more information if needed.

**Comment by michaelherger** [comment]
Maybe you should describe in what way the results seem to be wrong?

**Comment by michaelherger** [comment]
Ok, I do see that this would happen if there was no record for a track in `persist.db`. Could you please check whether this is the case for you?

Would a full wipe & rescan fix this issue? There should always be such a record in that database.

**Comment by CDrummond** [comment]
@michaelherger The issue _seems_ to be related to supplying the the `R` parameter to the `tags:` field in a `status` request (and also when browsing the library). As detailed in https://github.com/CDrummond/lms-material/issues/192 the following command only returned 1 track, but stated there were 2 in the queue:

```
curl 'http://localhost:9000/jsonrpc.js' --data '{"id":1,"method":"slim.request","params":["c8:60:00:8a:xx:xx",["status",0,500,"tags:cdegltysAKNSR"]]}'
```
Response: https://github.com/CDrummond/lms-material/issues/192#issuecomment-555642364

But without the `R` in `tags:` both tracks were returned:

```
curl 'http://localhost:9000/jsonrpc.js' --data '{"id":1,"method":"slim.request","params":["c8:60:00:8a:xx:xx",["status",0,500,"tags:cdegltysAKNS"]]}'
```
Resaponse: https://github.com/CDrummond/lms-material/issues/192#issuecomment-555634236

I'm guessing that its probably only Material using the `R` value here. I use it as  quick way to get ratings for tracks, as opposed to querying LMS (via trackstat?) for each track. This is probably why its not been an issue before.

p.s. I think the title of this report is wrong, or miseleading. It's not so much the songinfo command, as much as using the tags detailed in songinfo for other commands (which state to use the tags detailed there).

**Comment by mherger** [comment]
I think this is a problem with inconsistent data: the code is assuming that for every track in the library there's a record in the `tracks_persistent` table, too. It therefore does a lazy (default) `INNER JOIN` on the tables. If a track is missing from the `tracks_persistent` table, it does not show up in those queries. By changing the code to using a `LEFT JOIN` I would get all the results as expected.

Now whether this is a bug in the query code, or a bug in the scanner code not creating the necessary record, I don't know. But it's probably good enough a solution to change the `JOIN` type.

I'd still love to know how these users could have ended up with an incomplete track list in `tracks_persistent`.

**Comment by grasshide** [comment]
I did a complete wipe and rescan of my database. No errors in the scanner.log. It did not solve the problem.
Then I did a query on my persistent database to see if there are tracks missing. No track is missing. In fact I seem to have retagged the album twice. Therefore I see the album three times in my library. Only one real copy does exist on my drive though:
![image](https://user-images.githubusercontent.com/4366857/69267557-b587d280-0bcd-11ea-9d8b-83ab03f5dfad.png)
If I remember correctly this is not a problem and no error. It is the intended behavior in case music gets retagged. If so, trackstat would be able to recover the ratings by the url or the musicbrainz_id.

**Comment by grasshide** [comment]
Here is an inner join of the tables:
```
SELECT tracks.id, tracks.url, tracks.title, tracks.musicbrainz_id, track_statistics.musicbrainz_id
FROM tracks
INNER JOIN track_statistics
ON tracks.url = track_statistics.url
where tracks.url like '%Overloaded%';
```
The result contains all the songs:
![image](https://user-images.githubusercontent.com/4366857/69268434-6a6ebf00-0bcf-11ea-88a4-93d276e14877.png)
