### ISSUE TITLE
--httpaddr :: (listen on IP4 and 6) does not work

### ISSUE THREAD

**Issue by mnd999** [LMS-Community/slimserver#302]
If I try to instruct slimserver to list on both an IPV4 address and IPV6 it fails to start:

```
[20-01-08 12:37:15.6659] Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Web::HTTP::acceptHTTP: Bad arg length for Socket::inet_ntoa, length is 16, should be 4 at /opt/logitechmediaserver/Slim/Web/HTTP.pm line 248.
```
Looks like it's not coping with the 16 octet address.

**Comment by mherger** [comment]
I think there is a larger "make LMS IPV6 ready" issue...

**Comment by mnd999** [comment]
> I think there is a larger "make LMS IPV6 ready" issue...

I couldn't find anything - agree if this work has never been looked at though there are likely other bits that need fixing.

**Comment by mnd999** [comment]
Will close this, could not reproduce locally, as when I ran on my desktop (`Linux 5.4.7-arch1-1 x86_64`)  I got:
```
Slim::Web::HTTP::openport (169) Can't setup the listening port 9000 for the HTTP server: Invalid argument
```
Which is what I would expect if it's not supported at all. No idea why it got further on my media server (`Linux 4.14.158 armv7l` ).
