### ISSUE TITLE
Boom subwoofer output still on while unit is off

### ISSUE THREAD

**Issue by born-daniel** [LMS-Community/slimserver#303]
I have two Squeezebox Booms often synced together. In the morning I listen to one in the kitchen while the one in the bedroom is off. I have a script that uses the CLI to unsync the two, turn on the Boom in the bedroom and play a sound clip as an alarm clock. Once it's done, it clears the playlist and turns off the boom in the bedroom and re-syncs the two players. This stops the music in the kitchen as there is no more playllist but that's ok since I keep an ear out for my wife getting up. Then I turn the music back on in the kitchen (radio). Out of the synced but off Boom in the bedroom, comes the synced output from the kitchen Boom but only on the Sub channel while the Boom is definitely off. Sound control doesn't work. If I turn on the Boom, it will start playing normally and if I turn it off again, everything stops including the Sub output.

Please let me know if you need anything, logs, exact steps to reprodude, etc.
Thanks,

**Comment by michaelherger** [comment]
I'm sorry to say that even if that proved to be a real bug, there's no way it's going to be fixed. Firmware changes on these units are virtually impossible to do today.

**Comment by born-daniel** [comment]
I was hoping for a fix in LMS but ok, I understand. I'll just have to find a workaround.
I think it's a real bug :) it happened 2 out of 2 times since I connected the sub...

Cheers,
Daniel
