### ISSUE TITLE
Malformed UTF-8 character during rescan

### ISSUE THREAD

**Issue by tgol** [LMS-Community/slimserver#304]
[20-01-24 19:56:13.6730] main::main (338) Error: Failed when running main scan: [Malformed UTF-8 character (fatal) at /Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Utils/Text.pm line 162.
]
[20-01-24 19:56:13.6732] main::main (339) Error: Skipping post-process & Not updating lastRescanTime!

---

Logitech Media Server Version: 8.0.0 - 1579819365 @ Fri Jan 24 00:29:18 CET 2020
OS: macOS 10.14.6 - EN - utf8
Platform: x86_64
Perl Version: 5.18.4 - darwin-thread-multi-2level
Audio::Scan: 1.02
IO::Socket::SSL: 1.966
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

**Comment by mherger** [comment]
Could you please enable logging for the scanner (from Settings/Advanced/Logging - there's a drop-down at the top), then re-run a scan. Once done, please provide the full scanner.log.zip file as linked from Settings/Information.

**Comment by tgol** [comment]
Here is the log:
[scanner.log.zip](https://github.com/Logitech/slimserver/files/4114636/scanner.log.zip)

Scanning runs fine on version 7.9.3

**Comment by michaelherger** [comment]
That's not a complete log file. It lacks start and end. And the error message you quoted.

**Comment by tgol** [comment]
Sorry, here is another attempt.

[scanner.log.zip](https://github.com/Logitech/slimserver/files/4233138/scanner.log.zip)

Thank you.

**Comment by mherger** [comment]
Unfortunately while this is the full file, it's been created without the additional logging settings for the scanner.

**Comment by tgol** [comment]
Not sure why but I tested latest nightly and no scanning errors. Sorry about this, closing issue.
