### ISSUE TITLE
Handling of wav mimetypes

### ISSUE THREAD

**Issue by t2000** [LMS-Community/slimserver#307]
After debugging why my openHAB doesn't play wav files on my Logitech Media Server with squeezebox clients I found this: https://github.com/openhab/openhab-core/issues/1350

To summarize: the LMS uses only `audio/x-wav` as a mimetype for wav files. If a wav file is served by a webserver with a mimetype of `audio/wav`, it won't be played.

I see the problem here:
https://github.com/Logitech/slimserver/blob/7e817bb15aff97084007cd4411f389edb2b6416c/types.conf#L55

If I create a `custom-types.conf` with
```
wav     wav,wave        audio/x-wav,audio/wav                     audio
```
all is fine and LMS plays my files on the squeezelite clients.

From the aforementioned issue and https://github.com/jshttp/mime-db/issues/22 the mimetype might even be `audio/vnd.wave`.

Since you support setting multiple mimetypes anyway, I wonder it it would be an option to include these other mimetypes for wav files by default?

**Comment by michaelherger** [comment]
Thanks! Please give the next nightly build a try and report back.
