### ISSUE TITLE
New setting or pattern to exclude folders from library ?

### ISSUE THREAD

**Issue by trou** [LMS-Community/slimserver#311]
Hi,
I have all my music stored in one place, but I'd like to exclude some folders from the library scan but still be able to reach them through the "Music folder" page.

It seems there's already some provision in `Utils/Scanner/LMS.pm` to ignore some directories. It would be nice to be able to either:
* specify some paths/patterns to ignore
* allow the user to add a file to mark the containing folder to be ignored (like `.lms_ignore` or sth like this)

What do you think ?

**Comment by michaelherger** [comment]
I have a plugin called "Ignore files and folders" which you could use to do this.

**Comment by trou** [comment]
Indeed, I never saw it. Thanks !

It's a bit annoying that it also applies to "music folder" but I can live with that. Feel free to close the issue if you want.

**Comment by mherger** [comment]
You can always use the "Browse Filesystem" feature to browse whatever you want, unfiltered.
