### ISSUE TITLE
Put text on the player's display do not work correctly with non ascii character 

### ISSUE THREAD

**Issue by harryklein** [LMS-Community/slimserver#312]
I try to send a message via the Logitech Media Server Web Interface to my Squeezebox Classic.

The message include a non ascii character. I use the following command: 

`curl "http://localhost:9000/status.html?p0=display&p1=Status&p2=HTTP%20Sp%C3%BClmaschine%20ist%20fertig&p3=30&player=00%3A04%3A20%3A07%3Af6%3Af3"`

Instead of 

> STATUS
> HTTP Spülmaschine ist fertig

I see on the display the message 

> STATUS
> HTTP SpÃ¼lmaschine ist fertig

With the cli I get the correct message.

`echo -en "00%3A04%3A20%3A07%3Af6%3Af3 display Status CLI%20Sp%C3%BClmaschine%20ist%20fertig 30\nexit\n" | nc localhost 9090`

> STATUS
> HTTP Spülmaschine ist fertig

LMS 7.9.3 
debian 9 (64bit)

**Comment by michaelherger** [comment]
I assume the second command would say
> CLI Spülmaschine ist fertig

😉 

But beyond that you could try to use an HTML entity instead of the utf8 encoded character (&uuml;). As a workaround of course, until I've found time to take care of this issue.

**Comment by mherger** [comment]
Oh, and you should use the JSON/RPC interface rather than the old `status.html`:

```
curl -X POST -d '{"id":0,"params":["00:04:20:07:f6:f3",["display","Status","JSON/RPC: Spülmaschine fertig", 30]],"method":"slim.request"}' http://localhost:9000/jsonrpc.js
```

That would encode correctly.

**Comment by harryklein** [comment]
The fix works perfectly. 

I will use the JSON/RPC interface in the future.
