### ISSUE TITLE
Alarm off, player state

### ISSUE THREAD

**Issue by devdems** [LMS-Community/slimserver#317]
Hi,

to which player state should plugin subscribe when alarm turns off?

I can see that irblaster is subscribing to those states:
Slim::Control::Request::subscribe( \&commandCallback, [['power', 'play', 'playlist', 'pause', 'client']]);

It gets triggered when alarm starts but not when alarm is stoped.

**Comment by michaelherger** [comment]
I think there are `alarm sound|snooze|end` events available.

**Comment by devdems** [comment]
Tnx. Working with alarm end.
