### ISSUE TITLE
Starting playlist via preset button deletes playlist (baby)

### ISSUE THREAD

**Issue by fmueck** [LMS-Community/slimserver#318]
I wanted to assign a playlist to a preset button on my Squeezebox Radio (baby).
However, whenever I push that hardware button, that playlist is in fact deleted (not found on the server anymore). The playlist URL remains in the preset dialog box, but the actual playlist file is gone, on the Radio I see "Current Playback: None".
Using logitechmediaserver_7.9.3~1584993250_arm.deb on a raspberry Pi 3 (Raspbian).

In the log, I see this message:
`[20-04-01 19:29:16.7627] main::init (387) Starting Logitech Media Server (v7.9.3, 1584993250, Tue Mar 24 04:15:11 CET 2020) perl 5.028001 - arm-linux-gnueabihf-thread-multi-64int
[20-04-01 19:41:13.1155] Slim::Formats::Playlists::Base::_filehandleFromNameOrString (86) Error: Could't open /lms_root/playlist/omen_tst.m3u for writing.`

BTW, I wanted to use this opportunity to say 'thank you' for the working Opus support =)

**Comment by michaelherger** [comment]
That's most likely a permissions issue. Please make sure LMS is allowed to write to `/lms_root/playlist`.

**Comment by fmueck** [comment]
>
>
> That's most likely a permissions issue. Please make sure LMS is allowed to write to `/lms_root/playlist`.

Thanks, that's exactly what it was. Sorry for the 'false alarm'. I just got confused because everything related to playlist creation seemed to work from the web GUI, but when calling it from the preset, it suddenly seemed to disappear.
