### ISSUE TITLE
Artists from online sources shown in Authors library

### ISSUE THREAD

**Issue by pascalberger** [LMS-Community/slimserver#323]
I've enabled the virtual library for authors and online integration with Spotify through Spotty. The `Authors` library now shows, beside artists from audiobooks, also all artists from my Spotify library.

## Repro

1. In settings for `Additional Browse Modes` enable `Create an Audiobooks library view and a view without audio books based on the following genres`
2. Make sure the additional browse mode for `Authors` is created
3. Make sure Online Music Library integration is installed and enabled, Spotty setup and some albums available in the Spotifiy library
4. Clear library and rescan
5. Navigate to `My Music \ Authors`

Instead of only authors from audiobooks, also all artists from the Spotify library are shown. It doesn't seem to matter if they have a genre attached or not (through Genre Replacement).

## Environment

LMS 8.0.0 - 1586839173 / Default Skin

**Comment by pascalberger** [comment]
@mherger I updated to `8.0.0 - 1587049226 @ Thu Apr 16 17:19:02 CEST 2020` but still have the same behavior.  Does it require a rescan?

**Comment by michaelherger** [comment]
Yes, a scan is required.
