### ISSUE TITLE
Can't search favourites via CLI

### ISSUE THREAD

**Issue by peteS-UK** [LMS-Community/slimserver#324]
Searching favourites using the search: tag doesn't work.

If I do "favorites items 0 20" I get the whole list of favourites. 

If I do "favorites items 0 1 item_id:4" I get the one favourite that has ID=4 (the 5th one in the list).

But, if I do "favorites items 0 1 search:Classic" I just get the first item in the list - it ignores the search. Oddly, it does change the session id, which is returned as the first part of the id string to be id:xxxxxxxx_Classic.0 - i.e. it's tagging the search term onto the session id.

This is using current nightly for 8.0.0

**Comment by mherger** [comment]
How do you plan to use this feature?

**Comment by peteS-UK** [comment]
Hi Michael

For my home automation stuff, I use old, but still very functional, Pronto TSU9400 which have a full javascript engine, so I connect via tcp to the server.  I pass it the name of the favourite from my client app on the remote and need to search for its ID and then pass it to the playlist.  At the minute, I return the whole favourite list and search it in the client instead, rather than passing the search to the server.

I also found that "favorites items" doesn't work on its own, where this should return all favourites.  You have specify <start> <itemsPerResponse> for it to work e.g.  "favorites items 0 300".

Peter


------ Original Message ------

**Comment by peteS-UK** [comment]
Hi Michael

I just tested “favorites items 0 search:” and it seems to work now 😊

I think there’s something odd with <itemsPerResponse> parameter.  “favorites items 0 1 search:Classic” doesn’t work, although you’d think it should return 1 item.  Instead, “favorites items 0 50 search:” does work.  Or, “favorites items 0 search:” works.  So, it looks like itemsPerResponse is perhaps behaving more as characterPerResponse perhaps.

Peter
