### ISSUE TITLE
Searching with different text cases

### ISSUE THREAD

**Issue by rdenny100** [LMS-Community/slimserver#327]
I have set up a small script to use in IFTTT to ask google assistant to play an album on LMS. It works only if the Google Voice sends the request to LMS in title case e.g. Let It Be. LMS wont search for alums if it recieves a request in small letters e.g. let it be. LMS wipes the playlist in this case. Could LMS allow serarching for albums in with all lower case words?

**Comment by michaelherger** [comment]
Search should be case insensitive. In order to be able to help I'd need to know what exact commands are being used to interact with LMS.

**Comment by rdenny100** [comment]
I’m not an expert so please bear with me!

I’ve set up chromecast bridge on the Plugins section which works nicely with all my chromecasts. I then can set up a command in IFTTT to play an album or artist to one of the chromecasts. Setting up the chromecast command I select google assistant. The command is **“Ask Den Office (chromecast) to play the album $”** 

For the second part I select Webhooks and in URL type: **http://(Username):(Password)@(my DDNS):9000/status?p0=playlist&p1=loadalbum&p2=*&p3=*&p4={{TextField}}&player=(Chromecast Mac address)** When I try this I look at the Activity in IFTTT. It plays when the ingredients textfield has capital letters for each word. When the ingredients is all in lower case. It doesn’t. Looking at LMS webview, tracks appear in the first instance and disappear in the second instance.


Thanks for replying.

**Comment by michaelherger** [comment]
Helpful information, thanks. This indeed must be a command which hardly is being used any more, as it has been this way for 14 years! As I understand it you (or Google) would just throw an artist or album name at LMS, which LMS then would play, if it found it. Or is there any smarter integration with LMS? Eg. could you get an `album_id` value or something?
