### ISSUE TITLE
Skipping to next song

### ISSUE THREAD

**Issue by jeckman** [LMS-Community/slimserver#33]
Running Logitech Media Server Version: 7.8.1 - 1408690219 on an ubuntu server box. 

Player is iPeng on an iPad. 

Server is hard wired ethernet, iPad is on wifi but with very strong good signal. 

Getting skips where a song doesn't finish but the player jumps ahead. 

Obviously lots of things to isolate here, but what should I enable in server logging that would most likely point to a culprit?

**Comment by mherger** [comment]
player.streaming might be a good starting point. Do you have any SB hardware to see whether this is limited to iPeng use? You might want to join the community at forums.slimdevices.com, as pippin (iPeng's author) would be there, too.

**Comment by jeckman** [comment]
Rebooting the ipad fixed it. Thanks to mherger for the pointer to the forums.
