### ISSUE TITLE
Search Artist list all Spotify Artist

### ISSUE THREAD

**Issue by hellgelino** [LMS-Community/slimserver#330]
After start a normal search and choosing artist, i get all my spotify Artist shown, not only the artist i searched for. In the search Preview it shows correct only one hit for my  searched artist.
V.8 lates nightly

**Comment by mherger** [comment]
I think I see what you mean: you enter an artist name in the quick search field, then choose to list all artists matching that term. That would list all online artists in addition to the local hit?

**Comment by michaelherger** [comment]
Thanks!

**Comment by hellgelino** [comment]
Awsome - works fine now. Thank you very much!
