### ISSUE TITLE
Media files not played from the start

### ISSUE THREAD

**Issue by schnillerman** [LMS-Community/slimserver#332]
Often, files are not played from the start if selected to play while playing another file.
I cannot reproduce this consistently, but it happens every 4th or 5th time a new file is selected to play.

**Comment by michaelherger** [comment]
I think you should take this to [forums.slimdevices.com](https://forums.slimdevices.com) with a lot more information about LMS version, player type, file formats etc.

**Comment by schnillerman** [comment]
Will do.
