### ISSUE TITLE
Available plugins from 3rd party repos do not display in 8.0.0 yet are able to update

### ISSUE THREAD

**Issue by worsco** [LMS-Community/slimserver#334]
I upgraded from a 7.9.0 installation to Logitech Media Server Version: 8.0.0 - 1588799628 @ Wed May 6 23:47:22 CEST 2020.

When running 7.9.0, Additional Repositories (plugins) show content in those repos, however, they don't show up in 8.0.0.

Additional Repositories such as:
https://erland.github.io/squeezebox-downloads/repositories/latest.xml
https://sourceforge.net/projects/sdt-weather-com/files/repo.xml

The titles show up in the Plugins tab/page, but no content of the repo.  

The titles for these repos display as:

Erland's pluins and applets
SuperDateTimeRepository

There are no logged errors in /var/log/squeezeboxserver/server.log regarding the repos

I have "Update plugins automatically" enabled, and I have received notification via lms that plugins from the repo  SuperDateTimeRepository have updated.

Why don't packages from 3rd party plugin repos display the packages?

This is the content from https://sourceforge.net/projects/sdt-weather-com/files/repo.xml
```
<extensions>
	<details>
		<title lang="EN">SuperDateTime Repository</title>
	</details>
	<plugins>
		<plugin name="SuperDateTime" creator="G Brown, D Grossman" link="https://sourceforge.net/projects/sdt-weather-com/" maxTarget="8.*" minTarget="7.4" sha="6464c9d9d9c0b48828134f74d095fa2fc3584d9a" url="https://downloads.sourceforge.net/project/sdt-weather-com/SuperDateTime5-11-1.zip" version="5.11.1">
			<desc lang="EN">Displays local time, date, weather, sports, and stock information.  
			(5.11.1) - Added Weather Radar Map accessible through Custom Clock Helper.</desc>
			<title lang="EN">SuperDateTime</title>
		</plugin>
	</plugins>
</extensions>
```

**Comment by worsco** [comment]
I believe I misinterpreted the groupings of plugins on the Plugin page/tab.  If I enabled a plugin from one of the Additional Repos, it gets moved into "Active plugins" group, even though the source was from an Additional Repository.  The "Active plugins" group does not indicate the source of the plugin (if it was from an Additional Repository).

**Comment by worsco** [comment]
My goal was to install DynamicPlayList from erland's repo, but I see the issue from that package in the repo is the max.Target is set to 7.* and I'm running 8.0.0

Snippet from https://erland.github.io/squeezebox-downloads/repositories/latest.xml
```
<plugin name="DynamicPlayList" version="2.10.247" minTarget="7.4.0" maxTarget="7.*">
```

**Comment by michaelherger** [comment]
As you’ve figured out the author needs to make sure the maxVersion matches LMS8. See eg. http://forums.slimdevices.com/showthread.php?t=112097 for a discussion around this issue.

**Comment by worsco** [comment]
Closing this as it is not an issue of the LMS8 code.
