### ISSUE TITLE
Select all items of a list de-selects initial item

### ISSUE THREAD

**Issue by schnillerman** [LMS-Community/slimserver#336]
In order to make an item selection and to display the _select all/none_ buttons, an initial item has to be selected via item's menu.
Once the initial item is selected, the select _all/none buttons_ appear. Clicking the _select all_ button then selects all items of the list except the initial item which is de-selected.

Is this behavior intended? I think it's quite counter-intuitive.

Behavior noticed in both v7.9.2.x and v8.0.x, with any skin.

**Comment by michaelherger** [comment]
What list are you referring to?

**Comment by schnillerman** [comment]
Playlists in general.

**Comment by schnillerman** [comment]
Update: I think this is applicable only to material skin. Closing this one ...

**Comment by CDrummond** [comment]
Bit late here, but Material has no 'Select All' The button you are referring to inverts the selection - as detailed in its tooltip.
