### ISSUE TITLE
LMS+SqueezeLite won't play short files over SSL (https:)

### ISSUE THREAD

**Issue by Moonbase59** [LMS-Community/slimserver#337]
Playing short (<4s) MP3 files over SSL (`https:` links to Home Assistant) to SqueezeLite 1.9.7 doesn’t work—LMS shows the URI and the seconds counter counts forever, without playing a sound. These are meant to be short audible alerts from Home Assiatant to a dedicated SqueezeLite player. _Longer files work without a problem._

Would you please care to chime in on https://github.com/ralph-irving/squeezelite/issues/94 ?

I already have all the information, sample files and log files there but it turns out we suspect LMS doing something odd (like maybe secretly proxying instead of simply passing on the URI).

I’d appreciate some assistance on further diagnosing this issue on the LMS side (like what logs to generate, and how).

**Comment by mherger** [comment]
Dupe of issue #350
