### ISSUE TITLE
Debian testing updated Perl to 5.20 - missing modules

### ISSUE THREAD

**Issue by LeZerb** [LMS-Community/slimserver#34]
Would it be possible to add the corresponding perl modules?

**Comment by mherger** [comment]
Sooner or later this is going to happen. But as this topic has been bugging me for years now, I want to change something in 7.9. We've been adding binaries as needed, resulting in packages of almost 120MB, when 20-25MB should be enough...

I started a discussion in the forums (http://forums.slimdevices.com/showthread.php?102110-How-to-deal-with-LMS-Perl-binaries-mess-on-Linux). You might be one of the first to experience whatever solution we might come up with ;-).

**Comment by LeZerb** [comment]
In the meantime I recompiled the modules myself. I needed - however - to disable the Tests for Locale-Hebrew-1.04 and Font-FreeType-0.03 - somehow those failed.

**Comment by mherger** [comment]
Yeah, that's probably why I stopped building them... they're only of importance if you set your LMS to Hebrew and were using a Classic/Boom/Transporter.

But other than that building for 5.20 did work ok?

**Comment by tomscytale** [comment]
I've just updated to ubuntu 14.10 and updated to the latest nightly build (7.9.0~1414578742)
I'm using a 1st generation EEE PC (remember them) as a media server so this is x86. 

```
/usr/sbin/squeezeboxserver  --d_startup

The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name
```

It looks like only x86_64 versions of the perl 5.20 CPAN packages have been built and bundled with the .deb (correct?)

I'm currently building https://github.com/Logitech/slimserver-vendor (it takes forever on this old hardware)
AFAICT I need to copy `slimserver-vendor/CPAN/build/5.20/lib/perl5/i686-linux-gnu-thread-multi-64int/` into `/usr/share/squeezeboxserver/CPAN/arch/5.20/`
Am I correct?

Are there any instructions for this build process on the wiki?

If I can get this working I may (if i find the time) be able to update the github repo to add x86 support for perl5.20

**Comment by mherger** [comment]
You might need to tweak the folder name (i386-linux-thread-multi-64int), as LMS is mangling it on its end, too, to fit all kinds of variations.

And yes, I do have an EEEpc in the basement, too. Not powered up, though :-)

**Comment by tomscytale** [comment]
I copied the dir over as suggested and the squeezebox server starts ok now. I do see some tracebacks but they seem to be SQL related and so not (directly) caused by this

should I add this dir to `CPAN/arch/5.20` in this repo and open a pull request?

there is a rather large discrepancy between the number of subdirs that are present in this dir compared to the same dir in, say 5.18. However that's probably better discussed in the pull request

**Comment by mherger** [comment]
@tomscytale I'm sorry this took so long. I've finally added binaries for i386-linux-thread-multi-64int to 7.9. Would this work for you, too? What's your machine's exact perl version string?

**Comment by tomscytale** [comment]
great! thanks for that - (I was just about to send a pull request)

I'm on ubuntu 14.10 (just upgraded from 14.04 - hence the breakage)

```
$ perl -v

This is perl 5, version 20, subversion 1 (v5.20.1) built for i686-linux-gnu-thread-multi-64int
(with 37 registered patches, see perl -V for more detail)
```

I use the nightly `.deb` - that should be available from the download page by tomorrow morning?

**Comment by mherger** [comment]
yes, tomorrow's build should come with the latest files.

**Comment by tomscytale** [comment]
installed latest nightly and everything now works as it should. thanks very much.

**Comment by mherger** [comment]
excellent! Thanks for testing!

**Comment by csrhodes** [comment]
Hi,

I'm running on armhf/Debian jessie (hence Perl 5.20); I have rebuilt the modules for myself, and my installation is OK.  I would be happy to work on (in free-time) either making my builds available, or on reducing the use of the bundled libraries.  Let me know what would help.
