### ISSUE TITLE
Discussion on 2020-05 issue with HTTPS and NB sockets

### ISSUE THREAD

**Issue by philippe44** [LMS-Community/slimserver#341]
This is not really an issue but more, per title, a discussion on use of NB sockets in HTTPS. 

Last year, we moved to use Net::HTTPS::NB as a base of Slim::Networking::Async::Socket::HTTPS to solve problem described here https://github.com/Logitech/slimserver/issues/261

That makes sense to not have blocking *connect()* in all cases but it could be argued to move back to blocking after connection as AnyEvent is used generally in LMS so select() is probably wisely used to never block, at least in a read. I'm not sure at that point about write and I'm not sure if the issue above was purely due to blocking connect() or as well due to the fact that HTTPS sockets were in general blocking. I'll forget for now the idea of moving back to blocking after connect (could be done in Slim::Networking::Async.pm, _async_connect).

Now, looking at CPAN::Net::HTTP::NB.pm; function
```
sub read_entity_body {
    my $self = shift;
    ${*$self}{'httpnb_read_count'} = 0;
    ${*$self}{'httpnb_save'} = ${*$self}{'http_buf'};
    # XXX I'm not so sure this does the correct thing in case of
    # transfer-encoding tranforms
    my $n = eval { $self->SUPER::read_entity_body(@_); };
    if ($@) {
	$_[0] = "";
	return -1;
    }
    return $n;
}
```
return -1 only on error, so it's fair to assume that caller of this will handle -1 as an error case and do whatever it feels appropriate

But when we switched to CPAN::Net::HTTP::NB.pm, we now have this
```
sub read_entity_body {
	my $self = shift;
	${*$self}{'httpsnb_reading'} = 1;
	${*$self}{'httpsnb_read_count'} = 0;
	${*$self}{'httpsnb_save'} = ${*$self}{'http_buf'};
	
	my $chunked = ${*$self}{'http_chunked'};
	my $bytes   = ${*$self}{'http_bytes'};
	my $first_body = ${*$self}{'http_first_body'};
	my @request_method = @{${*$self}{'http_request_method'}}; 
	
	# XXX I'm not so sure this does the correct thing in case of
	# transfer-encoding tranforms
	my $n = eval { $self->SUPER::read_entity_body(@_) };
	${*$self}{'httpsnb_reading'} = 0;
	if ($@ || (!defined($n) && $HTTPS_ERROR == HTTPS_WANT_READ)) {
		if ($@ eq "Multi-read\n") {
			# Reset some internals of Net::HTTP::Methods
			${*$self}{'http_chunked'} = $chunked;
			${*$self}{'http_bytes'} = $bytes;
			${*$self}{'http_first_body'} = $first_body;
			${*$self}{'http_request_method'} = \@request_method;
		}
		$_[0] = "";
		return -1;
	}
	return $n;
}
```
Which feels to me a very different game as we can return -1 when the TLS negotiation is still happening, so the caller of this should have a special handling of -1. In fact, we can see that in the recommended use in NB.pm

```
while (1) {
		my $buf;
		my $n;
		# try to read until error or all data received
		while (1) {
			my $tmp_buf;
			$n = $s->read_entity_body($tmp_buf, 1024);
			if ($n == -1 || (!defined($n) && ($! == EWOULDBLOCK || $! == EAGAIN))) {
				last; # no data available this time
			}
			elsif ($n) {
				$buf .= $tmp_buf; # data received
			}
			elsif (defined $n) {
				last; # $n == 0, all readed
			}
			else {
				die "Read error occured: ", $!; # $n == undef
			}
		}
	
		print $buf if length $buf;
		last if defined $n && $n == 0; # all readed
		die "Body timeout" unless $sel->can_read(10); # wait for new data
	}
```
when the recommended use for the non SSL version of read_entity_body is
```
 while (1) {
    die "Body timeout" unless $sel->can_read(10);
    my $buf;
    my $n = $s->read_entity_body($buf, 1024);
    last unless $n;
    print $buf;
 }
```
So that made me think that our correction in  Slim::Networking::Async::HTTP.pm to not do anything if -1 was return is really necessary as otherwise, the rest of the function was executed although we had nothing to read (still in TLS negociation) and it ended up bad.
```
sub _http_read_body {
	my ( $socket, $self, $args ) = @_;
	
	my $result = $socket->read_entity_body( my $buf, BUFSIZE );
	return if $result < 0;
```
Still, I'm wondering if there are other cases where we use on  Slim::Networking::Select::addRead() that could be problematic when used with SSL and NB sockets

**Comment by Moonbase59** [comment]
I follow you but this is far out of my range of expertise. In general, I’m in favour of doing things async/NB but that poses new risks of running into deadlock situations.

Anyway, your patch much helped getting things going smoothly again here.

**Comment by philippe44** [comment]
> I follow you but this is far out of my range of expertise. In general, I’m in favour of doing things async/NB but that poses new risks of running into deadlock situations.

Yep and I obviously got bitten by one of these corner case. I'm even surprised that it did not appear in non-Windows platform before. Maybe because it was happening only under special case of SSL failure.

**Comment by philippe44** [comment]
I'll close that for now and keep track of it
