### ISSUE TITLE
"play this Song" from playlists doesn't start track

### ISSUE THREAD

**Issue by guillaumezin** [LMS-Community/slimserver#364]
Hello,

I see the same behavior from Jivelite and my SB radio: if a track is currently playing, if I do a short click on an item from a playlist, from my local collection, I have a context menu and choose "play this Song", nothing happens. If i do a long press and choose "play", it plays immediatly. In the first case, I have this log message in server log: "Slim::Menu::BrowseLibrary::_doRequest (947) Bad params!".

Please note that the short click from another play from a playlist, for instance from "New Music", or "Music Folder", it works as expected, I see the problem from "My Music" -> "Playlists" only.

Logitech Media Server Version : 8.0.0 - 1591161678 @ Wed Jun 3 07:50:42 CEST 2020
Perl : 5.28.1 - arm-linux-gnueabihf-thread-multi-64int
Audio::Scan : 1.02
DBD::SQLite 1.58 (sqlite 3.22.0)
SB Radio 7.7.3-r16676

Thank you.

Guillaume

**Comment by michaelherger** [comment]
Is this something new in LMS8 or did you see this in 7.9.x already?

**Comment by guillaumezin** [comment]
I'm sorry, I don't know. I switched to LMS8 quite recently. I saw the problem for the first time two days ago, but it doesn't mean it wasn't here for some time... Is it possible to downgrade to LMS7.9 without damage ?

**Comment by michaelherger** [comment]
Yes, the downgrade would trigger a rescan. Apart that it should be seamless.

**Comment by guillaumezin** [comment]
I downgraded to logitechmediaserver_7.9.3~1591161343_arm.deb and I see the same behavior.

**Comment by guillaumezin** [comment]
Thank you, you rock! ;-)
