### ISSUE TITLE
Gapless pcm Playback broken with Squeezebox1

### ISSUE THREAD

**Issue by michaldie** [LMS-Community/slimserver#366]
This has been around for a while (since 7.7 or so)
it appears that the refactoring that was done that introduced "currentTrack"  did miss to also adjust 

sub isReadyToStream {
function inside Squeezebox1.pm

the fix is : instead of 

> 				if (   $playingSong->channels   == $song->channels
> 					&& $playingSong->samplesize == $song->samplesize
> 					&& $playingSong->samplerate == $song->samplerate

we would need : 
if (   $playingSong->currentTrack->channels   == $song->currentTrack->channels
	&& $playingSong->currentTrack->samplesize == $song->currentTrack->samplesize
        && $playingSong->currentTrack->samplerate == $song->currentTrack->samplerate

with this fix in place, my player will do gapless pcm playback again.
I also tested that switching samplerate (44.1k - > 48k) still does cause decoder restart as expected.

**Comment by michaelherger** [comment]
Could you please provide a pull request?

**Comment by mherger** [comment]
Fixed in PR #369
