### ISSUE TITLE
LMS 8.0.0 Where did albums tagged with "Various Artists" disappear to? They are not displayed under "Album Artist" or "Albums"

### ISSUE THREAD

**Issue by worsco** [LMS-Community/slimserver#368]
I'm running 8.0.0 nightly, and I have many albums that are tagged with ALBUMARTIST as "Various Artists".

In the "New Music" section, when I click on the "Various Artists" link under an album, the next page displays the one word "Empty" and the breadcrumbs heading reads "Home > Artist (Various Artists)"..

In the Web UI, when I click on "Album Artists" and then "V", there is no "Various Artists" icon.  Also, under "Albums", when I click on "V", there is no "Various Artist" grouping of albums.

Was it this way prior to 8.0.0?

Logitech Media Server Version: 8.0.0 - 1591851652 @ Thu Jun 11 07:16:53 CEST 2020
Server HTTP Port Number: 9000
Operating system: Red Hat - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.16.3 - x86_64-linux-thread-multi
Audio::Scan: 0.95
IO::Socket::SSL: 1.94
Database Version: DBD::SQLite 1.34_01 (sqlite 3.7.7.1)
Total Players Recognized: 3

**Comment by michaelherger** [comment]
Are you using any kind of library view?

I'd suggest you ask this type of support question in forums.slimdevices.com. You'll get better and more responses from the community than from me alone :)

**Comment by worsco** [comment]
No library views are in use in 8.0.0.  I've upgraded to a most recent version of 8.0.0 nightly, and if I click on a "Various Artists" link, it sends me to "Compilations".  I am closing this issue.
