### ISSUE TITLE
Custom added main menu items not preserved across update

### ISSUE THREAD

**Issue by schnillerman** [LMS-Community/slimserver#370]
Items that are added to the main menu _in material skin_ (e.g. Soundcloud shortcut) are not preserved across LMS updates.

Build info:
Logitech Media Server Version: 8.0.0 - 1592130094 @ Sun Jun 14 12:49:11 CEST 2020
Hostname: LMS
IP-Adresse des Servers: 192.168.1.102
Server-HTTP-Portnummer: 9000
Betriebssystem: Debian - DE - utf8
Plattformarchitektur: x86_64-linux
Perl-Version: 5.24.1 - x86_64-linux-gnu-thread-multi
Audio::Scan: 0.95
IO::Socket::SSL: 2.044
Datenbankversion: DBD::SQLite 1.58 (sqlite 3.22.0)
Anzahl erkannter Player: 3

**Comment by michaelherger** [comment]
That's a Material issue. Please report on https://github.com/cdrummond/lms-material/issues.
