### ISSUE TITLE
Pandora Premium LMS limits to 6 skips

### ISSUE THREAD

**Issue by swvalenti194** [LMS-Community/slimserver#375]
Like the title says I have Pandora premium and I am limited to 6 skips, LMS and squeeze show account as premium.  Any ideas?

Thanks, 
Scott

**Comment by mherger** [comment]
Thanks for letting me know! I'll reach out to Pandora to see what's wrong there.

**Comment by swvalenti194** [comment]
@mherger Any update on this?

**Comment by michaelherger** [comment]
I'm sorry for the lack of update. Basically my contact at Pandora's said he was able to reproduce the limitation and that he'd double-check. But he hasn't gotten back to me, yet.

**Comment by swvalenti194** [comment]
Well that sounds promising if he can replicate the issue hopefully a fix gets pushed soon.  Let me know, thanks!

**Comment by swvalenti194** [comment]
Any update on this?

**Comment by michaelherger** [comment]
Unfortunately no. The response I got was "I am guessing it was always at 6".

Please do understand that my contact at Pandora's is relatively new there, doesn't know much about the history, and that we have become a neglectable partner from their POV. Therefore it's difficult to get anything out of them. The update to 192kbps has taken years to happen, and was only possible thanks to the personal initiative of that person. Anything beyond that will be very hard to achieve :-(.
