### ISSUE TITLE
tracks command ignores role_id if tags specified

### ISSUE THREAD

**Issue by CDrummond** [LMS-Community/slimserver#387]
In Material I have added an "All Songs" action when listing an artist's albums. I populate this using the 'tracks' command as follows:

```
["tracks", 0, 1000, "sort:albumtrack", "tags:cdrilstyES", "artist_id:<ARTIST_ID>", "role_id:<ROLE>" ]
```
but it seems as if "role_id" is ignored _if_ "tags:" is also specified.

e.g. the following returns a count of 379:
```
["tracks","0",1,"tags:cdrilstyES","artist_id:4320","role_id:ALBUMARTIST"]
```

but the following returns a count of 377:
```
["tracks","0",1,"artist_id:4320","role_id:ALBUMARTIST"]
```

I have tried changing "tags" by removing the parameters one by one, but only when "tags" is not specified is "role_id" respected.

**Comment by mherger** [comment]
Not sure how to fix this for good without breaking other stuff... it seems that the role was only taken into account if the tag `a` (artist name) was defined. If you don't specify any tags, `gald` would be used - which explains why it would work without tags. From looking at the code I'm not sure when exactly we should filter, what the expectations are. But I believe it's safe to say that we could treat `s` (artist ID) the same, thus filter when `a` or `s` is defined. This should fix your use case, but hopefully won't break too many other queries...

If you wanted to stay compatible with older LMS versions, just use the `a` tag in addition to what you have today.
