### ISSUE TITLE
Smartfade Logic when playing short tracks

### ISSUE THREAD

**Issue by d6jg** [LMS-Community/slimserver#406]
By trial and error I have established that the minimum length track required for correct play on a Smart Crossfade player is about 11.5 seconds. Anything less and the track gets played twice (sort of).
At the moment I can say that my findings apply to Squeezelite players (Windows & Linux). I haven’t had a chance to test with a hardware player.
This scenario did not appear with iPeng but then I realised that iPeng player doesn’t support crossfade (I checked with Pippin sometime ago).

@Michael. Is this a bug in the Smart crossfade logic. Surely it should not apply to any track with a duration less than the crossfade duration set for the player + whatever tolerance is needed?

To re-cap the scenario
Squeezelite Player set to crossfade with Smart crossfade ON and Smart gain ON.
Crossfade duration at default 10 seconds and also at 5 seconds.
Mixed playlist from numerous albums including tracks under 10 seconds long
Player attempts to crossfade the short tracks which results in the short track playing 1.5 - 2 times. First play is truncated.
Adding silence at front and end of short track to make it over 11.5 seconds resolves issue (11 seconds is not sufficient).

Version: 8.0.0 - 1597263993 @ Wed Aug 12 22:47:06 CEST 2020
Hostname: vortexbox-ssd
Server IP Address: 10.0.0.11
Operating system: Red Hat - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.22.2 - x86_64-linux-thread-multi
Audio::Scan: 0.95
IO::Socket::SSL: 2.023
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

**Comment by mherger** [comment]
I wasn't able to reproduce the repeating, but saw some other oddities, like skipped tracks etc. I decided to shorten the fade duration if the track length was less than twice the default duration. Please let me know if that doesn't help your issue.
