### ISSUE TITLE
LMS not notifying properly of 7.9.3 upgrade

### ISSUE THREAD

**Issue by pssc** [LMS-Community/slimserver#407]
Nothing is displayed on the homepage as you would expect...

I notice that http://www.mysqueezebox.com/update/?version=7.9&revision=3&geturl=1&os=deb knowlonger returns a url to a deb fle for upgrade.

Also see screen shots below.

![Screenshot 2020-08-25 20 23 19](https://user-images.githubusercontent.com/1763553/91218438-f38fc500-e710-11ea-99bc-01b6dd2af1fb.png)
![Screenshot 2020-08-25 20 23 27](https://user-images.githubusercontent.com/1763553/91218439-f4c0f200-e710-11ea-87ca-fee6b07e7cba.png)
![Screenshot 2020-08-25 20 21 34](https://user-images.githubusercontent.com/1763553/91218440-f4c0f200-e710-11ea-8959-6b60eb0cf3bb.png)

**Comment by michaelherger** [comment]
I kind of "deprecated" the download of the full .deb as it hardly ever makes sense any more. You should be using one of the CPU specific flavours (`debi386`, `debarm`, `debamd64`), as they're only a fraction of the size of the full deb file with all supported platforms.

**Comment by pssc** [comment]
@mherger makes sense the all loadload was a bit cumbersome I actually don't use it either the returned url was then subbed _all for the relevant arch...  as I cant seem to do an arch specific probe, things are better then they where I am now seeing an update notification in LMS the changelog seems to include the 3.7.4 changes though ;-).

*edit*
I see that in the probe url `os=debarm` should work
