### ISSUE TITLE
Squeezebox Radio loose the link with the server...

### ISSUE THREAD

**Issue by Adherack** [LMS-Community/slimserver#409]
Hello All !

Since the LogitechMediaServer-7.9.3-1596358162 version, all the squeezebox Touch work fine, but all the squeezebox Radio loose the connexion / link with the server after some minutes (between 3 and 15. I need toe start again the device.

I re-install the Logitech Media Server Version : 7.9.3 - 1591161343, all seem ok sibce 2 days...

Have you an idea ?

Have a warm day !

**Comment by michaelherger** [comment]
Please join the community at http://forums.slimdevices.com - you'll get better help there.

**Comment by Adherack** [comment]
I'll do.

Many Thanks !
