### ISSUE TITLE
Volume surge/noise while crossfading

### ISSUE THREAD

**Issue by MarSOnEarth** [LMS-Community/slimserver#412]
When crossfade is enabled, there is either a volume surge, or a burst of noise at the final moment of the crossfade process. For example, if the crossfade is set to 10 seconds, the glitch will be at the last second, or so, of the transition.

I'm running LMS v.7.9 series on Windows 10, feeding RPis running HiFIBerryOS.

**Comment by michaelherger** [comment]
Is there any relevant discussion on forums.slimdevices.com where I would get more information? I doubt there's a general issue with this, as 7.9 is many years old already.

**Comment by MarSOnEarth** [comment]
On Tue, 01 Sep 2020 02:28:07 -0700 michaelherger <notifications@github.com> wrote:

Hi Michael,

Thank you for following up on my entry.

> Is there any relevant discussion on forums.slimdevices.com where I would get more information?
Not exactly a discussion because no one responded, but I posted about this in the LMS forum, here:
https://forums.slimdevices.com/showthread.php?112788-Volume-surge-in-crossfade

> I doubt there's a general issue with this, as 7.9 is many years old already.
And you are right. Such a coincidence! After being plagued by this affliction since I put my setup together (months only), as soon as I brought myself to finally post about it, the problem was fixed today with an update to the player’s OS. It’s something that I completely dismissed as a possibility after looking at the crossfading code in LMS, but that’s exactly where the problem turned out to be!
FYI, my setup consists of a few RPIs with either HiFiBerry DAC+ Pro, or HiFiBerry DAC+/AMP2 HAT, and all running HiFiBerryOS, and today’s software update made the issue go away.

With apologies for raising a false alarm, and thank you for still maintaining and improving LMS
---- 
/MarSOnEarth

**Comment by mherger** [comment]
Thanks for letting me know!

**Comment by MarSOnEarth** [comment]
Hi Michael,

Although I reported that the problem was gone, that's not entirely the case. As opposed to repeating myself, here's a link to my (short) exchange with HiFiBerry engineer. He is right. The crossfading is done server-side, so what's is happening on my system that creates this volume surge, that no one else complains about. Tell me how I can assist you (debug logs, sound samples, anything).

Thanks

https://support.hifiberry.com/hc/en-us/community/posts/360013296138-Volume-surge-on-crossfading

**Comment by philippe44** [comment]
The cross-fading is done inside squeezelite, not in LMS. Do you have the same on less than 10s? What is the sample rate you're using and what is the output buffer size?

**Comment by MarSOnEarth** [comment]
It's obvious that I'm clueless as to this system's architecture, and to whose attention I should be bringing encountered problems to, so the more I'm appreciative of any response, especially if it comes from people even tangentially involved with the actual module that's causal to the issue. So, thanks.

As to your questions, yes, the issue does persist with different overlap duration, but the shorter that is the less pronounced it seems. The sample rate is 44.1/16 for 99.9 of my collection.

Curious, since there was a significant improvement after HiFiBerryOS update, and you think the issue might be in Squeezelite, where does one end, and the other start? Hmm. I think I should ask this of HiFiBerry (too).

Thanks again

**Comment by philippe44** [comment]
That's interesting ... are you 100% you have the problem between 2 44.1/16 files? It's really important

**Comment by MarSOnEarth** [comment]
I understand, and the answer is "Yes".

BTW, majority of my tunes are in flac format, and maybe 1/5 in a mix of VBR/CBR high-bitrate mp3s. It makes no difference what's played.

**Comment by MarSOnEarth** [comment]
I just tried pCP, and although the crossfading is much, much cleaner, at times there's still a short "blip" like distortion that's hardly louder than the musical material surrounding it. So, no volume surge, but still perceptible if that's what one is looking for.

In the HiFiBerry bug tracker thread one more user chimed in with a similar but even more severe issue. On similar hardware, but different software he experiences similar volume surge and/or distortion on every forced next/previous song change.
