### ISSUE TITLE
Playing queue gets out of sync

### ISSUE THREAD

**Issue by MarSOnEarth** [LMS-Community/slimserver#414]
This seems to be caused by playlist items becoming "invisible" (they are not displayed in the Playing Queue, though the playlist does not appear to be corrupted, and the item does exist on the filesystem).

Not all encoutered instances can be attributed to any single cause, but it has been observed to happen when deleting/moving around items in the Playing Queue.

Here's a link to the relevant thread: https://forums.slimdevices.com/showthread.php?109624-Announce-Material-Skin&p=987125&viewfull=1#post987125

Thank you

**Comment by michaelherger** [comment]
Unfortunately I still haven't found a way to reproduce this. Other users have mentioned that failure to read a file because eg. the disk wouldn't spin up fast enough etc. did trigger this. Do you have a reliable way to reproduce this issue?

**Comment by MarSOnEarth** [comment]
Thank you Michael for looking into this. Since I posted about having encountered this issue, I had deleted LMS DB files and re-indexed my library, so today, while trying to get more information for you, I looked again at that playlist I used as example for my original reporting, and the problem I documented there has disappeared. I hope even this may be useful to you.

As I use/manipulate playlists a lot ("live", in the Playing Queue), that's where I noticed this off-by-one (or more?) getting out of sync issue. FYI, my "workflow" starts with a MusicIP playlist which I then extensively edit by playing (with crossfading on) tune transitions and I move songs around looking for a better beat/tempo/mood matches, and that involves rapid play->go to last few seconds->let it play into the next tune->stop->move a tune up or down->and repeat again. Even though this editing happens on a SSD based system, I suspect that this whole start/stop/move/play-again must stress the whole chain of moving parts that's involved, especially that, as I understand parts of it are single threaded.

Michael, I'll be on the lookout and I'll report it here should this happen again on a new playlist, but as of now this is all I can add to what I already documented.

Thanks again.

**Comment by mherger** [comment]
Is this still an issue?

**Comment by MarSOnEarth** [comment]
Hi Michael,

Thank you for your follow up. The issue has been solved.


P.S. Sorry for such late reply. Your query went to my spam folder.

**Comment by mherger** [comment]
Thanks!
