### ISSUE TITLE
8.0  ~1599249040_arm server dies on Raspberry PI (Raspbian Buster)

### ISSUE THREAD

**Issue by edegroot-nl** [LMS-Community/slimserver#418]
Before this update everything was fine.. changed back to 7.9.4.

sudo /usr/sbin/squeezeboxserver --d_startup
Found SELinux - setting security context to: texrel_shlib_t for *.so files.
Got @INC containing:
/usr/share/squeezeboxserver/CPAN
/usr/share/squeezeboxserver
/usr/sbin
/etc/perl
/usr/local/lib/arm-linux-gnueabihf/perl/5.28.1
/usr/local/share/perl/5.28.1
/usr/lib/arm-linux-gnueabihf/perl5/5.28
/usr/share/perl5
/usr/lib/arm-linux-gnueabihf/perl/5.28
/usr/share/perl/5.28
/usr/local/lib/site_perl
/usr/lib/arm-linux-gnueabihf/perl-base

Extended @INC to contain:
/usr/share/squeezeboxserver/CPAN/arch/5.28/arm-linux-gnueabihf-thread-multi-64int
/usr/share/squeezeboxserver/CPAN/arch/5.28/arm-linux-gnueabihf-thread-multi-64int/auto
/usr/share/squeezeboxserver/CPAN/arch/5.28.1/arm-linux-gnueabihf-thread-multi-64int
/usr/share/squeezeboxserver/CPAN/arch/5.28.1/arm-linux-gnueabihf-thread-multi-64int/auto
/usr/share/squeezeboxserver/CPAN/arch/5.28/arm-linux-gnueabihf-thread-multi-64int
/usr/share/squeezeboxserver/CPAN/arch/5.28/arm-linux-gnueabihf-thread-multi-64int/auto
/usr/share/squeezeboxserver/CPAN/arch/arm-linux-gnueabihf-thread-multi-64int
/usr/share/squeezeboxserver/CPAN/arch/5.28
/usr/share/squeezeboxserver/lib
/usr/share/squeezeboxserver/CPAN
/usr/share/squeezeboxserver
/usr/share/squeezeboxserver/CPAN
/usr/share/squeezeboxserver
/usr/sbin
/etc/perl
/usr/local/lib/arm-linux-gnueabihf/perl/5.28.1
/usr/local/share/perl/5.28.1
/usr/lib/arm-linux-gnueabihf/perl5/5.28
/usr/share/perl5
/usr/lib/arm-linux-gnueabihf/perl/5.28
/usr/share/perl/5.28
/usr/local/lib/site_perl
/usr/lib/arm-linux-gnueabihf/perl-base

Loaded module: [version] ok!
Loaded module: [Time::HiRes] ok!
Loaded module: [DBI] ok!
Loaded module: [EV] ok!
Loaded module: [XML::Parser::Expat] ok!
Loaded module: [HTML::Parser] ok!
Loaded module: [JSON::XS] ok!
Loaded module: [Digest::SHA1] ok!
Loaded module: [YAML::XS] ok!
Loaded module: [Sub::Name] ok!
The following modules are loaded after the first attempt:
	File/Spec.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/File/Spec.pm
	Time/HiRes.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Time/HiRes.pm
	Digest/base.pm => /usr/share/squeezeboxserver/CPAN/Digest/base.pm
	common/sense.pm => /usr/share/squeezeboxserver/CPAN/common/sense.pm
	vars.pm => /usr/share/perl/5.28/vars.pm
	B/Deparse.pm => /usr/share/perl/5.28/B/Deparse.pm
	POSIX.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/POSIX.pm
	File/Path.pm => /usr/share/perl/5.28/File/Path.pm
	Getopt/Long.pm => /usr/share/perl/5.28/Getopt/Long.pm
	overloading.pm => /usr/share/perl/5.28/overloading.pm
	re.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/re.pm
	overload.pm => /usr/share/perl/5.28/overload.pm
	strict.pm => /usr/share/perl/5.28/strict.pm
	Digest/SHA1.pm => /usr/share/squeezeboxserver/CPAN/Digest/SHA1.pm
	Fcntl.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Fcntl.pm
	EV.pm => /usr/share/squeezeboxserver/CPAN/EV.pm
	attributes.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/attributes.pm
	HTML/Parser.pm => /usr/share/squeezeboxserver/CPAN/HTML/Parser.pm
	File/Spec/Unix.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/File/Spec/Unix.pm
	Scalar/Util.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Scalar/Util.pm
	Exporter.pm => /usr/share/perl/5.28/Exporter.pm
	B/Op_private.pm => /usr/share/perl/5.28/B/Op_private.pm
	Slim/Utils/OS/Linux.pm => /usr/share/perl5/Slim/Utils/OS/Linux.pm
	YAML/XS/LibYAML.pm => /usr/share/squeezeboxserver/CPAN/YAML/XS/LibYAML.pm
	version/regex.pm => /usr/share/squeezeboxserver/CPAN/version/regex.pm
	base.pm => /usr/share/perl/5.28/base.pm
	XSLoader.pm => /usr/share/perl/5.28/XSLoader.pm
	Cwd.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Cwd.pm
	if.pm => /usr/share/perl/5.28/if.pm
	DynaLoader.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/DynaLoader.pm
	Slim/Utils/OS/Debian.pm => /usr/share/perl5/Slim/Utils/OS/Debian.pm
	warnings.pm => /usr/share/perl/5.28/warnings.pm
	constant.pm => /usr/share/perl/5.28/constant.pm
	B.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/B.pm
	locale.pm => /usr/share/perl/5.28/locale.pm
	warnings/register.pm => /usr/share/perl/5.28/warnings/register.pm
	feature.pm => /usr/share/perl/5.28/feature.pm
	version/vpp.pm => /usr/share/squeezeboxserver/CPAN/version/vpp.pm
	JSON/XS.pm => /usr/share/squeezeboxserver/CPAN/arch/5.28/JSON/XS.pm
	Slim/bootstrap.pm => /usr/share/perl5/Slim/bootstrap.pm
	DBI.pm => /usr/share/squeezeboxserver/CPAN/arch/5.28/DBI.pm
	Sub/Name.pm => /usr/share/squeezeboxserver/CPAN/Sub/Name.pm
	Config_git.pl => /usr/lib/arm-linux-gnueabihf/perl/5.28/Config_git.pl
	Carp.pm => /usr/share/perl/5.28/Carp.pm
	YAML/XS.pm => /usr/share/squeezeboxserver/CPAN/YAML/XS.pm
	File/Spec/Functions.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/File/Spec/Functions.pm
	Slim/Utils/OS.pm => /usr/share/perl5/Slim/Utils/OS.pm
	Config.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Config.pm
	Exporter/Heavy.pm => /usr/share/perl/5.28/Exporter/Heavy.pm
	Symbol.pm => /usr/share/perl/5.28/Symbol.pm
	HTML/Entities.pm => /usr/share/squeezeboxserver/CPAN/HTML/Entities.pm
	File/Basename.pm => /usr/share/perl/5.28/File/Basename.pm
	Config_heavy.pl => /usr/lib/arm-linux-gnueabihf/perl/5.28/Config_heavy.pl
	XML/Parser/Expat.pm => /usr/share/squeezeboxserver/CPAN/XML/Parser/Expat.pm
	version.pm => /usr/share/squeezeboxserver/CPAN/version.pm
	List/Util.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/List/Util.pm
	lib.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/lib.pm
	Slim/Utils/OSDetect.pm => /usr/share/perl5/Slim/Utils/OSDetect.pm
	Slim/Utils/OS/Unix.pm => /usr/share/perl5/Slim/Utils/OS/Unix.pm
	FindBin.pm => /usr/share/perl/5.28/FindBin.pm
	Tie/Hash.pm => /usr/share/perl/5.28/Tie/Hash.pm

The following modules are loaded after the second attempt:
	File/Spec.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/File/Spec.pm
	Time/HiRes.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Time/HiRes.pm
	Digest/base.pm => /usr/share/squeezeboxserver/CPAN/Digest/base.pm
	common/sense.pm => /usr/share/squeezeboxserver/CPAN/common/sense.pm
	vars.pm => /usr/share/perl/5.28/vars.pm
	B/Deparse.pm => /usr/share/perl/5.28/B/Deparse.pm
	POSIX.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/POSIX.pm
	File/Path.pm => /usr/share/perl/5.28/File/Path.pm
	Getopt/Long.pm => /usr/share/perl/5.28/Getopt/Long.pm
	overloading.pm => /usr/share/perl/5.28/overloading.pm
	re.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/re.pm
	overload.pm => /usr/share/perl/5.28/overload.pm
	strict.pm => /usr/share/perl/5.28/strict.pm
	Digest/SHA1.pm => /usr/share/squeezeboxserver/CPAN/Digest/SHA1.pm
	Fcntl.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Fcntl.pm
	EV.pm => /usr/share/squeezeboxserver/CPAN/EV.pm
	attributes.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/attributes.pm
	HTML/Parser.pm => /usr/share/squeezeboxserver/CPAN/HTML/Parser.pm
	File/Spec/Unix.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/File/Spec/Unix.pm
	Scalar/Util.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Scalar/Util.pm
	Exporter.pm => /usr/share/perl/5.28/Exporter.pm
	B/Op_private.pm => /usr/share/perl/5.28/B/Op_private.pm
	Slim/Utils/OS/Linux.pm => /usr/share/perl5/Slim/Utils/OS/Linux.pm
	YAML/XS/LibYAML.pm => /usr/share/squeezeboxserver/CPAN/YAML/XS/LibYAML.pm
	version/regex.pm => /usr/share/squeezeboxserver/CPAN/version/regex.pm
	base.pm => /usr/share/perl/5.28/base.pm
	XSLoader.pm => /usr/share/perl/5.28/XSLoader.pm
	Cwd.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Cwd.pm
	if.pm => /usr/share/perl/5.28/if.pm
	DynaLoader.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/DynaLoader.pm
	Slim/Utils/OS/Debian.pm => /usr/share/perl5/Slim/Utils/OS/Debian.pm
	warnings.pm => /usr/share/perl/5.28/warnings.pm
	constant.pm => /usr/share/perl/5.28/constant.pm
	B.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/B.pm
	locale.pm => /usr/share/perl/5.28/locale.pm
	warnings/register.pm => /usr/share/perl/5.28/warnings/register.pm
	feature.pm => /usr/share/perl/5.28/feature.pm
	version/vpp.pm => /usr/share/squeezeboxserver/CPAN/version/vpp.pm
	JSON/XS.pm => /usr/share/squeezeboxserver/CPAN/arch/5.28/JSON/XS.pm
	Slim/bootstrap.pm => /usr/share/perl5/Slim/bootstrap.pm
	DBI.pm => /usr/share/squeezeboxserver/CPAN/arch/5.28/DBI.pm
	Sub/Name.pm => /usr/share/squeezeboxserver/CPAN/Sub/Name.pm
	Config_git.pl => /usr/lib/arm-linux-gnueabihf/perl/5.28/Config_git.pl
	Carp.pm => /usr/share/perl/5.28/Carp.pm
	YAML/XS.pm => /usr/share/squeezeboxserver/CPAN/YAML/XS.pm
	File/Spec/Functions.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/File/Spec/Functions.pm
	Slim/Utils/OS.pm => /usr/share/perl5/Slim/Utils/OS.pm
	Config.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/Config.pm
	Exporter/Heavy.pm => /usr/share/perl/5.28/Exporter/Heavy.pm
	Symbol.pm => /usr/share/perl/5.28/Symbol.pm
	HTML/Entities.pm => /usr/share/squeezeboxserver/CPAN/HTML/Entities.pm
	File/Basename.pm => /usr/share/perl/5.28/File/Basename.pm
	Config_heavy.pl => /usr/lib/arm-linux-gnueabihf/perl/5.28/Config_heavy.pl
	XML/Parser/Expat.pm => /usr/share/squeezeboxserver/CPAN/XML/Parser/Expat.pm
	version.pm => /usr/share/squeezeboxserver/CPAN/version.pm
	List/Util.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/List/Util.pm
	lib.pm => /usr/lib/arm-linux-gnueabihf/perl/5.28/lib.pm
	Slim/Utils/OSDetect.pm => /usr/share/perl5/Slim/Utils/OSDetect.pm
	Slim/Utils/OS/Unix.pm => /usr/share/perl5/Slim/Utils/OS/Unix.pm
	FindBin.pm => /usr/share/perl/5.28/FindBin.pm
	Tie/Hash.pm => /usr/share/perl/5.28/Tie/Hash.pm

syntax error at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 577, near ")
			if"
syntax error at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 583, near "elsif"
Global symbol "$header" requires explicit package name (did you forget to declare "my $header"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 583.
Global symbol "$metaint" requires explicit package name (did you forget to declare "my $metaint"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 584.
Global symbol "$header" requires explicit package name (did you forget to declare "my $header"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 587.
Global symbol "$redir" requires explicit package name (did you forget to declare "my $redir"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 588.
Global symbol "$header" requires explicit package name (did you forget to declare "my $header"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 591.
Global symbol "$contentType" requires explicit package name (did you forget to declare "my $contentType"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 592.
Global symbol "$header" requires explicit package name (did you forget to declare "my $header"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 595.
Global symbol "$length" requires explicit package name (did you forget to declare "my $length"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 596.
Global symbol "$header" requires explicit package name (did you forget to declare "my $header"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 599.
Global symbol "$rangeLength" requires explicit package name (did you forget to declare "my $rangeLength"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 600.
Global symbol "$startOffset" requires explicit package name (did you forget to declare "my $startOffset"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 601.
Global symbol "$self" requires explicit package name (did you forget to declare "my $self"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 602.
Global symbol "$self" requires explicit package name (did you forget to declare "my $self"?) at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 602.
syntax error at /usr/share/perl5/Slim/Player/Protocols/HTTP.pm line 603, near "}"
/usr/share/perl5/Slim/Player/Protocols/HTTP.pm has too many errors.
Compilation failed in require at /usr/share/perl5/Slim/Formats/XML.pm line 21.
BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Formats/XML.pm line 21.
Compilation failed in require at /usr/share/perl5/Slim/Buttons/XMLBrowser.pm line 27.
BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Buttons/XMLBrowser.pm line 27.
Compilation failed in require at /usr/share/perl5/Slim/Buttons/Common.pm line 43.
BEGIN failed--compilation aborted at /usr/share/perl5/Slim/Buttons/Common.pm line 43.
Compilation failed in require at /usr/sbin/squeezeboxserver line 235.
BEGIN failed--compilation aborted at /usr/sbin/squeezeboxserver line 235.

**Comment by michaelherger** [comment]
Please update to the latest nightly build.

**Comment by edegroot-nl** [comment]
thanks
