### ISSUE TITLE
Slimserver-vendor compilation on FreeBSD

### ISSUE THREAD

**Issue by NikolajHansen** [LMS-Community/slimserver#42]
I had to edit the build file a bit to compile on FreeBSD.
1. libz cannot be found even if installed manually.
2. The patches from OSX had to be applied on FreeBSD as well (builtin conflict with clang / llvm).

See the edited build file here http://pastebin.com/fXRurGLP

**Comment by mherger** [comment]
Could you please send a pull request?

**Comment by phaethon** [comment]
Did not notice this issue earlier and reinvented the wheel ;). BarnabasDK, can you check the buildme.sh from py Pull request? I fixed some similar issues in mine: https://github.com/phaethon/slimserver-vendor/blob/public/7.9/CPAN/buildme.sh
And, mherger, now there is a pull request on slimserver-vendor repo.

Also, libmediascan has serious issues with FreeBSD. There is some logic, which checks whether os is OSX, Linux or Win, leaving everybody else (e.g. FreeBSD) excluded. I am now looking into that. mherger, should submit fixes as a change to libmediascan or as a patch file/buildme.sh change for slimserver-vendor?

**Comment by phaethon** [comment]
I created a pull request for libmediascan, but I am not sure if anybody follows that code anymore. It fixes scanning of pictures and videos for FreeBSD. Without this patch it does not scan those files at all.
https://github.com/andygrundman/libmediascan/pull/3

**Comment by mherger** [comment]
@phaethon - Please see my comment in your pull request

**Comment by NikolajHansen** [comment]
Sorry for the late reply, for some reason the mails for this thread only started ticking in yesterday.

I have two issues - one not really important for the build a such.

1) I build in a freebsd jail, and on a jail you have no localhost interface. That makes some of the tests fail since they use this. I just build with -t.

2) The linker produces the following error

CPAN/build/include/../lib/libdb.a   -lm -lz -lintl
/usr/bin/ld: /root/logitech/slimserver-vendor/CPAN/build/include/../lib/libavcod
ec.a(deinterlace.o): relocation R_X86_64_PC32 against `ff_pw_4' can not be used 
when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
cc: error: linker command failed with exit code 1 (use -v to see invocation)
**\* Error code 1

Stop.
make: stopped in /root/logitech/slimserver-vendor/CPAN/libmediascan-0.1/bindings
/perl
make failed, aborting

maybe just give it the build argument it asks for?

**Comment by phaethon** [comment]
On 2), this is the flag that helped me with the issue, so I changed the respective place in buildme.sh. My ARCH is amd64-freebsd-thread-multi. What is your ARCH (as calculated by script)? If it is different, we likely just have to add it here.
    if [ "$ARCH" = "x86_64-linux-thread-multi" -o "$ARCH" = "amd64-freebsd-thread-multi" ]; then
        FFOPTS="$FFOPTS --disable-mmx"
    fi
I assume you did a clean rebuild of ffmpeg with the builme.sh. Otherwise, that could be the issue.

**Comment by NikolajHansen** [comment]
Yes, I deleted the build artifact folder completely.

the following script 

root@squeezebox:/root/logitech/slimserver-vendor/CPAN # cat arch.sh 
#!/bin/sh
ARCH=$(/usr/bin/perl -MConfig -le 'print $Config{archname}' | sed 's/gnu-//' | sed 's/^i[3456]86-/i386-/' | sed 's/armv5tejl/arm/')

echo $ARCH

outputs

root@squeezebox:/root/logitech/slimserver-vendor/CPAN # ./arch.sh
amd64-freebsd

**Comment by phaethon** [comment]
Interesting. Which FreeBSD version you have? I have 10.1 and I get amd64-freebsd-thread-multi
Anyway, try changing above code in buildme.sh (around line 1192) to:
if [ "$ARCH" = "x86_64-linux-thread-multi" -o "$ARCH" = "amd64-freebsd-thread-multi" -o "$ARCH" = "amd64-freebsd" ]; then
FFOPTS="$FFOPTS --disable-mmx"
fi

and try again.

**Comment by NikolajHansen** [comment]
You are right. This seems to be another jail issue.

(12:38:10 <nikolaj@atlas:~>) $ uname -a
FreeBSD atlas.barnabas.dk 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
(12:38:36 <nikolaj@atlas:~>) $ /area51/jails/squeezebox.barnabas.dk/root/logite
ch/slimserver-vendor/CPAN/arch.sh 
amd64-freebsd-thread-multi

If I am to build on the root host I have to install all of the build dependencies in that context, and I would rather not. I actually think you script works now and the rest of the issues tie to the fact I am using a chrooted context.

Thanks!
