### ISSUE TITLE
LMS Deezer plugin only shows a max of 399 entries for huge playlists 

### ISSUE THREAD

**Issue by ransome1** [LMS-Community/slimserver#423]
Hi there.

I am not sure if this is really related to LMS or just a problem with the Deezer plugin. But for the latter I can't find a Git project so I hope you guys can help me on this one.

So I have these huge playlists for playing 24/7. It consists of more than 1.400 items and it is a Deezer playlist. I am using the Deezer plugin on LMS which is provided by mysqueezebox.com. 
![Bildschirmfoto_2020-09-23_08-29-00](https://user-images.githubusercontent.com/11188741/93975672-12b55d00-fd78-11ea-8482-15f51e729a7f.png)

Playing the list on Deezer itself it works fine with all those songs, but playing the exact same list through my LMS, it only loads 399 songs. That happens with other Deezer playlists too. 
![Bildschirmfoto_2020-09-23_08-28-01](https://user-images.githubusercontent.com/11188741/93975668-121cc680-fd78-11ea-93ae-386fc394cbdf.png)

And I would say that a limitation of 399 looks suspiciously like a limitation by configuration. Although I just can't find anything useful on this and I hope it's not hard coded somewhere. 

Can anybody give me a hint on this and maybe clarify if this might be a bug?

Thanks so much
ran

**Comment by michaelherger** [comment]
We usually do indeed limit the number of results, as the APIs have limitations in how many results we can get in one request. I don't know the details for Deezer off the top of my head. But often this is like 50 items per request. Which means we'd have to run dozens of calls to cover a playlist the size of yours. Which in turn the service would not like us to do. Therefore these deliberate limitations.

**Comment by ransome1** [comment]
Ok, that I understand. Though it doesn't make me happy ;)
