### ISSUE TITLE
LMS running on macOS cannot access files on attached volumes

### ISSUE THREAD

**Issue by darylfoster** [LMS-Community/slimserver#428]
I am running the Logitech Media Server on my iMac. The media is on a separate network drive. After a recent macOS upgrade, LMS is no longer able to access the files on the network drive.

I can view the files in the Finder. They are in the path: /Volumes/Public/Shared Music/
<img width="793" alt="Screen Shot 2020-09-27 at 1 58 08 PM" src="https://user-images.githubusercontent.com/4106905/94486826-f2d5cd00-01ad-11eb-89b1-c4d802ed2b81.png">

However when I access the LMS settings in a browser, I go to Basic Settings -> Media Folders -> Browse, but I do not see any sub folders under the /Volumes/Public folder.
<img width="1000" alt="Screen Shot 2020-09-28 at 11 21 12 AM" src="https://user-images.githubusercontent.com/4106905/94486845-fc5f3500-01ad-11eb-86eb-a3e28be797da.png">

**Comment by michaelherger** [comment]
You need to grant perl5.18 full disk access. Go to Privacy settings to drag'n'drop it from Finder. You might need to 
un-hide system folders (Cmd + Shift + . (dot)) to see it in `/use/bin`

**Comment by darylfoster** [comment]
@michaelherger Thank you for your response. I was able to get LMS working, but I had to do something slightly different from what you suggested.
I'm running macOS Catalina version 10.15.7. This machine has 3 versions of the perl executable in the `/usr/bin` directory: `perl`, `perl5.18`, `perl5.28`.
When I run `perl -version` it says I am running v5.18.4, which is the same result I get when I run `perl5.18 -version`. I had already given the `perl` executable full disk access. So I stopped the LMS service and started it from the command line using `perl` instead of `perl5.18`. When I did that, everything worked.

I then gave `perl5.18` full disk access:
<img width="663" alt="Screen Shot 2020-09-29 at 9 23 58 AM" src="https://user-images.githubusercontent.com/4106905/94568669-ccaa3e80-023a-11eb-940c-a52c5d477776.png">

I then stopped LMS and restarted it in the normal manner from the System Preferences, but LMS could no longer access the contents of the Public volume.

**Comment by michaelherger** [comment]
What LMS version are you running? Make sure you're using a recent build.

**Comment by darylfoster** [comment]
Logitech Media Server Version: 8.0.0 - 1601129375

**Comment by mherger** [comment]
Are you still seeing this issue?

There's a lot of information in this discussion: http://forums.slimdevices.com/showthread.php?t=111037

**Comment by darylfoster** [comment]
@mherger, thank you for getting back with me. I upgraded LMS to version 8.0.0 - 1601590552 a few days ago, and that seems to have solved my issue.

**Comment by darylfoster** [comment]
Today I upgraded LMS to version 8.0.0 - 1602925693, and the issue has returned.

**Comment by mherger** [comment]
Recent discussion around this topic suggested that the problem might be related to the startup options: with "start LMS with system" things wouldn't work, while if started manually or "when user signs in" would work. Can you confirm?
