### ISSUE TITLE
Version 7.9.4-1601565762 server not recognized by player

### ISSUE THREAD

**Issue by jwb-sqadict** [LMS-Community/slimserver#433]
I have 3 PC's running the slimserver software. After the updat to version 7.9.4-1601565762 the player (2x Touch, 1x Duet) can't connect anymore to the server. Furthermore if I use the webcontrol it does not see any player.
Current solution I went back to version  7.9.4-1600144323 that runs flawless.
Jan Broenink

**Comment by michaelherger** [comment]
Please join the community on forums.slimdevices.com to further discuss this issue. It's most likely some temporary hiccup, rather than an issue with this build. Please post there more information about the system your running LMS on etc.
