### ISSUE TITLE
Logitec Media Server does not install/run correctly on Ubuntu 20.04

### ISSUE THREAD

**Issue by durgadas311** [LMS-Community/slimserver#436]
I had been running LMS on Ubuntu 18.04, then upgraded to 20.04 and that installation failed. I have un-installed and re-installed many times, trying both 7.9.3 and the latest build 8.0.0~1601590552.

One thing I notice is that certain files are not getting installed, even though 'dpkg' lists them. Most noticeably, the files:
```
/etc/logrotate.d/logitechmediaserver
/etc/init.d/logitechmediaserver
/etc/squeezeboxserver/modules.conf
/etc/default/logitechmediaserver
```
If I fumble around and try to start the server manually, I see this error:
```
modules.conf not found at /usr/share/perl5/Slim/bootstrap.pm line 353.
BEGIN failed--compilation aborted at /usr/sbin/squeezeboxserver line 178.
```
Which is not surprising, given the missing files. If I manually install those four files, I get further but still not functional:
```
# /usr/sbin/squeezeboxserver --prefsdir /var/lib/squeezeboxserver/prefs --logdir /var/log/squeezeboxserver/ --cachedir /var/lib/squeezeboxserver/cache --charset=utf8
dirsFor: Didn't find a match request: [scprefs]
[20-10-11 08:58:51.1828] main::init (388) Starting Logitech Media Server (v8.0.0, 1601590552, Fri Oct  2 01:03:07 CEST 2020) perl 5.030000 - x86_64-linux-gnu-thread-multi
dirsFor: Didn't find a match request: [videos]
dirsFor: Didn't find a match request: [pictures]
[20-10-11 08:58:51.1893] main::changeEffectiveUserAndGroup (1005) Warning: Logitech Media Server must not be run as root!  Trying user squeezeboxserver instead.
[20-10-11 08:58:52.2364] Slim::Utils::SQLiteHelper::postConnect (377) Optimizing DB because of missing or empty sqlite_stat1 table
[20-10-11 08:58:52.3433] Slim::Schema::forceCommit (2157) Warning: Trying to commit transactions before DB is initialized!
[20-10-11 08:58:52.6884] Slim::Utils::SQLiteHelper::postConnect (377) Optimizing DB because of missing or empty sqlite_stat1 table
[20-10-11 08:58:52.7954] Slim::Schema::forceCommit (2157) Warning: Trying to commit transactions before DB is initialized!
Can't call method "log" on an undefined value at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender.pm line 189.
Can't call method "log" on an undefined value at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender.pm line 189.
```
If I use "/etc/init.d/logitechmediaserver start" I get basically the same thing, in "/var/log/squeezeboxserver/server.log":
```
[20-10-11 08:58:51.1829] main::init (388) Starting Logitech Media Server (v8.0.0, 1601590552, Fri Oct  2 01:03:07 CEST 2020) perl 5.030000 - x86_64-linux-gnu-thread-multi
[20-10-11 08:58:51.1894] main::changeEffectiveUserAndGroup (1005) Warning: Logitech Media Server must not be run as root!  Trying user squeezeboxserver instead.
[20-10-11 08:58:52.2365] Slim::Utils::SQLiteHelper::postConnect (377) Optimizing DB because of missing or empty sqlite_stat1 table
[20-10-11 08:58:52.3434] Slim::Schema::forceCommit (2157) Warning: Trying to commit transactions before DB is initialized!
[20-10-11 08:58:52.6885] Slim::Utils::SQLiteHelper::postConnect (377) Optimizing DB because of missing or empty sqlite_stat1 table
[20-10-11 08:58:52.7955] Slim::Schema::forceCommit (2157) Warning: Trying to commit transactions before DB is initialized!
```
I'm not sure why the DB is not initialized. I do have SQLite installed (libsqlite3-0:amd64 3.31.1-4ubuntu0.2)

So, I see a problem with the "debian installer" scripts/packaging, plus I can't seem to make this work on Ubuntu 20.04. Possibly these two are related (DB initialization would be part of install?).

**Comment by tmancill** [comment]
Interesting.  I run LMS inside a Docker container and recently switched from running on `debian:stretch` to `ubuntu:20.04` and didn't run into any issues.   I rebuilt the container just now to verified that the build is pulling `logitechmediaserver_8.0.0~1601590552_all.deb` and all is working as expected.

In case it gives you any ideas, here's the Dockerfile.  There's not much happening here except for the installation of a few dependencies and the step where it renames the URL fetched from mysqueezebox.com from `_all.deb` -> `_amd64.deb` before fetching the binary .deb package.

```dockerfile
FROM ubuntu:20.04

ENV SQUEEZE_VOL /srv/squeezebox
ENV HOME=/usr/share/squeezeboxserver
ENV LANG C.UTF-8
ARG DEBIAN_FRONTEND=noninteractive
ARG PACKAGE_VERSION_URL=http://www.mysqueezebox.com/update/?version=8.0.0&revision=1&geturl=1&os=deb

RUN apt-get -y update \
	&& apt-get -y upgrade \
	&& apt-get -y --no-install-recommends install sudo curl wget flac faad lame sox libsox-fmt-all libio-socket-ssl-perl libio-socket-ssl-perl ffmpeg ca-certificates \
	&& url=$(curl "$PACKAGE_VERSION_URL" | sed 's/_all\.deb/_amd64\.deb/') \
	&& curl -Lsf -o /tmp/logitechmediaserver.deb $url \
	&& dpkg -i /tmp/logitechmediaserver.deb \
	&& rm -f /tmp/logitechmediaserver.deb \
	&& apt-get clean

VOLUME $SQUEEZE_VOL
EXPOSE 3483 3483/udp 9000 9090 5353

#COPY custom-convert.conf /etc/squeezeboxserver
COPY start-lms.sh /start-lms.sh
RUN chmod 755 /start-lms.sh
CMD ["/start-lms.sh"]
```

If you want to go the Docker container route, the startup mechanism I'm using is to have a systemd unit file exec the `run-lms-container.sh` script (below), which in turn runs `start-lms.sh` as the entrypoint in the container.  The setup works well for me.

### start-lms.sh

```sh
#!/bin/sh

if [ "$SQUEEZE_VOL" ] && [ -d "$SQUEEZE_VOL" ]; then
	for subdir in prefs logs cache; do
		mkdir -p $SQUEEZE_VOL/$subdir
		chown -R squeezeboxserver:nogroup $SQUEEZE_VOL/$subdir
	done
fi

exec sudo -u squeezeboxserver -E squeezeboxserver \
	--prefsdir $SQUEEZE_VOL/prefs \
	--logdir $SQUEEZE_VOL/logs \
	--cachedir $SQUEEZE_VOL/cache "$@"
```

### run-lms-container.sh

```sh
#!/bin/bash

NAME=$(hostname)
docker run -p 9000:9000 \
           -p 3483:3483 \
           -p 3483:3483/udp \
           -p 5353:5353 \
           -p 9090:9090 \
           -v /etc/localtime:/etc/localtime:ro \
           -v /srv/squeezebox:/srv/squeezebox \
           -v /data/Music:/srv/music \
           -e "HOSTNAME=${NAME}" \
           -h ${NAME} \
           --name "${NAME}-lms" \
           --net host \
           --rm \
           lms:latest
```

**Comment by durgadas311** [comment]
I was able to get running by doing some cleanup and manually starting the server as the 'squeezeboxserver' user.

The install was still broken, so that should be fixed. I don't know why those 4 files were not getting installed, but that also prevents the auto-start of the server and the "installing" of the symlinks so that it will start on every reboot.

**Comment by michaelherger** [comment]
There's some good information in this thread: https://forums.slimdevices.com/showthread.php?112185

**Comment by durgadas311** [comment]
> There's some good information in this thread: https://forums.slimdevices.com/showthread.php?112185

I had seen that thread, but it did not help my case. There seems to be a lot of variability in how/whether the install works.

**Comment by mw9** [comment]
> I was able to get running by doing some cleanup and manually starting the server as the 'squeezeboxserver' user.
> 
> The install was still broken, so that should be fixed. I don't know why those 4 files were not getting installed, but that also prevents the auto-start of the server and the "installing" of the symlinks so that it will start on every reboot.

The four files listed are all "configuration" files. The debian installer is treating these specially - it will not install them or overwrite them if the user has already modified them, or even deleted them. (User knows best ?)

So I'm wondering if these files had been inadvertently deleted before upgrading LMS.
Here's some information:
https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html

Addendum:
`dpkg --install --force-confmiss` might be helpful in these circumstances.

**Comment by durgadas311** [comment]
I tried various types of install (but did not know about "dpkg --install --force-confmiss"), and they were all scratch install, usually preceded by search-and-destroy on any LMS related files. It's not clear to me why dpkg would have avoided installing those files, especially since they did not exist.

**Comment by mw9** [comment]
@durgadas311 

Section 5.1 in the offered link explains `dpkg`'s actions, see in particular the penultimate paragraph which refers to deleted configuration files.

The effect of having these files as "configuration" files allows the user to change them in whatever way he pleases, without having the installer subsequently overwrite his good work. That can be both a blessing and a curse.

If you want to ensure a clean install, always "purge" a previously installed package. Otherwise `dpkg` may assume that any modifications to the configuration files are to be retained. (There's more to it than that, there always is).

At this stage, I'd say that it is not self evident that the `dpkg` installer failed in any way. Perhaps it did, perhaps it didn't. I think you'd need to know the precise state of your system at the time the events took place to determine that.

There is an argument to be made that the installation process could be improved. Perhaps some of these files should not be classed as "configuration" files, and should just be replaced on every install/upgrade. And/or perhaps some "obvious error" checking could be introduced,  with an offer to fix.

But that would require modifications and additions to the existing package installation scripts, and someone, possessing Debian packaging knowledge, to keep it maintained. It may be very straightforward. There again, it may add unwanted complexity. Something to chew on.

For my future reference, the "configuration" files are:

```
# dpkg -s logitechmediaserver
Package: logitechmediaserver
Status: install ok installed
<snip>
Conffiles:
 /etc/default/logitechmediaserver d3cb9f46768fef3a368e86dd0840597c
 /etc/init.d/logitechmediaserver 8e88164cdf663989c9cf7092658e1900
 /etc/logrotate.d/logitechmediaserver 1e1e60b156a199052fdfdea28868ad80
 /etc/squeezeboxserver/convert.conf 0981846ce7b392e763f919350a4dbf13
 /etc/squeezeboxserver/modules.conf a5198bdf4f2dca349d8babd029d90aba
 /etc/squeezeboxserver/types.conf 2f45a2c881956d9d2046472c72fd8f70
<snip>
````

**Comment by durgadas311** [comment]
I see, it is the dpkg (at al.) database that was telling the install that the files were intentionally deleted, so don't install them. So, by doing a search-and-destroy (without updating/purging the database) I actually created the problem.
