### ISSUE TITLE
New Music and Virtual Libraries

### ISSUE THREAD

**Issue by CDrummond** [LMS-Community/slimserver#437]
When Material is listing "New Music" it uses the following JSONRPC command:

```
["albums",0,25000,"sort:new","tags:ajlsyKSE","menu:1","library_id:LIBRARYID"]
```

It appears as if LMS filters the returned items using library_id **after** obtaining the 100 newest albums. Therefore, if all albums in library_id are older than the 100 newest, nothing is returned.

With the default UI, setting a library sets it per-player. In this instance the library_id is used correctly. i.e. LMS obtains the album in library_id, then gets the 100 newest.

Discussed on forum:
https://forums.slimdevices.com/showthread.php?111797-separate-libraries&p=969087&viewfull=1#post969087
https://forums.slimdevices.com/showthread.php?109624-Announce-Material-Skin&p=991166&viewfull=1#post991166

**Comment by mherger** [comment]
The albums query code indeed does cache using the client's `library_id` rather than the one passed as a parameter. 

Need to review whether similar corner-cases do exist in other queries, too.

**Comment by mherger** [comment]
@CDrummond did I ever address this issue?... I wanted to look into other cases. But did I fix this one?

**Comment by CDrummond** [comment]
@mherger Not as far as I can tell. Just tried the following, using Material Skin (as it does not set library on player):

1. Checked current 'New Music'
2. Performed advanced search to select an album no currently in 'New Music'
3. Created a virtual library from results
4. Changed to virtual library
5. Re-open 'New Music'
6. List is empty

**Comment by michaelherger** [comment]
I should leave notes about findings here. Because I must have looked into this before, decided not to do it right away, but didn't write down why. Now I have to start over. Stupid me.
