### ISSUE TITLE
Tidal - Error from cloudfront

### ISSUE THREAD

**Issue by tomcat24** [LMS-Community/slimserver#438]
I am unable to stream tidal. After going through the logs i find the below:

Cache-Control: no-cache
Connection: close
Accept: */*
Host: sp-pr-cf.audio.tidal.com
User-Agent: iTunes/4.7.1 (Windows; N; Windows 10; 8664; EN; cp1252) SqueezeCenter, Squeezebox Server, Logitech Media Server/7.9.3/1597753178
Icy-Metadata: 1

[20-10-16 13:12:17.2360] Slim::Control::Request::notify (2013) Notifying playlist open
[20-10-16 13:12:17.2364] Slim::Control::Request::notify (2051) Notifying Slim::Buttons::Playlist::knobPlaylistCallback of playlist open =~ [['playlist']]
[20-10-16 13:12:17.2367] Slim::Control::Request::notify (2051) Notifying Slim::Player::Playlist::modifyPlaylistCallback of playlist open =~ [['playlist']]
[20-10-16 13:12:17.2371] Slim::Control::Request::notifyFromArray (842) (prefset server currentSong 158)
[20-10-16 13:12:17.2377] Slim::Control::Request::notify (2013) Notifying playlist open
[20-10-16 13:12:17.2380] Slim::Control::Request::notify (2051) Notifying Slim::Buttons::Playlist::knobPlaylistCallback of playlist open =~ [['playlist']]
[20-10-16 13:12:17.2383] Slim::Control::Request::notify (2051) Notifying Slim::Player::Playlist::modifyPlaylistCallback of playlist open =~ [['playlist']]
[20-10-16 13:12:17.2388] Slim::Control::Request::notify (2013) Notifying prefset
[20-10-16 13:12:17.2391] Slim::Control::Request::notify (2051) Notifying Slim::Networking::SqueezeNetwork::PrefSync::prefEvent of prefset =~ [['prefset']]
[20-10-16 13:12:17.3417] Slim::Player::Squeezebox2::directHeaders (470) Processing headers for direct streaming:
HTTP/1.1 403 Forbidden
Server: CloudFront
Date: Fri, 16 Oct 2020 18:12:16 GMT
Content-Type: text/xml
Content-Length: 110
Connection: close
**X-Cache: Error from cloudfront****
Via: 1.1 98636d06a0d9ef7b80707f034d708434.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: IAH50-C4
X-Amz-Cf-Id: yCwwnck4ZhIFGQtcFAqt4Kxpl2pvTNv3Wdy-4tolh6UogCJSbP8euA==

[20-10-16 13:12:17.3422] Slim::Player::Squeezebox2::directHeaders (521) Invalid response code (403) from remote stream http://sp-pr-cf.audio.tidal.com/mediatracks/CAEaKRInMDY0Yzc1ZGE4NTcxZjc0NWE3NDhmZTU5NjU5YzQ4NDBfNjEubXA0/0.flac?Expires=1602875536&Signature=B1I~PwTZPOOuT7OU74eEmLEMfsdrNxP34caYaBCeizJ-eg75UuYUqc4RFwQEUL07v1XlzjiXDVRmSDNY8zD0nVKnMfPWGfO7cqc960cn60uGphpWOI4OTUnn3fGte-eGqxVgg3MyFRj2F-T4adT4bPKMAtdKOx7v77~~E7pcLW1H4nPb4iYGPBUxnyo883r-PS8ElWT9HIgccmmszoj1irPt1xjtgJzXX0TKTjORaaUmRRYnmTmMMhth4zoSn0jv2~1fbDfDSGzvtUdsMb4Uagkmuf-XTj2WIbgbwAgUlrnNnHu3eJjnVtzftWeBHE3-fCQdOr04aiNaCXUKEF75uw__&Key-Pair-Id=APKAIZ3WPBE4R6SP555A
[20-10-16 13:12:17.3424] Slim::Plugin::WiMP::ProtocolHandler::handleDirectError (114) Direct stream failed: [403] HTTP/1.1 403 Forbidden

**Comment by mherger** [comment]
Wow... that's very interesting! Thanks a lot for this data. I'll see whether I can get in touch with some TIDAL engineer ASAP.

**Comment by tomcat24** [comment]
Thanks, I am able to perform all other functions like search, view playlist albums etc. but when I try to stream/hit play it, no sound  and the tracks starts to skip in a loop. This started happening about 2 days back.

**Comment by swvalenti194** [comment]
Same exact issue as @tomcat24 , any resolution yet?

**Comment by michaelherger** [comment]
> Same exact issue as @tomcat24 , any resolution yet?

Where do you live? What OS you're running LMS on? What LMS version?

**Comment by swvalenti194** [comment]
NJ, USA

Operating system: Debian - EN - utf8
Platform Architecture: armv7l-linux
Perl Version: 5.24.1 - arm-linux-gnueabihf-thread-multi-64int
Audio::Scan: 1.02
IO::Socket::SSL: 2.044
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

Logitech Media Server Version: 8.0.0 - 1602796130
Player Model: SqueezeLite
Player Type: squeezelite
Firmware: Max2Play v1.0.2 based on v1.8.4-726

**Comment by marcelo-g-simas** [comment]
I believe this is the issue I am experiencing, upgraded to LMS 8.0 from 7.9.3 and kept seeing the same behavior.  Time frame matches @tomcat24's.

**Comment by marcelo-g-simas** [comment]
I am running on Ubuntu 20.04:

Logitech Media Server Version: 8.0.0 - 1602925693 @ Sat Oct 17 11:25:13 CEST 2020
Operating system: Debian - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.26.1 - x86_64-linux-gnu-thread-multi
Audio::Scan: 0.95
IO::Socket::SSL: 2.060
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

**Comment by michaelherger** [comment]
Turns out CloudFront would only accept https, but not http. And our players can't do https.

TIDAL uses a different cache in other parts of the world which does support http. That's why I can play TIDAL in CH, but not US.

**Comment by swvalenti194** [comment]
How come it worked in previous LMS versions?

**Comment by michaelherger** [comment]
This issue has nothing to do with any LMS version. It's a change in the TIDAL infrastructure which is not compatible with LMS. I can test those URLs outside LMS and am seeing the problem.

**Comment by swvalenti194** [comment]
Sooooo you're saying Tidal will be forever unsupported?

**Comment by marcelo-g-simas** [comment]
Any chance https support could be added or is this the end of the line for these players?

**Comment by tomcat24** [comment]
How is all other Tidal functionality working? why apply HTTPS selectively to streaming alone?

**Comment by tomcat24** [comment]
Also any idea on when Tidal switched to HTTPS? Tidal was working just fine 3 days back.

**Comment by marcelo-g-simas** [comment]
I think 3 days ago is when it broke.  Thursday morning for me.  Maybe if the LMS community were to approach TIDAL they could consider reverting this change?

There is a general push to have most http traffic moved over to https as it prevents man in the middle attacks and is generally more secure, that may be why TIDAL has started this move.  I suspect that over time they will do this to all of their APIs.

**Comment by michaelherger** [comment]
I've already sent them our findings so far. But I guess my contacts don't work on weekends...

**Comment by marcelo-g-simas** [comment]
> I've already sent them our findings so far. But I guess my contacts don't work on weekends...

Did you see my question about the feasibility of adding https support to the players?  Or maybe relay the streams through the LMS server so the server is streaming from https and then relaying that to the players over http (too hard?)...

**Comment by michaelherger** [comment]
SSL in players: nope. Proxying through LMS: done already.

**Comment by marcelo-g-simas** [comment]
So there is hope after all...

**Comment by tomcat24** [comment]
Michael, 
Tidal started working again.
Pandora stopped working now, error: client restricted due to licensing restriction(are you not in the US?).
Looks like to fix Tidal HTTPS situation you are connecting from outside the US which broke Pandora.

**Comment by swvalenti194** [comment]
Same happening here same error as @tomcat24

**Comment by tomcat24** [comment]
Michael,  Thank you for getting Tidal up and running.

**Comment by michaelherger** [comment]
You probably didn't see the other messages on forums and twitter: we have an outage in the US. Therefore all customers are re-directed to the EU datacenter while we bring the US back up. And that's why Pandora is complaining, too... Hopefully it'll all be over in a few hours, as TIDAL responded they'd turn off the enforced https again.

**Comment by tomcat24** [comment]
:-) Good news, thanks for the update.

**Comment by marcelo-g-simas** [comment]
Thanks, TIDAL is back here as well!

**Comment by gstalnaker** [comment]
Help with GitHub account settings...

At some point in the past I subscribed to some issue. It's long since been done. But I continue to receive notifications. But about ALL issues, etc. for LMS dev.

I've checked my GitHub account and there are no subscriptions or notifications set. And when I attempt to use the Unsubscribe link that is a part of the email notifications I get, GitHub tells me the what you see on the attached screens hot.

Anyone know how to "fix" this?

Thanks.[Image]


________________________________

**Comment by michaelherger** [comment]
> Help with GitHub account settings... 

Totally does not belong here... but anyway: at the top right you have an "eye" icon where you can "unwatch" a repository etc.

**Comment by tomcat24** [comment]
Tidal and Pandora is back to normal, thanks Michael for the help.

**Comment by michaelherger** [comment]
Great to hear, thanks!
