### ISSUE TITLE
Service repeatedly dies on startup (ReadyNas Duo sparc) 

### ISSUE THREAD

**Issue by oatsoda** [LMS-Community/slimserver#442]
Hi

I've had an instance of LMS running for years on my ReadyNas Duo sparc which yesterday suddenly decided to start playing up.  The NAS powers down overnight and automatically powers up in the morning.  Yesterday when the NAS powered up, the LMS failed to start up correctly.  I tried rebooting but with no luck.

After a clean install of LMS I got it back up and running.  However, the same again occurred today when the NAS powered up.

The /var/log/slimserver.log contains repeated:

>2020-10-21 08:34:43 Logitech Media Server died. Restarting.
[20-10-21 08:35:07.8283] main::init (394) Starting Logitech Media Server (v7.9.0, 1433513811, Wed Jun 10 04:18:13 UTC 2015) perl 5.008008
2020-10-21 08:35:41 Logitech Media Server died. Restarting.
[20-10-21 08:36:06.0696] main::init (394) Starting Logitech Media Server (v7.9.0, 1433513811, Wed Jun 10 04:18:13 UTC 2015) perl 5.008008

I tried to start `/usr/sbin/squeezeboxserver` but it tells me one is already running.

I then tried to stop the service with `/etc/init.d/squeezeboxserver stop` but it seems to attempt to start it again:

>:/etc/init.d# squeezeboxserver stop
[20-10-21 08:52:52.5415] main::init (394) Starting Logitech Media Server (v7.9.0, 1433513811, Wed Jun 10 04:18:13 UTC 2015) perl 5.008008
Bus error

So I then killed the process with `ps aux | grep squeeze` and killed the first process:

>root      1267  0.0  0.9  5568 2160 ?        S    07:32   0:00 /bin/bash /usr/sbin/squeezeboxserver_safe /usr/sbin/squeezeboxserver --prefsdir /c/.squeezeboxserver/prefs --logdir /c/.squeezeboxserver/log --cachedir /c/.squeezeboxserver/cache
root      2820 95.7 26.6 68304 60400 ?       R    09:05   0:59 /usr/bin/perl /usr/sbin/squeezeboxserver --prefsdir /c/.squeezeboxserver/prefs --logdir /c/.squeezeboxserver/log --cachedir /c/.squeezeboxserver/cache

Then attempted to start it manually with `/usr/sbin/squeezeboxserver --d_startup` but it fails with:

> ... 
Loaded module: [Slim::Display::NoDisplay] ok!
Bus error

_Note: As you may have seen, I am running v7.9.0 - I did attempt to install 7.9.3 and 7.9.2 but had other issues with "dirsFor: Didn't find a match request: [scprefs] Segmentation fault", so I have reverted back to this 7.9.0 build as it has been running fine for 4 years!_

**Does anyone have any ideas or can assist me with digging deeper.  I didn't make any changes to the NAS and there is plenty of disk space!**

I had a google around for "Bus error" - is it likely a hardware failure?  The NAS has a pair of RAIDed disks but it tells me both are ok.  It's strange thought that a re-install of LMS yesterday had it working again, but it fails on startup.

**Comment by mherger** [comment]
If it suddenly started to crash without LMS being updated, you should try to figure out what else might have changed. New music added? Software updates on the NAS (I doubt that!)? Running low on memory? Or maybe some memory module failing?

As for the LMS versions: There seem to be users even running LMS8 on the sparc model. I can't believe somebody would do that, considering how slow they are... I would strongly suggest you get a Raspberry Pi to run LMS. It'll be so much more fun to use than running on that NAS! Even if you leave the files on the NAS, any interaction with the system will just be much faster.

**Comment by oatsoda** [comment]
@mherger Thanks for replying so quickly.

Like I say, nothing changed. I've not updated anything in a while.  No new music added or rescanned for a few weeks.

Not really sure how to check memory status (my linux is a bit rusty) but I will have a google around...

I have been planning to update for a while, just not sure which way to go - I have considered large SD card and a Pi as I already have a few Pi running around the house!

Startup file attached:
[startup.txt](https://github.com/Logitech/slimserver/files/5414529/startup.txt)

**Comment by oatsoda** [comment]
Hmmm, yeah, could be a mem issue

> total       used       free     shared    buffers     cached
> Mem:        226352     213024      13328          0      74176      99296
> -/+ buffers/cache:      39552     186800
> Swap:       255968          0     255968

Bit weird if it just started failing though.  Maybe it was just scraping through on memory.  Months ago I did add HTTP access to one of the shares on the NAS and I notice there are several `apache_ssl` processes running...

**Comment by michaelherger** [comment]
As you already have Pis around I'd really suggest you give https://www.picoreplayer.org a try. You should be up and running with LMS in minutes (see https://docs.picoreplayer.org/how-to/install_lms/).

**Comment by oatsoda** [comment]
I'm less sure about the memory now as on a reboot there seems to be plenty free, but the squeezeboxserver process keeps dying.

Thanks, I'll take a look at the PiCorePlayer. I didn't realise it would be able to serve the music off of a NAS - is there a guide/docs for that?

What Pi version / RAM is best for using it?

**Comment by michaelherger** [comment]
Haha... compared to the Sparc based ReadyNAS any Pi is a power machine 😄! I use a 3B+ in the office (one or two players), a 4/2GB at home (a dozen or so players). I'd say anything 2/3/4 would do. I assume you don't serve >100k tracks from your NAS?

**Comment by oatsoda** [comment]
Hey, that Sparc box has served me very well for over 10 years! ;)   Amazingly the two 500GB drives have never failed too!

OK.  I have an old Pi 2 spare at the moment, so I'm going to give it a go serving from the NAS.  I can buy a newer Pi later (Pi 4 seems overkill).  I think about 10k tracks, so seems like it shouldn't need anything too powerful!

**Comment by oatsoda** [comment]
@michaelherger Thanks - I'm up and running on the Pi 2 now with the latest.

Took me a bit of fiddling to get the mounted network drive working - turns out I had to add `vers=1.0` to the mount options!

I'd say LMS web interface is probably about same speed on the Pi 2...

One other nice thing is that I can look at using the Spotty plugin now I am off the Sparc!

**Comment by tmancill** [comment]
> Hey, that Sparc box has served me very well for over 10 years! ;) Amazingly the two 500GB drives have never failed too!

@oatsoda That "bus error" make the system memory suspect to me.  LMS needs to allocate and access a fair chunk of memory at startup and Perl is not going to be able to correct a hardware exception.  If you want to triage the hardware further, you might have a look at the output of `dmesg` after the Duo has been running for a while.  (BTW, I ran one of Sparc-based Duos for years.  It was rock solid, but very slow.  I expect that you'll be happier with Raspberry Pi.)
