### ISSUE TITLE
Sending playlist from group player to an alone squeezebox doesn't work

### ISSUE THREAD

**Issue by sifus** [LMS-Community/slimserver#443]
Hi,

when I want to send my playlist from a group player to a single squeezebox, nothing happens. I have to press pause and start sending again and it works.
But sending playlist from a single squeezebox to a group player works.

**Comment by philippe44** [comment]
what to do you to transfer playlist? You must use my special edition of switchplayer if you want it integrated with iPeng. It works correctly but not perfectly with Music Walk With Me as well

**Comment by mherger** [comment]
No response - closing.
