### ISSUE TITLE
Enable files larger than 4.x GB to be handled by the UPnP/DLNA Media Interface plugin

### ISSUE THREAD

**Issue by Arduous** [LMS-Community/slimserver#445]
I am running a Logitech Media Server Version: 8.0.0 - 1603391272 with a MySQL 10.3.23-MariaDB-0+deb10u1
Currenty, the filesize in bytes is stored in the videos.filesize in the database which is of int type. This is not suitable for files larger something like 4 GB. These files are then not visible within the UPnP/DLNA server.
My naive approach to fix the issue was to manually modify the database to store videos.filesize as bigint. This quick fix seems to be working properly, but not understanding well the structure of LMS, I prefer to submit an issue rather than a pull request.

**Comment by michaelherger** [comment]
Feel free to submit a PR... I don't think the Video/Images functionality is very popular among the LMS user base. And there certainly are even less folks using MySQL. So the risk of breaking any installation is rather minor 😁.

SQLite is flexible in that regard: whether you define int or bigint doesn't matter.

**Comment by Arduous** [comment]
I expected to have time to submit the PR, but guess what :) Please keep the issue open two additional weeks. If I can't by then, I'll live with my local fix.
