### ISSUE TITLE
Module for FreeType font missing

### ISSUE THREAD

**Issue by devdems** [LMS-Community/slimserver#446]
Missing Font::FreeType

`Slim::Display::Lib::Fonts::__ANON__ (84) Warning: Unable to load TrueType font support: Can't locate loadable object for module Font::FreeType in @INC (@INC contains: /lms/Plugins/Bandcamp/lib /config/cache/InstalledPlugins/Plugins/Bandcamp/lib /config/cache/InstalledPlugins /lms/CPAN/arch/5.24/x86_64-linux-thread-multi /lms/CPAN/arch/5.24/x86_64-linux-thread-multi/auto /lms/CPAN/arch/5.24.1/x86_64-linux-gnu-thread-multi /lms/CPAN/arch/5.24.1/x86_64-linux-gnu-thread-multi/auto /lms/CPAN/arch/5.24/x86_64-linux-gnu-thread-multi /lms/CPAN/arch/5.24/x86_64-linux-gnu-thread-multi/auto /lms/CPAN/arch/x86_64-linux-gnu-thread-multi /lms/CPAN/arch/5.24 /lms/lib /lms/CPAN /lms /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /lms/Slim/Display/Lib/Fonts.pm line 83.
Compilation failed in require at /lms/Slim/Display/Lib/Fonts.pm line 83.`

**Comment by michaelherger** [comment]
That's using the Docker image? What if you added libfont-freetype-perl to Dockerfile?

**Comment by michaelherger** [comment]
Should be fixed https://github.com/Logitech/slimserver-platforms/commit/8d3a72e5d2704cb05c4e8b45e98d21fe81cfabd9 - please give it a try and report back. Thanks!

**Comment by devdems** [comment]
Added libfont-freetype-perl. Will check the logs tomorrow and write an update here.

**Comment by devdems** [comment]
Got the error again. A bit different this time.

`[20-10-25 20:26:24.0743] Slim::Display::Lib::Fonts::__ANON__ (84) Warning: Unable to load TrueType font support: Font::FreeType object version 0.07 does not match $Font::FreeType::VERSION 0.03 at /usr/lib/x86_64-linux-gnu/perl/5.24/DynaLoader.pm line 204.
Compilation failed in require at /lms/Slim/Display/Lib/Fonts.pm line 83.`

Probably here: CPAN/Font/FreeType.pm

`our $VERSION = '0.03';`

**Comment by michaelherger** [comment]
That's not using the latest Dockerfile, is it?

**Comment by devdems** [comment]
> That's not using the latest Dockerfile, is it?

Correct. I forgot to remove CPAN/Font as you did. I'm testing it now with this.

**Comment by devdems** [comment]
Looks to be using the correct font now. Closing.
