### ISSUE TITLE
Sudden Static blast of sound in between FLAC tracks

### ISSUE THREAD

**Issue by SquigglyDog** [LMS-Community/slimserver#447]
I am running 3 Touch players from a Linux Mint 20 server. Occasionally I get loud static blasts of sound when a track ends and a new track is about to begin. I don't know if this happens with MP3s but has happened with FLAC tracks. This occurs when either Cross Fade or Fade In and Out are enabled. I have reset my players  to No Fade and have not had the problem. This started to happen recently after a few years without issue. A few years ago I had the same issue but it seemed to go away. The players use Toslink optical connection and two are alternately connected to a switching receiver and the other a more traditional Denon receiver. Here is a link to the problem I brought up on the forums
https://forums.slimdevices.com/showthread.php?113053-Sudden-Static-Noise-in-between-tracks
Here's one from another user
https://forums.slimdevices.com/showthread.php?101470-LMS-7-8-1-bug-noise-at-end-of-song&highlight=static+noise

**Comment by michaelherger** [comment]
When you're saying "this started to happen recently", what changed? Did you update LMS? New DAC? New music?

**Comment by SquigglyDog** [comment]
It has occurred on the last 2 versions of LMS I installed (at least)
logitechmediaserver_8.0.0~1602486506_amd64, 
logitechmediaserver_8.0.0~1596358186_amd64
These were tracks I have had for awhile. No new equipment recently. The switching amp is about a year old the denon many years old

**Comment by michaelherger** [comment]
Older builds (eg. 7.9.3) would not show this behaviour? And you can reliably reproduce this issue? Any particular track? Are you using crossfading?

**Comment by SquigglyDog** [comment]
I tried to find the original thread I started where this happened. I believe it was at least a few years ago but I don't remember. At the time I was installing nightlies every  month or so but I couldn't say which version of LMS I was using.If I enable Crossfade or Fade In Out I think it will start  again although I have no way of predicting when. I don't know that there are specific tracks involved but occurs with FLAC 44.1 kHz, 16 bit stereo but it may happen with higher res. Almost all my FLAC files are standard CD quality. I am reluctant to test whether this will happen with specific tracks, but I could re-enable Fade and see. Is there any way I can do this without risking damage to my speakers?

**Comment by SquigglyDog** [comment]
I should add that I modified the Touch players software through SSH to enable a graphic feature in Custom Clock Helper. However the problem occurred years ago also when no such modification was made

**Comment by SquigglyDog** [comment]
OK at the risk of blowing the speakers I tried it with Fade In Out enabled with volume lowered a bit. I had a static burst after about 4 tracks with one occurring between Meat City and Crystal. Here is track info :Disc: 1/1
Track Number: 15
Libraries: FLAC
File Format: FLAC
Duration: 2:37
Volume Adjustment: -5.74 dB
Album Volume Adjustment: -6.77 dB
Rating: 47
Bitrate: 647kbps VBR
Sample Rate: 44.1 kHz
Sample Size: 16Bits
File Length: 12,809,538
Play Count: 1
Last Played: Friday, October 30, 2020, 2:13 PM
Location: /mnt/Music/Flac/ROCK/Lennon, John/04 - Japanese Imported Box Set 2007/05 - Mind Games [Bonus Tracks] 1973/15 - Meat City.Flac
Date Modified: Thursday, November 29, 1979, 11:00 PM

Track Number: 4
Libraries: FLAC
File Format: FLAC
Duration: 3:49
Volume Adjustment: -2.63 dB
Album Volume Adjustment: -1.87 dB
Rating: 88
Bitrate: 3153kbps VBR
Sample Rate: 96.0 kHz
Sample Size: 24Bits
File Length: 90,659,911
Play Count: 11
Last Played: Friday, October 30, 2020, 2:13 PM
Location: /mnt/Music/Flac/ROCK/Buckingham-Nicks/Buckingham Nicks 1973/04 - Crystal.flac
Date Modified: Thursday, November 29, 1979, 11:00 PM

I have no idea why the date modification is 1979. I tried reproducing the problem by playing the tracks again 2X it did not happen on either test. Attached is a Server log. Burst happened at about 14:13
[server.log.zip](https://github.com/Logitech/slimserver/files/5466912/server.log.zip)

**Comment by SquigglyDog** [comment]
I noticed the second track is 96/24 bit. If the issue is playing both low and high res tracks is there a way of mitigating it. I don't have many high res tracks but if I have random play or dynamic playlists going I can't predict when they occur

**Comment by philippe44** [comment]
There is an option to disable X-fade when sampling rate is different. I've already modified a few things there, but here is a comment extract from Slim::Player::Squeezebox.pm

```
	# Don't do transitions if the sample rates of the two
	# songs differ. This avoids some unpleasant white
	# noise from (at least) the Squeezebox Touch when
	# using the analogue outputs. This might be bug#1884.
	# Whether to implement this restriction is controlled
	# by a player preference.
```

**Comment by SquigglyDog** [comment]
Thanks...I was using Material skin and the option wasn't there but I will set it in Classic and revert back to Material. I was using digital (Optical Toslink) outputs

**Comment by philippe44** [comment]
To elaborate a bit on this, we can adopt a different logic, but I made changes a while ago for the following reasons:
There is a UI option to **enable** cross-fade across multiple sample rate. So the correct logic is, I think, to disable cross-fade when:

1/ GUI option is set to *disable* cross-fade across different sample rate
2/ fading is a cross-fade (1 or 5)
3/ sample rate differs

Previously, any fading was disabled when GUI option was set and sample rate differed. This is the change I've made back then: https://github.com/Logitech/slimserver/commit/6edab58effdd245de068dd5a4880fd127ccee76e#diff-3709e641e995d13c67430cd411c8f1770a0aa398d60e1e4866bbd3e186af7f86

Now we can adopt a logic where we simply hide the option (force it to disabled) for players that we know are problematic. I don't if others than Touch have the issue. I know that squeezelite does not do cross-fade when sample rate are different, but I think that was the right assumption from LMS to think that further firmware releases or players could have that possibility.

**Comment by SquigglyDog** [comment]
I will monitor the player to ensure it is not happening between tracks with the same sample rate, which is what I had thought happened

**Comment by slartibartfast3** [comment]
I have experienced this white noise at the end of a single FLAC track when Fade in-Fade out is used so I don't think sample rate is necessarily involved.

**Comment by SquigglyDog** [comment]
I haven't had a single occurrence since I enabled Philippe's UI option

**Comment by aloneagainor** [comment]
I also have this issue but only one one of my Raspberry Pi squeezelite clients. It's actually a lot more noticeable with crossfade completely disabled which causes it to happen between most tracks. With crossfade enabled, it only occurs when there is a very long fadeout from the currently playing track which causes a period of silence before the next track. This has occurred on every version of LMS since I've been running it (7.7 up to 8.1).

2 of my players (both Raspberry Pis) are nearly identically configured. Both have the same player settings in LMS, both run the same version of squeezelite and both have the same HifiBerry DAC. The only 2 differences are that the affected player is a Pi3 and the non affected player is a Pi4 and that the pi3 is also running shairport-sync on a different alsa device. I have a spare Pi4 so I'll swap this in for the pi3 and see if it makes a difference.

**Comment by mherger** [comment]
@SquigglyDog Could you please summarize the issue, and what you did to address it?

**Comment by SquigglyDog** [comment]
**Start of Issue**
Touch player connected with Optical Toslink
Fade In and Out enabled
Loud white noise occurred  between tracks where the first was Sample Rate: 44.1 kHz Sample Size: 16Bits 
and the next track was Sample Rate: 96.0 kHz Sample Size: 24Bits
Tired a number of steps to fix this including using coxial instead of toslink, updating LMS, changing the optical cable
**Solution**
In the end enabling  Crossfade across different sample rates seemed to correct my issue(LMS player settings). I haven't had any problems since October.
Thanks to Michael and Philippe

**Comment by michaelherger** [comment]
Could you please share the exact settings you're using (screenshot)? I'm still a bit confused about enabling vs. disabling options...

**Comment by SquigglyDog** [comment]
Here is a screen shot
![Selection_002](https://user-images.githubusercontent.com/9086038/109010136-6c9ab580-767d-11eb-992f-cb564f571c56.png)

**Comment by michaelherger** [comment]
Ok, got it. But this is a bit confusing, as that option was added to _disable_ crossfading in case of different sample rates, as it could cause static... you are saying you have to _enable_ it to prevent the bursts?

**Comment by SquigglyDog** [comment]
I guess I meant that Crossfading was disabled by the selection. That is I choose yes in the option. Sorry for any confusion

**Comment by slartibartfast3** [comment]
> 
> 
> I guess I meant that Crossfading was disabled by the selection. That is I choose yes in the option. Sorry for any confusion

So does "Yes" enable or disable crossfading? I understood yes would leave it enabled. I.E. same as before the setting was available.

**Comment by SquigglyDog** [comment]
I assumed it disabled crossfading only where high sample rate files are introduced after normal FLAC or MP3s. In any case once I marked it Yes my problems disappeared
EDIT: I see how the title of the setting suggests otherwise. The caption below seems to be unclear, that is it seems to suggest the opposite of the title

**Comment by slartibartfast3** [comment]
On my LMS the "Crossfade across different sample rates" setting doesn't have any effect at all. i see the same behaviour regardless of the setting. However the behavior is not what you would expect. Crossfading always takes place between a 44.kHz track and a 96kHz track. Crossfading doesn't take place between a 96kHz track and a 44.1kHz track. I have no idea what is going on.
Actually it does crossfade between 96 and 44.1 kHz. The tick box still has no effect whatsoever though.

**Comment by SquigglyDog** [comment]
Then I am not sure why my problem disappeared, but I was getting static blasts every day more than once a day and now I haven't had one for months

**Comment by slartibartfast3** [comment]
> 
> 
> Then I am not sure why my problem disappeared, but I was getting static blasts every day more than once a day and now I haven't had one for months

I have no idea why the tick box has no effect on my LMS. It must work for others.

**Comment by SquigglyDog** [comment]
OK I tried playing the two songs as above Meat City(FLAC 44.1 kHz, 16 bit) and Crystal(FLAC 96.0 kHz
24Bits) both with the Option for Crossfading between low and high resolution files marked as yes and then again with it marked no and then back to yes. Made no difference for these tracks so I can't reproduce the occurence of white noise or say why it disappeared when I initially changed that setting to yes
