### ISSUE TITLE
Provide CPAN for perl 5.32

### ISSUE THREAD

**Issue by jmingremeau** [LMS-Community/slimserver#450]
Hello, could you provide the CPAN binaries for perl 5.32? This is the required version for future Mageia 8 (currently Cauldron).
Thanks for your work!

**Comment by davidfox2116** [comment]
Hi - I need this update for Fedora 33 as well. It seems other Linux distros will not work without this update either.
Thanks!

**Comment by jmingremeau** [comment]
It works fine with Mageia Cauldron now. Thanks!

**Comment by davidfox2116** [comment]
It's working under Fedora 33.  Thanks much!

**Comment by davidfox2116** [comment]
I's working under Fedora 33.  Thanks much!
