### ISSUE TITLE
TIDAL/Update issue

### ISSUE THREAD

**Issue by HAsendorf** [LMS-Community/slimserver#455]
Hi, when the Problem with the new login to TIDAL came up this autumn, I upgraded my Synology to the at the time latest version of 8.0.0.
The current version I am on is 8.0.0-1600144351.
Until a while ago, Tidal was working perfectly on all my devices, including a SB Boom.
Two days ago, I realised, that I can connect to Tidal, search, see my playlists, but when I try to play something It will end with an error saying: „Can‘t connect to Server...“
I then went to my Synology to see whether there might be an update available and found an Update pending.
The package center has the following Information.
New version 8.0.0-16051665211... 
However, the upgrade to this version fails with the message:  „Upgrade failed. The package does not contain a digital signature.“
No Idea if the upgrade would solve my Tidal issue, but right now I cannot try it.
Any ideas what else I could try?

**Comment by michaelherger** [comment]
Please see with the Synology package's author about this issue. 

Or check out this thread on the forums: https://forums.slimdevices.com/showthread.php?111876-LmsUpdate-and-LmsRepack-Synology-8-0-*-packages&highlight=synology

**Comment by mherger** [comment]
I'm closing this issue, as it's not a LMS issue per se, but related to the packaging for the Synology NAS.
