### ISSUE TITLE
Can every wake-up alarm-signal have it's own setting for the volume?

### ISSUE THREAD

**Issue by vhDavid** [LMS-Community/slimserver#457]
Don't know if it is possible in the software. On days that I don't have to get up immediately I want to set a lower volume to the radio-station so it is not that irritating. Therefore the alarm-signal-volume should be adjustable per alarm signal instead of only one possibility.

**Comment by michaelherger** [comment]
This currently is not possible.

**Comment by vhDavid** [comment]
> 
> 
> This currently is not possible.

No problem, thanks. I was thinking it would need a firware-update but not sure of it.
