### ISSUE TITLE
Wrong coverart for favorites added by CLI

### ISSUE THREAD

**Issue by Gagi2k** [LMS-Community/slimserver#458]
Adding a track to the favorites using the CLI works correct and also the correct coverart is added.

When doing the same with items from spotty or tunein results in a favorite entry with a default plugin coverart.

Doing the same using the WebUI (e.g. the material skin) works fine.

**Comment by michaelherger** [comment]
Then you must be doing something wrong :-). Please provide more information, the exact command you're using etc.

**Comment by Gagi2k** [comment]
Here a small example:

>>> favorites add title:Test-1 url:http%3A%2F%2Fopml.radiotime.com%2FTune.ashx%3Fid%3Ds97458%26formats%3Daac%2Cogg%2Cmp3%2Cwmpro%2Cwma%2Cwmvoice%2Chls%2Creal%26partnerId%3D16

<<< favorites add title%3ATest-1 url%3Ahttp%3A%2F%2Fopml.radiotime.com%2FTune.ashx%3Fid%3Ds97458%26formats%3Daac%2Cogg%2Cmp3%2Cwmpro%2Cwma%2Cwmvoice%2Chls%2Creal%26partnerId%3D16 count%3A1

>>> favorites items 0 100 with_url:1

<<< ... pe%3Aaudio image%3Ahtml%2Fimages%2Fplaylists.png isaudio%3A1 hasitems%3A0 id%3A12 name%3ATest-1 type%3Aaudio image%3A%2Fplugins%2FTuneIn%2Fhtml%2Fimages%2Fpodcasts.png isaudio%3A1 hasitems%3A0 count%3A13

**Comment by mherger** [comment]
Ok, documentation is incomplete here. `favorites add` accepts another optional parameter called `icon` 😀 . That should be the URL of the artwork you'd like to use with the favorite.

**Comment by Gagi2k** [comment]
works!, thx a lot
