### ISSUE TITLE
unstable debian repo: logitechmediaserver_7.8.1~1424277835_all.deb Size mismatch

### ISSUE THREAD

**Issue by eddgrant** [LMS-Community/slimserver#46]
Hi,
I'm trying to install logitechmediaserver on Ubuntu 14.04. I've ended up having to use the unstable debian repo as the version of Perl in Ubuntu 14.04 is incompatible with the version required by the logitechmediaserver debian package in the stable repository.

When installing from the unstable repository I'm experiencing 2 issues:
1. The package is unsigned
2. There's a checksum/ size mismatch between the repository index and the actual debian artefact

This is evidenced in the output below:

```
WARNING: The following packages cannot be authenticated!
  logitechmediaserver
Install these packages without verification? [y/N] y
Get:1 http://debian.slimdevices.com/ unstable/main logitechmediaserver all 7.8.1~1424277835 [123 MB]
Fetched 123 MB in 43s (2,841 kB/s)                                             
E: Failed to fetch http://debian.slimdevices.com/pool/main/l/logitechmediaserver/logitechmediaserver_7.8.1~1424277835_all.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

/logitechmediaserver_7.8.1~1424277835_all.deb  Size mismatch

Are the developers of this gitrepo responsible for publishing to the debian repository? It would be great if artefact signing could be implemented and the size mismatch issue fixed (I'm guessing this is just an issue with the repo index being out of step?). Failing that are there any known workarounds to force apt to ignore the warnings?

Many thanks,

Edd

**Comment by mherger** [comment]
The simplest workaround probably is to not use the repositories any more. There simply is no one around with enough knowledge to make it work reliably any more. Just head over to http://downloads.slimdevices.com/nightly/, download the .deb package and use dpkg to install it.

**Comment by eddgrant** [comment]
Understood, works a charm. Thanks for that.
