### ISSUE TITLE
Retrieving a genre by ID using the CLI is not possible

### ISSUE THREAD

**Issue by Gagi2k** [LMS-Community/slimserver#460]
I'm trying to retrieve the name of a genre by id.

Listing all genres works fine:

`dc%3A44%3A6d%3Acb%3Acf%3Aae genres 0 100
dc%3A44%3A6d%3Acb%3Acf%3Aae genres 0 100 id%3A74 genre%3A1981 id%3A159 genre%3A1983 id%3A175 genre%3A1989 id%3A160 genre%3A1990 id%3A137 genre%3A1992 id%3A176 genre%3A1994 id%3A161 genre%3A1995 id%3A162 genre%3A1996 id%3A100 genre%3A1997 id%3A154 genre%3A1998 id%3A193 genre%3A1999`

Limiting the result to only one genre doesn't:

`dc%3A44%3A6d%3Acb%3Acf%3Aae genres 0 100 genre_id:74
dc%3A44%3A6d%3Acb%3Acf%3Aae genres 0 100 genre_id%3A74`

**Comment by michaelherger** [comment]
Heh... this actually is hitting a SQL bug on my end. Could you please check your server.log file to see whether you're getting the same? You're still on 7.9.x, aren't you? Here's a patch that would fix the issue for me:

```patch
diff --git a/Slim/Control/Queries.pm b/Slim/Control/Queries.pm
index 851cb05d3..4dfbd90ec 100644
--- a/Slim/Control/Queries.pm
+++ b/Slim/Control/Queries.pm
@@ -1538,7 +1538,7 @@ sub genresQuery {
        }
        elsif (defined $genreID) {
                my @genreIDs = split(/,/, $genreID);
-               push @{$w}, 'genre_track.genre IN (' . join(', ', map {'?'} @genreIDs) . ')';
+               push @{$w}, 'genres.id IN (' . join(', ', map {'?'} @genreIDs) . ')';
                push @{$p}, @genreIDs;
        }
        else {
```

The lines might be different for 7.9 (not by much, but anyway). But search for the `elsif (defined $genreID) {` line.

**Comment by Gagi2k** [comment]
Works fine on LMS 7.9
