### ISSUE TITLE
Extremely slow startup (caused by SQLite)

### ISSUE THREAD

**Issue by maniac103** [LMS-Community/slimserver#468]
On my system (an Intel NUC6i3SYH running Ubuntu 18.04) LMS 7.9/8.0 take extremely long to start up: it takes 10-15 minutes until the web UI is reachable and players work. During that time, the LMS process takes 100% CPU usage. Running strace on the LMS process reveals it's busy reading in a file in 1kB chunks:

```
<snip>
lseek(19, 43316224, SEEK_SET)           = 43316224
read(19, "\r\0\0\0\6\0\226\0\3m\2\335\2F\1\263\1)\0\226\0\0\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
lseek(19, 43317248, SEEK_SET)           = 43317248
read(19, "\r\0\0\0\7\0.\0\3w\2\357\2d\1\307\1B\0\271\0.\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
lseek(19, 43318272, SEEK_SET)           = 43318272
read(19, "\r\0\0\0\6\0\226\0\3m\2\335\2F\1\263\1)\0\226\0\0\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
lseek(19, 43319296, SEEK_SET)           = 43319296
read(19, "\r\0\0\0\7\0.\0\3w\2\357\2d\1\307\1B\0\271\0.\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
lseek(19, 43320320, SEEK_SET)           = 43320320
read(19, "\r\0\0\0\6\0\226\0\3m\2\335\2F\1\263\1)\0\226\0\0\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
lseek(19, 43321344, SEEK_SET)           = 43321344
read(19, "\r\0\0\0\7\0.\0\3w\2\357\2d\1\307\1B\0\271\0.\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
lseek(19, 43322368, SEEK_SET)           = 43322368
read(19, "\r\0\0\0\6\0\226\0\3m\2\335\2F\1\263\1)\0\226\0\0\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
<snip>
```

where FD 19 is an Sqlite DB:
```
ls -l /proc/30940/fd/19
lrwx------ 1 squeezeboxserver nogroup 64 Dez  4 09:08 /proc/30940/fd/19 -> /var/lib/squeezeboxserver/cache/persist.db
```

That DB is about 85MB in size:
```
ls -l /var/lib/squeezeboxserver/cache/persist.db
-rw-r--r-- 1 squeezeboxserver nogroup 84957184 Dez  4 09:00 /var/lib/squeezeboxserver/cache/persist.db
```
FWIW, from what I can gather from [this SO post](https://stackoverflow.com/a/54507942) about half the size of that DB lies in the 'track_history' table which has ~178k rows and ~33MB size.

Question: is that startup time to be expected? My music library isn't *that* large actually (about 14k titles), and I don't consider my server underpowered either. Judging from `iotop`, there's no actual disk activity at that time, so the file seems to be served from fs cache and the time seems to be consumed in the LMS and/or sqlite code.

**Comment by mherger** [comment]
Are you using the TrackStat plugin? It's known to cause this kind of issues.

**Comment by maniac103** [comment]
I have it installed, yes, but am not actively using it at this point. I'll uninstall and report back. Thanks for the quick answer! :+1:

**Comment by maniac103** [comment]
Indeed it was TrackStat that caused this. Thanks for the help and sorry for the noise :-)
