### ISSUE TITLE
Broken functionality: Album > "More"

### ISSUE THREAD

**Issue by Apesbrain** [LMS-Community/slimserver#473]
In any view of Albums click on the [M] mouseover icon for "More":

![Clipboard02](https://user-images.githubusercontent.com/26585705/101652238-030af380-3a0c-11eb-892d-dbe7987fd9a2.jpg)

On the page that comes up, the items in red do not work:

![Clipboard01](https://user-images.githubusercontent.com/26585705/101652293-14540000-3a0c-11eb-9e6e-0b5c8f35ad45.jpg)

Not sure this is specific to LMS 8 as I've never has reason to notice it before.

Also, on first image above, the [❤] mouseover should have description "Add to Favorites".

**Comment by slartibartfast3** [comment]
> 
> 
> In any view of Albums click on the [M] mouseover icon for "More":
> 
> ![Clipboard02](https://user-images.githubusercontent.com/26585705/101652238-030af380-3a0c-11eb-892d-dbe7987fd9a2.jpg)
> 
> On the page that comes up, the items in red do not work:
> 
> ![Clipboard01](https://user-images.githubusercontent.com/26585705/101652293-14540000-3a0c-11eb-9e6e-0b5c8f35ad45.jpg)
> 
> Not sure this is specific to LMS 8 as I've never has reason to notice it before.
> 
> Also, on first image above, the [❤] mouseover should have description "Add to Favorites".

Just noticed this and can confirm the issue. I am a little surprised there are no other comments in over a month.

**Comment by odin81** [comment]
Hello, I can confirm this issue with LMS 8.2.0
