### ISSUE TITLE
aarch64 and alac

### ISSUE THREAD

**Issue by philippe44** [LMS-Community/slimserver#477]
I'm moving to an aarch64 platform and I realized that alac *files* are failing on players that support alac codec. The type detected from the mp4 file container remains 'mp4' and is not set to 'alc', as it should be (and is) on other platforms. 

As a consequence (and because LMS assumes mp4 is aac - there is confusion a bit all over the place here), for players supporting alac, they receive a stream_s that claims to be aac in an mp4 enclosure. For players not supporting alac, transcoding rule is 'mp4 flc' using faad which works because the modified faad detects the codec inside the mp4 container.

I have not investigated why for now, it's just an FYI

**Comment by mherger** [comment]
Why would that be limited to aarch64?

**Comment by philippe44** [comment]
> Why would that be limited to aarch64?
>
I would assume something maybe with Audio::Scan, I really don't know. I will investigate tomorrow when I have time

**Comment by philippe44** [comment]
Oops ... my bad, it was an issue between my NAS and that system (an odroid c4) that made the file (in favorites) non-accessible, so the returned type was just the extension. What fooled me for a while as it was failing when trying to stream, not earlier, probably because it was a favorite.

Well, the positive side is that I found a couple of aarch64 issues in my plugins and in the alac reference codec.
