### ISSUE TITLE
CometD: connect response (/meta/connect) does not include ID of request

### ISSUE THREAD

**Issue by cleemansen** [LMS-Community/slimserver#478]
Version **Logitech Media Server Version: 8.0.0 - 1605892076 @ Fri Nov 20 21:29:02 CET 2020**

At least the [CometD Java-Library](https://cometd.org/) expects the ID of the request during CONNECT (`/meta/connect`) in the servers response.

Slimserver does not reply with the requested ID: https://github.com/Logitech/slimserver/blob/public/8.0/Slim/Web/Cometd.pm#L259

Therefore no connection can be established using `long-polling` by the Java-CometD-Library.

Current state:

Request:

```
[20-12-16 18:35:43.6115] Slim::Web::Cometd::handler (149) Cometd request (<IP.xx>:60727): [
  {
    advice => { timeout => 0 },
    channel => "/meta/connect",
    clientId => "d8a45836",
    connectionType => "long-polling",
    id => 2,
  },
]
```

Response (the ID from the request (`id => 2`) is not part of it):

```
[20-12-16 18:35:43.6275] Slim::Web::Cometd::sendHTTPResponse (724) Sending Cometd response (<IP.xx>:60727):
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: Keep-Alive
Pragma: no-cache
Content-Length: 137
Content-Type: application/json
Expires: -1
X-Time-To-Serve: 0.0216019153594971

[{"channel":"/meta/connect","advice":{"interval":0},"successful":true,"timestamp":"Wed, 16 Dec 2020 18:35:43 GMT","clientId":"d8a45836"}]
```

**Please add the ID from the request to the response body during CONNECT.**

For reference: [this code block expects the ID in the response](https://github.com/cometd/cometd/blob/5.0.x/cometd-java/cometd-java-client/cometd-java-client-common/src/main/java/org/cometd/client/BayeuxClient.java#L1693)

**Comment by cleemansen** [comment]
For those looking for a **workaround** in the java-client: 

You can add a `okhttp3.Interceptor` to the `okhttp3.OkHttpClient` which:

1. buffers the `id` of the request to `/meta/connect`
2. adds the remembered `id`to the response of this request

**Comment by cleemansen** [comment]
In case anybody else will search for this issue:

1. set log-level of `org.cometd` to `DEBUG`
2. `/meta/connect` request will be aborted with the log message: `2020-12-16 20:03:03.327 [OkHttp http://localhost:9000/...] DEBUG o.c.client.BayeuxClient.161f6623 - Mismatched /meta/connect reply: expected reply for {clientId=03d43396, advice={timeout=0}, channel=/meta/connect, id=2, connectionType=long-polling}, received {clientId=03d43396, advice={interval=0}, channel=/meta/connect, successful=true, timestamp=Wed, 16 Dec 2020 19:03:00 GMT}`

I hope this helps someone and points her to this issue (b/c I struggled with this a lot)..

**Comment by michaelherger** [comment]
Thanks for the report and documenting a client side workaround. I must admit that I'm hesitating to touch that code which has been in place without complaint for that many years... So I'll take it as informational, and see whether this report collects a lot of attention. Ok?

**Comment by cleemansen** [comment]
As I'm happy with my workaround and I understand your reason to not touch this section I'm okay with that, of course.

This is my first contact with the _CometD_ and the _Bayeux_-protocol. So I am absolutely not an expert! Just for future reference I will post my findings from the CometD-documentation about this topic:

> If a message published to a meta channel contains an id field, then any response messages delivered to the client MUST contain an id field with the same value.
https://docs.cometd.org/current/reference/#_bayeux_meta_channels

> A connect request MUST contain the message fields:
> [..]
> `id`
https://docs.cometd.org/current/reference/#_bayeux_meta_connect

So let's wait if this report collects attention (or not)..

**Comment by cleemansen** [comment]
The missing `id` field in the connect-response also prevents using the [`cometd-javascript-client`](https://docs.cometd.org/current7/reference/#_javascript) (which is unsurprising as this client is from the same project). 

[This client also expects the `id` in the `/meta/connect` response.](https://github.com/cometd/cometd/blob/5661837633623f5369c44c4560caca80e5236e97/cometd-javascript/common/src/main/webapp/js/cometd/cometd.js#L2335)

For now I have no real idea how to intercept this. It is some kind of annoying.

[Others simply removed this check in the library](https://github.com/Logitech/slimserver/issues/530) - which is just another workaround and will produce additional work every time the cometd-library gets updated and prevents using the library as a node dependency..

**Comment by cleemansen** [comment]
Some more details about the affected endpoints missing the `message-id` in their responses:

```
missing message-id in the response of request for channel '/meta/handshake'
missing message-id in the response of request for channel '/meta/connect'
missing message-id in the response of request for channel '/meta/subscribe'
found message-id in the response of request for channel '/8c0d444b/slim/serverstatus'
missing message-id in the response of request for channel '/meta/connect'
missing message-id in the response of request for channel '/meta/subscribe'
found message-id in the response of request for channel '/8c0d444b/slim/playerstatus/****'
missing message-id in the response of request for channel '/meta/connect'
missing message-id in the response of request for channel '/meta/disconnect'
```

So it seems all `/meta` endpoints (the [meta-channels](https://docs.cometd.org/current7/reference/#_concepts_channels_meta)) are affected. Also the [service-channels](https://docs.cometd.org/current7/reference/#_concepts_channels_service) do response with the provided `message-id`.

**Comment by michaelherger** [comment]
Hi @cleemansen - there's a new report #765 with a corresponding PR. Would that fix your issue, too?

**Comment by cleemansen** [comment]
Yes - this sounds very similar. I will test the next version by removing [all](https://github.com/cleemansen/pi-audio-multiroom/blob/a7355f853e67855e8a404f3e3c3769c244f047fe/pictl-ktor/src/org/unividuell/pictl/server/network/cometd/SqueezeboxCometConnectPatchInterceptor.kt) my [workarounds](https://github.com/cleemansen/pi-audio-multiroom/commit/a7355f853e67855e8a404f3e3c3769c244f047fe).

Thanks for linking and for [providing the fix](https://github.com/Logitech/slimserver/pull/767) and also for accepting the PR.

PS: It could also be interesting for https://github.com/Logitech/slimserver/issues/530

**Comment by cleemansen** [comment]
Tested with `Logitech Media Server Version: 8.3.0 - 1648757675 @ Thu 31 Mar 2022 11:24:41 PM CEST` and `cometd 7.0.6`. It works now as expected w/o any patches - great :)
