### ISSUE TITLE
Unified Library shows Spotify Items although disabled

### ISSUE THREAD

**Issue by Gagi2k** [LMS-Community/slimserver#491]
Using LMS 8.2.0~1609139175 i changed the Online-Library-Integration to disable it for all services and also selected to only show local titles.

In the Spotty plugin i disabled the import for all users and also selected the option to delete the saved playlist folder.

Restartet the sever, but also afterwards the "My Music" Menu still shows Spotify entries in Playlists and Albums.

**Comment by michaelherger** [comment]
Did you run a wipe & rescan?

**Comment by Gagi2k** [comment]
No, that fixed it, but it wasn't aware that this is needed.

**Comment by michaelherger** [comment]
I should probably add a hint, or trigger a rescan. Thanks for the heads up.
