### ISSUE TITLE
Albums not using sort tags correctly

### ISSUE THREAD

**Issue by aloneagainor** [LMS-Community/slimserver#497]
**Version:**

8.1.0 - 1608700893

**Scenario:**

An album artist with multiple albums whose 'sort album artist' tags are different are not sorted correctly. For example, the album artist 'Berliner Philharmoniker, Herbert von Karajan' has multiple albums, some of which have the 'sort album artist' field set to 'Bach', others 'Beethoven' and others 'Strauss'. This occurs in album view, with the 'Artist, Year, Album' sort mode. All files are FLAC.

**Expected behaviour:**

The albums should be sorted using the 'sort album artist' tag. Albums tagged 'Bach' should be sorted under 'Ba...', Beethoven under 'Be...' and Strauss under 'St...'

**Actual behaviour:**

All albums are sorted under Bach, possibly because it's the first alphabetically. Other music players reading from the same tags (MPD, iTunes/Apple Music) sort the albums as described in the 'expected behaviour' section.

---
Please let me know if you need any more information, screenshots or example audio files.

**Comment by michaelherger** [comment]
An artist can only have one sort value, as it's always the same artist. Bach certainly is not the correct sort value for "Karajan". Use Bach as the composer or something.

**Comment by mherger** [comment]
Closing, as this is not a LMS issue, but rather wrong expectations and invalid use of metadata.
