### ISSUE TITLE
Issue when moving from slimserver 7.9.1 tot 8.1.0

### ISSUE THREAD

**Issue by JWBro** [LMS-Community/slimserver#499]
I have a music library with about 9600 albums, all in FLAC format and properly tagged.
With version 7.9.1 (oct 22, 2020) the album count is 9604 and correct
With version 8.1.0 the album count is at 9965 albums and incorrect.
There are several in the list that are duplicated. How to solve this?

best regards

**Comment by michaelherger** [comment]
This most likely is due to CUE sheets: 8.1 introduced a new feature where a CUE sheet with multiple `FILE` tags would be evaluated. Previously those were skipped. If the individual files already have tags, this can lead to duplication. Check those albums and delete any CUE sheets related to them.

**Comment by JWBro** [comment]
Thanks, I will check the music libarry.

All the best for 2021 and take care !!

Regards
Jan

**Comment by mherger** [comment]
Does 8.1.1 fix this for you?

**Comment by JWBro** [comment]
I found quite a few cue sheets in the cikkection. Rather than removing these cue sheets I renamed the file extension from .cue to .que (you can always throw away at a later stage) ..... Inn the meantime I installed version 8.1.1 and it worked well.
Thanks a lot.
best regards
Jan
