### ISSUE TITLE
TIDAL plugin functions, but doesn't appear on the Home page in the server web UI (LMS 8.1.0)

### ISSUE THREAD

**Issue by tmancill** [LMS-Community/slimserver#503]
Hi,

I have recently enabled the TIDAL plugin on LMS 8.1.0 and am not seeing it appear in the Home page.  I am expecting to see TIDAL appear beneath `My Apps`.  I have used this plugin successfully in the past with LMS 7.9.x and it was accessible via the Home at that time.  The plugin is active and functional - that is:
- I see my TIDAL playlists beneath Home > Playlists (or My Music -> Playlists)
- I can navigate to http://localhost:9000/plugins/wimp/index.html and interact with TIDAL successfully, including searches, etc.

I see the following in server.log during startup (but I think that just means that `/plugins/wimp` will function), and am not seeing any errors related to WiMP or TIDAL in the logs.

```
[21-01-03 15:57:05.2721] Slim::Utils::PluginManager::load (241) Loading plugin: WiMP
[21-01-03 15:57:05.2798] Slim::Utils::PluginManager::load (374) Adding HTML directory: [/usr/share/perl5/Slim/Plugin/WiMP/HTML]
```

I tried changing the `menu` in https://github.com/Logitech/slimserver/blob/public/8.1/Slim/Plugin/WiMP/Plugin.pm#L37-L38 to be `radios` (to match Spotty - https://github.com/michaelherger/Spotty-Plugin/blob/master/Plugin.pm#L114 - which appears beneath `My Apps` on the Home page), and then restarted, but didn't see TIDAL appear.

Apologies for filing an issue.  I'm still learning my way around the code base and will continue to do more digging, but any hints would be appreciated.  Maybe someone else has seen this?

**Comment by michaelherger** [comment]
Please see https://forums.slimdevices.com/showthread.php?113587-Tidal-app-not-appearing-on-SB-Receiver-amp-Radio

Did you buy your player second hand? Would you mind sharing your full server.log.zip with me? Any hint in there about failing to connect to mysb.com?

**Comment by tmancill** [comment]
Thank you for the link to the thread.

I bought my Squeezebox Booms new (years ago) and they shouldn't be associated with any other TIDAL account.  My local players include several [squeezelite](https://github.com/ralph-irving/squeezelite) clients.  The Booms and (some of) the squeezelite clients were players during a previous trial of TIDAL, both via LMS and TIDAL's web player, and I cancelled that trial and am now resubscribing.  Maybe that's causing the issue?

From what I can tell from the logs, I'm not seeing any issues reaching mysb.com, but I will take you up on your offer and send them (via PM in the forum).

**Comment by michaelherger** [comment]
I see "Not direct streaming because player is synced" in the log file. Could you please try without grouping players? And with the 8.1.1 nightly build (http://downloads.slimdevices.com/nightly/?ver=8.1).

And it would still be nice if you could get me your list of MAC addresses, rather than expect me to find them in your log file...

**Comment by tmancill** [comment]
> I see "Not direct streaming because player is synced" in the log file. Could you please try without grouping players? And with the 8.1.1 nightly build (http://downloads.slimdevices.com/nightly/?ver=8.1).
> 
> And it would still be nice if you could get me your list of MAC addresses, rather than expect me to find them in your log file...

@michaelherger Updated log from the 8.1 nightly build and the MAC addresses sent via PM.  (Sorry about that.)

If it makes a difference, I *do* see TIDAL appear in My Apps when I interact with the Boom interface directly.  But it still doesn't appear in the Home page of the LMS web UI.

**Comment by michaelherger** [comment]
Back on https://www.mysqueezebox.com/user/apps/WiMP: please check whether your account is listed with each player in the Player Settings. 

If that's the case, then please follow the steps as outlined in https://forums.slimdevices.com/showthread.php?113587-Tidal-app-not-appearing-on-SB-Receiver-amp-Radio&p=1002886&viewfull=1#post1002886.

**Comment by tmancill** [comment]
I verified the Player Settings on mysb.com - they appear as below:

![image](https://user-images.githubusercontent.com/1195611/103974996-ec99aa00-5127-11eb-9ec9-b2a9b471fd50.png)


And then I followed the steps in the [forum post](https://forums.slimdevices.com/showthread.php?113587-Tidal-app-not-appearing-on-SB-Receiver-amp-Radio&p=1002886&viewfull=1#post1002886).

TIDAL still doesn't appear on the home page in LMS for any of the players.  However, it (still) appears in menus on the Booms, and I noticed that it also appears beneath My Apps in the [Squeezer](https://github.com/nikclayton/android-squeezer) android app for all players.  Whether or not players or grouped doesn't change the LMS home page behavior.

This makes me think that this issue might be distinct from https://forums.slimdevices.com/showthread.php?113587-Tidal-app-not-appearing-on-SB-Receiver-amp-Radio.  The issue I'm having is only with the LMS web UI.  Aside from that, TIDAL is working perfectly on all players.  Since I can control my headless players with Squeezer and with a bookmark per player to `/plugins/wimp/index.html `, it's a very minor issue for me.  I will close this for now and report back if I am able to figure it out.

Thank you for your help and for looking into this.

**Comment by mherger** [comment]
Thanks for the feedback. This still is odd, and I haven't got to the ground of it yet. I'll keep investigating. You'll see whether I succeed or not :-)

**Comment by tmancill** [comment]
@mherger The TIDAL icon now appears in LMS for me.  Initially I assumed this was because I updated to 8.1.2, but looking back through the logs ([gist link](https://gist.github.com/tmancill/c1bc485452f20d06d31de998be5686d9); timestamps in UTC), I believe the change occurred during the first MySB SN sync on 2021-01-12.  I didn't look closely at LMS during the week and so can't say for sure what was in the UI at that time, but the logs start showing TIDAL/wimp during the sync on that day.

In any event, it is working 100% as expected now.  Thanks again!

![image](https://user-images.githubusercontent.com/1195611/104819720-39dee100-57e4-11eb-9afb-7f5306ef4a25.png)

**Comment by mherger** [comment]
I'm sorry for not getting back to you: this actually was a mysqueezebox.com side issue. One of the database hosts had lost its replication link, thus wasn't picking up changes any more. It's now back in sync.

**Comment by tmancill** [comment]
@mherger No worries - that fits the symptoms perfectly.  Thank you for fixing the issue on the MySB side and for the explanation.
