### ISSUE TITLE
Perl loop with label - huh?

### ISSUE THREAD

**Issue by philippe44** [LMS-Community/slimserver#504]
I just tried a group with a bit rate limitation and my LMS went down. The log contained 100'k of lines of error happening in TranscodingHelper.pm here [~345)
```
	RATELIMIT: if ($rateLimit) {
		foreach (@$want) {
			last RATELIMIT if /B/;
		}
		push @$want, 'B';
	}
```
And the error is
```
[21-01-05 00:15:09.1982] Slim::Networking::IO::Select::__ANON__ (130) Error: Select task failed calling Slim::Networking::Async::HTTP::_http_read_body: Label not found for "last RATELIMIT" at /usr/share/perl5/Slim/Player/TranscodingHelper.pm line 345.
```
If I remove the label, it's all good. Indeed, the label is not correctly placed (should be on the line of the "for", but I think it has always been like that. I've moved to Perl 5.30 on aarch64. Is that an ancient error that suddenly surfaces on a more recent Perl version??

**Comment by philippe44** [comment]
And it's late, but I don't really get the code. We exit the loop if B is found but we add another one right after???. Why not 
```
push (@$want, 'B') unless grep /B/ @$want;
```
(getting late)

**Comment by michaelherger** [comment]
I'm not sure about the exact syntax. But I wouldn't be surprised if we were still using deprecated or removed functionality. Should be easy to fix: isn't this one complicated way to "add 'B' unless it's already in the list"?

I'll hopefully find some time this afternoon to try to reproduce this. The Docker image now is running 5.32. 

BTW: I re-installed my aach64 based Rock64 over the weekend to build binaries for 5.32. What OS are you running on your aarch64 system?

**Comment by michaelherger** [comment]
I wasn't able to reproduce the loop even with Perl 5.32. Do you have any other modifications? Or am I missing something? I tried to reproduce by limiting to 64kbps MP3 (which would enter that condition.

FWIW: here's how I would write it.

```diff
diff --git a/Slim/Player/TranscodingHelper.pm b/Slim/Player/TranscodingHelper.pm
index afab929d9..e0c810ca6 100644
--- a/Slim/Player/TranscodingHelper.pm
+++ b/Slim/Player/TranscodingHelper.pm
@@ -336,20 +336,14 @@ sub getConvertCommand2 {
        my $rateLimit
                = $rateOverride ? $rateOverride
                : $client ? _rateLimit($client, $type, $track->bitrate) : 0;
-       RATELIMIT: if ($rateLimit) {
-               foreach (@$want) {
-                       last RATELIMIT if /B/;
-               }
-               push @$want, 'B';
+       if ($rateLimit) {
+               push @$want, 'B' unless grep /B/, @$want;
        }
 
        # Check if we need to downsample
        my $samplerateLimit = $song ? Slim::Player::CapabilitiesHelper::samplerateLimit($song) : 0;
-       SAMPLELIMIT: if ($samplerateLimit) {
-               foreach (@$need) {
-                       last SAMPLELIMIT if /D/;
-               }
-               push @$need, 'D';
+       if ($samplerateLimit) {
+               push @$need, 'D' unless grep /D/, @$need;
        }
 
        # make sure we only test formats that are supported.
```

**Comment by philippe44** [comment]
No I don’t have any other modification, that happened on a 8.1.1 nightly which is about a week old. The OS is Armbian on a Odroid C4

**Comment by michaelherger** [comment]
Would my patch fix the behaviour for you? Armbian here, too.

**Comment by philippe44** [comment]
It would - I would have done everything in one sentence, but you know me, I'm crazy :-)
```
push @$need, 'D' if $samplerateLimit && !grep /D/, @$need;
```
More important, it's really weird why my system has this behavior

**Comment by philippe44** [comment]
right, I think you're going to like that: this code has never worked, but we have never hit it to a point where it caused problem. Try, with any Perl version
```
use strict;

my $a = 2;
my $array = [1,2,3];

MYLOOP: if ($a > 1) {
    foreach (@$array) {
        print "$_\n";
        last MYLOOP if $_ > 10;
    }
}

if ($a > 1) {
MYLOOP2:  foreach (@$array) {
        print "$_\n";
        last MYLOOP2 if $_ > 1;
    }
}

MYLOOP3: if ($a > 1) {
    foreach (@$array) {
        print "$_\n";
        last MYLOOP3 if $_ > 1;
    }
}
```
It should fail on MYLOOP3 and the explanation is for sure that the "MYLOOP3" statement is outside of the context of the for loop, so you can"t "last" there, you can just "goto". I had that issue already in some other part of the code but never did a whole verification

**Comment by mherger** [comment]
I changed this in 8.1+. Thanks for the heads up!
