### ISSUE TITLE
MyCloud Ex2 Ultra Install Failed

### ISSUE THREAD

**Issue by gthomson100** [LMS-Community/slimserver#505]
Hi everyone, thanks to those who work on this project.
I have the MyCloud Ex2 Utra (OS 3 version firmware) by Western digital I try to install the, it just says "install failed".
The install is from the nightly build the file is logitechmediaserver_8.1.1_1609569900_all.deb
Install is though the myCloud dashboard "Install an app manually", not SSH install, which might be my problem?
Perhaps I am doing something fundamentally wrong?

**Comment by mherger** [comment]
This is a very 3rd party hardware specific question. Please head over to https://forums.slimdevices.com/ to ask the question. There might be users who know this device - I don't. Thanks!
