### ISSUE TITLE
[Feature Request] Podcast OPML import/export

### ISSUE THREAD

**Issue by cavemandaveman** [LMS-Community/slimserver#509]
Currently with the Podcast plugin, feeds need to be added/saved one by one; there is no bulk import. For people with many feeds, this becomes tedious. An 'OPML import' function in the plugin's settings would solve this problem, making it much more automated. A similar 'export to OPML' function would help as well, for those wanting to move all their feeds at once.

If there is currently a way to bulk import, please let me know! I noticed in the < config directory >/prefs/plugins/podcast.prefs there is a list of feeds. Although it is not in OPML format, I thought maybe feeds can be added directly here with the name,value convention. However, changes here do not reflect in the UI, and the file resets upon interaction with the UI.

**Comment by mherger** [comment]
Sounds like a reasonable request. We do have an OPML import feature for favorites, but not podcasts.

And no, you can't modify the file while LMS is running. LMS reads those files at startup. After that it keeps a copy in memory and only writes it out on updates. No more reading. You'd have to shut down LMS to modify the file.

Exporting from it OTOH should work at any time.
