### ISSUE TITLE
WHS Version 8.0.1 File Scanner Issue - Track 1 with Title "Radio Free Europe" skipped by Scanner?

### ISSUE THREAD

**Issue by lynniemagoo** [LMS-Community/slimserver#511]
I have an album by R.E.M. entitled Murmur

Track #1 on this album 

Has the following tags:
Title: "Radio Free Europe"
Artist: "R.E.M."
Album:"Murmur (24bit-192KHz)"
TrackNum:"01"

The full path of this file is:
F:\Audio\HiResMusic\HDTracks\R.E.M\Murmur (24bit-192KHz)\01 - Radio Free Europe - Rock.flac

Not sure if this problem existed prior to 8.0.1 but here goes.

If I scan the above album, every track is detected except Track #01 with the title "Radio Free Europe".  If I then change the Title to "Radio Free Europe (Album Version)" the file is detected and added as Track #01 to the Album.  If I then re-tag the file with the Title as "Radio Free Europe" but don't modify the file name, after another scan, Track #01 is removed.  

Is there some RegEx in the Scanner or some property somewhere that is matching "Radio Free Europe".  I thought it might be a RegEx for "Radio" but when I add the suffix " (Album Version)", the track is indeed detected.  

I have the same song in another R.E.M. album but it is at Track #02.  This file scans with no issue.  I am wondering if there's a RegEx that is detecting a file with tags Track #01 and Title:"Radio Free Europe" and choosing to ignore a file with that name and tagging.

If you need a scanner log, I'm happy to oblige.

**Comment by michaelherger** [comment]
Would you have CUE sheets (might be embedded into the FLAC file)?

In any case please update to 8.1.1 and test again. There are a few changes/fixes related to CUE sheets and FLAC files in that version.

**Comment by lynniemagoo** [comment]
Michael,

Thanks for getting back so quickly.  The file does not contain a cue sheet.  

Attached is a screenshot of all tags from MP3Tag.

I will update to 8.1.1 and retest.

![MHerger](https://user-images.githubusercontent.com/75147249/104791380-14a88f00-5760-11eb-9edd-08e8e196dcf6.png)

**Comment by lynniemagoo** [comment]
Here's what I did.

1.  Updated to 8.1.1 public release.
2.  Opened MP3Tag and changed the Title above to "Radio Free Europe" and then updated the filename such that it is now "01 - Radio Free Europe - Rock.flac"
3. Ran a Folder Scan (Not a clear library and rescan).
4. In the image here, you can see that it is "Removing a deleted file"

![MHerger2](https://user-images.githubusercontent.com/75147249/104791954-402c7900-5762-11eb-8354-ef1c559c4b85.png)


I'll be happy to upload the actual flac file but it is 183MB.

**Comment by lynniemagoo** [comment]
Michael,

In an attempt to isolate Track # vs Title or a combination thereof, I changed the Track # from 1 to 13 and reindex Tracks 2-13 to be 1-12.  Filenames have new track numbers in them as well. So the file in question went from "01 - Radio Free Europe - Rock.flac" to "12 - Radio Free Europe - Rock.flac"

I then repeated another scan.  You can see it removed the previously 11 files that were scanned and then added all 12 of the tracks.

![MHerger3](https://user-images.githubusercontent.com/75147249/104792192-39eacc80-5763-11eb-8d31-ef54a4d5093c.png)

So, it would seem that the Track # and Track Title as a pair are somehow excluding the track from being added to the database.  As a hunch, I expected this behavior as I have other albums with the same song, but not in the position of Track #01.

Let me know if you need something else please.

**Comment by michaelherger** [comment]
You'll have to run a full wipe & rescan. Before you do so please enable logging for `formats.playlists` (Settings/Advanced/Logging). Then send me the server.log.zip file and the file in question: https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a

**Comment by lynniemagoo** [comment]
Do you also want debug level of the scanner log?   I neglected to mention that there is also a playlist.m3u file in the same folder.  I will rar up 2 flac files and the playlist used to repro the issue once I get this completed.

**Comment by lynniemagoo** [comment]
Hello Michael,

As my audio collection is 133K+ tracks, I'm going to isolate this test down to a single audio folder that contains 2 versions (both low and high resolution tracks from the same album.  

I have 3 players on the server and all of the client playlists are empty and contain the following text

#CURTRACK 0
#EXTM3U

clientplaylist_00032d24b189.m3u
clientplaylist_00301807ab95.m3u
clientplaylist_b827eb41de42.m3u

I have done the following steps:
1. Stopped LMS Service
2. Removed the Cache folder
3. Started LMS
4. After startup, scan initiates of F:\Audio\LMSTest which contains both versions of the album.
5. After the initial full scan, Track 01 - Radio Free Europe - Rock is scanned for both the Los and High res folders and has been added to the database.
6. I then attempted a folder rescan and as none of the files have changed, the DB remains intact.
7. I then attempted a folder rescan after updating the tags in the Lo Res Files (touched each file) - DB Remains intact.
8. I then attempted a folder rescan after updating the tags in the High Res Files (touched each file) - DB Remains intact. 
9. I then attempted a System rescan clearing all files.  For whatever reason, this worked and the server did not remove 01-Radio Free Europe for either the Low Res or High Res folders.   


I will continue to monitor this but for now, I cannot reproduce the problem.

It may be worth mentioning that once I removed the Cache folder and removed all client playlists, this problem went away.

Here's  my server log from last evening where this problem was cropping up.  Don't rely on this log as the filenames have extra text - Title had (Album Version) appended.  

[server.log](https://github.com/Logitech/slimserver/files/5825464/server.log)

**Comment by lynniemagoo** [comment]
Can we put this issue on ice for now and reopen it later?  I'm OK if you close it for now.

**Comment by mherger** [comment]
Sure, thanks for sharing your findings. Feel free to re-open should you see a need.
