### ISSUE TITLE
LMS crashing (out of memory) with plugin "Group Players" activated

### ISSUE THREAD

**Issue by schnillerman** [LMS-Community/slimserver#513]
Hi,

since update to version 8.1.2-1610697261, with the **_Group Players_** plugin installed, the server crashes / does not respond anymore. It runs out of memory (uses 11G+ on 12G linux box).

Deleting the directory of the *_Group Players_* plugin (location: `/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/`_**Groups**_) solves the issue.

`systemctl restart logitechmediaserver.service` afterwards works fine and occupies about 350-400MB of memory as usual.

**Comment by michaelherger** [comment]
If this issue really is limited to the use of the Groups plugin you better submit a report over at its repository: https://github.com/philippe44/LMS-Groups

**Comment by schnillerman** [comment]
Yes, I kinda figured ... But wanted to let you know this way anyhow. Will link issue from Group plugin here as well.

**Comment by schnillerman** [comment]
https://github.com/philippe44/LMS-Groups/issues/30#issue-787736285
