### ISSUE TITLE
Operation behind Proxy / Loadbalancer / NAT

### ISSUE THREAD

**Issue by fuero** [LMS-Community/slimserver#518]
I tried running the docker container in a Kubernetes deployment, but my radio can't make the connection due to the cluster-private IP address the container is assigned. Same problem would occur if I were to run slimserver behind any kind of proxy, loadbalancer, VPN, or similar indirection.

I suggest introducing parameters matching the *addr parameters to allow specifying a different IP address that's advertised to the outside world to the one you end up using as the socket bind address.

Similarly, if you were to transmit URLs to the client (don't know if you do), allow overriding the base part of a generated one with a parameter.

**Comment by michaelherger** [comment]
A log of speculation here, and little information. Maybe you want to describe your network settings, players, what you tried, and how players fail to connect?

**Comment by fuero** [comment]
@michaelherger ok, will do - I'll try to provide this tomorrow.

**Comment by michaelherger** [comment]
I'd actually recommend you do this on forums.slimdevices.com. There are more knowledgeable people than just me.

**Comment by fuero** [comment]
ok. I'll reopen this when I have more information.

**Comment by fuero** [comment]
I can't inspect the request lms makes to mysqueezebox.com, as it's an encrypted connection, but I can confirm (using tcpdump) that the player device tries to contact lms via the private address the container is assigned by Kubernetes.

Here's a screenshot of the packets in Wireshark:
![image](https://user-images.githubusercontent.com/108815/105560992-d853d080-5d15-11eb-9c94-4bd31b1d125b.png)

192.168.1.193 is the Squeezebox Radio's IP in my local network, 10.42.2.117 is the ip assigned to the container:

```
root@lms-6b59768865-bl8xf:/config# ip a sh eth0
3: eth0@if74: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether a2:1b:4f:e5:76:a0 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.42.2.117/24 brd 10.42.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a01b:4fff:fee5:76a0/64 scope link 
       valid_lft forever preferred_lft forever
```
