### ISSUE TITLE
LMS doesn't play existing content of playlists

### ISSUE THREAD

**Issue by bungh0l10** [LMS-Community/slimserver#519]
Hi Michael,

thank you so much for keeping SB alive!

I encountered an issue with local playlists having  8.2.0 - 1611117489 
To reproduce the issue: I've created a .m3u having just one url inside. After re-scanning the local playlists through LMS this pops up within LMS playlists and is playable. So far, so good.
If I eg exchange this url within the .m3u LMS won't recognize this change and even after refreshing LMS:9000 still plays the "outdated" url which doesn't exist within the playlist anymore. The current content of the .m3u won't be played through LMS until I do a manual re-scan of the playlists.

**Comment by bungh0l10** [comment]
Same applies to playlists using Spotty plugin.

**Comment by michaelherger** [comment]
What you're describing is expected behaviour. Local files are read during the scan. Thereafter LMS relies on the information stored in its database. You'd therefore have to rescan your playlists for LMS to pick up the changes.

**Comment by bungh0l10** [comment]
OK, I'll work with daily rescan and LMS:9000/settings/index.html?p0=rescan&p1=playlists then.
