### ISSUE TITLE
Track rating metadata on LMS >= 8.x

### ISSUE THREAD

**Issue by hctom** [LMS-Community/slimserver#527]
I am currently setting up a new LMS instance using >= 8.1. and I run into problems regarding reading rating metadata from audio tracks. For 7.x there were the TrackStat and CustomScan plugins, but those are only installable manually with 8.x and they also seem to have some issues with the new version (e.g. see #422).

Are there any known alternatives to those plugins that may provide the same functionality (reading rating metadata from audio files to be able to run SQL queries against these values to generate top rated track lists) or is this something that may be introduced to LMS core in the near future?

I'd appreciate your feedback & thanks for all the hard work!

**Comment by michaelherger** [comment]
8.2 has support for no longer maintained plugins like some of Erland's. It's not released yet, but you might want to give it a try anyway. 

I'd recommend you visit forums.slimdevices.com: there is an alternative rating plugin actively being developed right now. And you get better feedback there as it's the place where the community gathers.

**Comment by hctom** [comment]
@michaelherger Thanks for your feedback. I'll try it over there and I guess you are talking about the **Ratings light plugin**? If so, this one does not really meet my requirements as far as I understand from all the explanations as it is for rating tracks via the LMS UI.. but I only want to be able to read/use what is saved in the tracks themselves... but I'll give the 8.2 LMS a try to see if the CustomScan plugin works there.
