### ISSUE TITLE
Plugin file permissions

### ISSUE THREAD

**Issue by mavit** [LMS-Community/slimserver#528]
For my LMS plugin, I'm using GitLab to [automatically pack the latest Git commit into a downloadable zip](https://gitlab.com/mavit/lms-mixlr/-/blob/master/.gitlab-ci.yml).  It turns out that the default GitLab umask was 0000, and this was carrying over to the permissions of files inside my zip.  When LMS downloads and installs the plugin, it respects these permissions, with the outcome that the files for my plugin were all `a=rw`.

This doesn't seem like something that anyone would ever want.  Would it be a sensible precaution to reset the permissions to, say, `u=rw,go=r` when unpacking?

**Comment by michaelherger** [comment]
I'm always a bit hesitant to "fix" issues which haven't been seen in a decade... in particular when they scream "platform support!", too 😀. Would you have a one line fix for this ready to be tested?

**Comment by mavit** [comment]
I'm afraid it stretches to five lines, including a comment.  See https://github.com/Logitech/slimserver/commit/e36c865328d92de6447d39ecf43239b555572846.
