### ISSUE TITLE
Load errors DBI

### ISSUE THREAD

**Issue by theking2** [LMS-Community/slimserver#53]
After an update of Arch, which did update Perl as well I can't start LMS 7.9 anymore. Not sure if LMS comes with it own Perl, but perl --version gives:

This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi

slimserver --d_startup inlcudes this is the error
...
Loaded module: [version] ok!
Loaded module: [Time::HiRes] ok!
Module [DBI] failed to load:
DBI object version 1.633 does not match $DBI::VERSION 1.616 at /usr/lib/perl5/core_perl/DynaLoader.pm line 216.
BEGIN failed--compilation aborted at /opt/slimserver-public-7.9/CPAN/DBI.pm line 268.
Compilation failed in require at (eval 11) line 1.
BEGIN failed--compilation aborted at (eval 11) line 1.
...
Rename the Cache folder doesn't help.

**Comment by theking2** [comment]
In fact downgrading to 5.20 did allow LMS starting normally. 

pacman -Ud /var/cache/pacman/pkg/perl-5.20.2-1-x86_64.pkg.tar.xz

**Comment by stefansielaff** [comment]
There are precompiled binary objects of perl modules for different platforms delivered with slimserver. There are no precompiled versions for Perl 5.22 available here yet.
So you'll have to compile them yourself (look at slimserver-vendor), or wait for someone to provide them here, or install lms via AUR (https://aur.archlinux.org/packages/logitechmediaserver) where I try to take care of some of these problems ;)

**Comment by theking2** [comment]
thanks for your answer, stefan. and for pointing out the update on AUR. I had installed the git package as there was silence in AUR LMS some time ago. Good that you took this up again.!

As I don't think I have other Perl dependent software in my Arch box I'm fine with 5.20 for the time being. But i'd be curious to know what the show stopper of 5.22 is.

**Comment by mherger** [comment]
5.22 isn't a real show stopper. It's just latest code for which binaries haven't been added to the LMS repository yet. But as Stefan has outlined, they can be compiled.

This is not a bug, but a re-occurring issue whenever there's a new Perl version/OS/architecture combination. Of which there are too many for LMS to handle in a good way, unfortunately.
