### ISSUE TITLE
play WavPack DSD the duration is wrong

### ISSUE THREAD

**Issue by aeeq** [LMS-Community/slimserver#534]
play WavPack DSD the duration is wrong,duration change short

**Comment by philippe44** [comment]
Well... what is certainly short is your explanation. If your want support, you have to describe a bit better the problem & the environment!

**Comment by terual** [comment]
Please also check your Audio::Scan version in the Information tab in the Settings page and post it here.

**Comment by aeeq** [comment]
play the same song
LMS:
![LMS](https://user-images.githubusercontent.com/8926331/107744603-f5e0ec80-6d4d-11eb-83b2-74deeeeb48c5.png)
MPD:
![MPD](https://user-images.githubusercontent.com/8926331/107744606-f8434680-6d4d-11eb-830e-3df5fabb49a2.png)

Logitech Media Server Status
Logitech Media Server Version: 8.1.1 - 1610364019 @ Thu Jan 14 06:27:19 CET 2021
Hostname: aeeq-bswp1
Server IP Address: 192.168.2.19
Server HTTP Port Number: 9000
Operating system: Linux - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.32.0 - x86_64-linux-thread-multi
Audio::Scan: 1.02
IO::Socket::SSL: 2.069
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)
Total Players Recognized: 1

**Comment by terual** [comment]
Based on the file length indeed the MPD duration seems more plausible. Do you have this issue just with this file? Do other WavPack DSD files have the correct duration?

**Comment by aeeq** [comment]
Yes,so are the other files.

**Comment by terual** [comment]
Could you share a WavPack DSD file where the duration is incorrect?

**Comment by aeeq** [comment]
dff file info
General
Complete name                            : Cembalo Deluxe Vol. 2.dff
Format                                   : DSDIFF
Format/Info                              : Direct Stream Digital Interchange File Format
Format version                           : Version 1.5.0.0
File size                                : 1.26 GiB
Duration                                 : 32 min 2 s
Overall bit rate                         : 5 645 kb/s
Album                                    : Cembalo Deluxe Vol. 2
Track name                               : Beat Time With The Hand
Track name/Position                      : 12
Performer                                : Cembalo Deluxe Vol. 2
Genre                                    : Other
Recorded date                            : 2014-17-09
Writing application                      : SACD Ripper release 0.38 Copyright (c) 2010-2015 by respective authors. /  / Report bugs to mr_wicked@hotmail.com
Comment                                  : Material ripped from SACD: Cembalo Deluxe Vol. 2

Audio
Format                                   : DSD
Format/Info                              : Direct Stream Digital
Commercial name                          : DSD64
Format settings                          : Big
Duration                                 : 32 min 2 s
Bit rate                                 : 5 645 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 2 822 kHz
Compression mode                         : Lossless
Stream size                              : 1.26 GiB (100%)

wv file
File Format: WavPack DSD
Duration: 6:40
Bitrate: 13922kbps VBR
Sample Rate: 2822.4 kHz
Sample Size: 1Bits
File Length: 696,793,736
Location: /home/aeeq/Downloads/Cembalo Deluxe Vol. 21.wv

download link
[https://onedrive.live.com/embed?cid=8FDF6DDA6B54C329&resid=8FDF6DDA6B54C329%21636&authkey=APWRoprsOMYXVZQ](url)

**Comment by terual** [comment]
It seems to be a problem in Audio::Scan

The info from the wavpack file:
```
$VAR1 = {
          'audio_size' => 696793736,
          'file_size' => 696793736,
          'audio_offset' => 0,
          'encoder_version' => 1040,
          'bitrate' => 13922300,
          'song_length_ms' => 400390,
          'total_samples' => 1130061824,
          'channels' => 2,
          'lossless' => 1,
          'samplerate' => 2822400,
          'bits_per_sample' => 1,
          'jenkins_hash' => 1973334605
        };
```

The info from the decompressed dff file:
```
$VAR1 = {
          'bitrate' => 5644814,
          'id3_version' => 'ID3v2.3.0',
          'audio_size' => 1356257280,
          'tag_diar_artist' => 'Cembalo Deluxe Vol. 2',
          'song_length_ms' => 1922133,
          'channels' => 2,
          'bits_per_sample' => 1,
          'jenkins_hash' => 2820175086,
          'samplerate' => 2822400,
          'file_size' => 1356260682,
          'audio_offset' => 144,
          'tag_diti_title' => 'Cembalo Deluxe Vol. 2'
        };
```
In the latter the correct song_length_ms is given.

**Comment by mherger** [comment]
Please submit an issue with Audio::Scan (https://github.com/andygrundman/Audio-Scan/issues)
