### ISSUE TITLE
adding track to playlist (CLI) duplicates displayed comment tag info

### ISSUE THREAD

**Issue by AF-1** [LMS-Community/slimserver#535]
When you add a track to a playlist using

`Slim::Control::Request::executeRequest(undef, ['playlists', 'edit', 'cmd:add', 'playlist_id:'.$playlistid, 'url:'.$trackURL]);`

the **comment tag of the added track** (as displayed in the LMS context menu/song details) 
goes from "EXAMPLESTRING" to "EXAMPESTRING / EXAMPLESTRING". 
Furthermore, whenever you repeat the command yet **another** "/ EXAMPLESTRING" is appended.

The file tag info and the info in the LMS database comments table remain unchanged (=correct and not duplicated).

Might have sth to do with Slim::Schema::Track:comment.

**Comment by mherger** [comment]
More details in #781.
