### ISSUE TITLE
If you create an album browse mode AND filter by contributor role, sorting by artist doesn't work any more

### ISSUE THREAD

**Issue by michaelherger** [LMS-Community/slimserver#536]
From http://forums.slimdevices.com/showthread.php?t=113980:

> I was trying to find a way to browe mi hi res albums and found one
Creating a entry HI Res in custom browse, selecting COMPOSER having
previously tagged all my HI Rest Albums with FLAC24 tag as composer.
The menu appears and i see all mųy hi res albums
But the pb is that they do appear in orders that never start with artist
despite i choose it

![ext browse mode](https://forums.slimdevices.com/attachment.php?attachmentid=33444&d=1613732719)
![](https://forums.slimdevices.com/attachment.php?attachmentid=33445&d=1613732745)

**Comment by mherger** [comment]
The problem is that the relationship between album and contributor is done based on the role the contributor has (composer in your case). Therefore the sorting happens on the composer, rather than the album artist shown. But that role currently isn't shown. Therefore the confusing result.
