### ISSUE TITLE
Installation.txt

### ISSUE THREAD

**Issue by theking2** [LMS-Community/slimserver#54]
The Installation.txt file says:"Version 5.10.0 or higher of Perl is required." but it would be helpful which Perl version is supported. 5.22 is not. 

Please update the the Installation.txt file to include what the lowest and highest version of Perl is required to run slimserver.

**Comment by mherger** [comment]
Please read the first paragraph "Generic notes". Just because we don't provide binary modules for a new perl and/or OS version, or CPU architecture and combination of them all, doesn't mean it doesn't run there. You just might need to build binaries yourself.
