### ISSUE TITLE
Long LMS client playlist disappears during wipe and rescan

### ISSUE THREAD

**Issue by jrfinlay** [LMS-Community/slimserver#554]
An existing long (>2000 entries) client playlist disappears from the browser display after starting a full wipe and rescan of the music library. The process to illustrate this behavior is:

1. With LMS running and an empty playlist for a player, add 2000+ files to the playlist which creates a clientplaylist file in /var/lib/squeezeboxserver/prefs containing references like:

```
#EXTURL:file:///music/Music/Jazz/Keiko%20Matsui/A%20Drop%20of%20Water/01%20Ancient%20Wind.wav
#EXTINF:382,Ancient Wind
/music/Music/Jazz/Keiko Matsui/A Drop of Water/01 Ancient Wind.wav
#EXTURL:file:///music/Music/Jazz/Keiko%20Matsui/A%20Drop%20of%20Water/02%20Light%20above%20the%20Trees.wav
#EXTINF:288,Light above the Trees
/music/Music/Jazz/Keiko Matsui/A Drop of Water/02 Light above the Trees.wav
```

2. Start a full wipe and rescan which first rewrites the clientplaylist in prefs with tmp:// urls similar to:

```
#EXTURL:tmp:///music/Music/Jazz/Keiko%20Matsui/A%20Drop%20of%20Water/01%20Ancient%20Wind.wav
#EXTINF:382,Ancient Wind
tmp:///music/Music/Jazz/Keiko%20Matsui/A%20Drop%20of%20Water/01%20Ancient%20Wind.wav
tmp:///music/Music/Jazz/Keiko%20Matsui/A%20Drop%20of%20Water/02%20Light%20above%20the%20Trees.wav
```

3. Shortly after the clientplaylist is rewritten with tmp:// urls, the browser display is automatically refreshed and all the playlist entries disappear similar to the image in:

[https://forums.slimdevices.com/showthread.php?114177-LMS-can-t-display-playlist&p=1015416&viewfull=1#post1015416](url)

4. After the rescan is complete, the clientplaylist still contains just tmp:// urls as above.

5. Neither a forced refresh of the browser page or restarting LMS will cause a correct browser display of the playlist though the playlist will play properly. No files can be added to the playlist and there is no way to clear the playlist from the browser.

6. Stop LMS and edit the clientplaylist to change 'tmp://' to 'file://' and the entries look like:

```
#EXTURL:file:///music/Music/Jazz/Keiko%20Matsui/A%20Drop%20of%20Water/01%20Ancient%20Wind.wav
#EXTINF:382,Ancient Wind
file:///music/Music/Jazz/Keiko%20Matsui/A%20Drop%20of%20Water/01%20Ancient%20Wind.wav
file:///music/Music/Jazz/Keiko%20Matsui/A%20Drop%20of%20Water/02%20Light%20above%20the%20Trees.wav
```

7. Start LMS and soon the browser window is refreshed and the playlist is displayed correctly. The clientplaylist still contains file:// urls.

**Comment by michaelherger** [comment]
Should be fixed in 8.2 - please give it a try.
