### ISSUE TITLE
Error with < in Album / Artist name in Default Skin

### ISSUE THREAD

**Issue by pascalberger** [LMS-Community/slimserver#57]
I've a mp3 file containing the following tags:

```
Artist Name : <kaeb
Album Artist : Beak>; <kaeb
Album Title : Beak> / <kaeb Split Ep
```

LMS scans the file and seems to read the tags correctly (they are shown correctly in SqueezeCommander on Android). But the default skin fails to show the info correctly:

```
ARTIST:
ALBUM ARTIST: Beak>;
ALBUM: Beak> /
```

It seems like the skin has a problem with the leading < in the artist name.

**Comment by mherger** [comment]
What LMS version are you running?

**Comment by pascalberger** [comment]
I currently don' t have access to the server at the moment. But it is a 7.9 build from a few weeks ago. I can let you know the exact version later tonight.

**Comment by mherger** [comment]
Ok, I fixed a bunch of related issues. Please update to tomorrow's build and let me know if you still encounter any issues. Thanks!

**Comment by pascalberger** [comment]
@mherger Thanks, fixed it
