### ISSUE TITLE
jsonrpc - error calling favorites add/addlevel without a player

### ISSUE THREAD

**Issue by timbell** [LMS-Community/slimserver#614]
`Slim/Plugin/Favorites/Plugin.pm

The call to [showBriefly](https://github.com/Logitech/slimserver/blob/ae5465d35f8e1783f7f972ba5fae21b7c7e25362/Slim/Plugin/Favorites/Plugin.pm#L894) in `cliAdd` needs to be protected by the same test as is present in `cliDelete`:

```
# show feedback if this action came from jive cometd session
if ($request->source && $request->source =~ /\/slim\/request/) {
  ...
  $client->showBriefly({
  ...
}
```

Otherwise you get an error like this when calling `favorites add/addlevel` without a player:

```
[21-06-09 16:38:44.9130] Slim::Control::Request::execute (1888) Error: While trying to run function coderef [Slim::Plugin::Favorites::Plugin::cliAdd]: [Can't call method "string" on an undefined value at D:/dev/slimserver/Slim/Plugin/Favorites/Plugin.pm line 898.
```

**Comment by michaelherger** [comment]
Would you have a simple way to reproduce the error?

**Comment by timbell** [comment]
Yes, navigate to your server (eg http://192.168.1.23:9000) in the browser and open "Developer tools". In the console, paste the following and hit return:
```
var player = ''; // set to a player MAC to avoid error
var levelName = 'test'; // name of folder to create in favorites
fetch(`${location.origin}/jsonrpc.js`, {
    method: 'POST',
    cache: 'no-cache',
    headers: {
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({
        method: 'slim.request',
        params: [player, ['favorites', 'addlevel', `title:${levelName}`]]
    })
})
    .then(response => response.json())
    .then(data => console.log('Success:', data))
    .catch(error => console.log('Error:', error));
```
Without the fix the error will occur. I also get multiple "test" folders created. With the fix, or if you set a player MAC then the folder is created fine without any error.

**Comment by michaelherger** [comment]
Oh, if you have the fix coded already, could you please provide a pull request? Thanks!

**Comment by michaelherger** [comment]
Unfortunately my build host isn't responding any more. And I fear I won't get "remote hands" to the datacenter where it's running (hanging...) before the weekend.
