### ISSUE TITLE
Deezer playlists don't work properly when added as presets (tested on baby)

### ISSUE THREAD

**Issue by kalon33** [LMS-Community/slimserver#623]
When you add a Deezer playlist as preset on baby, it won't play when you call it from the button.

**Comment by kalon33** [comment]
It's the same when adding them as favorites in fact

**Comment by mherger** [comment]
Can you give me an example URL? You can use the Presets Editor plugin to get to it.

**Comment by kalon33** [comment]
for example deezer://257190201.dzl (when choosing preset from listed deezer playlists) or https://www.mysqueezebox.com:443/api/deezer/v1/opml/album_tracks?artist_name=Scorpions&name=Born%20To%20Touch%20Your%20Feelings%20-%20Best%20of%20Rock%20Ballads&id=51337612 (when choosing preset from Favorites an album I saved as Favorites in LMS, from Deezer Favorites Album list).

**Comment by mherger** [comment]
I guess you're running LMS on Linux and would be able to modify a file to test something? Would the following work for the first case?

```diff
diff --git a/Slim/Plugin/Deezer/ProtocolHandler.pm b/Slim/Plugin/Deezer/ProtocolHandler.pm
index 9dfa0d822..3357d2cbe 100644
--- a/Slim/Plugin/Deezer/ProtocolHandler.pm
+++ b/Slim/Plugin/Deezer/ProtocolHandler.pm
@@ -200,6 +200,10 @@ sub explodePlaylist {
                }
        }
 
+       if ($url =~ m{^deezer://([0-9a-z])\.dzl}) {
+               $url = 'deezer://playlist:' . $1;
+       }
+
        my $tracks = [];
 
        if ( $url =~ m{^deezer://((?:playlist|album|artist):[0-9a-z]+)}i ) {
```

**Comment by kalon33** [comment]
yep, I'm running it on a Raspberry Pi with Raspbian. I looked at the exact path from the deb package and found `/usr/share/perl5/Slim/Plugin/Deezer/ProtocolHandler.pm`. I added the relevant code lines at the proper place in the file with correct indentation, but it seems to have no effect. I have the playlist name displayed on the Radio, "retrieving track information" (the message is in French but I imagine that's something like that in English) is displayed for a few seconds, and that's all.

**Comment by mherger** [comment]
Did you try with both types of URLs? The suggested fix would only be for the deezer://257190201.dzl case. If you want to simplify the testing you could paste such a URL in the "Tune in to..." field in the Radios section.

**Comment by kalon33** [comment]
I tested the first one, deezer://257190201.dzl

**Comment by michaelherger** [comment]
Ok, that needed a little more work (besides fixing a small but important mistake in the above regex...). But playing `deezer://*.dzl` URLs should work now. The others are a bit more involved. I'll see what I can do there.

**Comment by kalon33** [comment]
Awesome! Just tested, that also works properly here for these ones :)
