### ISSUE TITLE
Unable to save favorites in mysqueezebox.com, missing error message

### ISSUE THREAD

**Issue by viertelb** [LMS-Community/slimserver#635]
I tried to save the term `randomplay://tracks?genres=rock` in [https://mysqueezebox.com/settings/favorites](https://mysqueezebox.com/settings/favorites) but this does not work, and it also does not show an error message.

If I try to add a valid URL that is unable to respond, the website does sometimes return a message that it tried to verify the connection but failed. Sometimes it does not show anything.

(1) There should better be always a message. 

(2) It would be good to beeing able to add a LMS-specific command like `randomplay://tracks?genres=rock` to the favorites.

**Comment by michaelherger** [comment]
The URL you're trying to add is a LMS only URL. mysqueezebox.com doesn't have a concept of a music library, therefore there are no "tracks" available.

Why would you want to have this URL on mysqueezebox.com?

**Comment by viertelb** [comment]
I was thinking I could add it to the mysqueezebox.com favorites and start it from a LMS that has its own library by going in the web GUI to Hauptmenü->Favorites->auf mysqueezebox.com->.

This way I could save it and if I setup a new server I can connect to mysqueezebox.com and have my custom presets availlable.

I can then long press on the physical device to easily add this URL as a shortcut to the physical Schnellwahltaste (EDIT: Actually, I am not sure if this works with the random preset URL).

But I know since you told me last week that favorites are easily editable in the GUI. So, it is not very necessary to have this. But it would be a good backup.
