### ISSUE TITLE
mysqueezebox.com has an option to change buffer size of a player, which seems to be missing in the LMS

### ISSUE THREAD

**Issue by viertelb** [LMS-Community/slimserver#636]
Not sure if this is an issue but I found this interesting setting for the "buffer size for internet stream" of a specific player under "Network": https://mysqueezebox.com/player/viewPlayers

I was searching for such a setting in the LMS server setup for a player but could not find it.

**Comment by mherger** [comment]
In LMS go to Settings/Advanced/Networking/Buffer size (or similar - "Puffergrösse" in German).

Please use forums.slimdevices.com for user questions like this. Thanks!
