### ISSUE TITLE
Explicit port in stream URL not being handled properly

### ISSUE THREAD

**Issue by polyfloyd** [LMS-Community/slimserver#64]
When attempting play a HTTP stream and the port has been explicitly set in the URL, the port part is not separated form the host part. Because of this, Slim will attempt use a host:port format to look up the host.

Form the log:

```
[15-12-13 23:28:14.4653] Slim::Utils::Scanner::Remote::__ANON__ (193) Error: Can't connect to remote server to retrieve playlist for, http://127.0.0.1%3A3000/data/raw%3Ftrack%3D548133509: Couldn't resolve IP address for: 127.0.0.1:3000.
```

Version: 7.9 (cc50c1b0)

**Comment by mherger** [comment]
Are you sure you didn't accidentally URI encode the colon in the host:port part? That's what I'm seeing from above message. Please copy paste the url here.

Enable debug logging for scan.scanner and re-try to play the stream. Then provide your server.log file (not only the one line you consider crucial - all of it).

**Comment by polyfloyd** [comment]
Ah, yes. The encoding seemed to be the issue. My URI encoder was indeed encoding the `:`. I must have misinterpreted the error message since the `:` appears to be decoded.

Anyway, thank you for your time.
