### ISSUE TITLE
Typo in help text for Browse Artists.

### ISSUE THREAD

**Issue by mfraser** [LMS-Community/slimserver#640]
The help text is currently:
Choose whether you want to use a single, configurable artists list, or two lists for Album Artists and All Artists. Album Artists is a list where Album Artist is the sole artist on an album or is the artist specified in the ALBUMARTIST tag. All Artists is a list of every artist that appears in a contributor role tag (ARTIST, COMPOSER etc.). The single, configurable list of artists on the other hand let's you define which contributor roles should be part of the Artists menu.

The "let's you define..." should be "lets you define..." as lets means allows not let us.

**Comment by michaelherger** [comment]
Thanks!
