### ISSUE TITLE
Please provide CPAN for Perl 5.34

### ISSUE THREAD

**Issue by alastair-dm** [LMS-Community/slimserver#642]
Gentoo just pushed perl 5.34 to stable, although earlier versions remain available so it's not yet a show stopper. Fedora 35 is due to be using 5.34 when it's released on October. I don't know what timetable other linux distros are on, but it probably won't be long before others need 5.34.

**Comment by fsoc** [comment]
This is also a problem for all arch linux users, please fix this!

**Comment by michaelherger** [comment]
Did you try to build yourself from https://github.com/Logitech/slimserver-vendor/tree/public/8.0/CPAN?

**Comment by fsoc** [comment]
Rebuilding 8.1.1 worked well for me, thanks for the tip.

**Comment by RobertCL** [comment]
How did you manage to build 8.1.1?  I only see 8.0, 8.2 and 8.3 in the branches list and all fail for me when running buildme.sh with a SQLite error.

`Can't load '/opt/logitechmediaserver/CPAN/arch/5.34/auto/DBD/SQLite/SQLite.so' for module DBD::SQLite: /opt/logitechmediaserver/CPAN/arch/5.34/auto/DBD/SQLite/SQLite.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE at /usr/lib64/perl5/5.34/x86_64-linux-thread-multi/DynaLoader.pm line 193.`

**Comment by alastair-dm** [comment]
After finding a suitable machine to test on I ran into what looks to be the same problem as @RobertCL but haven't dug any further yet.

**Comment by gloomytrousers** [comment]
In case any Fedora 35 users find this, here's the step-by-step instructions to work around (with [version 8.3](http://downloads.slimdevices.com/nightly/index.php?ver=8.3) on x86_63):
```shell
sudo dnf install nasm # You may need other deps listed on https://github.com/Logitech/slimserver-vendor/tree/public/8.3/CPAN
git clone git@github.com:Logitech/slimserver-vendor.git # Slow
cd slimserver-vendor/CPAN
git checkout public/8.3
./buildme.sh # Very slow
sudo cp -r build/arch/5.34/x86_64-linux-thread-multi /usr/share/squeezeboxserver/CPAN/arch/5.34/
```

**Comment by bernd-ol** [comment]
My experience by generating CPAN in a fresh installed Fedora 35:

> In case any Fedora 35 users find this, here's the step-by-step instructions to work around (with [version 8.3](http://downloads.slimdevices.com/nightly/index.php?ver=8.3) on x86_63):
> 
> ```shell
> sudo dnf install nasm # You may need other deps listed on https://github.com/Logitech/slimserver-vendor/tree/public/8.3/CPAN
sudo dnf install zlib-devel # 
> git clone git@github.com:Logitech/slimserver-vendor.git # Slow
works only with github account, without account use:
git clone https://github.com/Logitech/slimserver-vendor.git
> cd slimserver-vendor/CPAN
> git checkout public/8.3
> ./buildme.sh # Very slow

# buildme finished with error: "xlocale.h not found". This error is patched in 2018! After reading some
# hundreds lines of output I found the reason of the error: the command "patch" was not installed.
sudo dnf install patch  # and buildme finish with success!!

> sudo cp -r build/arch/5.34/x86_64-linux-thread-multi /usr/share/squeezeboxserver/CPAN/arch/5.34/
> ```
# eventually LMS 8.3 works without problem under Fedora 35

**Comment by alastair-dm** [comment]
This should have been fixed by https://github.com/Logitech/slimserver/commit/4e5f5b45198f28388e6de6a09f983cb5590538a8 and https://github.com/Logitech/slimserver/commit/4b7240703a7f2f01023d19e76ab3b95179e99401 but I haven't tried it on Gentoo yet.

**Comment by gloomytrousers** [comment]
Tested the latest [nightly](http://downloads.slimdevices.com/nightly/index.php?ver=8.3) (8.3.0-0.1.1647754697 RPM) on Fedora 35. All looks good.

Remember to remove the manually-copied /usr/share/squeezeboxserver/CPAN/arch/5.34 before installing, otherwise you'll be left with files not managed by your package manager.

**Comment by psaffrey** [comment]
Sorry to comment on a closed issue, but is there any chance you could start baking Perl 5.34 support into the released debs and rpms? The most recent Fedora (36) and Ubuntu (22) both come with Perl 5.34.

Edit: I've been using `buildme.sh` but it's a shame to require `gcc`, `g++` and `yasm` just to get the LMS working. Happy to work on a PR if you give me a few pointers.

**Comment by mherger** [comment]
I guess you're on an ARM based platform?

**Comment by psaffrey** [comment]
@mherger No, I'm on x86_64.

**Comment by michaelherger** [comment]
LMS 8.3 should support Perl 5.34 on x86_84 out of the box: https://github.com/Logitech/slimserver/tree/public/8.3/CPAN/arch/5.34/x86_64-linux-thread-multi/auto

**Comment by psaffrey** [comment]
Fantastic, thank you. I guess I was caught out by downloading my copy of LMS from here:

https://www.mysqueezebox.com/download

Where the supplied version is 8.2. For others finding this, 8.3 (and other versions) are found here:

https://downloads.slimdevices.com/nightly/index.php?ver=8.3

**Comment by alastair-dm** [comment]
Coincidentally I was going to revisit this after hearing of people having problems with LMS on recent OS versions for the Raspberry Pi. I hadn't thought about other architectures when I suggested it was probably fixed.

**Comment by mherger** [comment]
This issue can't really be "fixed". As soon as there's a new OS version or Perl version we'd have to compile for all possible permutations of the two plus any possible hardware platform. Not only would this be a huge effort, but it's also not reasonable to ship binaries for platforms which only a hand full of people are using. 

I'm not saying x86_64 was such a platform of course. But PowerPC or ARMv5 once were a thing, but aren't relevant any more in our context, for example.

**Comment by alastair-dm** [comment]
I wondered if OBS could help with this, but its support for other architectures is limited:
https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets

What would you need people to submit to get a new platform/arch combination included? Is it just the content of `build/arch/{Perl version}/{your architecture string}/ ` after building from https://github.com/Logitech/slimserver-vendor/tree/public/8.3/CPAN (or whatever the latest branch is at the time) or are other actions needed?

**Comment by michaelherger** [comment]
First of all it's a good number of requests. As I sad I wouldn't include binaries unless I see a real need by a good number of users. As long as the vast majority of LMS on Pi users is running pCP or Raspbian, that will be what I'll concentrate on (well, pCP is maintained by the pCP guys). 

And then I'm hesitant to include binaries from third parties for security reasons: an evil guy could submit a PR with infected binaries, or libraries with "enhanced" functionality.

**Comment by alastair-dm** [comment]
That's understandable. I guess anyone frustrated by this should put their efforts into #138
