### ISSUE TITLE
playback time problem

### ISSUE THREAD

**Issue by cshin1213** [LMS-Community/slimserver#645]
Hi everyone:
I have used LMS for 2-3 months and found 3 unusual problems.
So I hope someone could fix these problems. (Please endure my poor English writing)

1. Track time synchronization problem with Hires music file : It's only happen with hires music file (>44.1). The track time is not correct with the actual time while I jump the track time location. If I change the track time to the last couple seconds and keep the playback to the end, the display of track time is the same as the actual music play time. After the actual music playback ends, I have to wait for several seconds or minutes to the next track. 
2. Spotify connect problem : With using spotify connect, while I move the slider to the last couple seconds, it's fine to change the track time and play, but after the end of the track, the player sometimes  skips the next song and play the "next next" track.
3. Spotify connect time synchronization issue : With spotify connect, the track time will not synchronize with the music while it's ok to use the material skin.

**Comment by michaelherger** [comment]
Spotty is a bit weird. But that's not a LMS issue.

As for the LMS issue would you mind posting to forums.slimdevices.com?

**Comment by cshin1213** [comment]
Thanks for reply.
No problem, I will post to the forum.
