### ISSUE TITLE
Libs for perl 5.22 armv7l-linux-thread-multi-64int missing

### ISSUE THREAD

**Issue by jgrulich** [LMS-Community/slimserver#66]
Please add libs for perl 5.22 for armv7l-linux-thread-multi-64int.

**Comment by mherger** [comment]
What hardware/operating system are you running this on?

**Comment by paul-1** [comment]
This is for rpi/piCore.   Picore 7 comes with perl 5.22.   While the perl version stated armv7l, this perl was actually armv6 compatable.  We have built perl 5.20.3 that works, although we hunted all weekend for armv6 CPAN libraries.  Looks like you just pushed them to git.   Will test

**Comment by jgrulich** [comment]
We're running it on the piCore armv6, Raspberry board B and B+ as Paul 
already stated.
For continuous support we need to have the LMS CPAM modules compatible with 
the latest perl, now 5.22.1
and have it compatible for both board versions RPi1 armv6 and Rpi2 armv7.

Even the 5.20.3 which we're using need to use the older CPAN LMS modules 
dated 2015-11-04.
The last LMS ones, which are in the nightly build run only on the armv7, 
means on the RPi2 board.
When run on the B, or B+, it reports error during startup: "Illegal 
Instruction".

---------- Původní zpráva ----------
Od: mherger notifications@github.com
Komu: Logitech/slimserver slimserver@noreply.github.com
Datum: 25. 1. 2016 8:45:08
Předmět: Re: [slimserver] Libs for perl 5.22 armv7l-linux-thread-multi-64int
missing (#66)

"

What hardware/operating system are you running this on?

—
Reply to this email directly or view it on GitHub
(https://github.com/Logitech/slimserver/issues/66#issuecomment-174429333). 

"=

**Comment by mherger** [comment]
Have you tried to build the binaries using https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN? It should be straight forward. The build for 5.20 took a while on a Pi2, but it just run.

The latest binaries I committed a day or two ago do work on my 1st generation Pi. Tested this on two different devices running Raspbian Jessie.

**Comment by stefansielaff** [comment]
I don't know if this is on topic but maybe it might help:

To make this work on Arch Linux (ARM) (on perl 5.22 for quite a while) I had to remove the distributed CPAN/version module.
Also had to pull in the distros perl-cgi package on installation.

**Comment by paul-1** [comment]
I will check the armv6 binaries for perl 5.20 on the slimserver git tree,   I glanced at them last night, and they appear to be the same that jgrulich mentioned.

Note Rasbian-jesse is still using 5.20,   the maintainers at piCore, normally try to stay more current with builds.  That was why we were looking for 5.22 support.  However, I see a bigger issue with the archname built into perl at compile time.  Is there anyway to a perl that reports as armv7l-linux-thread-multi-64int to know that it can use CPAN modules listed as arm-linux-gnueabihf-thread-multi-64int

or is that just a limitation of perl that we have to live with?

**Comment by jgrulich** [comment]
I've tested the last git version and now it works at RPi B board, means that the issue in CPAN modules was solved for 5.20 perl.

**Comment by mherger** [comment]
@paul-1 - I'll ask again: did you try to compile the modules as outlined in one of my previous comments? Should really be straightforward and you'd no longer depend on the main repository. As you're building your own "distribution", I think that would be a reasonable approach.

**Comment by paul-1** [comment]
I have tried, but never got past the image scaling part.  it would build, but always fail testing on arm.

Anyway, I think we are good for now, we have a fully working version distro with perl 5.20.3

**Comment by jgrulich** [comment]
For Image Scaling need to be used only libpng, libjpeg-turbo is not 
compatible.

**Comment by mherger** [comment]
I updated Image::Scale a few days ago to fix those build issues. Please give it another try (Image::Scale 0.11). You can test Image::Scale before doing the whole bunch:

```
 ./buildme.sh Image::Scale
```

**Comment by paul-1** [comment]
I'll give it a shot.

**Comment by paul-1** [comment]
Compiled and built fine.  slimserver started just fine.

**Comment by mherger** [comment]
Good to know, thanks!

**Comment by paul-1** [comment]
Forgot to mention that I had to manually copy Image/Scale.pm in to the 5.22/arm-linux/  folder to allow for version 0.11 instead of the old v0.08

I copied the file out of the 5.20/arm-linux..... folder.

**Comment by mherger** [comment]
Good point. I should look into this for the build script.

**Comment by mherger** [comment]
@paul-1 - I only just saw your discussion in the TC forums. WRT. to data folders etc.: you might want to look into this wiki article about how to customize your LMS installation using a custom OS specific module:

http://wiki.slimdevices.com/index.php/Customizing_Logitech_Media_Server_using_Slim::Utils::OS::Custom

We have such modules for most major OS or distributions to define default behavior. This could be helpful for your use-case, too?

**Comment by paul-1** [comment]
That's interesting.    I'll have to look into that.   The symlinks seem to work well, and is probably easier for a user to alter a Shell Script.   Thanks for the info.

**Comment by mherger** [comment]
Now that we have 5.24 binaries (thanks @paul-1 !), is there still a need for 5.22?

**Comment by paul-1** [comment]
I do have these binaries , but I don't see a need to add them anymore.    Perl 5.22 was used on piCore 7. (pCP 2.0)  PiCore 8 and 9 use Perl 5.24.  I'm not aware of any other common OS that uses 5.22

**Comment by mherger** [comment]
Thanks!
