### ISSUE TITLE
'Advanced genre replacement' link in 'Online Music Library Integration'

### ISSUE THREAD

**Issue by CDrummond** [LMS-Community/slimserver#679]
In the server settings page for 'Online Music Library Integration' there is a 'Advanced genre replacement' link. This link works fine in Default skin - where it links to 'http://SERVER:9000/Default/plugins/OnlineLibrary/editMappings.html' But if the Classic skin is used ('http://SERVER:9000/Classic') this link fails, as it points to 'http://SERVER:9000/Classic/settings/server/editMappings.html'

As MaterialSkin uses Classic for settings pages, this also fails there.

Changing the link in 'Slim/Plugin/OnlineLibrary/HTML/EN/plugins/OnlineLibrary/settings.html' to 'plugins/OnlineLibrary/editMappings.html' seems to resolve the issue - and the link works in Default, Classic, and Material. But note when hovering the link (in Default) it shows as 'http://SERVER:9000/Default/plugins/OnlineLibrary/plugins/OnlineLibrary/editMappings.html' - which looks odd, but seems to work.

**Comment by michaelherger** [comment]
Good catch! I guess this should be something like ˋ[% webroot %]plugin/...ˋ. Will give that a try tomorrow.

**Comment by michaelherger** [comment]
Thanks for the hint!
