### ISSUE TITLE
Json RPC api messed up for IP and model

### ISSUE THREAD

**Issue by an0Nym0us63** [LMS-Community/slimserver#693]
Hello i'm using the json RPC api which works very fine but i discovered an issue 

Each request for model and ip using  player model ?  or player ip ? results in the same result whatever ref i use

It's just like it was answering the data of only one player whatever ref i pass.

every other requests i tested gave me results depending on the player i want but for IP and MODEL whatever player i get the same results for all of my players

Thanks

**Comment by michaelherger** [comment]
Can you provide some example snippets how you're calling the request, and the results you get? Eg. using the `curl` tool?

**Comment by an0Nym0us63** [comment]
Of course Michael. You are right i'm pretty conviced i don't use the right syntax for those specific name/ip/model stufff. I'm just suprised as i really get a good formated response.


request : {"id":43,"method":"slim.request","params":["00:04:20:28:6c:0e",["player","model","?"]]}

result : {"id":43,"method":"slim.request","result":{"_model":"squeezelite"},"params":["00:04:20:28:6c:0e",["player","model","?"]]}



For all things related to the state of the player i have no issue

**Comment by michaelherger** [comment]
Ok, got it. Please note that those queries are slightly different than most (they are old, pre-dating the JSON interface). Instead of prepending the query with the player ID, the ID is the parameter. Instead of `<id> player ip ?` you need to send `player ip <id> ?`.

**Comment by michaelherger** [comment]
Maybe you should rather use `<id> status 0 10` instead anyway, to get a lot of information in one request?

**Comment by an0Nym0us63** [comment]
@michaelherger i really appreciate your fast responses thanks

{"id":43,"method":"slim.request","params":["player",["ip","aa:aa:aa:aa:aa:22","?"]]}
{"id":43,"method":"slim.request","params":["player","ip","aa:aa:aa:aa:aa:22","?"]}

None of those two gave results.

Considering the use of status yes i use it it's great but if i'm not wrong i think it misses the model in the result (baby,squeezelite etc...

**Comment by an0Nym0us63** [comment]
With telnet all is ok. But i would rather get rid of telnet  (only keep it for callbacks)

so i'm pretty missing the right way for the post request i guess (for those old queries)

**Comment by michaelherger** [comment]
Use `{"id":43,"method":"slim.request","params":["",["player", "ip","aa:aa:aa:aa:aa:22","?"]]}`. The first (outer) parameter is always either a player ID (MAC) or nothing. As in these cases the MAC is a query parameter it belongs in the query array.

**Comment by an0Nym0us63** [comment]
Oh yes that's it, i didnt think of putting an empty outer param. That solves the issue for those old queries request via json rpc

Thanks for your help and availability

And by the way thanks for all what youve done since all those years..... Really.....
