### ISSUE TITLE
LMS sends broken radio URL to players

### ISSUE THREAD

**Issue by robho** [LMS-Community/slimserver#706]
When trying to play the radio station "JULRADIO.se" it fails if LMS asks a player to open the URL directly.

The HTTP data in the strm request to the player looks like this:
```
GET ?DIST=TuneIn&TGT=TuneIn&maxServers=2&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzODkxMjY3NywiaXNzIjoidGlzcdYifQ.XyG36BZcWivvelm0wGoaxFiqX284c65SZ_5g7KdLO1M HTTP/1.0
Cache-Control: no-cache
Connection: close
Accept: */*
Host: relay2.julradio.se:9000
Range: bytes=0-
User-Agent: iTunes/4.7.1 (Linux; N; Debian; armv7l-linux; SV; utf8) SqueezeCenter, Squeezebox Server, Logitech Media Server/8.2.0/1627922070
Icy-MetaData: 1

```
When the player sends this request the radio server responds with "400 Bad request" because the Request-URI is invalid. If the URI would be "/?DIST=...", then it would work, but the missing "/" in the beginning of the URI makes the URI invalid.

I see that when I try to play the radio station LMS first opens a connection to the radio server (to get media parameters?) and soon afterwards it asks the player to connect to the radio server for direct playback. The initial request to the radio server from LMS is correct, but LMS then seems to strip the leading "/" when contacting players.

To recreate the problem:
* Search for "julradio.se" in the radio app (one match is expected)
* Try to play the radio station (it will fail)

I'm running LMS 8.2.0 and the players I've tried are Squeezebox radio, squeelizelite and SqueezeESP32.

**Comment by michaelherger** [comment]
I'm not sure exactly what is going on here. Most likely it's the service's web server not supporting the http `HEAD` request or some other server side configuration deciding not to accept the request. Fetching the URL from TuneIn (the service behind our Radio menu):

```
% curl "http://opml.radiotime.com/Tune.ashx?id=s236911&formats=aac,ogg,mp3,wmpro,wma,wmvoice,hls,real&partnerId=16"
http://relay2.julradio.se:9000?DIST=TuneIn&TGT=TuneIn&maxServers=2&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzOTAyNjc5NywiaXNzIjoidGlzcnYifQ.UjX9WRYQRW4O1pqUOQbMPQn9KWdmyU7LsxjiObcq1uI
```

TuneIn returns a "playlist" with a single entry, the URL you've seen, too. I can play this URL in the browser, or even pipe the stream to a file. But if I try to get its header information it would return a status 400:

```
% curl -I "http://relay2.julradio.se:9000?DIST=TuneIn&TGT=TuneIn&maxServers=2&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTYzOTAyNjc5NywiaXNzIjoidGlzcnYifQ.UjX9WRYQRW4O1pqUOQbMPQn9KWdmyU7LsxjiObcq1uI"
HTTP/1.1 400 Bad Request
Server: nginx/1.18.0 (Ubuntu)
Date: Thu, 09 Dec 2021 05:13:33 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Cache-Control: no-cache, no-store
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Pragma: no-cache
Access-Control-Allow-Origin: *
```

The exact same request without the `-I` (get header only) parameter would receive the audio data stream. So IMHO this is a problem on the server side. Maybe you can get in touch with them?

**Comment by robho** [comment]
Yes, I see that HEAD requests fail and I don't know why that is. It doesn't work better if I add a leading '/' to the URL. But, I don't see that LMS uses HEAD so I don't think that's a problem.

Here are the HTTP requests sent to the radio server when trying to play the radio station on a squeezebox radio (it's a screenshot from wireshark):
![image](https://user-images.githubusercontent.com/4707486/145371459-8688d47c-cdba-4a8a-b1db-61746a567494.png)

The initial, working, request is from LMS and the second, failing, request is from a squeezebox radio. LMS has "repaired" the URL before sending it to the server, while squeezebox radio doesn't do that (and LMS sends the broken URL in the strm request).

Curl and my browser also repairs the URL before it's sent.
Here's firefox's network traffic as seen in the developer tool:
![image](https://user-images.githubusercontent.com/4707486/145368992-0548775c-842c-4248-be2f-374b992d1080.png)
The URL in firefox's address bar is broken, but what's actually sent to the server is repaired.
*Edit:* The URL in the address bar is not broken. But it was a broken URL that I entered and firefox seems to have repaired it immediately.

Maybe the real problem is the URL that's returned from TuneIn, but I don't know how to fix that. I think it would be possible to fix the problem in LMS by passing a repaired URL to the squeezebox radio.

I have been in contact with the radio station and they are helpful. They can support us if we need. But right now I think their server does the right thing when it rejects the broken URL. I checked the HTTP RFCs and to me it looks like the URL really is broken. I think the relevant RFC sections are https://datatracker.ietf.org/doc/html/rfc2616#section-5.1.2 and https://datatracker.ietf.org/doc/html/rfc2396#section-3.

**Comment by mherger** [comment]
Can you ask them to reach out to TuneIn.com? And/or submit feedback to them yourself? They have a form for this:

https://help.tunein.com/contact

I'm hesitant to modify such core functionality when this seems to be a very special case (first report in 10+ years). I fear a fix might break more than it fixes...

**Comment by mherger** [comment]
FWIW: I submitted the feedback collected in here to TuneIn.com. Let's see whether they actually pick it up.

**Comment by philippe44** [comment]
If I may, is the path really broken or is it that it is only an opaque path and our crackURL should in fact not do 
```
$path ||=/
```
But 
```
$path = ´/´ . $path unless substr($path, 0, 1) eq '/´
```
Or something more subtle with a regex I'd have to think about

**Comment by michaelherger** [comment]
Thanks @philippe44! You're spot on, of course. The nicely looking regex could be `/^\//` 😂.

**Comment by robho** [comment]
Thanks for fixing this!

Is this fix going to reach people who don't run their own server?

**Comment by michaelherger** [comment]
Should be out on mysb later today. Please give it another try in the evening or tomorrow. Thanks!
