### ISSUE TITLE
Logitechmediaserver 8.2.0 stops unnoticed on Debian 11.2 bullseye

### ISSUE THREAD

**Issue by LeDucCestMoin** [LMS-Community/slimserver#714]
Logitechmediaserver 8.2.0 stops on Debian 11.2 without any output to `/var/log/squeezeboxserver/server.log` or `journalctl`

restarting via 
`sudo service logitechmediaserver  restart `
gets it up again.

**Comment by michaelherger** [comment]
A lot more information is needed if you want to get help. 

Does the process exit? Or is it "stuck"? Does this happen after some time or right at startup? What Perl version are you using? What platform?

**Comment by marcelfischer** [comment]
Weird, having a similar Problem since two days. But I have LMS 8.3.0 and Debian 11.1
Sound output just stops. Port 9001 on server isnt reachable anymore. But dont see anything in Logs and my last OS Update happend in November.
Noticed that the lms process on the server consumes one cpu core at 100%
But I got here to check if an issue exists and I found this one.
Perl is v5.32.1 on Debian 11.1 x86_64

**Comment by mherger** [comment]
@marcelfischer assuming you're German, could it be this happens while listening to one of the public German radios? There's an open issue #700 which has caught some attention recently. And that other issue seems to be limited to one particular streaming service used by many German stations.

**Comment by LeDucCestMoin** [comment]
@mherger since I am german and listen to deutschlandfunk (dlf) via 

http://d121.rndfnk.com/ard/dlf/01/aac/192/stream.aac?aggregator=tunein&sid=22b9NYu3lyBUZ0eOiHRA0yYfnmq&token=HjQPDCDv6NLfIATP1gtV9VG0Y8yxdFrA1OsZFMXsTQg&tvf=4RnL8rPdwhZkMTIxLnJuZGZuay5jb20

This might be related. I noticed now the first time the load issue so I wait until my connection to LMS breaks change to mp3 without https and wait what happens. Christmas is a good time to check this out...

I keep you posted. 

Edit told me to formulate more clear...

**Comment by michaelherger** [comment]
@LeDucCestMoin I wasn't sure seeing your username 😁. But please don't forget to chime in on #700. There's a representative of the streaming service behind those stations on that issue.

**Comment by LeDucCestMoin** [comment]
I did not find a nice user name, so I thought this might be one ... ;-)

I add to  [#700](https://github.com/Logitech/slimserver/issues/700) when I find out a bit more...

**Comment by marcelfischer** [comment]
Im using rndfnk too. And Im streaming to two player in sync. I guess that is switching me to "proxied" streaming instead of direct.

**Comment by michaelherger** [comment]
Proxying is always used with https sources anyway. And please comment on #700.

**Comment by LeDucCestMoin** [comment]
Issue did not occur again when changed (german) Radio Streams to

- use mp3 
- none SSL
to avoid proxying, so it seems to have the same root cause as Issue [#700](https://github.com/Logitech/slimserver/issues/700).

Thanks for your help and wish you a happy new year
