### ISSUE TITLE
Make transparent background on non square covers

### ISSUE THREAD

**Issue by werdeil** [LMS-Community/slimserver#716]
Hi,

I have non square covers (as the real album is not square. Currently on LMS the image is resized to be square with white borders.

It quite visible on the material skin in dark mode.

Could it be possible to make fill the empty space in transparent?

If someone points me where the cover art are generated from the tags I can try to find a solution.

**Comment by mherger** [comment]
Would you have a screenshot? I thought we were using transparent fillings.

**Comment by werdeil** [comment]
As it would be easier you can see the screenshot on the issue I first opened on lms-material
https://github.com/CDrummond/lms-material/issues/548

Could this be that lms-material uses a custom pre-caching specifications?

**Comment by mherger** [comment]
That's most likely a Material issue. It has to request the images with the transparent border (as the Default skin does). Let's continue the discussion over there.
