### ISSUE TITLE
Doesn't continue to next song

### ISSUE THREAD

**Issue by nodiaque** [LMS-Community/slimserver#717]
Hello everyone,

I'm using lms on my unraid server into a docker container. I control it with squeezer for android.

Regardless of what source (YouTube, mp3, etc), when I start a song, it never end and play the other track. Looking at the player in squeezer, let's say the song is 3:44, the player goes beyong like 4:15 and continue.

On the server, it goes at 0sec remaining, then 1 and loop. 

I'm playing directly to a Sony amp str-dn1080.

Unraid server 6.9.2
Docker container on host network version 8.2.0
Operating system: Debian - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.30.0 - x86_64-linux-gnu-thread-multi
Audio::Scan: 1.02
IO::Socket::SSL: 2.067
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

Str-dn1080
Player Model: CastBridge
Player Type: squeezelite

Thank you

**Comment by michaelherger** [comment]
This most likely is a problem with Castbridge and your player. You better post to forums.slimdevices.com, where you'll find more information about the plugin, and help from its author.
