### ISSUE TITLE
Items in 'My apps' not sent to 3rd party remote applications when the device is not connected to right mysquezeebox.com account

### ISSUE THREAD

**Issue by tbrandysky** [LMS-Community/slimserver#74]
Hello,

I've bought few Boom devices from Ebay and I found out that one device is yet registered to former owner's mysqueezebox.com account. 
The device is actually connected to my local LMS Linux server to stream music from.
Also a few applications (BBC, Sounds&Effects) are installed on this device and both of them are visible in 'My apps' menu on Boom itself as well as on LMS web page. 

I'm using Squeeze ctrl (https://play.google.com/store/apps/details?id=com.angrygoat.android.squeezectrl) Android application to control all my devices and I've found out that when I enter the 'My apps' menu from this Android application to control this particular Boom device the menu is completely empty (nor BBC, nor Sounds&Effects applications are listed). I've discussed this with Squeeze ctrl developers and I was told the problem is with LMS which actually sends the menu to client application which is just displaying it.

I'm not sure where the problem really comes from but I've found out this behaviour occurs only with this particular Boom device which is not connected to my mysqueezebox. com account. If this really is the source of the problem I think this it is a bug as I'd suppose menus to be listed with the same entries regardless from where it is accessed (Boom's display, LMS web interface, other 3rd party application connected to LMS)

Thank you

Tomas

**Comment by mherger** [comment]
Hi Tomas,

it's not a bug, but probably not the best design decision. Feel free to send your player's MAC address (printed on a sticker on the bottom of the device) to michael ät slimdevices dott com. I'll take care of it.

Michael
