### ISSUE TITLE
Volume jumps after turning on synced Squeezebox Radio's or Squeezebox Classic

### ISSUE THREAD

**Issue by TomDue** [LMS-Community/slimserver#745]
Volume jumps to 63 after I turn on a synced pair of Squeezebox Radios (one left channel, one right channel). Then, after I turn on a Squeezebox Classic (also synced), that Volume jumps to 63 as well.
After turning all volumes down to about 20, everything works fine and in sync. When I turn off the 2 Squeezebox Radios, the volume of the Squeezebox Classic jumps again to 63.  All SB's are conneced via RJ45-LAN.
Not having this issue with unsynced Squeezeboxes (also Radios).
The issue started with 8.2 or 8.3 (not sure anymore). I can provide logs if needed.

**Comment by michaelherger** [comment]
Volume syncing can be configured on the syncing page of the players. Please double check this is set correctly.

**Comment by TomDue** [comment]
![Livingclassic](https://user-images.githubusercontent.com/97290227/148577102-01e6f578-4f06-4adb-af76-7bc317756cf8.JPG)
![Kitchen2](https://user-images.githubusercontent.com/97290227/148577106-ba3bf28f-6ef1-4d57-9de8-792f00968d68.JPG)
![Kitchen](https://user-images.githubusercontent.com/97290227/148577109-a8658981-424b-474c-b279-7a80723d5b3b.JPG)

Volume jumps happen on all these players. The 2 kitchen players jump together, since they are volume synced. If I take this out, they jump individually. Jump ist always to 63, no matter what the setting was before. It happens after turning on, and it happens (to the Livingclassic) after I turn the kitchen players off.
Screenshots attached. Is there any other place to configure this?

**Comment by philippe44** [comment]
What plugins do you have?

**Comment by TomDue** [comment]
Screenshot of my plugins:
![image](https://user-images.githubusercontent.com/97290227/148641412-14512905-b51b-4e20-b592-61ea1393dcb4.png)

**Comment by michaelherger** [comment]
Are you using Spotty's Connect mode, controlling one or more devices using a Spotify app? There's an issue where this can lead to volume changes. But it's typically going to 49... But anyway: if that's the case, try disabling Spotty Connect for a while to see whether the problem persists.

**Comment by TomDue** [comment]
Hey Michael, seems to be OK again without Spotty 😃. I will watch it over the next week and report back.
I also just updated to 8.3.0~1641537242, to have the latest code on this installation. I have 2 more installations at other places - both without Spotty but only 1 or 2 SB-Radios there.
