### ISSUE TITLE
Incorrect LMS playlist display when  adding dezzer albums or playlists through CLI

### ISSUE THREAD

**Issue by Rich-AU** [LMS-Community/slimserver#747]
When adding dezzer albums or playlists through CLI, the the playlist on LMS UI (including standard webUI and "material skin") can only display the album art and track info(track name, artist and album name) for the first track, other tracks only have the standard deezer icon. But when the next track is played, the album art and track info of that track will be updated in "material skin", but not the standard LMS webUI.

screen captures are reported here:  https://forums.slimdevices.com/showthread.php?104738-Deezer-Plugin&p=1043105&viewfull=1#post1043105

**Comment by michaelherger** [comment]
Can you give me a real CLI command you're using? I tried to reproduce this issue, but it worked as expected.

Please note that I currently don't have any subscription. Thus it's all mp3 for me. Did this work before the fix for lossless playback I applied a few days ago?

**Comment by Rich-AU** [comment]
It didn't work before that fix, I don't think that fix causes this issue. And just one more observation when I repeated the test, if the song has been played recently, the playlist display will be fine (I guess the info was cached), please try a new album you haven't played before.

I am using jsonrpc.js to send the cli, here are a couple http body examples I tested:
sample one: Adele 25
{"id":1,"method":"slim.request","params":["b8:27:eb:68:eb:ba",["playlist","play","deezer://album:14880539"]]}
sample two: Adele 30:
{"id":1,"method":"slim.request","params":["b8:27:eb:68:eb:ba",["playlist","play","deezer://album:273425942"]]}

**Comment by michaelherger** [comment]
New builds are on their way (give it another hour). They'll hopefully improve the situation.

**Comment by Rich-AU** [comment]
Do you mean a new LMS server build? i.e. I need to install the nightly build to test the improvement?

**Comment by michaelherger** [comment]
Yes, it's a LMS side change. Or are you using MySB only?

**Comment by Rich-AU** [comment]
Thanks for the clarification, I am using both LMS server and MySB(for Tidal and Deezer). Will update LMS server, test again and report back.

**Comment by Rich-AU** [comment]
Just tested and can confirm that now it's working perfectly! Thanks again for the prompt response!
