### ISSUE TITLE
AirMusic Android App fails to stream to UPnP/DLNA Media Interface Plugin

### ISSUE THREAD

**Issue by streumix** [LMS-Community/slimserver#753]
AirMusic allows to stream Android system audio via DLNA (or Airplay), which works without rooting the device on Android 10+. This is great, as this (currently)unique app allows not only to stream local media files, but audio of any app.

But sadly it is having issues playing on the LMS UPnP/DLNA Media Interface plugin from Andy. The DLNA Renderer is found, but when trying to stream, it throws an error not able to establish a connection. 

This error can be replicated by installing the free demo version of the AirMusic app on an Android phone (e.g. from Play Store). Just be aware that you need at leat Android 10 or the phone has to be rooted to get it work. 

Is there someone maintaining this plugin and a chance that this incompatibility get's fixed? Maybe it's an issue inside AirMusic with their DLNA implementation (which works with rontier Silicon/UNDOK based HiFi Hardware ). But I'm the DLNA protocol expert to determine the bad guy. 

Thanks,
Toby

**Comment by philippe44** [comment]
The UPnP bridge is doing things the other way around: meeting UPnP devices being used from LMS. Seems you want Andy's plugin for your need but that has not been maintained in years

**Comment by streumix** [comment]
Sorry, I've already corrected myself. I'm using UPnP Media Interface for this purpose. 
And after activating debug logging, I was able to determine the root cause: The plugin doesn't support the LPCM MIME-Type / codec requested by AirMusic.

> [22-02-01 10:39:53.3958] Slim::Plugin::UPnP::SOAPServer::processControl (139) Invoking Slim::Plugin::UPnP::MediaRenderer::AVTransport->SetAVTransportURI( {
>   CurrentURI => "http://192.168.178.31:41861/AirMusic.LPCM",
>   CurrentURIMetaData => "Live AudioAirMusic Trial Google Pixel 3object.item.audioItem.musicTrackAirMusic Trial Google Pixel 3AirMusic Trial Google Pixel 3http://192.168.178.31:41861/AirMusic.jpeghttp://192.168.178.31:41861/AirMusic.LPCM",
>   InstanceID => 0,
> } )
> [22-02-01 10:39:53.3996] Slim::Plugin::UPnP::SOAPServer::processControl (155) SOAPServer: Slim::Plugin::UPnP::MediaRenderer::AVTransport->SetAVTransportURI returned error: [[714, "Illegal MIME-type"]]
> [22-02-01 10:39:53.4063] Slim::Plugin::UPnP::SOAPServer::fault (230) UPnP fault: 714 / Illegal MIME-type
> [22-02-01 10:39:53.4070] Slim::Plugin::UPnP::SOAPServer::fault (231) Result: s:ClientUPnPError714Illegal MIME-type
> 

Any chance to get this added?

**Comment by streumix** [comment]
Just looked at the code, and there are a lot of L16 PCM formats supported, right?
So there must be some sort of incompatibility in handshake. Either UPnP Media Interface or AirMusic.
Or are there LPCM variants Air Music might be using and not supported by UPnP Media Interface ?

**Comment by streumix** [comment]
OK, I had a closer look. The problem seems to tbe the ProtocolInfo of the resource sent by AirMusic for LPCM compared to WAV. 
For WAV it is
`protocolInfo=\"http-get:*:audio/wav:DLNA.ORG_PN=WAV;DLNA.ORG_OP=00;DLNA.ORG_FLAGS=01700000000000000000000000000000\"`
and of for LPCM it is
`protocolInfo=\"http-get:*:audio/L16;rate=44100;channels=2:DLNA.ORG_PN=LPCM;DLNA.ORG_OP=00;DLNA.ORG_FLAGS=01700000000000000000000000000000\"`

UPnP Media Interface AV Transport (AVTransport.pm@lione 712) is using the following line to extract the MIME type:
`my ($mime) = $iwav =~ /[^:]+:[^:]+:([^:+]+):/;`
Which means, it grabs anything between 2nd and thrid colon. 
So for WAV we get  "audio/wav", but for LPCM we get "audio/L16;rate=44100;channels=2", as LPCM seems to be coding some properties separated by semi-colons. 

An  straight forward fix would be to change the MIME type extraction to 
`my ($lmime) = $ipcm =~ /[^:]+:[^:]+:([^:;+]+)/;`

but is this the right thing to do? 
Is the ProtocolInfo string sent by AirMusic a valid one? 
Would the listed fix cause some regression to fail on other valid string? 
I'm not a DLNA protocl expert and do not want cause more harm than good.

Anybody out there who can guide me in how to fix MIME type extraction in a clean and save way, so UPnP Media Interface can deal with the strings sent by AirMusic?

**Comment by streumix** [comment]
And to finish up, I'd like to further comment that there's a fundamental issue with the types.conf file entry for LPCM and/or service function Music::Info::mimeToType().
According to [RFC2586](https://datatracker.ietf.org/doc/html/rfc2586) MIME type header for LPCM has sub type L16 with an required parameter _rate_ and some futher optional parameters. Therefore, AirMusic is sending MIME type _audio/L16;rate=44100;channels=2_, which is correct. But when using  this extracted type with Music::Info::mimeToType(), it cannot be found, as LMS supplied MIME type configuration file types.conf lists only MIME type _audio/L16_ without all variants defined by the parameters.

IMHO, either types.conf needs to list all variants of LPCM explicitely, or Music::Info::mimeToType() has to strip off any parameters, which are separated from the leading sub-type by a semi-colon, before mapping MIME type string to type return value.

Fixing UPnP Media interface plugin it may be an option to split parameters from sub-type and use only the leading sub-type as an argument to Music::Info::mimeToType(). (AVTransport.pm @ line 712+). This does work (verified), as _rate_ and _channels_ of MIME type string seem to be redundant; at least for counterpart _AirMuisc_. 
There are still proper elements _bitrate_ and _AudioChannels_ on the _res_ block. But as this doesn't make Music::Info::mimeToType() work properly, it's preferred to fix the inconsistency for any MIME type with parameters like LPCM in Music::Info::mimeToType() or types.conf, isn't it?

Reards,
Toby

**Comment by philippe44** [comment]
AFAIK, problem is that there is nobody to maintain the UPnP/DLNA interface and it's not very widely used (and this protocol is a real pain anyway). Unless somebody else wants to step in, you'll probably have to submit a PR yourself

**Comment by stsichler** [comment]
POST-MORTEM:
@streumix I'm currently working on the UPnP/DLNA Media Renderer Plugin and I'm also currently listening to music that is streamed by _AirMusic_ to LMS :)

Is this still an issue for you?

Regarding support of `audio/L16`, there are two problems involved here:
- As you already pointed out, the `rate` and `channels` parameters are currently not extracted / split away from the type spec for `audio/L16`, but this can be locally fixed in `Slim::Plugin::UPnP::MediaRenderer::AVTransport::_DIDLLiteToHash()`, so `mimeToType()` will work correctly afterwards and the additional parameters can be stored in the track Metadata.
- `audio/L16` is mapped to LMS' internal `pcm` format, which has a platform-dependent byte order (typically little endian) meanwhile RFC 2586 defines audio/L16 to be always network byte order, meaning big endian. So to fix this, an endianess conversion has to be inserted. 
I'm having this corrected in a working setup currently, but I'm unsure of the side-effects, because it required to add a pcm->pcm conversion entry in the global `convert.conf` table using `sox` for endianess conversion.

If you are (or anyone else) is still interested in this, we could re-open this issue (but I would appreciate any help :) )....

Btw. this would also fix support of `foobar2000` which is also able to stream music via UPnP/DLNA to LMS, but also uses `audio/L16` for this.

**Comment by stsichler** [comment]
Addition: Maybe it could be a cleaner solution (less risky???) to instead introduce a new unique format `l16` instead of `pcm` that `mimeToType()` is mapping `audio/L16` to, in order to allow a better way to handle the difference in endianess.
But I have no idea what this will break instead....

**Comment by stsichler** [comment]
see #1647
