### ISSUE TITLE
no diag or network utils available in container build of slimserver

### ISSUE THREAD

**Issue by xpseudonym** [LMS-Community/slimserver#755]
Trying to debug a container build of slimserver is frustrated by lack of diagnostic or networking utilites, see [slimdevices forum post](https://forums.slimdevices.com/showthread.php?115872-Network-Topology&p=1046087&viewfull=1#post1046087).

Please include rudimentary diag and network utils in container builds of slimserver, or at least the ability to install them, eg: `apt install <some useful package>`

**Comment by michaelherger** [comment]
The image is based on Debian bullseye-slim. Yes, it's stripped down. But after running `apt update` you should be able to install whatever you need.

**Comment by xpseudonym** [comment]
Thanks Michael, sorry for the noise. Closed.
