### ISSUE TITLE
ARM perl module libraries not page aligned

### ISSUE THREAD

**Issue by HarryDolan** [LMS-Community/slimserver#76]
I have been trying unsuccessfully to install the Logitech Media Player onto a WD My Cloud NAS device.
This device uses an ARM processor and runs Debian.  After a lot of troubleshooting I isolated the problem to the LMS-included Perl module libraries: they are not page aligned.

Here are the details:

When I run /usr/sbin/squeezebox server I get the message:

```
The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name


*******

NOTE:

If you're running some unsupported Linux/Unix platform, please use the buildme.sh 
script located here:

https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN

If 7.9 is outdated by the time you read this, Replace "7.9" with the major version
You should never need to do this if you're on Windows or Mac OSX. If the installers
don't work for you, ask for help and/or report a bug.

*******


Exiting..

```

I get more information by running the following perl script, which tries to use one of the modules:

```
#!/usr/bin/perl

BEGIN {
    push @INC, "/usr/share/squeezeboxserver/CPAN";
    push @INC, "/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/EV";
}

use EV;

printf ("Hello!\n");

```

It results in:

```
Can't load '/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/EV/EV.so' for module EV: /usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/EV/EV.so: **ELF load command alignment not page-aligned** at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at /usr/share/squeezeboxserver/CPAN/EV.pm line 127
BEGIN failed--compilation aborted at /usr/share/squeezeboxserver/CPAN/EV.pm line 127.
Compilation failed in require at ./harold.pl line 8.
BEGIN failed--compilation aborted at ./harold.pl line 8.

```

The problem occurs with versions 7.6 through 7.9.

I would be happy to assist in fixing this problem.  I am a competent programmer, but I do not have a development enviroment for the ARM.

Harry Dolan

**Comment by mherger** [comment]
What gives "perl -v"?

**Comment by HarryDolan** [comment]
WDMyCloud:~# perl -v

This is perl 5, version 14, subversion 2 (v5.14.2) built for arm-linux-gnueabihf-thread-multi-64int
(with 80 registered patches, see perl -V for more detail)

**Comment by mherger** [comment]
Please add --d_startup to your startup parameters. Then post the full server.log.

What package did you install anyway?

You might have more luck finding help on forums.slimdevices.com. There's a 3rd party hardware group.

**Comment by HarryDolan** [comment]
Here are the packages I tried:

squeezeboxserver_7.6.1_all.deb
logitechmediaserver_7.7.5_all.deb
logitechmediaserver_7.8.0_all.deb
logitechmediaserver_7.9.0~1455784650_all.deb

It is a Debian 7 (wheezy) system.

**Comment by HarryDolan** [comment]
/usr/sbin/squeezeboxserver --d_startup

Module [DBI] failed to load:
Can't load '/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/DBI/DBI.so' for module DBI: /usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/DBI/DBI.so: ELF load command alignment not page-aligned at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at /usr/share/squeezeboxserver/CPAN/DBI.pm line 268
BEGIN failed--compilation aborted at /usr/share/squeezeboxserver/CPAN/DBI.pm line 268.
Compilation failed in require at (eval 17) line 2.
BEGIN failed--compilation aborted at (eval 17) line 2.

Module [EV] failed to load:
Can't load '/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/EV/EV.so' for module EV: /usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/EV/EV.so: ELF load command alignment not page-aligned at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at /usr/share/squeezeboxserver/CPAN/EV.pm line 127
BEGIN failed--compilation aborted at /usr/share/squeezeboxserver/CPAN/EV.pm line 127.
Compilation failed in require at (eval 18) line 2.
BEGIN failed--compilation aborted at (eval 18) line 2.

Module [XML::Parser::Expat] failed to load:
Can't load '/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/XML/Parser/Expat/Expat.so' for module XML::Parser::Expat: /usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/XML/Parser/Expat/Expat.so: ELF load command alignment not page-aligned at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at (eval 19) line 2
Compilation failed in require at (eval 19) line 2.
BEGIN failed--compilation aborted at (eval 19) line 2.

Module [HTML::Parser] failed to load:
Can't load '/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/HTML/Parser/Parser.so' for module HTML::Parser: /usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/HTML/Parser/Parser.so: ELF load command alignment not page-aligned at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at (eval 20) line 2
Compilation failed in require at (eval 20) line 2.
BEGIN failed--compilation aborted at (eval 20) line 2.

Module [JSON::XS] failed to load:
Can't load '/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/JSON/XS/XS.so' for module JSON::XS: /usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/JSON/XS/XS.so: ELF load command alignment not page-aligned at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at (eval 21) line 2
Compilation failed in require at (eval 21) line 2.
BEGIN failed--compilation aborted at (eval 21) line 2.

Module [Digest::SHA1] failed to load:
Can't load '/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/Digest/SHA1/SHA1.so' for module Digest::SHA1: /usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/Digest/SHA1/SHA1.so: ELF load command alignment not page-aligned at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at (eval 22) line 2
Compilation failed in require at (eval 22) line 2.
BEGIN failed--compilation aborted at (eval 22) line 2.

Module [YAML::XS] failed to load:
Can't load '/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/YAML/XS/LibYAML/LibYAML.so' for module YAML::XS::LibYAML: /usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/YAML/XS/LibYAML/LibYAML.so: ELF load command alignment not page-aligned at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at /usr/share/squeezeboxserver/CPAN/YAML/XS.pm line 18
Compilation failed in require at /usr/share/squeezeboxserver/CPAN/YAML/XS.pm line 18.
BEGIN failed--compilation aborted at /usr/share/squeezeboxserver/CPAN/YAML/XS.pm line 18.
Compilation failed in require at (eval 23) line 2.
BEGIN failed--compilation aborted at (eval 23) line 2.

Module [Sub::Name] failed to load:
Can't load '/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/Sub/Name/Name.so' for module Sub::Name: /usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto/Sub/Name/Name.so: ELF load command alignment not page-aligned at /usr/lib/perl/5.14/DynaLoader.pm line 184.
 at (eval 24) line 2
Compilation failed in require at (eval 24) line 2.
BEGIN failed--compilation aborted at (eval 24) line 2.

Module [DBI] failed to load:
DBI object version 1.622 does not match $DBI::VERSION 1.616 at /usr/lib/perl/5.14/DynaLoader.pm line 207.
BEGIN failed--compilation aborted at /usr/share/squeezeboxserver/CPAN/DBI.pm line 268.
Compilation failed in require at (eval 25) line 2.
BEGIN failed--compilation aborted at (eval 25) line 2.

Module [EV] failed to load:
Can't locate loadable object for module EV in @INC (@INC contains: /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/sbin /usr/local/NSPT/WDSafe/lib /usr/local/NSPT/WDShare/lib /usr/local/NSPT/WDNAS/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /usr/share/squeezeboxserver/CPAN/EV.pm line 127
BEGIN failed--compilation aborted at /usr/share/squeezeboxserver/CPAN/EV.pm line 127.
Compilation failed in require at (eval 26) line 2.
BEGIN failed--compilation aborted at (eval 26) line 2.

Module [XML::Parser::Expat] failed to load:
Can't locate loadable object for module XML::Parser::Expat in @INC (@INC contains: /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/sbin /usr/local/NSPT/WDSafe/lib /usr/local/NSPT/WDShare/lib /usr/local/NSPT/WDNAS/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at (eval 27) line 2
Compilation failed in require at (eval 27) line 2.
BEGIN failed--compilation aborted at (eval 27) line 2.

Module [HTML::Parser] failed to load:
Can't locate loadable object for module HTML::Parser in @INC (@INC contains: /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/sbin /usr/local/NSPT/WDSafe/lib /usr/local/NSPT/WDShare/lib /usr/local/NSPT/WDNAS/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at (eval 28) line 2
Compilation failed in require at (eval 28) line 2.
BEGIN failed--compilation aborted at (eval 28) line 2.

Module [JSON::XS] failed to load:
Can't locate loadable object for module JSON::XS in @INC (@INC contains: /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/sbin /usr/local/NSPT/WDSafe/lib /usr/local/NSPT/WDShare/lib /usr/local/NSPT/WDNAS/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at (eval 29) line 2
Compilation failed in require at (eval 29) line 2.
BEGIN failed--compilation aborted at (eval 29) line 2.

Module [Digest::SHA1] failed to load:
Can't locate loadable object for module Digest::SHA1 in @INC (@INC contains: /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/sbin /usr/local/NSPT/WDSafe/lib /usr/local/NSPT/WDShare/lib /usr/local/NSPT/WDNAS/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at (eval 30) line 2
Compilation failed in require at (eval 30) line 2.
BEGIN failed--compilation aborted at (eval 30) line 2.

Module [YAML::XS] failed to load:
Attempt to reload YAML/XS/LibYAML.pm aborted.
Compilation failed in require at /usr/share/squeezeboxserver/CPAN/YAML/XS.pm line 18.
BEGIN failed--compilation aborted at /usr/share/squeezeboxserver/CPAN/YAML/XS.pm line 18.
Compilation failed in require at (eval 31) line 2.
BEGIN failed--compilation aborted at (eval 31) line 2.

Module [Sub::Name] failed to load:
Can't locate loadable object for module Sub::Name in @INC (@INC contains: /usr/share/squeezeboxserver/CPAN /usr/share/squeezeboxserver /usr/sbin /usr/local/NSPT/WDSafe/lib /usr/local/NSPT/WDShare/lib /usr/local/NSPT/WDNAS/lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at (eval 32) line 2
Compilation failed in require at (eval 32) line 2.
BEGIN failed--compilation aborted at (eval 32) line 2.

Found SELinux - setting security context to: texrel_shlib_t for *.so files.
Got @INC containing:
/usr/share/squeezeboxserver/CPAN
/usr/share/squeezeboxserver
/usr/sbin
/usr/local/NSPT/WDSafe/lib
/usr/local/NSPT/WDShare/lib
/usr/local/NSPT/WDNAS/lib
/etc/perl
/usr/local/lib/perl/5.14.2
/usr/local/share/perl/5.14.2
/usr/lib/perl5
/usr/share/perl5
/usr/lib/perl/5.14
/usr/share/perl/5.14
/usr/local/lib/site_perl
.

Extended @INC to contain:
/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int
/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto
/usr/share/squeezeboxserver/CPAN/arch/5.14.2/arm-linux-gnueabihf-thread-multi-64int
/usr/share/squeezeboxserver/CPAN/arch/5.14.2/arm-linux-gnueabihf-thread-multi-64int/auto
/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int
/usr/share/squeezeboxserver/CPAN/arch/5.14/arm-linux-gnueabihf-thread-multi-64int/auto
/usr/share/squeezeboxserver/CPAN/arch/arm-linux-gnueabihf-thread-multi-64int
/usr/share/squeezeboxserver/CPAN/arch/5.14
/usr/share/squeezeboxserver/lib
/usr/share/squeezeboxserver/CPAN
/usr/share/squeezeboxserver
/usr/share/squeezeboxserver/CPAN
/usr/share/squeezeboxserver
/usr/sbin
/usr/local/NSPT/WDSafe/lib
/usr/local/NSPT/WDShare/lib
/usr/local/NSPT/WDNAS/lib
/etc/perl
/usr/local/lib/perl/5.14.2
/usr/local/share/perl/5.14.2
/usr/lib/perl5
/usr/share/perl5
/usr/lib/perl/5.14
/usr/share/perl/5.14
/usr/local/lib/site_perl
.

Loaded module: [version] ok!
Loaded module: [Time::HiRes] ok!
Removing [DBI] from the symbol table - load failed.
Removing [EV] from the symbol table - load failed.
Removing [common::sense] from the symbol table - load failed.
Removing [XML::Parser::Expat] from the symbol table - load failed.
Removing [HTML::Parser] from the symbol table - load failed.
Removing [HTML::Entities] from the symbol table - load failed.
Removing [JSON::XS] from the symbol table - load failed.
Removing [common::sense] from the symbol table - load failed.
Removing [Digest::base] from the symbol table - load failed.
Removing [Digest::SHA1] from the symbol table - load failed.
Removing [YAML::XS] from the symbol table - load failed.
Removing [Sub::Name] from the symbol table - load failed.
The following modules are loaded after the first attempt:
    Slim/Utils/OS/Debian.pm => /usr/share/perl5/Slim/Utils/OS/Debian.pm
    File/Spec/Functions.pm => /usr/lib/perl/5.14/File/Spec/Functions.pm
    POSIX.pm => /usr/lib/perl/5.14/POSIX.pm
    Getopt/Long.pm => /usr/share/perl/5.14/Getopt/Long.pm
    /usr/lib/perl/5.14/auto/POSIX/load_imports.al => /usr/lib/perl/5.14/auto/POSIX/load_imports.al
    Tie/Hash.pm => /usr/share/perl/5.14/Tie/Hash.pm
    Cwd.pm => /usr/lib/perl/5.14/Cwd.pm
    warnings.pm => /usr/share/perl/5.14/warnings.pm
    Slim/Utils/OSDetect.pm => /usr/share/perl5/Slim/Utils/OSDetect.pm
    /usr/lib/perl/5.14/auto/POSIX/autosplit.ix => /usr/lib/perl/5.14/auto/POSIX/autosplit.ix
    Slim/Utils/OS/Linux.pm => /usr/share/perl5/Slim/Utils/OS/Linux.pm
    Fcntl.pm => /usr/lib/perl/5.14/Fcntl.pm
    Symbol.pm => /usr/share/perl/5.14/Symbol.pm
    UNIVERSAL.pm => /usr/share/perl/5.14/UNIVERSAL.pm
    Exporter.pm => /usr/share/perl/5.14/Exporter.pm
    Slim/Utils/OS.pm => /usr/share/perl5/Slim/Utils/OS.pm
    version/vpp.pm => /usr/share/squeezeboxserver/CPAN/version/vpp.pm
    File/Spec.pm => /usr/lib/perl/5.14/File/Spec.pm
    File/Path.pm => /usr/share/perl/5.14/File/Path.pm
    FindBin.pm => /usr/share/perl/5.14/FindBin.pm
    locale.pm => /usr/share/perl/5.14/locale.pm
    warnings/register.pm => /usr/share/perl/5.14/warnings/register.pm
    XSLoader.pm => /usr/share/perl/5.14/XSLoader.pm
    Slim/bootstrap.pm => /usr/share/perl5/Slim/bootstrap.pm
    Time/HiRes.pm => /usr/lib/perl/5.14/Time/HiRes.pm
    version.pm => /usr/share/squeezeboxserver/CPAN/version.pm
    Config_git.pl => /usr/lib/perl/5.14/Config_git.pl
    base.pm => /usr/share/perl/5.14/base.pm
    Config.pm => /usr/lib/perl/5.14/Config.pm
    File/Basename.pm => /usr/share/perl/5.14/File/Basename.pm
    Carp.pm => /usr/share/perl/5.14/Carp.pm
    YAML/XS/LibYAML.pm => 
    Exporter/Heavy.pm => /usr/share/perl/5.14/Exporter/Heavy.pm
    File/Spec/Unix.pm => /usr/lib/perl/5.14/File/Spec/Unix.pm
    vars.pm => /usr/share/perl/5.14/vars.pm
    strict.pm => /usr/share/perl/5.14/strict.pm
    constant.pm => /usr/share/perl/5.14/constant.pm
    Config_heavy.pl => /usr/lib/perl/5.14/Config_heavy.pl
    overload.pm => /usr/share/perl/5.14/overload.pm
    AutoLoader.pm => /usr/share/perl/5.14/AutoLoader.pm
    lib.pm => /usr/lib/perl/5.14/lib.pm
    Slim/Utils/OS/Unix.pm => /usr/share/perl5/Slim/Utils/OS/Unix.pm
    DynaLoader.pm => /usr/lib/perl/5.14/DynaLoader.pm

The following modules failed to load on the first attempt: [DBI, EV, XML::Parser::Expat, HTML::Parser, JSON::XS, Digest::SHA1, YAML::XS, Sub::Name] - will try again.

Removing [DBI] from the symbol table - load failed.
Removing [EV] from the symbol table - load failed.
Removing [common::sense] from the symbol table - load failed.
Removing [XML::Parser::Expat] from the symbol table - load failed.
Removing [HTML::Parser] from the symbol table - load failed.
Removing [HTML::Entities] from the symbol table - load failed.
Removing [JSON::XS] from the symbol table - load failed.
Removing [common::sense] from the symbol table - load failed.
Removing [Digest::base] from the symbol table - load failed.
Removing [Digest::SHA1] from the symbol table - load failed.
Removing [YAML::XS] from the symbol table - load failed.
Removing [Sub::Name] from the symbol table - load failed.
The following modules are loaded after the second attempt:
    Slim/Utils/OS/Debian.pm => /usr/share/perl5/Slim/Utils/OS/Debian.pm
    File/Spec/Functions.pm => /usr/lib/perl/5.14/File/Spec/Functions.pm
    POSIX.pm => /usr/lib/perl/5.14/POSIX.pm
    Getopt/Long.pm => /usr/share/perl/5.14/Getopt/Long.pm
    /usr/lib/perl/5.14/auto/POSIX/load_imports.al => /usr/lib/perl/5.14/auto/POSIX/load_imports.al
    Tie/Hash.pm => /usr/share/perl/5.14/Tie/Hash.pm
    Cwd.pm => /usr/lib/perl/5.14/Cwd.pm
    warnings.pm => /usr/share/perl/5.14/warnings.pm
    Slim/Utils/OSDetect.pm => /usr/share/perl5/Slim/Utils/OSDetect.pm
    /usr/lib/perl/5.14/auto/POSIX/autosplit.ix => /usr/lib/perl/5.14/auto/POSIX/autosplit.ix
    Slim/Utils/OS/Linux.pm => /usr/share/perl5/Slim/Utils/OS/Linux.pm
    Fcntl.pm => /usr/lib/perl/5.14/Fcntl.pm
    Symbol.pm => /usr/share/perl/5.14/Symbol.pm
    UNIVERSAL.pm => /usr/share/perl/5.14/UNIVERSAL.pm
    Exporter.pm => /usr/share/perl/5.14/Exporter.pm
    Slim/Utils/OS.pm => /usr/share/perl5/Slim/Utils/OS.pm
    version/vpp.pm => /usr/share/squeezeboxserver/CPAN/version/vpp.pm
    File/Spec.pm => /usr/lib/perl/5.14/File/Spec.pm
    File/Path.pm => /usr/share/perl/5.14/File/Path.pm
    FindBin.pm => /usr/share/perl/5.14/FindBin.pm
    locale.pm => /usr/share/perl/5.14/locale.pm
    warnings/register.pm => /usr/share/perl/5.14/warnings/register.pm
    XSLoader.pm => /usr/share/perl/5.14/XSLoader.pm
    Slim/bootstrap.pm => /usr/share/perl5/Slim/bootstrap.pm
    Time/HiRes.pm => /usr/lib/perl/5.14/Time/HiRes.pm
    version.pm => /usr/share/squeezeboxserver/CPAN/version.pm
    Config_git.pl => /usr/lib/perl/5.14/Config_git.pl
    base.pm => /usr/share/perl/5.14/base.pm
    Config.pm => /usr/lib/perl/5.14/Config.pm
    File/Basename.pm => /usr/share/perl/5.14/File/Basename.pm
    Carp.pm => /usr/share/perl/5.14/Carp.pm
    YAML/XS/LibYAML.pm => 
    Exporter/Heavy.pm => /usr/share/perl/5.14/Exporter/Heavy.pm
    File/Spec/Unix.pm => /usr/lib/perl/5.14/File/Spec/Unix.pm
    vars.pm => /usr/share/perl/5.14/vars.pm
    strict.pm => /usr/share/perl/5.14/strict.pm
    constant.pm => /usr/share/perl/5.14/constant.pm
    Config_heavy.pl => /usr/lib/perl/5.14/Config_heavy.pl
    overload.pm => /usr/share/perl/5.14/overload.pm
    AutoLoader.pm => /usr/share/perl/5.14/AutoLoader.pm
    lib.pm => /usr/lib/perl/5.14/lib.pm
    Slim/Utils/OS/Unix.pm => /usr/share/perl5/Slim/Utils/OS/Unix.pm
    DynaLoader.pm => /usr/lib/perl/5.14/DynaLoader.pm

The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name

---

NOTE:

If you're running some unsupported Linux/Unix platform, please use the buildme.sh 
script located here:

https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN

If 7.9 is outdated by the time you read this, Replace "7.9" with the major version
You should never need to do this if you're on Windows or Mac OSX. If the installers
don't work for you, ask for help and/or report a bug.

---

Exiting..

**Comment by HarryDolan** [comment]
I've dug into this more deeply and discovered that the WD device runs a version of Debian that requires binaries to be 64k page aligned, but those distributed with LMS are 32k aligned.  I'll try to set up a build environment for cross compiling to create 64k binaries.

How do you build the .so files in the LMS distribution?

**Comment by mherger** [comment]
I don't cross-compile. Never got this to work... I've used a Raspberry Pi for the ARM builds.

**Comment by HarryDolan** [comment]
OK, after lots of work I figured out how to cross compile for the WD device and I can now build perl modules that load on that device.

Now I need to get LMS to use those modules instead of the ones distributed with the package.  It prioritizes its own before looking for others (i.e., anything in the normal @INC is secondary).

Do you have any suggestion on how to deal with this so I don't have to mangle the bootstrap.pm code?

Thanks.

**Comment by mherger** [comment]
It would probably be easier not to run from the .deb package, but a git clone instead. This way you could simply replace the files which are part of LMS with yours, without fearing that they will be reset with every update again. Or you write a little script which does the replacement after every update again.

**Comment by willberriss** [comment]
I have a similar issue, namely I get this with today's nightly build of LMS 7.9 deb file for ARM:

root:/var/log/squeezeboxserver# /usr/sbin/squeezeboxserver --prefsdir /var/lib/squeezeboxserver/prefs --logdir /var/log/squeezeboxserver/ --cachedir /var/lib/squeezeboxserver/cache --charset=utf8

The following modules failed to load: DBI EV XML::Parser::Expat HTML::Parser JSON::XS Digest::SHA1 YAML::XS Sub::Name

My system is this - a RPi 3 Model B with Ubuntu 16.04 installed on it.

root:/var/log/squeezeboxserver# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"

root:/var/log/squeezeboxserver# uname -a
Linux moya 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux

If I clone from github (https://github.com/Logitech/slimserver.git) and build it, which LMS files exactly do I need to replace with my systems ones?  

Ah, I've just spotted that this was closed 24 days ago.

**Comment by michaelherger** [comment]
Will - that's a different issue. Most likely you're using a Perl version for which we don't have binaries yet. Please open a new issue with details about your Perl environment (perl -v).

**Comment by willberriss** [comment]
Thanks, I've opened [https://github.com/Logitech/slimserver/issues/154](https://github.com/Logitech/slimserver/issues/154)
