### ISSUE TITLE
strange dns resolution error...

### ISSUE THREAD

**Issue by hs6666** [LMS-Community/slimserver#762]
hi, every few days my lms stops being able to resolve and i start getting errors like following in the log file...

Slim::Utils::Misc::msg (1343) Warning: [03:05:29.5505] EV: error in callback (ignoring): pack_sockaddr: invalid host at /usr/share/squeezeboxserver/lib/AnyEvent/DNS.pm line 1114.

restarting does not fix, ONY installing the the latest nightly build fixes the error

have confirmed host resolution is working fine when it happens

very odd?

harry

ps system info......

Logitech Media Server Version: 8.3.0 - 1644768372 @ Sun 13 Feb 2022 10:13:46 PM CET
Operating system: Debian - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.28.1 - x86_64-linux-gnu-thread-multi
Audio::Scan: 1.02
IO::Socket::SSL: 2.060
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)
Total Players Recognized: 7
Total Tracks: 16,499
Total Albums: 1,258
Total Artists: 2,656

**Comment by michaelherger** [comment]
That indeed sounds very odd... would stopping/starting (rather than restarting) fix the issue, too? An update doesn't any magic which could fix a networking issue.

**Comment by hs6666** [comment]
Hi, I did try restarting the lms server from the command prompt previously, that didn't work either...

.stab in the dark :) .... could it be a perl issue, were some "cache get unblocked" only on after an update, (the server has been upgraded from previous 7.x versions)?

**Comment by michaelherger** [comment]
Perl itself would not keep state if the process was terminated. That's why I asked whether you simply restarted, or actually shut down the process before doing so.

**Comment by hs6666** [comment]
ok thanks for clarification, i'll look at my network setup... lms is running inside a (proxmox) virtual machine with pfsense as a firewall, so quite a lot there to look into !

**Comment by michaelherger** [comment]
Any news on this?

**Comment by hs6666** [comment]
hi, yes, i was rebooting my debian every night with a cron job, this is what was creating the issue. Have no idea why, but rebooting it manually (its a virtual machine running on proxmox) doesn't seem to produce the issue :)

**Comment by hs6666** [comment]
hmm.... think i spoke too soon ....

same thing happened today, local dns working fine on debian host, multiple reboots, same issue in that lms logs showing all dns resolutions failing

the only fix seems to be installing the *same* deb file again with all lms dns resolution working straight away after reinstall (no need to reboot host)

i use the latest deb file from here....  

http://downloads.slimdevices.com/nightly/index.php?ver=8.3



Logitech Media Server Version: 8.3.0 - 1647000016 @ Fri 11 Mar 2022 01:25:40 PM CET
Hostname: lms.xxxxxxx.com
Server IP Address: 192.168.13.10
Server HTTP Port Number: 9000
Operating system: Debian - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.28.1 - x86_64-linux-gnu-thread-multi
Audio::Scan: 1.02
IO::Socket::SSL: 2.060
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)
Total Players Recognized: 6

**Comment by michaelherger** [comment]
Maybe LMS is starting before the network is fully up? I’d suggest you post to forums.slimdevices.com where there is a very active and knowledgeable community.

**Comment by hs6666** [comment]
ok thanks, will do, although issuing a service restart command does not make lms dns resolution come up, only a reinstall....

**Comment by mherger** [comment]
What if you stopped/started instead of a restart? There's really no magic an installation does, other than shutting down the previous version, and starting the new one.
