### ISSUE TITLE
DSD conversion with sox/C-3PO, multithreading not activated

### ISSUE THREAD

**Issue by th2j** [LMS-Community/slimserver#764]
I have installed the last version of LMS (8.3.0) and the plugin C-3PO.
When i tried to convert PCM to DSD with sox, it is working but sox isn't started with multithreading.

Here is the command launched by LMS :
[flac] -dcs --totally-silent $START$ $END$ -- $FILE$ | [sox] -q -t wav - -t dsf -b 1 --buffer 16384 --multi-threaded - gain -9 rate -v -M -t -b 90.7 -f 5644800 sdm

Despite that, i have only 1 thread of sox.
I tried to replace sox with sox-dsd and it is the same.

Can you help please ?

Thanks

**Comment by terual** [comment]
Can you please describe how you are determining that sox is not using multiple threads?

**Comment by th2j** [comment]
Hello,

Thanks for reply

With this command :
ps -eTo user,pid,tid,class,rtprio,ni,pri,psr,pcpu,stat,wchan:14,comm
 --sort=-rtprio

or with htop

Have a nice day
Thomas


Le sam. 19 févr. 2022 à 07:11, Bart Lauret ***@***.***> a
écrit :

**Comment by mherger** [comment]
Please get in touch with the plugin author, or join the community on forums.slimdevices.com. This is not a LMS issue.

**Comment by th2j** [comment]
Well i don't know, if it is not a LMS issue

The same plugin works well with multi-treading with the OS Daphile.
And I think Daphile use a modified version on LMS (or just older).
So maybe it comes from LMS.

How can you be so sure ?

Thanks

**Comment by michaelherger** [comment]
There have been no complaints about this before. Now it shows up for the use with that plugin alone.

I'll be happy to receive a bug report which clearly shows the issue _without_ using a third party plugin. But it would certainly be helpful to have the plugin author's opinion. I would be surprised if he hadn't noticed that what he implemented actually didn't work.

**Comment by michaelherger** [comment]
Ok, maybe I didn't read that report well enough. Is all you're saying that while the plugin is working, the sox process wasn't using multi-threading? It's not a bug, but a missed opportunity for optimization?

What OS are you using on what hardware?

**Comment by th2j** [comment]
yes exactly, sox process isn't using multi-threading, as it should because i use the option --multi-threaded

I tried on :
- ubuntu 20.04 with i7-4750HQ
- fedora server 33 with celeron j3455

**Comment by terual** [comment]
Maybe @ralph-irving can chime in as he provided the current binaries? Is the sox fork  from mansr used in LMS?

**Comment by ralph-irving** [comment]
LMS uses a snapshot of the mansr fork and other patches that restore some features used by LMS but have been removed from the newer sox sources.
sox uses openmp for multithreading support and I don't compile the linux lms binaries support it and here's why.
openmp chews up all available CPUs, sometimes to the point where the system performance is impacted.  I used to use it in squeezelite until users started complaining about poor performance.  The build option is still there today.
The sources and build script for the sox included in LMS is available at https://github.com/Logitech/slimserver-vendor/tree/public/8.3/sox  You can build it yourself. Install the libomp-dev ubuntu package and build-essentials and add  --enable-openmp to the sox configure command near the bottom of the buildme-linux.sh build script.  Then just replace the include sox binary with the one you've built.

**Comment by michaelherger** [comment]
Thanks for the clarification @ralph-irving!

**Comment by th2j** [comment]
OK thanks
I tried to replace the sox binary by the version witch is in Daphile (where multithreading works), but it doesn't work at all (not just multithreading, the all sox is not recognised). Do you know why this is not possible ?

**Comment by ralph-irving** [comment]
Likely because the daphile sox binary requires different system library versions and/or you don't have the openmp library installed on your OS. That's why I suggested you built sox on your system.

**Comment by th2j** [comment]
ok i will try,
but i have never did that !

thanks

**Comment by terual** [comment]
@th2j why would you want to use multithreading? Is using a single thread not enough to keep up in real time?

**Comment by th2j** [comment]
with one thread, i can only do conversion to DSD128,
i would like to test DSD256

**Comment by terual** [comment]
@michaelherger @ralph-irving if there is a legitimate use case for an openmp enabled sox, maybe we can provide a second sox binary (for instance as sox-mt)? Then the user can select this binary if needed. If you agree I am willing to make the necessary changes to the build scripts.

**Comment by michaelherger** [comment]
It's adding more maintenance work for a super esoteric use case. I don't see why we should be doing this. Feel free to provide your own plugin adding such a binary.
