### ISSUE TITLE
SlimServer does not work with the off-the-shelf cometd library from npm - I think it can with very small changes.

### ISSUE THREAD

**Issue by lynniemagoo** [LMS-Community/slimserver#765]
I have done quite a bit of research and testing with the cometd library available from npm.   I first started working with 5.0.0 version of the library and got things working using the long-polling version of the cometd client subscriptions.  The client library does not support streaming/pipeline subscriptions but I don't need this for my application just yet.

In order to get a client working that properly handles callbacks, the cometd client uses an 'id' field in each message to the server and upon receiving a response, uses the echoed 'id' to notifiy callbacks and listeners.  
The library properly sends the messages to slimserver but upon responding, the slimserver event does not include the incoming 'id' field.  From my initial observation of the comet implementation in slimserver, I see that the code extracts the clientId from each message and echoes that in the corresponding event.   I'm wondering if a fix would be as simple as including the original 'id' field if it exists in each emitted event.

@mherger - I'm prepared to do a fork and a PR but don't have the ability to build slimserver locally.

Comments are appreciated.

**Comment by lynniemagoo** [comment]
@mherger - I just confirmed the local changes I made to 5.0.0 version of cometd to allow to work with LMS also apply to the latest 7.0.5 version from npm.  I created 2 PRs for this issue for both v8.2 and v8.3.

**Comment by mherger** [comment]
Fixed via #767.

**Comment by lynniemagoo** [comment]
@mherger Fix confirmed and tested using 8.3 nightly for Windows.

http://downloads.slimdevices.com/nightly/8.3/lms/99bdfa09c450745600b4513ae5ec9fe7e9026087/LogitechMediaServer-8.3.0-1645360070.exe

My current setup still using outdated WHS Version 1.  I see from the nightly builds that the WHS version has not built since 20200216.  Is WHS support being discontinued?  

When fix is back-ported to 8.2, I can test there presuming that WHS builds are still working.
