### ISSUE TITLE
Imported online library albums appear twice in Artist Albums if album title contains non ASCII Chars

### ISSUE THREAD

**Issue by mwMiachel** [LMS-Community/slimserver#768]
Favourite Albums from Qobuz appear twice in Artist Listing if the Album Title contains non ASCII characters.

Version: 8.3.0 

To reproduce: 
Favourite for example https://play.qobuz.com/album/gtqeq4eq54dca (Title is VOILÀ)

![Arttist](https://user-images.githubusercontent.com/100064767/154833660-3833aeec-baf4-4776-b94a-b8489735e1f0.jpg)

**Comment by michaelherger** [comment]
Is this in the Qobuz menu or in the My Music section? 

In any case that's probably more of a Qobuz plugin issue rather than LMS (see https://github.com/pierrepoulpe/SqueezeboxQobuz).

**Comment by michaelherger** [comment]
Nope, I can confirm this is a LMS 8.3 regression. Most likely introduced by the recent changes to the scanner to _get rid_ of duplicated albums etc.... argh. I'm seeing the same with Spotty etc.

**Comment by mwMiachel** [comment]
It's the My Music Section. New Music Listing and Qobuz Menu are OK. This startet after the last commit.

A full Library Scan (after deleting all db files) fixes that until the next Scan. 

One of the two Albums listet has no tracks, and that stays if the favorite is removed.

**Comment by mherger** [comment]
Thanks @mwMiachel! New builds are in the pipeline.

**Comment by mwMiachel** [comment]
Thank you, that was fast, the Issue is fixed.
