### ISSUE TITLE
plugin squeeze2upnp downloads Virus?

### ISSUE THREAD

**Issue by trufy** [LMS-Community/slimserver#772]
I just seen on my Firewall that the squeeze2upnp was trying to download a file called "squeeze2upnp-sparc-static".
This file has been blocked and detected as a Virus on my Firewall "Virus/Linux.WGeneric.cfunaz".
While this might be a false/positive, would be great if someone could check the repo.

**Comment by michaelherger** [comment]
Upload the file to https://www.virustotal.com/ to see what that gives. It would scan the file with dozens of scanners (IIRC), which would give you an idea of the probability of it being a virus or not. Most likely it's a false positive.

Definitely not a LMS issue, but rather the plugin's. I'd recommend you post to forums.slimdevices.com or https://github.com/philippe44/LMS-to-uPnP.
