### ISSUE TITLE
New version FLAC codec 1.3.4

### ISSUE THREAD

**Issue by JWBro** [LMS-Community/slimserver#773]
I found that there's new version FLAC codec namely version 1.3.4..
Will this new one be included in one of the upcoming version of the Logitech / slimserver?
best regrads
ajan Broenink  jwbroenink@hotmail.com

**Comment by JWBro** [comment]
Thanks so much … Jan

**Comment by michaelherger** [comment]
Please note that the Windows version (and some of the less popular choices) hasn't been updated yet.
