### ISSUE TITLE
fab4: bin == bin.sha

### ISSUE THREAD

**Issue by fastfwd-zz** [LMS-Community/slimserver#782]
It is unclear to me where the baby, fab4, and jive firmware images come from -- they don't appear in this repo's Firmware/ directory -- but in my installation, the fab4 hash file erroneously contains the fab4 image instead.  Specifically:

```
root@NAS1:/usr/share/squeezeboxserver/Firmware# ll fab4*
-rw-r--r-- 1 root root 34280333 Jun 20  2020 fab4_7.8.0_r16754.bin
-rw-r--r-- 1 root root 34280333 Jun 20  2020 fab4_7.8.0_r16754.bin.sha
```

**Comment by mherger** [comment]
Please delete both files. LMS should re-download them if needed.

**Comment by fastfwd-zz** [comment]
Thanks, Michael.  Closing.
