### ISSUE TITLE
TIDAL not working

### ISSUE THREAD

**Issue by tomcat24** [LMS-Community/slimserver#784]
Clicking on TIDAL from LMS is throwing the below error...
"You must be a Premium Access subscriber to use TIDAL from this device."
I have a Premium and it was working fine this morning.

**Comment by michaelherger** [comment]
Did you check your server.log? Any communication errors?

**Comment by tomcat24** [comment]
It started working after I restarted LMS… please mark it as resolved. Thank you for following up.
