### ISSUE TITLE
Add an Album to Favorites goes wrong

### ISSUE THREAD

**Issue by BeActivated** [LMS-Community/slimserver#785]
Hi,

If there are several albums in the LMS collection with the same Title but by a different Artist it adds always the same Album to the favorites, but that is not the right one (except for the one case).
Example:
I add 'Anthology' from 'The Clean' to the favorites, but In the favorites appears 'Anthology' from 'The Babys'

Kind regards

**Comment by mherger** [comment]
The favoriting system indeed is a bit limited in this regard. It only ever uses an album title to identify the album. I'll see whether this can be changed.

**Comment by mherger** [comment]
Fixed/improved in 8.3

**Comment by BeActivated** [comment]
Thanks,
I can add then now on 'Album Artists' and 'All Artists' but not on 'Albums'.
But unfortunately they are not Playable and cannot be Add to the current playlist, only the one with has alphabetically the first artist.

**Comment by mherger** [comment]
I'm sorry, I don't understand what you're trying to do? What are you not able to add? This issue is about Albums - which I've tested extensively. It's not about adding artists to favorites.

**Comment by BeActivated** [comment]
Sorry I didn't explain it properly.
With 'Album Artists' , 'All Artists' and  'Albums' i mean the left side menus under My Music.
I can add ''Albums with the same Title'' to favorites when i choose an album in 'Album Artists' and 'All Artists' but not in 'Albums'.
When added in favorites, the ''Albums with the same Title'' cannot be Played or Add to the current playlist.
If the ''Album with the same Title'' in favorites has alphabetically the first artist it can be played.

**Comment by mherger** [comment]
Are you using the Default skin, or Material? If the latter, would it work with Default?

Would you mind sharing your favorites.opml file with me?

Do you have multiple artists for those albums (as shown in the left hand side menu)?

**Comment by BeActivated** [comment]
I tested it in the default skin.
Hereby the test Favorites.
[Uploading Favorites.zip…]()

**Comment by BeActivated** [comment]
[favorites.zip](https://github.com/Logitech/slimserver/files/8553703/favorites.zip)
![Favorites](https://user-images.githubusercontent.com/88147509/165071817-16571b3a-64e3-4bc5-af93-4c16d2266825.jpg)

**Comment by mherger** [comment]
Thanks! Can you tell me which one of these works, and which one doesn't? 

If you enabled logging for `database.sql` you'd get the SQL query resulting from the above information when you try to play an item. Would you mind sharing the server.log.zip file with me?

How does favoriting an album from the albums list fail? Do you get any error message?

**Comment by BeActivated** [comment]
[image: FavoritesNotPlaying.jpg]
With a red line are not playing.
Anthology - The Babys & The Best Of - Blur are playing

I do not get a message when i add an album to favorites and it fails.

Op ma 25 apr. 2022 om 13:29 schreef Michael Herger ***@***.***

**Comment by BeActivated** [comment]
[server.log.zip](https://github.com/Logitech/slimserver/files/8554749/server.log.zip)
![FavoritesNotPlaying](https://user-images.githubusercontent.com/88147509/165094688-5bc13c06-3398-4465-bcca-16c11ddccbdd.jpg)

**Comment by michaelherger** [comment]
Thanks for the additional information. I was able to reproduce some of what you reported. Please give the next build another try. I've improved handling of those favorites.

**Comment by BeActivated** [comment]
'Albums with the same Title' in Favorites can now be Played or Added to the current playlist.

'Albums with the same Title' can not be added to Favorites from My Music->Albums

Thank you for your work.

**Comment by michaelherger** [comment]
Could you please be a little more precise? Favoriting from the "Albums" menu actually is the only way I tested, and it's definitely working here. What exactly are you doing, what happens, what are you expecting to happen? Would you get the heart icon? Can you describe step by step what you are clicking?

**Comment by michaelherger** [comment]
Ok, I've found some more funkiness when drilling down to the album details page. And the heart icon on the album page seems to be suffering from some caching issue. It sometimes wouldn't show the correct state. More work to do.

**Comment by BeActivated** [comment]
Sorry, I closed it.

Op zo 27 okt 2024 om 19:02 schreef github-actions[bot] <
***@***.***>:
