### ISSUE TITLE
Squeezebox Boom Line input selection is not available anymore

### ISSUE THREAD

**Issue by kalon33** [LMS-Community/slimserver#789]
In latest 8.3 series snapshots, it seems that Line input selection for Squeezebox Boom is not available anymore in LMS client (Squeezer or web interface). I have to select it on the device to enable it.

Could you please investigate?

Best regards and thanks for your help.

**Comment by michaelherger** [comment]
Did you enable the plugin in Settings/Plugins?

**Comment by kalon33** [comment]
Yes, it's enabled.

**Comment by mherger** [comment]
Ok, can confirm. Behaviour has changed somewhere in between 7.7 and 8.3. What was the version you were using before?

**Comment by mherger** [comment]
Ok, or maybe not... what OS are you using? What Perl version? Can you post your system details from Settings/Information?

It's kind of unpredictable here... Sometimes it would work, sometimes it would not. At first I thought it was the LMS version. But then I went back to 8.3, but started using Perl v5.18 on my Mac. And suddenly it would work in 8.3, too. Switched back to Perl v5.34 - and continued to work. So it's neither LMS nor Perl version. But some other oddity. Maybe some internal state which wouldn't correctly be set.

Can you try to play with line in connected at startup etc. several times, to see whether that makes any difference?

**Comment by mherger** [comment]
Never mind - found the culprit. Thanks for this report! You discovered a regression caused by some other change.

**Comment by philippe44** [comment]
Is this something I should handle?

**Comment by mherger** [comment]
> Is this something I should handle?

No. I was surprised there was no state initialisation anywhere in the Slimproto module. It was always initialised as a side-effect of calling `stop()`. And that is no longer called in all circumstances the state object sometimes wasn't created. As you can see the change is pretty simple and should solve this for good.
