### ISSUE TITLE
Very small fix: bogus perl version queries

### ISSUE THREAD

**Issue by stsichler** [LMS-Community/slimserver#799]
Hi,
I just stumbled across an old commit from me in my fork of the slimserver which I never created a pull request from.
Please see my commit 516a500cd18ac3e1baf972ae6e01cebd03f4c1c6
(and explanation: https://www.tutorialspoint.com/perl/perl_special_variables.htm)

It's so long ago that I was actively working on that repo and it's such a small fix that I don't want to do the full process of update from upstream, checkout, create a feature branch for that and make a pull request.... 

Can anybody currently actively working here just (test and) commit this?
Thanks!

**Comment by michaelherger** [comment]
Thanks for the hint. Both these issues have been fixed upstream already. For `IO::String` it even seems to be the only change since the already old version we're using... (see https://metacpan.org/dist/IO-String/changes, latest entry). We might just update those modules instead of patching them.

**Comment by stsichler** [comment]
> ...We might just update those modules instead of patching them.

👍

**Comment by stsichler** [comment]
Btw. it's very cool that you all actively still maintain the Squeezebox Server! 
I'm happily still using all my Squeezeboxes and would not know how to replace them when they stopped working eventually...

*THANK YOU!*

It's a shame that they are no longer produced.

**Comment by mherger** [comment]
I decided not to deal with PAR, as I'd rather remove that module. It's really legacy for some really, really old plugins which haven't been maintained in a decade or more...
