### ISSUE TITLE
Recent 7.8 builds break (or are broken by) Triode's Network Test v1.0 plugin

### ISSUE THREAD

**Issue by fastfwd-zz** [LMS-Community/slimserver#8]
Michael: Thank you very much for all the excellent work you have done on slimserver.  I believe that I have found a bug that was introduced into LMS 7.8 sometime between 14 July and 15 September:
### Configuration
- Server: LMS 7.8 running on a Netgear ReadyNAS Pro (x86, Debian Etch variant)
- Server plugins: Many, including Network Test v1.0 by Triode
- Player: Squeezebox3 with firmware 137
### Issue

**With LMS 7.8 builds 1373542147 (2013-07-14) and earlier:**
No problem.

**With LMS 7.8 builds 1378973751 (2013-09-15) and 1380101233 (2013-09-27) -- and presumably with builds between those dates:**
Shortly after connecting to the server, the player suddenly starts to run Triode's Network Test plugin for no reason.  This can happen while at the Now Playing screen or just while browsing the player menus with the remote control: The music stops (if it was playing) and the Network Test meter and percentages appear.  The  test display is erratic and inaccurate, and when the remote-control LEFT or HOME button is pressed to exit Network Test, the player almost immediately re-enters Network Test; it is impossible to keep the player out of the Network Test state for more than one or two seconds.
### Things that _do not_ fix the problem
- Restart the player.
- Restart the server.
- Reinstall either of the problematic LMS 7.8 builds.
- Reinstall player firmware.
- Replace batteries in the IR remote control.
- Control the player with a Squeezebox Touch instead of the IR remote control.
### Things that do fix the problem
- Downgrade to build 1373542147 (2013-07-14).  Other builds between that one and 1378973751 (2013-09-15) might also work, but I do not have access to them.
  
  _or_
- Deactivate the Network Test plugin.

If I can provide more information to help you identify or debug the issue, please ask.

**Comment by mherger** [comment]
Now that's an interesting report... but I seriously doubt this is a generic problem and not limit to some configurations (yours :-)). I've never heard of this before, and have been running 7.8 "forever". Did you try a factory reset on the player? Remove the prefs & cache folder from the server (make a backup before doing so!)?

**Comment by mherger** [comment]
Please get in touch with Triode on forums.slimdevices.com should you still see this problem. Thanks!
