### ISSUE TITLE
Treat Disc Subtitles as a sub-collection of albums for collections

### ISSUE THREAD

**Issue by craigmaloney** [LMS-Community/slimserver#80]
I have several boxed sets (Herbie Hancock: The Complete Columbia Album Collection 1972 - 1988) that have multiple discs representing multiple albums.

The tags for the album (from Musicbrainz) are as follows for an example track:

DISCID: 340abe05
DISCNUMBER: 10
DISCSUBTITLE: V.S.O.P. (disc 2)
DISCTOTAL: 34

I'd like to have the ability to get to a particular DISCSUBTITLE after clicking on the album without having to look at the tags to see which track is part of which album.

So in this case it'd be:

Artist: Herbie Hancock [click]
Album: The Complete Columbia Album Collection 1972 - 1988 [click]
Disc Subtitle: V.S.O.P. (disc 2) [click](and then a list of the tracks)

**Comment by mherger** [comment]
A similar request has come up a few months ago where people would like to be able to browse discs from disc sets separately.

As for your particular request: I think we don't even store the sub title data in the database. Or does it somehow show up in LMS? Therefore there is little chance for this to happen

**Comment by craigmaloney** [comment]
I got that information via LMS via "View Tags" on the song itself. So the data is there but not being captured.

**Comment by chincheta0815** [comment]
I like that idea also...
But I fear that there is not DISCSUBTITLE in the database yet.
How would I get it in there? 
Can you tell me how to get an existing tag into the DB?
Do you have an example? E.g. "Do it as for DISCC."

**Comment by michaelherger** [comment]
Subtitles, works etc. have been implemented in LMS9.
