### ISSUE TITLE
Log is flodded with callback warnings "Can't call method "display" on an undefined value"

### ISSUE THREAD

**Issue by C2022H** [LMS-Community/slimserver#802]
Since quite a while my /var/log/messages get flooded from time to time  with
**Slim::Utils::Misc::msg (1347) Warning: [23:59:57.5143] EV: error in callback (ignoring): Can't call method "display" on an undefined value at /usr/lib/perl**
I wasn't able to find the client that causes the issue, I have some special clients and the issue is hard to reproduce. It occurs after hours/days, but once the flooding starts it will not stop until I shutdown the slimserver (10 or more messages per second).
This little patch fixes the issue and it should not harm anybody. Would be nice if this patch could be applied in future versions.

\# patch for errors flodding /var/log/messages with
\# Slim::Utils::Misc::msg (1347) Warning: [23:59:57.5143] EV: error in callback (ignoring): Can't call method "display" on an undefined value at /usr/lib/perl

--- /usr/lib/perl5/vendor_perl/Slim/Display/Lib/TextVFD.pm.org
+++ /usr/lib/perl5/vendor_perl/Slim/Display/Lib/TextVFD.pm
@@ -145,6 +145,9 @@

 sub vfdUpdate {
        my $client = shift;
\+
\+       return if !defined($client);
\+
        my $line1  = shift;
        my $line2  = shift;

**Comment by michaelherger** [comment]
Would be great to know where those requests are coming from. I quickly skimmed the code and didn't find how that call could end up without the `$client` object. Are you using some 3rd party plugin dealing with the display (MusicInfoSCR, Squeezelite-ESP32 or the like)?

**Comment by C2022H** [comment]
Hi Michael,
Besides the official players I am using a squeezeslave-1.3-393 with jivelite on my Linux computer and I have two piCore player in use. My son is using the command-line interface (via telnet) feeding his libwebsocket server with data from the slimserver.
I think it is the telnet interface, but as I already said, it is hard to debug it as it might take hours/days to happen.
