### ISSUE TITLE
Is Michael Herger okay?

### ISSUE THREAD

**Issue by worsco** [LMS-Community/slimserver#804]
There's been a few issues and PR submitted since June, and Michael Herger's contributions have github contributions have stopped.

https://github.com/mherger

Is @mherger okay?

**Comment by michaelherger** [comment]
Thanks for asking! I can reassure you that I'm very fine indeed. After two weeks in the Scandinavian wilderness I'm on my (slow) way back home. My only worry right now is whether the railway service will fail our overnight connection later today 😂.

(Damn those implicit activity trackers like Github! This has been the first time in many years that I've travelled more than a week without any dev tools. The [one commit](https://github.com/LMS-Community/lms-plugin-repository/commit/39932e0d7ce47308f9f8d68c29a00ef8786cc652) I did was done using my other account on my phone using [Working Copy](https://workingcopyapp.com) - highly recommended! 😉)

**Comment by worsco** [comment]
Michael, please enjoy your holiday, sorry for the intrusion as it's very rare for slimserver to not have a PR/MR completed once a week by someone (you, of course).  Safe travels and happy holiday!!!

Your work and efforts with slimserver are always appreciated here!!!!!  And I'm enjoying the "material" skin (a 3rd party plugin) more and more each day/interaction with it, too.
