### ISSUE TITLE
Getting error and looping starting LMS on fresh installation in a Docker Container

### ISSUE THREAD

**Issue by dlandon** [LMS-Community/slimserver#807]
I am having an issue with a Docker Container with a fresh installation.  This is not happening with an older installation:
Can't call method "log" on an undefined value at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender.pm line 189.
Can't call method "log" on an undefined value at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender.pm line 189.
Can't call method "log" on an undefined value at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender.pm line 189.
Can't call method "log" on an undefined value at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender.pm line 189.
Can't call method "log" on an undefined value at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender.pm line 189.
Can't call method "log" on an undefined value at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender.pm line 189.
Can't call method "log" on an undefined value at /usr/share/squeezeboxserver/CPAN/Log/Log4perl/Appender.pm line 189.
*** Shutting down runit daemon (PID 322)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
*** Init system aborted.
*** Killing all processes...
Start Logitech Media Server...
[22-08-28 06:49:55.2777] main::init (377) Starting Logitech Media Server (v8.3.0, 1661147463, Mon 22 Aug 2022 08:27:17 AM CEST) perl 5.030000 - x86_64-linux-gnu-thread-multi
[22-08-28 06:49:55.7088] Slim::Plugin::FullTextSearch::Plugin::_initPopularTerms (587) Fulltext index missing or outdated - re-building
[22-08-28 06:49:55.7090] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (475) Starting fulltext index build
[22-08-28 06:49:55.7091] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (483) Initialize fulltext table
[22-08-28 06:49:55.7113] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (496) Create fulltext index for tracks
[22-08-28 06:49:55.7116] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (506) Create fulltext index for albums
[22-08-28 06:49:55.7119] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (515) Create fulltext index for contributors
[22-08-28 06:49:55.7125] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (525) Create fulltext index for playlists
[22-08-28 06:49:55.7139] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (540) Optimize fulltext index
[22-08-28 06:49:55.7146] Slim::Plugin::FullTextSearch::Plugin::_rebuildIndex (555) Fulltext index build done!

**Comment by michaelherger** [comment]
Please share more information about your setup: what OS, Docker container configuration, full server.log etc.

**Comment by dlandon** [comment]
OS:
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"

Configuration:
#!/bin/bash

docker run -d --name="LogitechMediaServer" \
--net="bridge" \
-p 3483:3483/tcp \
-p 9000:9000/tcp \
-p 9090:9090/tcp \
-e PUID="99" \
-e PGID="100" \
-e TZ="America/Chicago" \
-v "/mnt/user/appdata/LogitechMediaServer":"/config":rw \
-v "/mnt/user/Music":"/music":rw \
dlandon/logitechmediaserver

Server logs:
[server.zip](https://github.com/Logitech/slimserver/files/9440060/server.zip)

**Comment by michaelherger** [comment]
you'll need 3483/udp, too. But I doubt that's the problem. Can you check none of those ports isn't already used on your host system? 9000 is particularly popular and therefore prone for conflicts.

**Comment by dlandon** [comment]
A little background.  This is not a newly created docker container.  This is a containter that I built for the Unraid OS and released in 2017.  https://hub.docker.com/r/dlandon/logitechmediaserver

It is a very popular container for Unraid.  It has been wortking without issues until recently a user reported this issue when they first tried to install a fresh copy of the LMS container.  I had never seen the issue because I have been testing on an existing configuration.  It occurs when the container is started and the database first created.  After shutting it down and restarting it, the error goes away.  On a system with an existing database, the error does not show up.

On Unraid the container will not start if there is a port conflict.  It is blocked for the reason you mention - port conflicts.

i will add 3483/udp.  I'n surprised this has not created an issue.

I suspect the there is a recent update to Ubuntu that has caused this.

I am a very experienced programmer and I can troubleshoot and test if you let me know what to look for.  I am not that good at coding in perl, but I understand enough to work with it.

**Comment by michaelherger** [comment]
Please get in touch with the creator of the image you're using. He would know better how to investigate this issue.

**Comment by dlandon** [comment]
That's me - I am the creator.  I have no idea where to start because I feel it is a LMS issue.

**Comment by michaelherger** [comment]
Haha... sorry, I didn't read carefully enough 😁. Now I'm not sure where exactly to begin. But first probably: what's the main difference between your image and the official one? Is there still a need for your image? You could save yourself the hassle of maintaining your own. Or you could use the official image as the base for yours and see whether that would work?

Next build or start the container with some more debug logging flags: `-d_startup` and/or `server=debug` might give you more information. Would that already reveal something useful?

**Comment by dlandon** [comment]
I'm probably going to see about using a different base image.  Most likely a compatibility issue with the latest Ubuntu Focal.
