### ISSUE TITLE
Index of spotify fails.

### ISSUE THREAD

**Issue by NikolajHansen** [LMS-Community/slimserver#815]
Hi,

I have just upgraded to the last logitechmediaserver-8.3.0-1662405429 and upgraded the spotty helper app to spotty] spotty v1.3.1 - using librespot 0.4.2 9b95691 (Built on 2022-09-19, Build ID: 5ToCSuBf, Profile: debug)

Platform: FreeBSD squeezebox.barnabas.dk 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64

I am having issues running the index of my music collection on spotify. The rest of the integration seems to work fine. I am able to play, browse music etc.

https://pastebin.ubuntu.com/p/nWZk7WSC5M/

What am I doing wrong? 

with regards
Nikolaj Hansen

**Comment by mherger** [comment]
Please post to https://github.com/michaelherger/Spotty-Plugin/issues - this isn't a LMS issue. Edit the pastebin to not show the full command run... Then run that command manually and report the result, too. Thanks!
