### ISSUE TITLE
A specific mp3 file is messing with the playlist

### ISSUE THREAD

**Issue by decibyte** [LMS-Community/slimserver#816]
I have recently acquired an mp3 file that does something weird to the playlist. I've attached a screen recording, trying to show what's going on.

[mp3-playlist-issue.webm](https://user-images.githubusercontent.com/224219/191207233-b8095121-0559-411a-9a65-edbfe78947b4.webm)

What I do:
 * Add the Ninajirachi album. This adds 2 songs to the playlist, as expected.
 * Add the eloq album. This apparently doesn't change the playlist. Expected result would be to add another song to the playlist.
 * Add the Liam Mour album. This adds 6 songs to the playlist, as expected.

The playlist now seems to contain 8 items: 2 songs from Ninajirachi and 6 songs from Liam Mour.

Then I press play on the first song and start skipping after a few seconds:
 * Skipping the song Petroleum (1st on playlist) plays the song Hidden Land (2nd on playlist) which is also highlighted with the :musical_note: in the playlist, as expected.
 * Skipping the song Hidden Land (2nd on playlist) plays the song LOSE YOU (not visible on playlist) and highlights When I Look Into Your Eyes (3rd on playlist). This is a weird mix of (un)expected behaviours. LOSE YOU is the next song I would expect to hear, according to how I composed the playlist. But unexpected according to the playlist shown. The highlighting of When I Look Into Your Eyes (3rd on playlist) is is what I expect when I skip from Hidden Land (2nd on playlist), but it doesn't correspond to the song that is actually being played.
 * The same inconsistency/off-by-one situation goes for the rest of the playlist.
 
Not shown in the screencast: If I press play on a specific song from position 3, it's also off-by-one. Pressing play on When I look Into Your Eyes (3rd on playlist) plays LOSE YOU (not visually present on playlist).

Similar issues are present if I look at data from the LMS CLI.

What is going on with this ghost song? Is this a known issue with certain files and is there a way to make them behave properly?

I can of course provide the mp3 privately to anyone who wants to look into this issue.

**Comment by michaelherger** [comment]
Could you please check the server.log whether there's any hint about a rendering issue? It looks as if rendering the two tracks failed for some reason. The count in the top section is correct. I would assume that the display on device or a mobile app would be correct?

**Comment by decibyte** [comment]
Going through this dance again gives me nothing in the log. Can I change the log level to get more information about what's happening?

**Comment by michaelherger** [comment]
`player.playlist` might give _something_, but probably not much helpful. What about the list on other UIs? Material skin or mobile app, device display?

**Comment by decibyte** [comment]
> `player.playlist` might give something

I'm not sure I understand this. Is `player.playlist` a setting og configuration somewhere I need to tweak?


As said, I have similar issues when querying the CLI.

While playing the hidden track, `<player_id> status 0 100 tags:gald` gives me:

```
<player_id> status 0 100 tags%3Agald player_name%3Avbro%3A%20Spisestue player_connected%3A1 player_ip%3A192.168.1.117%3A42426 power%3A1 signalstrength%3A0 mode%3Astop sync_master%3A00%3A04%3A20%3A10%3A0d%3A3b sync_slaves%3A00%3A04%3A20%3A23%3A09%3Acb mixer%20volume%3A75 playlist%20repeat%3A0 playlist%20shuffle%3A0 playlist%20mode%3Aoff seq_no%3A9 playlist_cur_index%3A0 playlist_timestamp%3A1663675737.74764 playlist_tracks%3A9 digital_volume_control%3A1 playlist%20index%3A0 id%3A54399 title%3APetroleum genre%3ANo%20Genre artist%3ANinajirachi album%3APetroleum%20%2F%20Hidden%20Land duration%3A198.769 playlist%20index%3A1 id%3A54400 title%3AHidden%20Land%20(feat.%20Raj%20Mahal) genre%3ANo%20Genre artist%3ANinajirachi album%3APetroleum%20%2F%20Hidden%20Land duration%3A205.734 playlist%20index%3A2 id%3A54393 title%3AWhen%20I%20Look%20Into%20Your%20Eyes genre%3ANo%20Genre artist%3ALiam%20Mour album%3ADreaming%20Of%20A%20Better%20Place duration%3A252.003 playlist%20index%3A3 id%3A54394 title%3ANineteen%20Ninety genre%3ANo%20Genre artist%3ALiam%20Mour album%3ADreaming%20Of%20A%20Better%20Place duration%3A353.696 playlist%20index%3A4 id%3A54395 title%3ALove genre%3ANo%20Genre artist%3ALiam%20Mour album%3ADreaming%20Of%20A%20Better%20Place duration%3A278.325 playlist%20index%3A5 id%3A54396 title%3AWaking%20After%20Accident genre%3ANo%20Genre artist%3ALiam%20Mour album%3ADreaming%20Of%20A%20Better%20Place duration%3A242.79 playlist%20index%3A6 id%3A54397 title%3ACaravan genre%3ANo%20Genre artist%3ALiam%20Mour album%3ADreaming%20Of%20A%20Better%20Place duration%3A277 playlist%20index%3A7 id%3A54398 title%3ADreaming%20Of%20A%20Better%20Place genre%3ANo%20Genre artist%3ALiam%20Mour album%3ADreaming%20Of%20A%20Better%20Place duration%3A305.874
```

And in a more readable version:

```
<player_id>
status
0
100
tags:gald
player_name:vbro: Spisestue
player_connected:1
player_ip:192.168.1.117:41183
power:1
signalstrength:0
mode:play
time:8.20416801834106
rate:1
duration:188.852
can_seek:1
sync_master:00:04:20:10:0d:3b
sync_slaves:00:04:20:23:09:cb
mixer volume:75
playlist repeat:0
playlist shuffle:0
playlist mode:off
seq_no:9
playlist_cur_index:2
playlist_timestamp:1663675737.74764
playlist_tracks:9
digital_volume_control:1
playlist index:0
id:54399
title:Petroleum
genre:No Genre
artist:Ninajirachi
album:Petroleum / Hidden Land
duration:198.769
playlist index:1
id:54400
title:Hidden Land (feat. Raj Mahal)
genre:No Genre
artist:Ninajirachi
album:Petroleum / Hidden Land
duration:205.734
playlist index:2
id:54393
title:When I Look Into Your Eyes
genre:No Genre
artist:Liam Mour
album:Dreaming Of A Better Place
duration:252.003
playlist index:3
id:54394
title:Nineteen Ninety
genre:No Genre
artist:Liam Mour
album:Dreaming Of A Better Place
duration:353.696
playlist index:4
id:54395
title:Love
genre:No Genre
artist:Liam Mour
album:Dreaming Of A Better Place
duration:278.325
playlist index:5
id:54396
title:Waking After Accident
genre:No Genre
artist:Liam Mour
album:Dreaming Of A Better Place
duration:242.79
playlist index:6
id:54397
title:Caravan
genre:No Genre
artist:Liam Mour
album:Dreaming Of A Better Place
duration:277
playlist index:7
id:54398
title:Dreaming Of A Better Place
genre:No Genre
artist:Liam Mour
album:Dreaming Of A Better Place
duration:305.874
```

Worth noting is `playlist_tracks:9`, but I'm only getting 8 tracks (0-7).

**Comment by michaelherger** [comment]
Logging options you can find in Settings/Advanced/Logging.

Did you check the file's tags? Or see whether it would behave the same on a different machine (eg. your desktop instead of the usual LMS machine)?

**Comment by decibyte** [comment]
I just did a complete rescan of my library and now the problem seems to have gone :facepalm: 

Sorry for wasting your time, @michaelherger.
