### ISSUE TITLE
WAV files over 2.1 GB go to No Album

### ISSUE THREAD

**Issue by steveleen** [LMS-Community/slimserver#819]
I am using LMS 8.3.0.  On this version and on previous versions I have noticed strange behavior for wav files over 2.1 GB in size.  Instead of appearing with their album, these files are sent to No Album. They play normally, but they are in the wrong place.  Wav files below 2.1 GB appear correctly in their album folder.

These large files are long classical tracks up-sampled to 24/352.  In their 16/44 format, LMS handled these tracks properly.  

Attached below are screen snips of the seven files shown in No Album and displayed in a Windows file folder with the file size field.

<img width="463" alt="LMS No Album" src="https://user-images.githubusercontent.com/42309778/192823195-ec3a2805-c405-4296-b515-4130b6a9f313.PNG">

<img width="726" alt="Files over 2 GB" src="https://user-images.githubusercontent.com/42309778/192823453-80bb952e-a61c-47e6-ab36-da7211126dee.PNG">

The file properties and tags seem ok. These are attached.

<img width="282" alt="File properties" src="https://user-images.githubusercontent.com/42309778/192824888-bf74d354-b178-4915-ad49-44b82363c90a.PNG">

<img width="280" alt="Tags" src="https://user-images.githubusercontent.com/42309778/192824983-ce3c683f-e52a-4a16-b3fe-4c7e80b82dbf.PNG">

I would appreciate someone looking into this issue.  LMS is a wonderful piece of software.  I've used it for many years!

Thanks,
Stephen L.

**Comment by mherger** [comment]
Most likely the scanner code can't handle files this large.

TBH: I doubt anyone will soon be looking into an issue caused by upsampling a file to insane numbers...

**Comment by steveleen** [comment]
Point taken.  This level of upsampling is rare, and the equivalent DXD file downloading/playback scene is a niche market for sure.  However, I would imagine there are, or will be in the future, a growing group of LMS users who wish to play DXD files of classical works with resulting very large file sizes.
I was hoping the file size limitation might be easily resolved by adjusting a parameter that, years ago when LMS was designed, was considered more than sufficient. 
Anyway, thanks for your response and the work you do on LMS.
