### ISSUE TITLE
LMS 8.3: Control Panel doesn't show up

### ISSUE THREAD

**Issue by sweetsounds** [LMS-Community/slimserver#822]
Windows 11 21H2
Intel iCore 12600K

Right-Clicking on System Tray only brings up splash screen and then nothing.
Same with run as administrator or starting it from cmd.
No messages in server.log

Disabling system locale UTF-8 support in Windows Settings->Time&Language -> Language&Region  fixes the problem.

**Comment by michaelherger** [comment]
Would you mind joining forums.slimdevices.com? There are more helpful people, and I'm not a Windows user any more...
