### ISSUE TITLE
Perl 5.36

### ISSUE THREAD

**Issue by zelea2** [LMS-Community/slimserver#826]
logitechmediaserver_8.3.0~1667251155_amd64.deb

debian testing switched to perl 5.36. There is no support for this in /usr/share/squeezeboxserver/CPAN/arch

$dpkg -l perl
ii  perl           5.36.0-4     amd64

**Comment by michaelherger** [comment]
There are instructions how to build yourself: https://github.com/Logitech/slimserver-vendor/tree/public/8.3/CPAN#readme

Or use the [Dockerfile](https://github.com/Logitech/slimserver-vendor/tree/public/8.3/CPAN/Docker) to build the binaries in a container. 

I'll look into adding support for 5.36, soon.

**Comment by mherger** [comment]
There's a tarball at the bottom of https://github.com/Logitech/slimserver-vendor/actions/runs/3392298402. Could you please download it, and extract it to your LMS installation's `CPAN/arch` folder? You might need to copy the following files and folders from `CPAN/arch/5.34` to `CPAN/arch/5.35`, too:

* Audio
* Class
* DBD
* DBI*
* Image
* JSON

**Comment by sbellon** [comment]
I downloaded the tarball, extracted as instructed and have LMS 8.3.0 up and running on Debian bookworm/sid. Thanks a lot. :-)

**Comment by michaelherger** [comment]
I added those files to LMS 8.3.1 and 8.4. Please let me know should you still encounter an issue.
