### ISSUE TITLE
Secret(s) found: 12 - [Product Security - Secret Scanning]

### ISSUE THREAD

**Issue by nhamzi** [LMS-Community/slimserver#845]
This is automated issue created by Logitech Secret Scanner v1.0 - Nabil Hamzi

It seems that information looking like a secret (password, token, credentials, ...) has been identified in this github repository.
We should avoid as much as possible to store secrets in Github code repository. Github has an 'encrypted secrets' feature for this.
Please react on this thread with @nhamzi for any question.

Here are the findings, SecretLink contains the link to the sensitive value to be renewed, refreshed and deleted.

SecretLink=https://github.com/Logitech/slimserver/blob/9452ce6c86f0ae03dcb7eb88d7891a6ae843d3b4/CPAN/arch/5.36/DBD/Proxy.pm#L839-L840
SecretLink=https://github.com/Logitech/slimserver/blob/214796455b7c11d5b1b89f61adc470e1f66403cc/CPAN/arch/5.34/DBD/Proxy.pm#L839-L840
SecretLink=https://github.com/Logitech/slimserver/blob/4e5f5b45198f28388e6de6a09f983cb5590538a8/CPAN/arch/5.34/DBD/Proxy.pm#L839-L840
SecretLink=https://github.com/Logitech/slimserver/blob/7da7dab329c604729cca2971a24125b4ae5881c4/CPAN/arch/5.32/DBD/Proxy.pm#L839-L840
SecretLink=https://github.com/Logitech/slimserver/blob/1030cd37b85a8fd07d3191798d7468694b5b5625/CPAN/arch/5.30/DBD/Proxy.pm#L839-L840
SecretLink=https://github.com/Logitech/slimserver/blob/913e9d36f0c84b4f9090830a8e016c670cc9f593/CPAN/arch/5.28/DBD/Proxy.pm#L839-L840
SecretLink=https://github.com/Logitech/slimserver/blob/1a1413289e02fd1a01acfd11d13ec7c1dd417cc9/CPAN/arch/5.8/MSWin32-x86-multi-thread/DBD/Proxy.pm#L785-L786
SecretLink=https://github.com/Logitech/slimserver/blob/9b435b3b3db2c404d3b26079c1aa31b172dded7c/CPAN/arch/5.6.0/darwin/DBD/Proxy.pm#L785-L786
SecretLink=https://github.com/Logitech/slimserver/blob/9b435b3b3db2c404d3b26079c1aa31b172dded7c/CPAN/arch/5.8.1/darwin-thread-multi-2level/DBD/Proxy.pm#L785-L786
SecretLink=https://github.com/Logitech/slimserver/blob/7f9d27e9d9edeb51d313774ef730be4a7116383d/CPAN/arch/5.8/MSWin32-x86-multi-thread/DBD/Proxy.pm#L785-L785
SecretLink=https://github.com/Logitech/slimserver/blob/9b84cc292eb49619142470af5a365c502c566f78/CPAN/AnyEvent/TLS.pm#L364-L367
SecretLink=https://github.com/Logitech/slimserver/blob/dd4389b9e4672e669c51719c83673acbf21b8984/CPAN/AnyEvent/Handle.pm#L1846-L1849

**Comment by terual** [comment]
All false positives

**Comment by michaelherger** [comment]
Yep, I'll have to see how to deal with these.

**Comment by mherger** [comment]
These are all strings coming from 3rd party modules.

**Comment by mherger** [comment]
These are all strings coming from 3rd party modules.
