### ISSUE TITLE
LMS starts song in album where last stopped

### ISSUE THREAD

**Issue by schnillerman** [LMS-Community/slimserver#847]
Hi Michael,

I've been noticing a behavior for quite some time now (LMS 7 and also 8 and various Squeezeplay versions until latest):

If an album is added to playlist via the **_play_** button in the library, LMS players would start playing  in the middle of the song in an album where seemingly, it was last stopped / where I switched to another song/album or where I turned the player off etc.

I don't know if this behavior is intentional, but it sure bugs me - whenever I hit play on an album that I haven't previously completed listening to until the end of the last song (random playlist or not), it starts somewhere in the middle of that last playing song instead of with the first song, at the start of the song.

Do you think this is a player issue? Do you ever experience the same problem? I checked the issues posted here and found [one by me](https://github.com/Logitech/slimserver/issues/332) related to this. But I never got any meaningful response in the [forums](https://forums.slimdevices.com/showthread.php?112124-Songs-are-not-played-from-the-beginning-when-song-is-started). Do I explain the issue in a too complicated way?

BTW - I'm so super happy with all the recent updates and general reliablity of LMS 8 for quite a long time now (running on a virtual linux machine on my Synology for continuous updates). No problems whatsoever, always available, sync and shifting playlists between my 4+ players works flawlessly).

BR, Till

**Comment by schnillerman** [comment]
[Slartibartfast](https://forums.slimdevices.com/member.php?35609-slartibartfast) has [found the culprit (bookmarks plugin)](https://forums.slimdevices.com/showthread.php?112124-Songs-are-not-played-from-the-beginning-when-song-is-started&p=1068621&viewfull=1#post1068621) with his hound dog nose. So closing this one, hope it helps others who might run into this problem.

**Comment by mherger** [comment]
Nice one! Thanks slartibartfast!
