### ISSUE TITLE
No result return while using Chinese Keyword in Fulltext Search 

### ISSUE THREAD

**Issue by silenker** [LMS-Community/slimserver#852]
Hello,
I updated my Daphile to the latest 22.12-x86_64 version which LMS 8.3 included.There's a problem with quick search.You get nothing when using Chinese Keyword in quick search，but correct results returned when using the same Keyword in advance search.Try to rebuild database but no help.

**Comment by michaelherger** [comment]
Stupid question: would it find anything else? Is a player connected?

**Comment by silenker** [comment]
> Stupid question: would it find anything else? Is a player connected?

Everything is OK but the quick search.
"Quick search" means when you type a keyword，system will lookup library and return a list of songs and albums whose meta information contain the keyword.Just like this:
![Screenshot_2022-12-29-21-22-01-77_82b10d9f3584360f08225ddcebbb4f6d](https://user-images.githubusercontent.com/64213185/209967184-2f33230a-8b9a-4f0e-9ec2-d11d27b3490f.jpg)

You get nothing when using Chinese Keyword in quick search:
![Screenshot_2022-12-29-21-22-29-19_82b10d9f3584360f08225ddcebbb4f6d](https://user-images.githubusercontent.com/64213185/209967887-66dcad93-890f-4b77-b0bc-84a7aca89020.jpg)

Use the same Chinese Keyword in advance search，correct result return:
![Screenshot_2022-12-29-21-24-24-15_82b10d9f3584360f08225ddcebbb4f6d](https://user-images.githubusercontent.com/64213185/209968168-b2c06e11-8d9f-42d1-a86c-4fe7659ac6ef.jpg)
![Screenshot_2022-12-29-21-24-45-35_82b10d9f3584360f08225ddcebbb4f6d](https://user-images.githubusercontent.com/64213185/209968197-048724ff-d33f-48c2-a484-01a5f606e065.jpg)

**Comment by michaelherger** [comment]
You mention an update to Daphile: did it work before that update?

And you're using the Material skin. Would you see the same behavior using the Default skin?

**Comment by silenker** [comment]
> You mention an update to Daphile: did it work before that update?
> 
> And you're using the Material skin. Would you see the same behavior using the Default skin?

There's no such problem before，and nothing business with the skin.I tried:
![Screenshot_2022-12-30-18-17-44-42_82b10d9f3584360f08225ddcebbb4f6d](https://user-images.githubusercontent.com/64213185/210060061-8a60ff8a-a3e6-41f5-8483-6c356595decc.jpg)
![Screenshot_2022-12-30-18-18-57-56_82b10d9f3584360f08225ddcebbb4f6d](https://user-images.githubusercontent.com/64213185/210060069-992e044e-fc91-4159-870a-638e3cc813f6.jpg)

**Comment by silenker** [comment]
I fixed this problem by disable the "Full text  search" plugin. Thanks

**Comment by silenker** [comment]
I fixed this problem by disable the "Full text search" plugin. Thanks

**Comment by michaelherger** [comment]
Oh, thanks for that finding! I should probably re-open this report! It _is_ a bug, after all.

**Comment by michaelherger** [comment]
We might need to define `tokenizer=unicode61` or similar (see https://www.sqlite.org/fts5.html#_changes_to_create_virtual_table_statements_).

**Comment by michaelherger** [comment]
Unfortunately `tokenizer=unicode61` isn't available in our builds of the SQLite/FTS libraries.

Rather surprising: Cyrillic titles work as expected.

**Comment by silenker** [comment]
> We might need to define `tokenizer=unicode61` or similar (see https://www.sqlite.org/fts5.html#_changes_to_create_virtual_table_statements_).

That might be the root cause，Thank you for your quick response

**Comment by michaelherger** [comment]
The issue actually is caused by a change in 8.3.0 which tries to de-duplicate keywords in the full text search. This fails for certain languages.

**Comment by michaelherger** [comment]
@kimmot - can you upgrade Daphile to the latest 8.3.1?

**Comment by kimmot** [comment]
New Daphile version 23.01 is now available and it includes the latest 8.3.1 (commit: 353c504).
