### ISSUE TITLE
Incorrect delimeter for multiple-artists when browsing tracks

### ISSUE THREAD

**Issue by CDrummond** [LMS-Community/slimserver#858]
As noted in the  [Material Skin thread on LMS forums](https://forums.slimdevices.com/forum/user-forums/3rd-party-software/106269-announce-material-skin?p=1627849#post1627849) when asking for multiple composers (and probably conductors, bands, artists, etc) the `status` message deliminates these with a comma and no space, e.g. "A,B". But, it appears that when these details are returned from a `tracks` message that comma+space is used, e.g. "A, B"

For a status message Material uses:
```
curl 'http://localhost:9000/jsonrpc.js' --data-raw '{"id":0,"method":"slim.request","params":["01:02:03:04:05:06",["status","-",1,"tags:cdegiloqrstuyAABIKNSTR"]]}'
```
...and this returns:

```
{"id":0,"result":{"playlist repeat":2,"playlist mode":"off","player_name":"Test","playlist_tracks":1,"digital_volume_control":1,"playlist_loop":[{"url":"file:///home/craig/Music/TEST/01.ogg","album_id":"10","coverid":"f6c80337","duration":124.567,"playlist index":0,"composer_ids":"14, 15","year":"2019","trackartist":"Seth Rosenbloom","composer":"Seth Rosenbloom,Sonya Rae Taylor","title":"Keep On Turning","albumartist":"Seth Rosenbloom","type":"ogg","samplerate":"44100","id":30,"tracknum":"2","trackartist_ids":"14","artist_id":"14","albumartist_ids":"14","bitrate":"124kbps VBR","genre":"Blues","album":"Keep On Turning"}],"playlist shuffle":0,"player_ip":"127.0.0.1:48270","player_connected":1,"signalstrength":0,"mode":"stop","seq_no":0,"power":1,"playlist_cur_index":0,"playlist_timestamp":1674468183.46194,"mixer volume":9},"params":["01:02:03:04:05:06",["status","-",1,"tags:cdegiloqrstuyAABIKNSTR"]],"method":"slim.request"}
```

When listing traks of an album, Material uses:
```
curl 'http://localhost:9000/jsonrpc.js'  --data-raw '{"id":6,"method":"slim.request","params":["01:02:03:04:05:06",["tracks",0,25000,"tags:digkstuACISlorTRE","sort:tracknum","album_id:10","artist_id:14","role_id:ALBUMARTIST","library_id:0"]]}'
```

...and this returns:

```
{"method":"slim.request","params":["01:02:03:04:05:06",["tracks","0",25000,"tags:digkstuACISlorTRE","sort:tracknum","album_id:10","artist_id:14","role_id:ALBUMARTIST","library_id:0"]],"id":6,"result":{"titles_loop":[{"id":30,"title":"Keep On Turning","duration":124.567,"genre":"Blues","artist_id":"14","tracknum":"2","url":"file:///home/user/Music/TEST/01.ogg","albumartist":"Seth Rosenbloom","composer":"Seth Rosenbloom, Sonya Rae Taylor","trackartist":"Seth Rosenbloom","compilation":"0","albumartist_ids":"14","composer_ids":"14, 15","trackartist_ids":"14","album":"Keep On Turning","type":"ogg","bitrate":"124kbps VBR","samplerate":"44100"}],"count":1}}
```

Material has been configured to show the composer for all genres (`*` entered in the relevent settin on Material's server-side settings).

The tags used are:

artist: Seth Rosenbloom
albumartist: Seth Rosenbloom
composer: Seth Rosenbloom
composer: Sonya Rae Taylor
genre: Blues

Attached is a royalty-free OGG file I found where I have added the above tags.

[01.zip](https://github.com/Logitech/slimserver/files/10478666/01.zip)

**Comment by michaelherger** [comment]
Had a brief look into this. And I think the difference might be using tags "A" (tracks) vs. "AA" (status). From the CLI doc:

> 

Tag | Description
-- | --
A | For every artist role (one of "artist", "composer", "conductor", "band", "albumartist" or "trackartist"), a comma and space (', ') separated list of names.
AA | This is like "A", but without the space after the comma. This should simplify parsing/splitting when required.

**Comment by CDrummond** [comment]
Aarg! You are correct, sorry for the  noise!
