### ISSUE TITLE
ogg/vorbis files tagged with album art in Foobar 1.1.7 work on my Booms - later versions of Foobar create files that don't

### ISSUE THREAD

**Issue by domcote** [LMS-Community/slimserver#861]
Until a few days ago, I did all my transcoding+tagging with Foobar 1.1.7, with ogg/vorbis being the target. As long as I keep albumart <64KB, this works fine.
But in testing for Opus as a replacement for dated vorbis, I also updated to a new version of Foobar from the Windows Store.
At first glance, everything seemed to work fine, BUT Foobar 1.6.x generates files that cause the dreaded "Out of decoder memory error" on my Booms, which crashes them so hard I need to power cycle them to recover.

Here are two files from the same album, tagged with the same albumart file, but different Foobar versions.

Foobar 1.1.7 --> Works
https://1drv.ms/u/s!AoQI5_3ipPc6pMkgC-rB30OS9QMf8w?e=dP93Gl

Foobar 1.6.x --> "Out of decoder memory"
https://1drv.ms/u/s!AoQI5_3ipPc6pbIadJkaClBEBeSzlg?e=AOX82F
The same file plays fine in Squeezelite-X and any other player I tried.

I can work around the issue by opening the Foobar 1.6.x. file in Foobar 1.1.7, removing all album art and then re-tagging with the same jpg file.
So whatever causes "out of decoder memory" is only present in files tagged with album art in recent Foobar versions.

Any ideas?

(PS. I am aware that album art in vorbis files has always been... tricky at best. Especially on legacy squeezeboxes. That is one of the reasons I am trying to switch to opus going forward. But that has its own issues... 😣)

**Comment by michaelherger** [comment]
Are there details available about what might have changed in Foobar related to OGG in between the two versions?

**Comment by domcote** [comment]
No idea, sorry. I'm just a user. 😉
Can you repro what I'm seeing?

**Comment by domcote** [comment]
On a side note: If we can get Opus working, specifically https://github.com/Logitech/slimserver/issues/793 I wouldn't need this fixed anymore.
I'm quite aware that I'm probably a fringe case (vorbis + Booms, as well as Opus + Booms)

**Comment by mw9** [comment]
> Can you repro what I'm seeing?

Same issue on a Squeezebox Classic.

There is a "subtle" difference in how the metadata is packaged up:

 - In the "working" ogg file, the metadata is split up into a sequence of several ogg pages of size around 4,000 / 4,500 bytes each, with a total of about 93,000 bytes.

 - In the "not working" ogg file, the metadata is split up into two ogg pages, with first page size around 65,000 bytes, and second page size around 28,000, with a total, again, of about 93,000 bytes.

My guess is that the ogg decoder in the Classic, and presumably the Boom, just doesn't handle these larger pages very well. The source code is not publicly available, so I can't verify the point.

`Audio::Scan` seems to handle both files without issue.

Perhaps you should just stick with Foobar 1.1.7. A review of the Foobar source code might reveal the reason for their change in approach. But I'm not sure that it would help you. (Unless there is some obscure option that allows you to limit ogg page sizes in 1.6.x).

I would not expect the firmware in the Classic, or the Boom, to be updated to handle the issue.

**Comment by domcote** [comment]
Wow - thanks for digging in to this. 👍
I agree - it sounds like a constraint of typical hardware players back in the day.
Not sure why Foobar changed their ogg pagination, but there probably is a good reason for it which in all honesty weighs heavier than supporting an (almost) obsolete hardware player platform.

I'll just continue to use Foobar 1.1.7 for Vorbis, until https://github.com/Logitech/slimserver/issues/793 is fixed - which should finally make Vorbis obsolete.
Meanwhile, I'll close this bug.
Thanks for your help @all!

**Comment by mw9** [comment]
> Not sure why Foobar changed their ogg pagination, but there probably is a good reason for it which in all honesty weighs heavier than supporting an (almost) obsolete hardware player platform.

I wouldn’t be so sure about there being a “good reason”. It might be worth raising the issue with the developer(s) in case it was an “inadvertent” change.

I don’t know what norms are expected, but I’d have thought that an ogg page size of circa 65k is probably well over the top. It might be worth seeing what the official Xiph.org tools would do. My uneducated guess is circa 4/5k.

**Comment by domcote** [comment]
Thanks for your perspective.
According to https://www.xiph.org/ogg/doc/oggstream.html
_Although packets have no size limit in Ogg, pages are a maximum of just under 64kB meaning that any Ogg stream can be captured with confidence after seeing 128kB of data or less [worst case; typical figure is 6kB] from any random starting point in the stream._
So new Foobar seems up to spec.
I know it still doesn't explain _why_ they changed it, but tbh I'd rather get Opus working than ask for more investments in both an obsolete codec and obsolete hardware player.

I can probably also get away with transcoding to PCM instead of native playback. That should shift all the mucking around with album art in OGG containers from the players to LMS.
And I already know that Foobar-generated .opus files with albumart do not exhibit this issue, likely due to transcoding, right?

**Comment by mw9** [comment]
> So new Foobar seems up to spec.

I don't doubt it.

I shall remark that the page sizes for all of the audio packets **do** fall within the range 4,000/4,500 bytes each. Perhaps that's as well.

> I can probably also get away with transcoding to PCM instead of native playback.

This might be a good test of the "premature ending while transcoding" issue #793, because the ogg transcoding rules also use `sox` alone, just like the opus rules. I would suggest that you use flac, rather than pcm, because I see that the ogg->pcm rule shares the same sample rate problem that the opus->pcm rule has. Which said, I would guess that your source files are all 44,100 Hz anyway (unlike opus), so perhaps not noticeable. Perhaps try both.

**Comment by mw9** [comment]
> And I already know that Foobar-generated .opus files with albumart do not exhibit this issue, likely due to transcoding, right?

Yes. When transcoding to flac/pcm, the player simply does not see the metadata, just the transcoded audio.

For what it's worth (not much), I have observed that, in the sample opus audio file that you provided, most of the ogg metadata pages are c. 65,000 bytes in size, whereas the ogg audio pages fall in the range 14,000/17,000 bytes.

I shall remark that the ogg specification (RFC 3533) speaks as follows:

> A physical Ogg bitstream consists of a sequence of concatenated
   pages.  Pages are of variable size, usually 4-8 kB, maximum 65307
   bytes.
 
https://www.rfc-editor.org/rfc/rfc3533#section-6

This was written in May 2003. Perhaps it informed the ogg decoder implemented in the Classic/Boom players.
