### ISSUE TITLE
Logitech Media Server:Can't player m3u8

### ISSUE THREAD

**Issue by yu13740000** [LMS-Community/slimserver#863]
https://github.com/MichaIng/DietPi/issues/6154

**Comment by michaelherger** [comment]
Try again with the PlayHLS plugin installed. m3u8 usually are HLS streams which aren't supported natively in LMS.

**Comment by yu13740000** [comment]
> Try again with the PlayHLS plugin installed. m3u8 usually are HLS streams which aren't supported natively in LMS.

Thank you so much!
