### ISSUE TITLE
ImageProxy failing to handle some artwork

### ISSUE THREAD

**Issue by PaulWebster** [LMS-Community/slimserver#864]
A particular piece of cover art should have been displayed but failed. URL can be seen below (between imageproxy/ and /image_)
The image displays in regular web browser.
Perhaps libjpeg needs an update.

[23-03-03 06:38:44.2894] Slim::Utils::Misc::msg (1325) Warning: [06:38:44.2887] Image::Scale libjpeg error: JPEG datastream contains no image ((data))
[23-03-03 06:38:44.2903] Slim::Web::ImageProxy::__ANON__ (319) Artwork resize for imageproxy/https://media.live365.com/download/fc499752-459d-45f5-a7e5-bfff2d8a63b0.jpg/image_270x270_m.jpg failed

**Comment by michaelherger** [comment]
Can you provide the URL (as used in the UI)? Is it using the LMS internal image proxy to resize, or MySB's? The URL there should come with the protocol (`http(s)://media.live365.com/...`). That could very well be the reason for the failure.

**Comment by PaulWebster** [comment]
The logs have gone - but the URL that was given to LMS via info->cover was
https://media.live365.com/download/fc499752-459d-45f5-a7e5-bfff2d8a63b0.jpg

However, I just faked one by putting the same URL into a .opml and imported it ... and it displays without a problem
h t t p://slimserver:9000/imageproxy/https%3A%2F%2Fmedia.live365.com%2Fdownload%2Ffc499752-459d-45f5-a7e5-bfff2d8a63b0.jpg/image.jpg

So I guess it was an internet glitch when the original fetch happened and this can be closed.

**Comment by mherger** [comment]
Interesting: I played around with it and at first thought there was a problem with the origin server, as even with `curl` I'd get an invalid image. But suddenly it would return a valid picture. So maybe this was a glitch on live365's end.
