### ISSUE TITLE
bbc app is as ugly as sin - how to get rid please?

### ISSUE THREAD

**Issue by xpseudonym** [LMS-Community/slimserver#873]
It would be really nice to get rid of 'bbc app' (as opposed to the bbc sounds app which is absolutely beautiful!!! And, used all the time.)
The bbc app doesn't seem to be available via the plug-in dialogue, which suggests it's hardcoded somehow, perhaps?  It is now the only app which doesn't conform to the overall theme:

![clipboard-edit](https://user-images.githubusercontent.com/5032475/226187251-2a2a9056-4f9a-491d-a97f-2478c3bfda31.png)
Can it be removed?

**Comment by michaelherger** [comment]
You can remove it on mysqueezebox.com.

**Comment by xpseudonym** [comment]
Ah!
Many thanks (by why is SBS still connected to mysqueezebox.com...?  sorry, ot, I'll raise that elsewhere.)
Done, bbc gone.  Looks much better.
M
