### ISSUE TITLE
Unable to dissociate SB with mysqueezebox.com & asociate with LMS

### ISSUE THREAD

**Issue by jujuinparis** [LMS-Community/slimserver#876]
Hello

I am not able to register my SB with LMS 7.9 or 8, each time I am getting this error 

[23-04-03 14:19:42.8967] Slim::Networking::SqueezeNetwork::Players::_disconnect_player_error (457) Disconnect SN player error: 411 Length Required

can you please help ?

thanks

**Comment by michaelherger** [comment]
I guess it's you who asked the same question in the forums?

https://forums.slimdevices.com/forum/user-forums/3rd-party-software/110192-announce-community-firmware-for-squeezebox-radio-touch-controller-and-lms-8/page34#post1635641

Let's continue the discussion there. Ok?

**Comment by jujuinparis** [comment]
Hello

yes it is me indeed 🗡️ 

I managed to disconnect using the api directly 
https://www.mysqueezebox.com/api/v1/players/disconnect/528399XX/192.168.2.10
