### ISSUE TITLE
Why do you reject cli access from the gateway address?

### ISSUE THREAD

**Issue by kettenbach-it** [LMS-Community/slimserver#881]
Here:

https://github.com/Logitech/slimserver/blob/feb5e256ad91cf07e58a0cee1a49392b21c7bdd6/Slim/Plugin/CLI/Plugin.pm#L248

In my case, I run a interface on my network gateway that needs to talk to the squeezeserver and there is no way to allow that.
Why? I doesn't make sense to me.

**Comment by michaelherger** [comment]
It's security reasons, obviously. You don't want the script kiddy on the internet to play music in your home at full volume around 2am. 

Now you seem to have a slightly more complicated setup in which case this might be a problem. But as you can see from the condition you pointed at you can change the behaviour. Feel free to disable this security measure. But you've been warned 😉.

**Comment by kettenbach-it** [comment]
What option in the menu does this refer to:

`$prefsServer->get('protectSettings'`

I don't want to enable authorization and all other conditions are out of my hands

**Comment by michaelherger** [comment]
As this is a potentially dangerous pref it's not exposed in the UI. It's really for those who know what they're doing. You'd have to shut down LMS and edit it in `server.prefs` directly.
