### ISSUE TITLE
lms fails after buildme.sh on aarch64 Debian-bookworm

### ISSUE THREAD

**Issue by klslz** [LMS-Community/slimserver#891]
LMS VERSION: github 5072984

When running the buildme.sh on a

```aarch64 (RPIOS) Debian bookworm```

 system, which comes with 

```perl 5.36``` 

CPAN gets compiled properly.

However lms then fails at start, with

```The following modules failed to load: DBI EV JSON::XS Digest::SHA1 YAML::XS Sub::Name```

Somehow it seems buildme.sh wrongly creates a x86_64 architecture path 

```/usr/share/lms/CPAN/arch/5.36/x86_64-linux-thread-multi/auto/```

with all relevant sub-dirs and files instead of loading

```./aarch64-linux-thread-multi```

If I start lms manually I get this message

```
 /usr/share/lms/slimserver.pl  \
             --prefsdir /var/lib/lms/prefs \
             --cachedir /var/lib/lms/cache \
             --logdir   /var/lib/lms/log \
             --tmpdir   /tmp \
             --charset utf8

The following modules failed to load: DBI EV JSON::XS Digest::SHA1 YAML::XS Sub::Name


This is perl 5, version 36, subversion 0 (v5.36.0) built for aarch64-linux-gnu-thread-multi
(with 52 registered patches, see perl -V for more detail)

Copyright 1987-2022, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at https://www.perl.org/, the Perl Home Page.


*******

NOTE:

If you're running some unsupported Linux/Unix platform, please use the buildme.sh
script located here:

https://github.com/Logitech/slimserver-vendor/tree/public/8.4/CPAN

If 8.4 is outdated by the time you read this, Replace "8.4" with the major version
You should never need to do this if you're on Windows or Mac OSX. If the installers
don't work for you, ask for help and/or report a bug.

*******

			
Exiting..
```

Let me know if you need more info.

THX

**Comment by michaelherger** [comment]
Feel free to grab the following tarball and extract it to LMS' CPAN//arch/5.36 folder. Would that work=

https://www.dropbox.com/s/oxeuhc4jtb5sg14/536-aarch64-linux-thread-multi.tar.gz?dl=0

**Comment by klslz** [comment]
That was quick. To keep up with the pace, I just tested it. 


And...
...it works! LMS is up'n running.

Great.

Can we expect a patch?

**Comment by michaelherger** [comment]
Thanks for the testing! The topic has come up before. So I already had binaries built, but only tested by one single user. Now you're two of them 😁. Are you on Raspberry Pi OS or some other Linux?

New builds should be out shortly.

**Comment by klslz** [comment]
As I wrote in my initial post, I am running tests on 

```
aarch64 (RPIOS) Debian bookworm
```

I am running  a RPi4 with 64bit RPiOS.

Debian "Bookworm", the base, is not yet released though.  I am doing some pre-release testing here.
The upgrade from Bullseye to Bookworm on my RPi server went smoothly - except for LMS. ;) 

I just finished testing your latest commit. I can confirm that my own build script using LMS buildme.sh 
builds a working CPAN env on my platform now. 

THX

**Comment by andybjackson** [comment]
Debian "Bookworm" upgrade on my Buffalo Linkstation LS421 hasn't gone well with LMS either. Guessing the problem isn't Perl as 5.36 support is included in nightlies. Problem is there are no new log entries so I am in the dark about what isn't working.

**Comment by mherger** [comment]
What CPU are you using? We only have binaries for x86_64 and aarch64. What does "perl -v" say?

**Comment by andybjackson** [comment]
Per the discussion on [Slim Devices Forums](https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1641420-debian-bookworm), Debian Linux 10 Buster's PERL 5.28 & 11 Bullseye's 5.32 had support for `arm-linux-gnueabihf-thread-multi-64int` built in. Hoping that 12 Bookworm's PERL 5.36 might now also get to include this? Meantime this issue should stay closed.

**Comment by michaelherger** [comment]
See https://github.com/Logitech/slimserver/commit/2d156178a15caf36af5f78bfc117c59ce54e7e91
