### ISSUE TITLE
Overall volume wrong in case of multi-room

### ISSUE THREAD

**Issue by schnillerman** [LMS-Community/slimserver#896]
When a virtual "all" player is created and active, the volume is displayed e.g. as follows:

![image](https://github.com/Logitech/slimserver/assets/17252473/79aeb12a-6507-43ac-85e6-6b47d3d3aead)

The calculation of the overall volume seems to be wrong if arithmetic mean is intended?

**Comment by michaelherger** [comment]
I recommend you post to https://forums.slimdevices.com with more information about what you're using, and how you're doing things. I'm not sure whether you're dealing with the Groups Plugin, Material, or whether this indeed is a LMS issue.
