### ISSUE TITLE
Incompatibility with Perl 5.36 still an issue on Fedora 38

### ISSUE THREAD

**Issue by FBachofner** [LMS-Community/slimserver#899]
Hi @michaelherger

>I added those files to LMS 8.3.1 and 8.4. Please let me know should you still encounter an issue.

_Originally posted by @michaelherger in https://github.com/Logitech/slimserver/issues/826#issuecomment-1306718393_

Distributions with Perl 5.36 (such as Fedora 38) can still not install / run LMS as provided in the [nightlies download area](http://downloads.slimdevices.com/nightly/index.php).

Perhaps I have grossly misunderstood your above comment, and we are still supposed to build it (i.e. the rpm file) ourselves?

**Comment by mherger** [comment]
This is dealt with in https://forums.slimdevices.com/forum/user-forums/logitech-media-server/113611-lms-8-3-and-perl-5-36.
