### ISSUE TITLE
Using Sounds & Effects as an alarm no longer repeat

### ISSUE THREAD

**Issue by mfraser** [LMS-Community/slimserver#906]
If I select a sound & effect to use as an alarm, it plays once and then stops even though the alarm timeout is set to at least 9 minutes. 

This worked until a recent update.

Logitech Media Server Version: 8.4.0 - 1694578754 @ Wed 13 Sep 2023 09:55:15 AM CEST
Hostname: server
Server IP Address: 192.168.2.109
Server HTTP Port Number: 9000
Operating system: Debian - EN_GB - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.34.0 - x86_64-linux-gnu-thread-multi
Audio::Scan: 1.05
Database Version: DBD::SQLite 1.58 (sqlite 3.22.0)

**Comment by michaelherger** [comment]
What kind of player are you using?

**Comment by mfraser** [comment]
> What kind of player are you using?

The main one is using Squeezelite - I've also tried with piCorePlayer.

**Comment by michaelherger** [comment]
AFAIK Squeezelite (which is being used by piCorePlayer, too) doesn't support the looping sounds. Did this ever work for you? I didn't know until I did some work on the plugin a few months ago and tried to use Squeezeplay to test with. I think @ralph-irving mentioned this wasn't implemented in the emulators.

**Comment by mfraser** [comment]
> AFAIK Squeezelite (which is being used by piCorePlayer, too) doesn't support the looping sounds. Did this ever work for you? I didn't know until I did some work on the plugin a few months ago and tried to use Squeezeplay to test with. I think @ralph-irving mentioned this wasn't implemented in the emulators.

Up until recently it worked fine. I had it loop for 90 minutes as a sleep aid.

**Comment by michaelherger** [comment]
Ok, good to know. Maybe there’s a difference between Squeezelite an Squeezeplay. Would you know, what LMS version still worked?

**Comment by ralph-irving** [comment]
Yes, squeezelite does not support looping, and squeezeplay does support it.

**Comment by michaelherger** [comment]
I double checked with a Radio, Squeezelite (ESP32) and Squeezeplay: Hardware and Squeezeplay did loop, Squeezelite did not.

@mfraser I wonder whether you've updated your client? Did you use Squeezeplay before?

**Comment by mfraser** [comment]
> I double checked with a Radio, Squeezelite (ESP32) and Squeezeplay: Hardware and Squeezeplay did loop, Squeezelite did not.
> 
> @mfraser I wonder whether you've updated your client? Did you use Squeezeplay before?

No, I've been using Squeezelite on this device for years and 1.8-4.1+b1 is installed. If Squeezelite doesn't support looping, how have I been getting it to work previously?
