### ISSUE TITLE
Balance option for esp32 device not available anymore

### ISSUE THREAD

**Issue by Eddie46848** [LMS-Community/slimserver#913]
Hi
Balance option for esp32 device not available anymore, its still there for other devices. i use a muse mn cast and ive asked in the squeezelite guthub and they say nothing has changed and said it could be a server change.
Im running latest 8.4 LMS and latest SqueezeESP32 (v0.501)  plugin.

Thanks

**Comment by michaelherger** [comment]
I think you better get in touch with the Squeezelite ESP32 guys over at https://github.com/sle118/squeezelite-esp32/discussions.

**Comment by Eddie46848** [comment]
Hi
Already asked in there.

**Comment by mherger** [comment]
Would have been kind if you had mentioned it. 

https://github.com/sle118/squeezelite-esp32/issues/322
