### ISSUE TITLE
album in favorites not browsable

### ISSUE THREAD

**Issue by grasshide** [LMS-Community/slimserver#918]
I use the latest lms docker stable (Version: 8.3.2).
When I add a music album to favorites it shows up in the favorites section. But the only option I have there is to play the complete album.
I expected to be able to click on the album to see its contents to play single songs. Instead, when I click the album a page opens printing the string "Empty".

**Comment by michaelherger** [comment]
I‘m not near a LMS. But isn’t there an option to enable the drilling down? Settings/Advanced/Favorites or the like?

**Comment by grasshide** [comment]
I didn't know that this was optional. But it is set to "when you select [...] drill down on its content".
The behavior is very different:
-  selecting a spotify playlist, it actually lists the songs of the playlist
-  selecting a local playlist it only brings up the playlist icon along with the playlist title and url
-  selecting an album a page with the string "Empty" is shown

**Comment by michaelherger** [comment]
Would you mind sharing your favorites.opml file (from the prefs or playlist folder - see Settings/Information) and the library.db (from the cache folder) with me? https://www.dropbox.com/request/T3RctyzGgNg0oFDubq6a

**Comment by mherger** [comment]
Thanks for the files! That's a bug indeed. I'll have to figure out what happened here.

**Comment by mherger** [comment]
Wow... that was a major WTF?!? moment... I was wondering why I and others wouldn't see this issue. Yet with your data I was clearly able to reproduce it. So I did my homework and (hopefully) fixed it. And then I wanted to merge from 8.3 to 8.4 and received a merging conflict. Because I already had fixed this in 8.4 and didn't remember it!... Argh... 😠

**Comment by grasshide** [comment]
Urgh, sh*t. Sorry that this ate up so much of your time!
I'm glad that there is a fix on the way though 😉
