### ISSUE TITLE
Enhancement request: include subtitle and discsubtitle in LMS scanning and expose these to UI

### ISSUE THREAD

**Issue by audiomuze** [LMS-Community/slimserver#927]
```subtitle``` and ```discsubtitle``` are Musicbrainz tags used to capture the following respectively:
- additional info related to to a track e.g.  'Live at ', Acoustic, Remix, Demo etc.
- the name of an album or disc when it is part of a box set or a multi-cd release e.g. live tracks bundled as a as a bonus CD along with a main album

Their tag mapping is as follows:
![image](https://github.com/Logitech/slimserver/assets/6852511/9880188e-e3e1-4192-be90-885108281f9f)

```subtitle``` when present would be displayed immediately after the track title

![image](https://github.com/Logitech/slimserver/assets/6852511/dfe9ca79-4449-479b-beb4-ee5cc8c09294)

```discsubtitle``` would be displayed alongside Disc number when present.  There's no need for it to b separately browseable etc. it just helps the user differentiate and find an album they're looking for in a box set or conveys useful information about a bonus disc that would aid a user in choosing which disc to play in a multi-disc album e.g. the Super Deluxe anniversary releases of albums that often include a number of additional discs comprising live sets by the band in the era of the main album's release.

Material skin already sees the value in providing this information where disc title is concerned, but the use of  ```comment``` to house the information is a workaround whereas subtitle and discubtitle are populated where appropriate in the MusicBrainz database and retrieved by Picard

![image](https://github.com/Logitech/slimserver/assets/6852511/b1d12bc7-145a-4f6d-9b8b-e1ef3a67e51e)

Adding support for these along with those requested in https://github.com/Logitech/slimserver/issues/877 and https://github.com/Logitech/slimserver/issues/878 will come together nicely with https://github.com/Logitech/slimserver/issues/879 to put LMS in a class of its own in terms providing coherent, meaningful and useful ways for users to browse/explore their music.  I appreciate that streaming content is unlikely to provide either tag, but that doesn't make them any less useful for users with local collections.

**Comment by tkgafs** [comment]
I'd also be keen to see this functionality added, The music playing part of Kodi has had this functionality for a few years now and allows you to search on Boxsets

see this example
[https://imgur.com/L3fo17N](url)

and then you can drill into any boxsets to see individual albums in the boxset for example

[https://imgur.com/26BjIQM](url)

I see there are a couple of closed issues in the material skin about this
[https://github.com/CDrummond/lms-material/issues/257](url)
and
[https://github.com/CDrummond/lms-material/issues/510](url)

but presumably there is little the skin author can do until this enhancement request has made some progress

**Comment by tkgafs** [comment]
I'd also be keen to see this functionality added, The music playing part of Kodi has had this functionality for a few years now and allows you to search on Boxsets

see this example

![BoxSet1](https://github.com/LMS-Community/slimserver/assets/1531083/57fb9b99-646f-44f6-9c3f-edd81b4a402c)

and then you can drill into any boxsets to see individual albums in the boxset for example

![BoxSet2](https://github.com/LMS-Community/slimserver/assets/1531083/309576f8-b3cd-406d-bd9b-9c94d7f520ef)

I see there are a couple of closed issues in the material skin about this

[https://github.com/CDrummond/lms-material/issues/257](https://github.com/CDrummond/lms-material/issues/257)
and
[https://github.com/CDrummond/lms-material/issues/510](https://github.com/CDrummond/lms-material/issues/510)

but presumably there is little the skin author can do until this enhancement request has made some progress

**Comment by michaelherger** [comment]
@darrell-k is some of this covered in your latest LMS9 work?

**Comment by darrell-k** [comment]
Yes, they're both written to the database now (see #1111 ) . Default Skin not doing much with them, but they're available as fields in the Title Format setting. Material is using `discsubtitle` instead of comments for disc names.

**Comment by tkgafs** [comment]
That's great news, a further question lots of box sets have different artwork for each actual disc, is there anyway that the correct artwork can be stored and subsequently displayed for a particular disc in a box set.

In my existing I have a folder structure as follows

Box set folder
   folder.jpg - top-level image for box set
   Disc 1 folder
      Tracks for this disc with correct discsubtitle set
       folder.jpg artwork for this disk
   Disc 2 folder
      Tracks for this disc with correct discsubtitle set
       folder.jpg artwork for this disk
Etc etc

**Comment by tkgafs** [comment]
Is there any possibility of handing the different artwork for each disc in a boxset as I mentioned above ?

I have had a look at the module Artwork.pm which i think is where the changes would be required , but the last time I wrote Perl code was about 20 years ago so I'm somewhat out of practice, and not entirely confident this would be the correct place.

**Comment by audiomuze** [comment]
> Yes, they're both written to the database now (see #1111 ) . Default Skin not doing much with them, but they're available as fields in the Title Format setting. Material is using `discsubtitle` instead of comments for disc names.

That's really great news.

**Comment by tkgafs** [comment]
> > Yes, they're both written to the database now (see #1111 ) . Default Skin not doing much with them, but they're available as fields in the Title Format setting. Material is using `discsubtitle` instead of comments for disc names.
> 
> That's really great news.

Thank you for your reply but you have misunderstood my query I was specifically asking about the artwork when I have structure similar to

Box set folder
folder.jpg - top-level image for box set
Disc 1 folder
Tracks for this disc with correct discsubtitle set
folder.jpg artwork for this disk
Disc 2 folder
Tracks for this disc with correct discsubtitle set
folder.jpg artwork for this disk
Etc etc

is the correct artwork now shown with this change or is it still the first folder.jpg encountered in the directory structure that is used for all lower level folders

**Comment by audiomuze** [comment]
Lyrion now ingests both discsubtitle and subtitle  tags when present and Material Skin uses them when present.  I think this thread can be closed.

**Comment by michaelherger** [comment]
Thanks for the confirmation!
