### ISSUE TITLE
Player not switched away from MySqueezebox

### ISSUE THREAD

**Issue by 80er** [LMS-Community/slimserver#939]
Hi,

cannot tell when this happened but it is also there with latest version of slimserver running in docker image.

I can see my squeezebox in the drop down of the web page. But after selecting it nothing happens. Neither on the radio nor on the web page. In default settings I also cannot find anything in the logs. 

What kind of log should I set to higher logging level to find more information?

regards,
Marco

**Comment by michaelherger** [comment]
`network.squeezenetwork` should give you more information about what's going on.

What LMS version are you using? Can you switch the player by selecting "My Music" on the device itself?

**Comment by 80er** [comment]
Hi,

Version according to docker Image is:

Logitech Media Server Version: 8.4.0 - 1696852117 @ Mon Oct 9 14:23:27 CEST 2023

I cannot select it on the device either. Doesn't even Show there.

Attached a Screenshot which Shows i can select it in the web ui and the Last 50 lines of the server.log right after selecting. 

Does that Error mean that the docker Image is not functional?
![Screenshot_20231119-124530](https://github.com/Logitech/slimserver/assets/3246438/5550765a-f786-407e-a0ae-057a8c664a4a)
[server.log.zip](https://github.com/Logitech/slimserver/files/13403709/server.log.zip)

**Comment by 80er** [comment]
Hi,

Version according to docker Image is:

Logitech Media Server Version: 8.4.0 - [1696852117](tel:1696852117) @ Mon Oct 9 14:23:27 CEST 2023

I cannot select it on the device either. Doesn't even Show there.

Attached a Screenshot which Shows i can select it in the web ui .

Last Line in server.log Shows an error. Does that Error mean that the docker Image is not functional?
23-11-19 12:45:36.1639] Slim::Control::Request::execute (1885) Error: While trying to run function coderef [Slim::Networking::SqueezeNetwork::Players::disconnect_player]: [Can't locate object method "header" via package "Slim::Control::Request" at /lms/Slim/Networking/SimpleHTTP/Base.pm line 147.
]

**Comment by michaelherger** [comment]
Hey, you've found a bug indeed! Introduced back in April of this year. Some variable naming conflict... I'll have to figure out the reason for that change. Thanks!

https://github.com/Logitech/slimserver/commit/c23c461dbc580f96c239d36b6cd9e97336c8614c

`request` would sometimes be a HTTP object, sometimes an internal CLI style request.

**Comment by michaelherger** [comment]
"Unfortunately" you're on Docker. Otherwise I would have asked you to test the following patch. You could still apply it in the Docker container, but it's a little more complicated:

```diff
diff --git a/Slim/Networking/SimpleHTTP/Base.pm b/Slim/Networking/SimpleHTTP/Base.pm
index f54ca1a41..2aba40cd8 100644
--- a/Slim/Networking/SimpleHTTP/Base.pm
+++ b/Slim/Networking/SimpleHTTP/Base.pm
@@ -100,7 +100,10 @@ sub _createHTTPRequest {
                || $params->{timeout}
                || $prefs->get('remotestreamtimeout');
 
-       my $request = $params->{request} || HTTP::Request->new( $type => $url );
+       my $request = $params->{request};
+       if (!$request || ref $request ne 'HTTP::Request') {
+               $request = HTTP::Request->new( $type => $url );
+       }
 
        if ( @_ % 2 ) {
                $request->content( pop @_ );

```

**Comment by 80er** [comment]
Thanks for pushing the docker Image. Unfortunately now I have a different Error:
Slim::Networking::SqueezeNetwork::Players::_disconnect_player_error (457) Disconnect SN player error: 403 Forbidden
But the Player ist listed in the Combo Box. Any Idea?
