### ISSUE TITLE
Player list is stuck 

### ISSUE THREAD

**Issue by oywino** [LMS-Community/slimserver#94]
I'm running the latest stable 7.9 Debian x86.
My list of available players is for some reason stuck. Removed players still appear in the list. 
Is there a way to clear the player list?
(Restarting LMS does not help)

**Comment by mherger** [comment]
How do you "remove" them? You'll have to shut them down to make them disappear.

**Comment by oywino** [comment]
:-) "Remove" = "Shut Down"
Problem is they do not disappear from the list. Is there a way to delete players from LMS manually (all or one by one) ?

**Comment by mherger** [comment]
Just wait a few minutes and they’ll be gone.

**Comment by oywino** [comment]
Well, after 26 hours waiting and a number of reboot, they are still in the list.... (!)
That's why I am asking.....

**Comment by mherger** [comment]
Ok, we need more details: what list are you talking about? Are you saying that the player, even though they are powered down, and have been for more than a  day, still show up in that list?

**Comment by oywino** [comment]
Exactly! I have two players (both software) that persistently remain in the list of available players to choose from (The list in the upper right hand corner of the LMS Web GUI - and in all other control Apps).

**Comment by mherger** [comment]
You better ask the player’s author. Maybe it’s not being shut down properly? I only can say that any player which really goes away, does disappear from LMS after a while. I see this every day when the kids walk away with a radio, which sooner or later would power off.

**Comment by oywino** [comment]
OK, I see.... you may have a point. I just assumed that LMS is keeping the information about connected players somewhere (in a config file?) that could be cleared easily?
Anyway, thank you for taking the time to answer :)

**Comment by nixusminimax** [comment]
this is sorted out here: http://forums.slimdevices.com/showthread.php?105785-Can-the-list-of-players-be-deleted&p=856508&viewfull=1#post856508
it was a missconfiguration on some player
