### ISSUE TITLE
Switch to LMS not working with 403 Forbidden

### ISSUE THREAD

**Issue by 80er** [LMS-Community/slimserver#944]
Thanks for pushing the docker Image. Unfortunately now I have a different Error:
Slim::Networking::SqueezeNetwork::Players::_disconnect_player_error (457) Disconnect SN player error: 403 Forbidden
But the Player ist listed in the Combo Box. Any Idea?

_Originally posted by @80er in https://github.com/Logitech/slimserver/issues/939#issuecomment-1820525957_

**Comment by michaelherger** [comment]
There indeed is a problem. I don't see any successful call in the server log files...

Can you still switch over using the on-device menus?

**Comment by 80er** [comment]
Nope. Device Does Not even Show the local Server.

Does it make sense to set another log to debug?

**Comment by michaelherger** [comment]
Don't you have a "My Music" menu? Can you do anything with that radio at all?!?

Can you confirm it's on the same network as your LMS?

**Comment by 80er** [comment]
Hi,

Yes. Can use it for listening radio streams for example. But in "my music" only the text in the Screenshot ist shown. Squeezebox and LMS are in same network. Docker exposes these three Ports: 3483, 9000, 9090
![PXL_20231125_172113943](https://github.com/Logitech/slimserver/assets/3246438/7528e0c0-93bd-4720-a9bd-00be708d2efa)
![PXL_20231125_172056946](https://github.com/Logitech/slimserver/assets/3246438/c622df56-ad72-4654-8f77-ce50910678f0)
![PXL_20231125_172049977](https://github.com/Logitech/slimserver/assets/3246438/173f6fe7-b1aa-495d-9d38-11a75ed5177f)

**Comment by michaelherger** [comment]
Do you export both TCP and UDP for port 3483? Are LMS and Radio in the same network? What are their IP addresses?

**Comment by 80er** [comment]
ok. my fault. 3483 udp was not shared on the container :( switching from the menu to the LMS now worked without problems. Switching on LMS itself on the web ui still fails with 403 forbidden. 
Thanks for helping me out here.
