### ISSUE TITLE
Can't use strings with strict refs console errors during startup of lms 8.4 git 577fadf5d 32-bit windows

### ISSUE THREAD

**Issue by ralph-irving** [LMS-Community/slimserver#948]
Perl Version: 5.14.2 - MSWin32-x86-multi-thread

```
[23-11-29 15:18:46.7631] Slim::Control::Request::execute (1885) Error: While try
ing to run function coderef [Slim::Plugin::Extensions::Plugin::appsQuery]: [Can'
t use string ("123456↓ ☻   ♦☻☺   ♦↓      "...) as a HASH ref while "strict refs"
 in use at C:/Program Files (x86)/Squeezebox/server.git/Slim/Plugin/Extensions/P
lugin.pm line 506.
]
[23-11-29 15:18:47.8952] Slim::Utils::Timers::__ANON__ (272) Error: Timer Slim::
Plugin::InternetRadio::Plugin::_initRadio failed: Can't use string ("123456♥♥
↨♠Browse♣   "...) as a HASH ref while "strict refs" in use at C:/Program Files (
x86)/Squeezebox/server.git/Slim/Plugin/InternetRadio/TuneIn.pm line 121.
```

**Comment by michaelherger** [comment]
Did you have an internet connectivity issue? Both these calls should handle some downloaded XML. Both seemed to have received invalid data. But it's difficult to tell why this wasn't caught earlier in the process.

The plugin manager could be debugged using `plugin.extensions`.

**Comment by mherger** [comment]
Can we close this report? Or do you have any further information?

**Comment by ralph-irving** [comment]
Yes that's fine, I'll close it.   
I haven't been able to reproduce it with logging since I reported it.   I have encountered this error before this report.
If it happens again, I'll reopen the issue.
