### ISSUE TITLE
Crossfade with network streams

### ISSUE THREAD

**Issue by gdhgdhgdh** [LMS-Community/slimserver#95]
Hi Michael - so many thanks for your tireless work on LMS - you are a legend :)

Should crossfade work when using e.g. GoogleMusic plugin? (I'm using the recently-forked https://github.com/squeezebox-googlemusic)

Playing tracks from the local library with Crossfade enabled works fine - it smoothly mixes across over the last few / first few seconds of the two tracks.

When I play anything from Google Music, no crossfade occurs. One track finishes and then the next one starts.

I just upgraded this evening to the current snapshot of 7.9 (1467357800) in the hope it would be magically fixed.

**Comment by mherger** [comment]
TBH: I don't know. Did you ask the plugin author?

**Comment by gdhgdhgdh** [comment]
That's a very interesting response which suggests to me that it should be possible. I guess my question was really 'Does LMS support crossfade of HTTP streams' (i.e. fixed `Content-Length` tracks rather than radio) ?

**Comment by mherger** [comment]
I'm not sure about Google Music, as I've never used it. But I just worked on crossfading and it did work with Spotify perfectly well. So yes, crossfading online streams can work.
