### ISSUE TITLE
LMS 8.4.0 64b as of 20231130 not working after fresh install

### ISSUE THREAD

**Issue by JWBro** [LMS-Community/slimserver#950]
Wanted to use LMS 8.4.0 64b version. I uninstalled the previous 32b version completely.
Downloaded the 64b LMS version as of 30 nov 2023; than installed it. Took a while as it was unpacking the archive with Perl and installing it. Installation completed. Than I wanted to start the LMS server, but no luck (also with admin rights). Nothing happened. Restarted the PC and same thing happened: can not start the LMS server. So I decided to uninstall this version of LMS. The SW was just partial uninstalled; wanted to remove the installation completely from the Program Files\Squeezbox folder, but I can not get rid of the Perl folder. I tried the program Unlock to remove it ....... took ages. My PC has the latest Windows 10 Pro version 64 bits installed with the latest updates.

**Comment by michaelherger** [comment]
How did you try to start LMS? Can you tell me the startup parameters as found in Windows' service manager?

**Comment by JWBro** [comment]
Just after the installation completed, got the popup to start the control panel. ..... but it did not turn up. Than I went with File Explorer to the folder 'Program Files\Squeezebox' and wanted to start SqzSvcMgr program with admin rights. It started up and completed but I see no running LMS server. And I don't see anything in Windows's service manager like Logitech Media Server under description nor squeezesvc. 
By the way I have installed the 64b LMS version as of 28 nov 2023 on another PC, where LMS 64b started normally and in this case I see squeezesvc had started and stopped.

**Comment by michaelherger** [comment]
Could you please check in the Windows service manager and get the startup parameters?

And please check the `server.log`, too.

**Comment by JWBro** [comment]
Hello Michael,

I have made a fresh install with LMS 8.4.0 64b on a W10 64b system. Prior to installing it, I completely removed the previous installation and installed the 64b version as of 6 dec 2023.
Installation went flawless; after the installation completed I clicked on the button to start the web version. I selected a small music library and scanned it with the web version. This finalized OK with the right set of albums that was in the library.

The only thing I see with this version that in the Windows Service manager that the Logitech Server has not started. If I try to start the program SqzSrvMgr.ex: it starts and asked if the Service Manager to start at power-up. I click on yes, but after a restart of the system I don’t see an indication that the Server is running. The only way to get to the web version is to start the default browser ( in my case Google Chrome) and after I enter localhost:9000 I see the web version.

Maybe I am so used to see the server manager as started and where I can click to start the web version or the Control Panel for the Server.

Best regards
Jan

**Comment by michaelherger** [comment]
That all sounds correct: there is no try icon or settings panel in the 64 bit version any more. There's the service, that's it. Everything else is in the LMS web UI itself.

**Comment by JWBro** [comment]
Hi Michael,

Thanks, but I am so used to the 32b version that one automatically assumes the 64b version works/looks the same ……
OK everything thru the web UI.
One question left: if I switch to the 64b version, does that version use the library and artwork db files as stored in ProgramData\Squeezebox\Cache? In other words do I have to re-scan the music lib(s) when switching?

Thanks for all the work you’re doing !!

Best regards
Jan

**Comment by michaelherger** [comment]
32-bit and 64-bit share the same library files. I believe the strings cache is the only one which would be re-built, but not the music library.

The try icon and control panel will likely never come back in their old form. They're based on tools which are no longer available. Maybe there will be some 3rd party solution at some point. Or Squeezelite-X integrates some features of them.

**Comment by JWBro** [comment]
Hello Michael,

All of my installations with Logitech Server (both 32 & 64b) are working perfectly.

As a token of my appreciaton I am sending your this Xmas/NewYear ‘card’.

Keep up the good work en enjoy the holiday season.

Best regards
Jan Broenink
