### ISSUE TITLE
Feature Request: Re-Add the startup option "-noupnp"

### ISSUE THREAD

**Issue by chincheta0815** [LMS-Community/slimserver#97]
Is there the possibility to re-add the startup option --noupnp to LMS?
On low performant systems (e.g. RasPi) with a lot of UPNP devices in the network LMS is causing a lot of workload for the server hardware. Disabling upnp by the lic at startup would help a lot.

**Comment by mherger** [comment]
There's no need for this any more: UPnP support has moved to the "Remote Library" and "UPnP/DLNA" plugins. Disable these plugin, or the UPnP support in the plugin's settings.
