### ISSUE TITLE
Assign release type to media folder/path?

### ISSUE THREAD

**Issue by 986ster** [LMS-Community/slimserver#976]
I'm trying to move away from MultiLibrary/CustomBrowse if I can, so the concept of using release types to separate out my large library of contemporary and classical albums, and singles looks like it has potential.

I already have them in three distinct paths, so I could define three media folders in the Basic Settings tab.  In this instance it would be good if a standard release type could be virtually applied to all files in the particular folder, so the Singles path could be defined as having a SINGLE release type that could be applied during scanning without having to physically tag all the files.

Maybe a thought for a possible enhancement?

**Comment by michaelherger** [comment]
Sounds like an idea for a third party plugin. But this is not going to happen in LMS core.
