### ISSUE TITLE
Suspected typo in LMS 8.4.0 changelog (ClassicRadio.com plugin should be ClassicalRadio.com?)

### ISSUE THREAD

**Issue by CornelisJ** [LMS-Community/slimserver#989]
The LMS 8.4.0 changelog says that a ClassicRadio.com plugin is added to LMS 8.4.0. I do not have LMS 8.4.0 installed yet, but https://github.com/Logitech/slimserver/tree/public/8.4/Slim/Plugin shows a plugin called ClassicalRadio, not ClassicRadio. So I suppose that the plugin that is added is ClassicalRadio.com, not ClassicRadio.com. Right?

**Comment by michaelherger** [comment]
Thanks!
