### ISSUE TITLE
RPI4 - bookworm install issue

### ISSUE THREAD

**Issue by kuzmanzs** [LMS-Community/slimserver#990]
Hi,

I would like to install it on bookworm. Unfortunately I got
`If you're running some unsupported Linux/Unix platform, please use the buildme.sh 
script located here:

https://github.com/Logitech/slimserver-vendor/tree/public/7.9/CPAN
`

I have cloned the repo **slimserver-vendor** and ran the **buildme.sh**

It has finished like:
`
Module/Build/Platform/VMS.pm
Module/Build/Platform/VOS.pm
Module/Build/Platform/Windows.pm
Module/Build/Platform/aix.pm
..
Tree/
Tree/DAG_Node.pm
common/
common/sense.pm

sent 532,010 bytes  received 998 bytes  1,066,016.00 bytes/sec
total size is 528,433  speedup is 0.99
`

What sould I do after that? Nothing 'new' has been installed, I see the /build directory.

**Comment by michaelherger** [comment]
What is "it" you want to install? LMS 7.9 certainly won't work on any recent Linux. Please try 8.3.2 or even 8.4 for best platform support on recent hard/software: https://lms-community.github.io/lms-server-repository/

**Comment by 986ster** [comment]
Also, I haven't tried the architecture-specific package, but the _all.deb package definitely installs and runs just fine on Debian Bookworm on an RPi4, as that's what I'm running my test instance on.

**Comment by kuzmanzs** [comment]
previously I have tried 7.9, 8.0. and 8.1

now I purged the old version and installed 8.4

sudo dpkg --purge logitechmediaserver

sudo dpkg -i logitechmediaserver_8.4.0~1707031398_arm.deb
```
Selecting previously unselected package logitechmediaserver.
(Reading database ... 131964 files and directories currently installed.)
Preparing to unpack logitechmediaserver_8.4.0~1707031398_arm.deb ...
Unpacking logitechmediaserver (8.4.0~1707031398) ...
Setting up logitechmediaserver (8.4.0~1707031398) ...
Adding system user `squeezeboxserver' (UID 114) ...
Adding new user `squeezeboxserver' (UID 114) with group `nogroup' ...
Not creating home directory `/usr/share/squeezeboxserver'.
Created symlink /etc/systemd/system/multi-user.target.wants/logitechmediaserver.service → /lib/systemd/system/logitechmediaserver.service.
```


less /var/log/squeezeboxserver/server.log

[24-02-04 19:38:58.7117] main::init (386) Starting Logitech Media Server (v8.4.0, 1707031398, Sun 04 Feb 2024 08:56:45 AM CET) perl 5.036000 - aarch64-linux-gnu-thread-multi
[24-02-04 19:38:59.3681] Slim::Networking::UDP::init (40) FATAL: There is already another copy of the Logitech Media Server running on this machine. (Address already in use)
[24-02-04 19:38:59.3687] Log::Log4perl::Logger::and_die (868) Warning: FATAL: There is already another copy of the Logitech Media Server running on this machine. (Address already in use) at /usr/share/squeezeboxserver/lib/Log/Log4perl/Logger.pm line 900


sudo service logitechmediaserver status
```
○ logitechmediaserver.service - Logitech Media Server
     Loaded: loaded (/lib/systemd/system/logitechmediaserver.service; enabled; preset: enabled)
     Active: inactive (dead) since Sun 2024-02-04 19:38:59 CET; 1min 58s ago
   Duration: 2.597s
    Process: 2639 ExecStart=/usr/sbin/squeezeboxserver --prefsdir $PREFSDIR --logdir $LOGDIR --cachedir $CACHEDIR --charset $CHARSET $SLIMOPTIONS (code=exited, status>
   Main PID: 2639 (code=exited, status=0/SUCCESS)
        CPU: 2.587s

Feb 04 19:38:56 raspberrypi systemd[1]: Started logitechmediaserver.service - Logitech Media Server.
Feb 04 19:38:57 raspberrypi squeezeboxserver[2639]: dirsFor: Didn't find a match request: [scprefs]
Feb 04 19:38:59 raspberrypi systemd[1]: logitechmediaserver.service: Deactivated successfully.
Feb 04 19:38:59 raspberrypi systemd[1]: logitechmediaserver.service: Consumed 2.587s CPU time.
```

I do not understand the another instance
`There is already another copy of`

ps: 'Not creating home directory `/usr/share/squeezeboxserver''  is ok?

**Comment by kuzmanzs** [comment]
I have find out... I have installed Home Assistant as well and it is using 9000-as well

thanks, 8.3.2 and 8.4 working well

**Comment by kuzmanzs** [comment]
8.3.2 and 8.4 working well
