### ISSUE TITLE
8.4.0 repeatedly indicating (the same) update is available - even after an install

### ISSUE THREAD

**Issue by jelockwood** [LMS-Community/slimserver#997]
Recently LMS aka Logitech Media Server aka slimserver was updated to 8.4.0. This resulted in a notification being delivered by the LMS software on Windows and apparently also macOS that this update was available to install.

I accordingly installed this update and it was successfully installed and my Windows computer now reports the version details of LMS as being -

Logitech Media Server Version: 8.4.0 - 1700745578 @ Thu Feb 8 12:16:32

The fault is that _every day_ it reports the _same_ update is available and awaiting installation. If one runs the install option again from the menu in the Windows the version reported remains the same and then the process repeats the next day, and the next and the next.

According to the follow post in the user forums…

https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1673928-logitech-media-server-8-4-0-released?p=1677098#post1677098

…the same thing is happening to at least one Mac user.

Note: the LMS 8.4.0 is working correctly after the update in that Squeezeboxs can successfully still connect to and use the server so this is purely an annoying distraction.

![Screen Shot 2024-02-22 at 01 49 17](https://github.com/Logitech/slimserver/assets/4300786/12ac22ff-edca-4f39-b660-35f2e4c21548)

**Comment by michaelherger** [comment]
Thanks for the report! I _hope_ I've fixed that for 8.4.1 already. But the problem with problems to the update mechanism is that you'll only really know once there's yet another update out. So we'll see once 8.4.1 has officially been released wether it's behaving correctly now...

**Comment by michaelherger** [comment]
See https://github.com/Logitech/slimserver/commit/cf4693f5fbfe52a3013e3a616d4a24dd9ee4d98d.

**Comment by reedy** [comment]
Any rough timeline on when we might see 8.4.1? Thanks!

**Comment by michaelherger** [comment]
I plan to release v8.5.0 within the next two weeks.

**Comment by michaelherger** [comment]
Is this still an issue?

**Comment by jelockwood** [comment]
Hmm, according to @michaelherger this is supposed to be fixed in 8.5.0 and it looked like 8.5.0 was released 4 days ago. I just told my system to install the update but it still shows as 8.4.0 afterwards.

I will recheck and retry presumably tomorrow as the 8.4.0 update may have been stuck in the queue first and it may next time recheck and this time see 8.5.0 as now being available.

**Comment by reedy** [comment]
![Screenshot 2024-03-18 at 15 33 51](https://github.com/LMS-Community/slimserver/assets/67615/30a0741e-4a54-4a16-bf7e-f93757ba9aa0)

^ A minor issue is that the "More" link is a link to https://github.com/LMS-Community/slimserver/commits/public/8.4, even though it's showing 8.5. It's similarly wrong on `/updateinfo.html?installerFile=/var/lib/squeezeboxserver/cache/updates/logitechmediaserver_8.5.0_amd64.deb`

Upgraded and it's showing as `Logitech Media Server Version: 8.5.0 - 1710422688 @ Thu 14 Mar 2024 03:03:02 PM CET` (as expected).

There is no update banner in the bottom left, but I'm not sure if it showed immediately, or only after a later (timed?) update check runs

**Comment by jelockwood** [comment]
I can confirm that today it updated successfully to 8.5.0 so as I suspected and hoped it was an already queued 8.4.0 download. I am going to close this ticket.
