### ISSUE TITLE
Firmware version and LMS version 7.x doc issue

### ISSUE THREAD

**Issue by clach04** [LMS-Community/slimserver#999]
https://forums.slimdevices.com/forum/user-forums/squeezebox-radio/1670674-trying-and-repeatedly-failing-to-patch-and-update-radio?p=1670677#post1670677 indicates the information in section https://github.com/Logitech/slimserver#sb-radio-sb-touch-sb-controller-and-logitech-media-server-8 is incorrect

**Comment by michaelherger** [comment]
It might be confusing, but IMHO correct:

> There's a workaround built in to Logitech Media Server 8+ now, but you might still get warnings in the log file or on the device.

And there's

> Please do not apply this procedure unless you trust a partially patched firmware more than you'd trust a community built alternative firmware as outlined in the previous section. We strongly recommend the Community Firmware over applying the patch.

Maybe I should simply remove all this information. What would you consider correct?

**Comment by clach04** [comment]
I don't know if I have a firm opinion other than this is confusing 😄

I'm not sure I understand the problem fully. It sounds like newer versions of LMS 8.something recognize old firmwares and workaround the issue. My guess is that some early 8.x version of LMS did not have this. So it sounds like the advice is really; use LMS 7.x (any 7 version) or 8.x where x is greater than ?? I.e. latest LMS 8 is fine but some older 8 versions are a problem.

Did I understand that correctly?
